### ISSUE TITLE
PDF documentation fails to build

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#10]
Doing make -C doc pdf results in

...
pdfTeX warning: pdflatex (file ./inheritance-a6ea610817660597b4a97d1eef82a61a61
49018b.pdf): PDF inclusion: Page Group detected which pdfTeX can't handle. Igno
ring it.
>] [71] [72] [73]
Underfull \hbox (badness 10000) in paragraph at lines 5250--5252
[]\T1/ptm/m/n/10 key, value pairs that will up-date the Es-ti-mate-Model.inputs
 at-tributes see
[74] [75]

! LaTeX Error: Too deeply nested.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5520 \begin{description}

attaching that .tex file (if I targetted it correctly).

I have python-sphinx 0.6.3-1, nipype rev 647

http://sourceforge.net/apps/trac/nipy/ticket/56

**Comment by satra** [comment]
fixed in readthedocs: http://readthedocs.org/projects/nipype/downloads/pdf/latest/
