### ISSUE TITLE
antsRegistration interface only using first items in fixed_image and moving_image input lists for all transforms

### ISSUE THREAD

**Issue by sgiavasis** [nipy/nipype#1005]
Hey guys,

We noticed this error after a recent change in one of our registration workflows. We have a workflow where we send a skullstripped brain into antsRegistration for the first two transforms, and then a skull-on image to the third (it used to be that we used the same input and references for all three).

In the report.rst, the correct list is shown as the inputs for fixed_image and moving_image (i.e. [input1, input1, input2] and [reference1, reference1, reference2]). However, when the command string is formed, it produces the antsRegistration command with input1 and reference1 being used for all three transforms, instead of using input2 and reference2 for the third one.

Thanks in advance.

Steve

**Comment by sgiavasis** [comment]
I was digging around, and after some testing, it seems that the interface for the ANTS command handles this properly:

From nipype/registration.py, line 110:

 def _image_metric_constructor(self):
retval = []
intensityBased = ['CC', 'MI', 'SMI', 'PR', 'SSD', 'MSQ']
pointSetBased = ['PSE', 'JTB']
for ii in range(len(self.inputs.moving_image)):
if self.inputs.metric[ii] in intensityBased:
retval.append(
'--image-metric %s[ %s, %s, %g, %d ]' % (self.inputs.metric[ii],
self.inputs.fixed_image[
ii],
self.inputs.moving_image[
ii],
self.inputs.metric_weight[
ii],
self.inputs.radius[ii]))
elif self.inputs.metric[ii] == pointSetBased:
pass
# retval.append('--image-metric %s[%s, %s, ...'.format(self.inputs.metric[ii], self.inputs.fixed_image[ii], self.inputs.moving_image[ii], ...))
return ' '.join(retval)

Could this be adapted to the antsRegistration interface? I am trying a hack of this now, but it seems it would need a few things to be changed. For example, this function returns a full string unlike antsRegistration's formatMetric, which returns only the metric descriptions.

**Comment by djarecka** [comment]
I think this was fixed in #1187 and #1196, but please reopen if this is still an issue.
