### ISSUE TITLE
interfaces.afni.preprocess.Copy creates incorrect 3dcopy command

### ISSUE THREAD

**Issue by beausievers** [nipy/nipype#1008]
When using outputtype = 'AFNI', interfaces.afni.preprocess.Copy will incorrectly add the -prefix flag to the 3dcopy command, like so:

c = afni.Copy()
c.inputs.in_file = 'bold1.nii.gz'
c.inputs.out_file = 'testcopy'
c.inputs.outputtype = 'AFNI'
c.cmdline

> '3dcopy -prefix testcopy bold1.nii.gz'

To which AFNI will reply:

Standard error:
++ 3dcopy: AFNI version=AFNI_2011_12_21_1014 (Sep 18 2014) [64-bit]
** FATAL ERROR: unknown option: -prefix
** Program compile date = Sep 18 2014
Return code: 1
Interface Copy failed to run.

**Comment by blakedewey** [comment]
This should be fixed after this PR #1131 is merged. @beausievers, once it is merged, re-install nipype from the github master and you should be good to go.
