### ISSUE TITLE
Some ANTs interfaces will be broken

### ISSUE THREAD

**Issue by armaneshaghi** [nipy/nipype#1014]
I'm documenting changes I need to make for ANTs interfaces, as a new built has broken some Nipype interfaces. Unfortunately, ANTs versioning and its backward compatibility are not the best.

 - N4BiasFieldCorrection:

         --image-dimension needs to be changed to --image-dimensionality 

I think there are some changes we need to make for the registration interface, please add below as you find any broken interface.

**Comment by armaneshaghi** [comment]
- antsRegistration
`collapse-linear-transforms-to-fixed-image-header`

and

 `transformRigid[2.0]`

are no longer available.

**Comment by lsqshr** [comment]
An open pull request in Nov.14 has fixed the problem of `collapse-linear-transforms-to-fixed-image-header` https://github.com/nipy/nipype/pull/999. However it has not been merged?

**Comment by JDWarner** [comment]
I'll update #999 with the N4 bias correction change, and look into transformRigid.

**Comment by armaneshaghi** [comment]
Thanks. @satra do you suggest anything for backward compatibility?

**Comment by JDWarner** [comment]
:+1: for the subprocess solution. Changing the flags is easy, adding robust logic to select the right one a little tricky. Unfortunately I'm away right now and my laptop doesn't have ANTs built, so it's difficult for me to play with the parsing necessary.

I didn't bother with backwards compatibility for the `collapse-linear-transforms-to-fixed-image-header` change, as it was not doing anything previously for over 2 years.

**Comment by satra** [comment]
@armaneshaghi - there are a few things to consider.

- ants rarely comes out with versions and we often end up running a git version of ants. if we can convince the ants folks to at least create versions every month, then versioning can be used.
- there is a PR #1004 by @hjmjohnson which reflects many of the changes, but merging that PR will break anyone without the latest version of ants.

so without having versions our only options might be to move some of these older interfaces to ants.legacy, but it will break some people's scripts.

@armaneshaghi - would you be willing to start a conversation on the ants thread about versioning? that would actually be most helpful, as nipype has support for versions through the `min_ver` and `max_ver` metadata flags. but this would also mean that we can resolve the version on an installation of ants. as far as i know, no version information is stored with the binaries.

**Comment by armaneshaghi** [comment]
I close this as the issue will be resolved by regular ANTs releases.

**Comment by blakedewey** [comment]
I know this is closed, but I just ran into this with ANTs and wanted to suggest an idea. The short CLI tag `-d` is used for both inputs even though the long tag has changed. At least for `N4BiasFieldCorrection` this might be a good reverse compatibility option until versioning can be worked out.

**Comment by oesteban** [comment]
:+1: @blakedewey

**Comment by blakedewey** [comment]
Great! I'll put in a PR
