### ISSUE TITLE
algorithms.metric.Distance Memory Error

### ISSUE THREAD

**Issue by lsqshr** [nipy/nipype#1031]
Hi Guys,

I am suffering Memory Error while using the algorithms.metric.Distance interface. It could simply be reproduced by
```python
from nipype.algorithms.metrics import Distance
d = Distance()
d.inputs.volume1='path/to/somerealbrain.nii.gz'
d.inputs.volume2='path/to/somerealbrain.nii.gz'
d.run()
```

By reviewing the code at https://github.com/nipy/nipype/blob/master/nipype/algorithms/metrics.py, could the problem be the call of `scipy.spatial.distance.cdist(...)`? Since it will allocate a pairwise dissimilarity matrix. For this case, suppose we have a brain.nii.gz with `192*192*60` voxels and 70% of them are non-zero. A cdist would need to allocate about 2397195730944 doubles to save the distmatrix (approx. 17860.5 GB)?

Thanks in advance

**Comment by oesteban** [comment]
Hi @lsqshr , may I suggest you to use ```nipype.algorithms.metric.ErrorMap``` instead and let us know?

**Comment by lsqshr** [comment]
@oesteban  Thanks for the reply. `nipype.algorithms.metrics.ErrorMap` works like a charm for me. In addition, I also need an overall average sum distance (a float) in my pipeline. 

Though I could just connect another Function interface to achieve this, is there a need to fix `nipype.algorithms.metrics.Distance`? Or that interface was only designed for small volumes like tumor label maps?

**Comment by oesteban** [comment]
Hi @lsqshr, the interface ```Distance``` was written before I ever used nipype. I contributed with ```ErrorMap``` for close reasons to yours. My opinion on this is that ```Distance``` should be deprecated after integrating the alternative metrics inside ```ErrorMap```. What do you think @satra?

Regarding the summary sum distance, we could easily add an output for it in ```ErrorMap```, would it work out for you?

**Comment by satra** [comment]
@oesteban - that sounds reasonable, we should include a deprecation warning in the next release and deprecate in the following one.

**Comment by oesteban** [comment]
Great, I will include the averaged sum for @lsqshr first. The deprecation of Distance will come afterwards.

**Comment by lsqshr** [comment]
guys thanks for the notice and support! Adding the alternative metrics to ErrorMap alongside the output_map sounds the best solution. @oesteban I am currently with a local subclass of the ErrorMap which outputs the average sum and will switch to the main repo when the new ErrorMap is ready. - Cheers!

**Comment by oesteban** [comment]
@lsqshr that's great!!. Would you consider requesting us a pull request? (https://github.com/nipy/nipype/blob/master/CONTRIBUTING.md)

**Comment by lsqshr** [comment]
@oesteban  Sure I will make one shortly
