### ISSUE TITLE
setup.py fails to find nibabel

### ISSUE THREAD

**Issue by dmwelch** [nipy/nipype#1040]
I'm following the instructions in 'Contributing.md'.  I set up a virtualenv, cd'ed to my local nipype repo (on nipy/master) and ran `make specs` which gives the error:
```
Checking specs and autogenerating spec tests
python tools/checkspecs.py
Traceback (most recent call last):
  File "tools/checkspecs.py", line 15, in <module>
    from nipype.external import six
ImportError: No module named nipype.external
make: *** [specs] Error 1
```
It's a clean virtualenv, so I installed six via pip - no change.  :-1: 

Okay, then I tried installing nose, nibabel, scipy, networkx, and traits (maybe the steps are out of order?).  Running setup.py vis-a-vi `python setup.py install/develop`:
```
Traceback (most recent call last):
  File "setup.py", line 289, in <module>
    pkg_chk('nibabel', INFO_VARS['NIBABEL_MIN_VERSION'])
  File "setup.py", line 199, in package_check
    raise RuntimeError(msgs['missing'] % pkg_name)
RuntimeError: Cannot import package "nibabel" - is it installed?
``` 
Doing a `pip freeze`:
```
decorator==3.4.0
networkx==1.9.1
nibabel==2.0.0
nose==1.3.4
scipy==0.15.1
six==1.9.0
traits==4.5.0
wsgiref==0.1.2
```

I'm not setting a `PYTHONPATH`, and my `sys.path` looks correct.  I'm sure I'm missing something simple.  Any ideas???

**Comment by lsqshr** [comment]
@dmwelch I believe the easiest way to install nipype is to run `pip install nipype` so pip will figure out all the dependencies. Then you can checkout the source and run `python setup.py install` when you have all the essentials available in your virtualenv. Hope this helps

**Comment by mwaskom** [comment]
Is it possible that your `python` binary and `pip` binary are pointing at different installations?

**Comment by dmwelch** [comment]
@lsqshr wrote:
> @dmwelch I believe the easiest way to install nipype is to run `pip install nipype` so pip will figure out all the dependencies. 
> Then you can checkout the source and run `python setup.py install` when you have all the essentials available in your virtualenv. Hope this helps.

Thanks, guys.  The solution from @lsqshr solves the issue and I think I'm good to go now.  I'm not very familiar with the `setup.py` mechanics (I use `pip` whenever I can), so it _feels_ like I was installing nipype twice! :open_mouth: 

1. First, checking my binary paths (thanks, @mwaskom!):
```shell
$ mkvirtualenv nipype_test
$ head $(which pip)
#!/IPLlinux/raid0/homes/dmwelch/.virtualenvs/nipype_test/bin/python
$ which python
/IPLlinux/raid0/homes/dmwelch/.virtualenvs/nipype_test/bin/python
```
2. Installing nipype via pip:
``` shell
$ pip install nipype  # fails to install numpy, so we do it manually...
$ pip install numpy
$ pip install nipype
$ cd ${LOCAL_NIPYPE_REPO}
$ python setup.py install
$ make specs
$ python setup.py develop
```
Success! :+1:

**Comment by mwaskom** [comment]
Also for future reference you can also do `pip install .` in a source directory and I think it will handle the dependency management for you.
