### ISSUE TITLE
win8 nipype build fails to import nipype @line9 of init.py

### ISSUE THREAD

**Issue by chchatham** [nipy/nipype#1050]
I have just installed Python (anaconda) and all Nipype dependencies today, as well as downloading and installing nipype itself. Upon launching ipython and trying "import nipype" I get the following error:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-feb2fc727b0b> in <module>()
----> 1 import nipype

C:\Users\CHATHC01\AppData\Local\Continuum\Anaconda\lib\site-packages\nipype\__init__.py in <module>()
      7                   STATUS as __status__,
      8                   __version__)
----> 9 from utils.config import NipypeConfig
     10 config = NipypeConfig()
     11 from utils.logger import Logging

C:\Users\CHATHC01\AppData\Local\Continuum\Anaconda\lib\site-packages\nipype\utils\config.py in <module>()
     19 from ..external import portalocker
     20 
---> 21 homedir = os.environ['HOME']
     22 default_cfg = """
     23 [logging]

C:\Users\CHATHC01\AppData\Local\Continuum\Anaconda\lib\os.pyc in __getitem__(self, key)
    423                 self.data[key.upper()] = item
    424             def __getitem__(self, key):
--> 425                 return self.data[key.upper()]
    426             try:
    427                 unsetenv

KeyError: 'HOME'

**Comment by chrisfilo** [comment]
Due to poor support of other neuroimaging software that Nipype depends on
we currently do not support windows system natively. To run Nipype on
windows you will need a virtual machine. This might be a good place to
start: http://nipy.org/nipype/users/vagrant.html You can also use a VM
provided by NeuroDebian http://neuro.debian.net/vm.html

**Comment by chchatham** [comment]
Thank you very much for the rapid reply. I would suggest the nipype github page be updated because it currently implies Nipype will work on Windows ( installation instructions are provided ). Best wishes and thank you for a wonderful project.

**Comment by satra** [comment]
@chchatham - could you please point us to where it says nipype will work on windows?

**Comment by chrisfilo** [comment]
I guess we can make it explicit here:
http://nipy.org/nipype/users/install.html
