### ISSUE TITLE
interfaces.ants.WarpImageMultiTransform mutual exclusive inputs

### ISSUE THREAD

**Issue by lsqshr** [nipy/nipype#1051]
In `interfaces.ants.WarpImageMultiTransform`, the out_postfix and the output_image are exclusive. However the out_postfix has a default value which will disable any output_image value and throw an Exception saying `IOError: Input "output_image" is mutually exclusive with input "out_postfix", which is already set`

Should the usedefault of out_postfix be canceled?

**Comment by satra** [comment]
if `out_postfix` changes the default state, then we have to add mandatory to both args. 

1. we can put a on_trait_change function that undefines `out_postfix` when `output_image` is set, and vice verse, perhaps reverting to the default.

2. usually we ask people to do the following for such a situation (and we can explicitly add it to the docstring).

```
from nipype.interfaces.base import Undefined
wimt.inputs.out_postfix = Undefined
wimt.inputs.output_image = 'filename'
```

the simpler for the user solution is 1.

another factor here is that that interface is no longer recommended by ants, and so most of us have moved away from it.

**Comment by lsqshr** [comment]
@satra  Thanks for clarifying. Considering it is not recommended, do you think it should better be deprecated or it needs a fix?

**Comment by djarecka** [comment]
@lsqshr @oesteban closing for now, please reopen or create a new one if this is still relevant
