### ISSUE TITLE
fs.SampleToSurface: projection_stem mandatory if reg_header=True ?

### ISSUE THREAD

**Issue by farkau** [nipy/nipype#1053]
When I run fs.SampleToSurface with reg_header=True, projection_stem is still mandatory thus I have to set projection_stem="" to get this node running. I think this is not intended, or do I miss something?

## works: 
import nipype.interfaces.freesurfer as fs
sampler = fs.SampleToSurface(
    hemi="lh",
    source_file = 'mynifti.nii.gz',
    subjects_dir='/path/to/freesurfer',
    reg_header=True,
    subject_id='sub001')
sampler.inputs.projection_stem=""
res = sampler.run()

# error:
import nipype.interfaces.freesurfer as fs
sampler = fs.SampleToSurface(
    hemi="lh",
    source_file = 'mynifti.nii.gz',
    subjects_dir='/path/to/freesurfer',
    reg_header=True,
    subject_id='sub001')
#sampler.inputs.projection_stem=""
res = sampler.run()

Thanks,
Falko

**Comment by satra** [comment]
@farkau - yes either projection stem (and it looks like that might actually be incorrectly specified for freesurfer 5.3) or a sampling method is required. when you sample to surface reg_header merely describes how the volume and surface are related, but you are still going from a 3d manifold to a 2d manifold, so you have to specify how to sample from 3d to 2d.

**Comment by farkau** [comment]
Makes sense to me. I'll try it with setting a sampling method to improve my result. Probably I was just lucky.

Thanks for the feedback and explanation.
