### ISSUE TITLE
Documentation clarification JoinNode "joinsource", name or variable?

### ISSUE THREAD

**Issue by gerddie** [nipy/nipype#1062]
In the [Documentation](http://nipy.sourceforge.net/nipype/api/generated/nipype.pipeline.engine.html#nipype.pipeline.engine.JoinNode) it is written, that the JoinNode takes the joinsource as the name of the corresponding node, but in [this working example](http://nbviewer.ipython.org/gist/satra/ed3760e9f849d9ca82a9) the joinsource is given as the variable of the iterable node. It would be good to clarify what is the correct way to do this, or if both are considered to be supported then this should be documented accordingly.

best.

**Comment by satra** [comment]
it does look like both are supported. i'll take a closer look and update the document accordingly.

**Comment by tfunck** [comment]
Hi, I was wondering if this had been clarified? I'm trying to figure out how to use "JoinNode" and it's not clear to which node "joinsource" is supposed to refer.

**Comment by mgxd** [comment]
@tfunck you can set both. If you pass in a node, JoinNode will get its name
