### ISSUE TITLE
rsfmri questions

### ISSUE THREAD

**Issue by mb3152** [nipy/nipype#1064]
New to nipype, and just want to make sure I understand what is going on.

How does the normalization on this script work? Is it a combination of ANTs and Freesurfer?
How do I change the number of iteration for ANTs?
i.e., what should this line ideally be, if time is not that big of an issue?
reg.inputs.number_of_iterations = [[10000, 11110, 11110]] \* 2 + [[100, 30, 20]]

What steps are done on the surface, and what are done on the volume?

Is it possible to get the data into average fs_LR32k mesh?

Thank you!

**Comment by satra** [comment]
> How does the normalization on this script work? Is it a combination of ANTs and Freesurfer?

it uses bbregister from freesurfer to register the median functional image to the freesurfer recon and then normalizes the structural from freesurfer using ants to mni space. then it combines those registrations into a single interpolation step. this combined warp is then used to map the mindboggle atlas to the individual functional space (to extract volume ROI timecourses - i use it mostly for the subcortical structures). also the freesurfer transform is used to generate aparc+aseg time courses and for resampling the timeseries onto the fsaverage4/5/6 (this is the target subejct choice) surfaces.

> What steps are done on the surface, and what are done on the volume?

in this script, almost everything is done on the volume and then resampled on to the surface.

> Is it possible to get the data into average fs_LR32k mesh?

theoretically yes, but i don't recollect if fs_LR32k has a mapping to fsaverage. if it does then it should be as simple as adding fs_LR32k to your freesurfer subjects dir and specifying fs_LR32k as your target surface.

**Comment by mb3152** [comment]
Is smoothing done on the surface?

Okay great, thank you. How easy would it be to extract ROI time courses from multiple atlases? Do I just need them in 2mm iso in MNI space?

**Comment by mb3152** [comment]
Also, I am having trouble with with the nipy.SpaceTimeRealigner. It is claiming my version is not new enough, even though I just downloaded it.

 150227-08:01:36,603 workflow INFO:
	 Traceback (most recent call last):
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 971, in run
    self._check_version_requirements(self.inputs)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 934, in _check_version_requirements
    version, min_ver))
Exception: Trait in_file (SpaceTimeRealigner) (version 0.3.0 < required 0.4.0.dev)

**Comment by satra** [comment]
smoothing is done on the surface, but you have to be careful as to which streams you choose. there is a smoothed volume stream as well as an unsmoothed stream (the one called bandpass).

https://github.com/nipy/nipype/blob/master/examples/rsfmri_vol_surface_preprocessing_nipy.py#L741

both of these streams get sampled to surface and the surf_fwhm is used to smooth the data on the surface.

to use a different atlas at least in MNI space, a couple of things need to be changed (the atlas file and the set of indices).

https://github.com/nipy/nipype/blob/master/examples/rsfmri_vol_surface_preprocessing_nipy.py#L857

the reason we use the mindboggle template and atlas, is that they were created from the same transformations.

**Comment by mb3152** [comment]
Okay, great, thanks. 

How would I determine the set of indices?

**Comment by satra** [comment]
whatever the indices are in the atlas.

**Comment by mb3152** [comment]
Okay, so if my atlas file is labeled by intensity from 1 to 300, I would just replace it with range(1,301)? 

Also, how long should spacetime_realign take? Mine has been hanging for about an hour. I have an hour of EPI data. Is that normal?

**Comment by satra** [comment]
spacetime realign is memory and cpu hungry and takes a while. for an hour worth of data, it's going to take a bit of time. spacetimerealign questions would be best asked on the nipy-devel mailing list (@alexis-roche) can provide some tune-up suggestions perhaps.

**Comment by mb3152** [comment]
Okay, thanks for all your help! I will just submit it to SGE and be patient :+1:

**Comment by mb3152** [comment]
Also, was I correct about the indices for the atlas?

**Comment by satra** [comment]
yes - you were correct about your atlas.
