### ISSUE TITLE
nipype_display_crash doesn't open crash files

### ISSUE THREAD

**Issue by blakedewey** [nipy/nipype#1068]
When using nipype_display_crash, I get False False in one line and then an ImportError complaining that there is no module called "utils". Anyone have an idea as to why?

**Comment by blakedewey** [comment]
Full traceback:
```
False False
Traceback (most recent call last):
  File "/p4/PipelineSoftware/anaconda/bin/nipype_display_crash", line 86, in <module>
    debug, args.directory)
  File "/p4/PipelineSoftware/anaconda/bin/nipype_display_crash", line 17, in display_crash_files
    crash_data = loadcrash(crashfile)
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 383, in loadcrash
    return loadpkl(infile)
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 404, in loadpkl
    return cPickle.load(pkl_file)
ImportError: No module named utils
```

**Comment by satra** [comment]
@blakedewey - the `False False` output has been removed in master. regarding the no module, it's possible that you have an older copy installed without a nipype installation. you might consider deleting the nipype_display_crash script and reinstalling nipype.

**Comment by blakedewey** [comment]
I completely removed nipype and nipype_display_crash and reinstalled from master. Still the same error (without the `False False`). I double checked the nipype_display_crash with which to make sure I wasn't using an orphaned one. It seems to be a problem in the `cPickle.load` command.

**Comment by satra** [comment]
is this a recent crash file or an old crashfile that you are trying to load? you could try to load it with just python's pickle to see if that helps. nipype's loadpkl uses that?

if there has been some module renaming between when you saved and now, one could try debugging and remapping:

https://wiki.python.org/moin/UsingPickle/RenamingModules

**Comment by blakedewey** [comment]
It's a brand new crash file. Created it right after reinstall.

**Comment by satra** [comment]
that is indeed very strange. would it be possible to do this?

```
def crash_func():
    raise ValueError()

from nipype import Workflow, Node, Function

wf = Workflow(name="crashflow")

wf.add_nodes([Node(Function(input_names=[], output_names=[], function=crash_func), name='crashfunc')])

wf.run()
```

if the above doesn't work:

- remove any trace of nipype (pip uninstall nipype - a few times) delete the nipype_display_crash binary
- reinstall nipype
- recreate the crash with the above snippet
- try loading it

**Comment by blakedewey** [comment]
Using the snippet, it works fine. I renamed one of my packages (previously called utils) to utilities and now the traceback shows `ImportError: No module named utilities`. Why would `cPickle.load` try to import my package?

**Comment by satra** [comment]
were you calling the package in the node that crashed? or using sys.path to add the package to python?

**Comment by blakedewey** [comment]
The Interface that the failed Node ran is defined in `utilities`.

**Comment by satra** [comment]
that's why pickle is trying to load it. nipype pickles the entire node object in the crash file. `nipype_display_crash` allows you to debug it (see `nipype_display_crash -h`). for the moment you can add the utilities package via `PYTHONPATH`.

**Comment by blakedewey** [comment]
Hmm. That worked. Maybe my importing should be cleaned up...Would it work if I referenced my modules using the relative `.` mechanics?

**Comment by satra** [comment]
relative won't work unless it's relative to a package on the python path. in that sense python is like matlab/R/executables - some path needs to indicate where things are. python doesn't store absolute path in pickles.

**Comment by blakedewey** [comment]
So my package structure is like this:
```
nipype_tnu
---- utilities.py
---- input_conversion.py
```
`input_conversion.py` has a CLI that I call from the command line and that runs a workflow that `input_conversion.py` builds based on CLI arguments. The workflow contains nodes that run interfaces from `utilities.py`. These are the ones that are crashing. The whole `nipype_tnu` package lives in my site-packages folder for my python distribution. 

Is there any other way to do this other than explicitly adding the `nipype_tnu` directory to my `PYTHONPATH`?

**Comment by blakedewey** [comment]
So the easiest solution to this was to split my script files (CLIs using argparse) from my interfaces and workflows. Then add my package to site-packages and move the scripts to the bin folder (similar to the nipype library setup). I'll mark this as closed
