### ISSUE TITLE
Switch documentation to readthedocs.org

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1074]

**Comment by souravsingh** [comment]
I would like to take this up.How should I start?

**Comment by chrisfilo** [comment]
Excellent! Please create an account on readthedocs.org and let me know what is your user name.

**Comment by souravsingh** [comment]
My username is souravsingh.

**Comment by chrisfilo** [comment]
I added you as a maintainer - as you can see I got the docs to build: http://nipype.readthedocs.org/en/latest/ but they don't look too great. The nav bar is missing for example. If you could work on getting it into shape it would be great!

**Comment by mwaskom** [comment]
Seems like this change would be in conflict with @arokem's push for a consolidated nipy.github.io domain?

**Comment by arokem** [comment]
No conflict, I think. You were probably thinking of redirecting from
nipy.org anyway, right?

**Comment by chrisfilo** [comment]
indeed, but thanks for checking @mwaskom!

**Comment by arokem** [comment]
While we're at it, could I ask why not use github for this?

**Comment by chrisfilo** [comment]
Readthedocs will autobuild dev documentation. I don't think github.io can
do this.

**Comment by arokem** [comment]
Do you mean it runs sphinx for you?

That's not really practical if building the docs requires data and software
(other than sphinx itself). For example, both nitime and dipy actually run
the examples when building the docs. That wouldn't work for that, would it?

**Comment by chrisfilo** [comment]
We can generate documentation without running example. One option for you
is to make Travis do that.

**Comment by arokem** [comment]
Interesting idea. I worry that, at least for dipy, running the examples
would time out travis. And it also requires gobs of data (that term is TM
of Satra, btw). Do you have something like that configured for nipype?

**Comment by chrisfilo** [comment]
Not really, but you might speed things up with Travis cashing feature.

**Comment by arokem** [comment]
BTW - has anyone figured out a way to generate the API documentation with RTD? It seems that it runs sphinx-build directly, not the `make html` directive, so it's hard to patch in a script such as `build_mod_ref` (https://github.com/nipy/nipype/blob/master/doc/Makefile#L38). Any ideas? 

Asking for a friend :-)

**Comment by oesteban** [comment]
Is this done?

**Comment by satra** [comment]
yes: http://nipype.readthedocs.io/en/latest/api/index.html
