### ISSUE TITLE
Interface ANTS Laplacian Thickness not running

### ISSUE THREAD

**Issue by nicofarr** [nipy/nipype#1082]
Hi, 

There seems to be an issue with the wrapper of ANTS LaplacianThickness. 

http://nipy.sourceforge.net/nipype/interfaces/generated/nipype.interfaces.ants.segmentation.html#laplacianthickness

In a terminal I ve run exactly the same command line than cort_thick.cmdline with appropriate inputs ( from segmentation) and it s running with meaningful results. 

Tracking the bug a little bit I could identify that it comes from the output specification, in the class LaplacianThickness, file nipype/interfaces/ants/segmentation.py , and particularly line 215 where the _listoutputs is defined. 

The _genfilename also doesn t seem to work properly because when actually feeding a filename (so no need to generate it ), it still goes in and generate a filename that including the specified output filename + the wm filename (which is what it s supposed to generate if the output filename is not specified). 

I d be really happy to solve this myself but I m just about to learn proper python programming - will be happy in a near future to solve similar small issue. 

Gist here: https://gist.github.com/nicofarr/b583e09f767f46f9dd7b 

Thanks in advance for your help ! 

Nicolas Farrugia

infos: 

ran on Ubuntu 15.04 

nipype 1.0.0dev

Running a version cloned on Friday 11th april 2015.

{'commit_hash': 'ccfcdcfbbeaeffac8b47be2309dc4edb48dd8078',
 'commit_source': 'repository',
 'networkx_version': '1.6',
 'nibabel_version': '1.3.0',
 'numpy_version': '1.6.1',
 'pkg_path': '/home/raid2/farrugia/git/nipype/nipype',
 'scipy_version': '0.9.0',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.3 (default, Dec 18 2014, 19:10:20) \n[GCC 4.6.3]',
 'traits_version': '4.0.0'}

**Comment by nicofarr** [comment]
Please, no comments on the data files - I know this segmentation is crap but it's not the point. ;)

**Comment by satra** [comment]
@nicofarr - we'll have to look into that interface. what i do know is that the antsCorticalThickness interface runs fine, and is also a better interface that gives you a bunch of things.

**Comment by nicofarr** [comment]
@satra thanks - anstCorticalThickness was the next step I wanted to look into, although I was not sure how to get all the right inputs to make it run  - do you have an example somewhere?  Especially how to generate the segmentation priors ? I was thinking about adapting the example script provided by the author https://github.com/ntustison/antsCookTemplatePriorsExample but wanted to experiment with the simpler Laplacian method first

**Comment by satra** [comment]
here are some instructions: https://github.com/stnava/ANTs/issues/157

**Comment by djarecka** [comment]
Hi @nicofarr , I just found this issue but I'm not able to access the gist link. I know it's been a while, but if you're still having the problem, please provide me an example that I can test.

**Comment by djarecka** [comment]
@nicofarr I'm closing the issue for now, but please feel free to reopen
