### ISSUE TITLE
Dynamic causal modeling (DCM) tools for Nipype SPM interface

### ISSUE THREAD

**Issue by armaneshaghi** [nipy/nipype#1084]
I'd like to work on a PR for DCM functionality (several steps, from time series extraction to model estimation), let me know if this is something that others are interested to have in Nipype.

**Comment by satra** [comment]
i know the slicer folks would be very interested it in this and also anders dale and colleagues would like such ability.

**Comment by ckbehemoth** [comment]
Quite interested here as well - would love to help if needed.

**Comment by armaneshaghi** [comment]
Thanks folks. Watch this space...

**Comment by mgxd** [comment]
@armaneshaghi is this still in progress? If so, feel free to submit a PR and we can continue the discussion there

**Comment by yidilozdemir** [comment]
Is this available currently? I cannot see it in spm package list.
