### ISSUE TITLE
dcmstack output file path

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1087]
Hello, I am trying to specify an ouput file path for the `nipype.interfaces.dcmstack.DcmStack` interface, which should be in my data hierarchy and not in my script hierarchy.

I am doing this ~via:

```
from nipype.interfaces.dcmstack import DcmStack
stacker = DcmStack()
stacker.inputs.out_format = "/path/to/my/data"
```

stubbornly, dcmstack will export the resulting file to `/path/to/my/script/_path_to_my_data`

Can we fix this somehow? Right now I hav to export to my script directory and then move the file -.- which is a dodgy and slow way to fix this (different hard drives etc).

**Comment by oesteban** [comment]
I guess that right now that's not possible: https://github.com/nipy/nipype/blob/44f75665bf4776d7e6ff63395254de3111da8ce5/nipype/interfaces/dcmstack.py#L76

A nice solution to the problem could be adding a bool switch to NiftiGeneratorBaseInputSpec indicating if the path is absolute or relative. Then, modify the line I've pointed out to choose between op.join or op.abspath.

**Comment by TheChymera** [comment]
and how would that switch get triggered?

**Comment by oesteban** [comment]
@TheChymera I have written a fast patch, let me know if it works out for you. I'm not 100% sure this will work, but you'll need to check it out from my branch:

```
git remote add oesteban git@github.com:oesteban/nipype.git
git remote update
git pull oesteban fix/DCMStackOutput-1087
```

**Comment by TheChymera** [comment]
Do I need to test this before the pull gets accepted? I am running the live nipype version, but setting up a development installation that works nicely with my package manager might take a while :-/

**Comment by TheChymera** [comment]
@oesteban how do I use this feature? 

I installed the live version of nipype, and still stuff gets exported to `/path/to/my/script/_path_to_my_data`.

**Comment by satra** [comment]
try `use_cwd = False` for that interface

**Comment by TheChymera** [comment]
@satra so:

```
stacker.inputs.out_format = "/path/to/my/data"
stacker.inputs.use_cwd = False
```
?

**Comment by satra** [comment]
yes

**Comment by TheChymera** [comment]
@satra tried it - that still exports the file to `/path/to/my/script/_path_to_my_data`

**Comment by satra** [comment]
i looked at the code, and it looks like it's doing the correct thing. can you insert a debug breakpoint and step through.

**Comment by TheChymera** [comment]
uhm, how do I do that? Can you maybe test this at your end as well?

I am just running the interface as:

```
			stacker.inputs.dicom_files = my_files_list
			stacker.inputs.embed_meta = True
			file_name = "EPIwhatever"
			stacker.inputs.out_format = /path/to/my/file
			stacker.inputs.use_cwd = False
			result = stacker.run()
			print(result.outputs.out_file)
```

And that prints `/path/to/my/script/path_to_my_file`, and puts the file there, as opposed to under the `/path/to/my/file` directory. By the way, how would the interface deal with an inexistent output path (i.e. one where some directories would need to be created) ?

**Comment by oesteban** [comment]
ok, I see. There is also this function https://github.com/nipy/nipype/blob/df63a28152540ff95e7955403a9dc09f6f6e0876/nipype/interfaces/dcmstack.py#L36 converting slashes to underscores.

**Comment by oesteban** [comment]
@TheChymera now you can do:

```
stacker.inputs.dicom_files = my_files_list
stacker.inputs.embed_meta = True
file_name = "EPIwhatever"
stacker.inputs.out_path = '/path/to/my'
stacker.inputs.out_format = 'file'
result = stacker.run()
print(result.outputs.out_file)
```

**Comment by satra** [comment]
[OT] @oesteban - i think it would be good to start building a set of regression tests with actual data using [Testkraut](https://github.com/neurodebian/testkraut). i know we have stayed away from regression tests because of data and software requirements, but i think it would be good to start adding these test specs.

**Comment by oesteban** [comment]
@satra I've taken a glipse on the testkraut project and it looks awesome. Very appropriate for nipype :)

**Comment by TheChymera** [comment]
@oesteban sadly, I have still not set up any ebuilds for different live sources than the main branch on the main tree. I believe I will not do so soon, actually. I hope you can pull this here within the next few days.

**Comment by oesteban** [comment]
I'm to merge this then. I've done the following:
```
import glob
from nipype.interfaces.dcmstack import DcmStack
s = DcmStack()
s.inputs.out_path = '/home/oesteban/tmp/very/long/nonexistent/path'
s.inputs.out_format = 'file'
s.inputs.embed_meta = True
s.inputs.dicom_files = glob.glob('../T1_1/MR.0003.0*.IMA')
res = s.run()
```

Then, ```print res.outputs``` yields:
```
out_file = /home/oesteban/tmp/very/long/nonexistent/path/file.nii.gz
```

**Comment by TheChymera** [comment]
Looks great!
