### ISSUE TITLE
Extend dcmstack interface

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1095]
As [I recently found out](https://github.com/moloney/dcmstack/issues/28), dcmstack can do a lot of fancy things (in particular rather advanced grouping), that can save lots of lines of code. Also, built-in grouping support on the dcmstack side saves users from having to iterate a lot (which at least in my experience does not always play well with nodes and workflows).

Sadly, I have no idea how to extend the interface myself to include these functionalities. I tried to have a look [over here](https://github.com/nipy/nipype/blob/44f75665bf4776d7e6ff63395254de3111da8ce5/nipype/interfaces/dcmstack.py#L95) and I can't even understand how the current interface ends up functioning - is there really no function for it (as seen [here](http://nipy.sourceforge.net/nipype/users/function_interface.html))?

Would you be able to extend the dcmstack interface support or walk me through extending it?

**Comment by satra** [comment]
there are times when you still want to take elements of dicomstack and write as a function. you may want to look at the gist here:

https://gist.github.com/satra/8701942/#file-dicomconvert2-py-L69

regarding extending an interface, the main thing is the run_interface_ function - that's where the actual execution takes place. so any dicomstack functionality should be implemented there.

it would be great at some point to turn the converter into a proper workflow. but originally there were too many custom pieces for our sequences. and for full fledged general purpose dicom conversion, we haven't gotten around the need for custom heuristics. yes, dicomstack can parse and group, but by itself cannot distinguish say scans belonging to two different tasks without help, or an erroneous scan, etc.,.

**Comment by TheChymera** [comment]
I wasn't thinking that far ahead - just parsing and group would be nice for now.

Quite a few of the classes in `dcmstack.py` have `_run_interface` methods, but how do I add support for `parse_and_stack`? Do I create a new class or add something to the DcmStack class?

For instance in its `_run_interface` method, I cannot see where any actual dcmstack function gets called :-/ 

```
def _run_interface(self, runtime):
        src_paths = self._get_filelist(self.inputs.dicom_files)
        include_regexes = dcmstack.default_key_incl_res
        if isdefined(self.inputs.include_regexes):
            include_regexes += self.inputs.include_regexes
        exclude_regexes = dcmstack.default_key_excl_res
        if isdefined(self.inputs.exclude_regexes):
            exclude_regexes += self.inputs.exclude_regexes
        meta_filter = dcmstack.make_key_regex_filter(exclude_regexes,
                                                     include_regexes)
        stack = dcmstack.DicomStack(meta_filter=meta_filter)
        for src_path in src_paths:
            if not imghdr.what(src_path)=="gif":
                src_dcm = dicom.read_file(src_path, force=self.inputs.force_read)
                stack.add_dcm(src_dcm)
        nii = stack.to_nifti(embed_meta=True)
        nw = NiftiWrapper(nii)
        self.out_path = \
            self._get_out_path(nw.meta_ext.get_class_dict(('global', 'const')))
        if not self.inputs.embed_meta:
            nw.remove_extension()
        nb.save(nii, self.out_path)
        return runtime
```

**Comment by TheChymera** [comment]
I also see there is [this class](https://github.com/nipy/nipype/blob/2117e8d6ca4165ad4b3b6152368e227362945701/nipype/interfaces/dcmstack.py#L176) that builds upon the DcmStack class, but I can't see where I could pass it an argument so that it knows what DICOM key to goup by, nor can I find any docs for that class :-/

**Comment by TheChymera** [comment]
@satra I looked at your gist, and I think it would be better if we had a Node for this. I see you are not using any pool/multiprocessing, so I guess your loops do not support paralellization. I am thinking especially for groupig and conversion paralellization would bring a great improvement in speed, no?

**Comment by mgxd** [comment]
@TheChymera feel free to open this again if needed
