### ISSUE TITLE
fsl afni standard image Info

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#11]
this will return a path/filename without checking that it exists

**Comment by djarecka** [comment]
@chrisfilo - is it still an issue? is this about `Info.standard_image` https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/base.py#L112 ?

**Comment by chrisfilo** [comment]
I don't remember anything about this issue besides what is here. Let's close it for now.
