### ISSUE TITLE
Stable ANTs (2.1.0) not working with stable nipype (0.10.0) 

### ISSUE THREAD

**Issue by gerddie** [nipy/nipype#1100]
The latest release of ANTs broke the nipype registration interface in the stable release. @oesteban told me that there is already a pull request for the nipype developers version, apparently  #999, but this only fixes an issues with the flags, and this is not all: 

My problem is that the interface is looking for some output_0InverseWarped.nii.gz that was created by ANTS 2.1.0-rc2 +git: 9103999 (the current version in Debian Jessie), but the new ANTs version creates some different .h5 files as composite output transform. 

It would be nice if someone could provide a patch against 0.10.0 (or create a 0.10.1 release) that fixes these incompatibilities, so that we can add it to Neurodebian (that already provides  ANTs  2.1.0). Packaging the (moving) developer version is unfortunately not an option. 

many thanks, 
Gert

**Comment by satra** [comment]
@gerddie - how about we cut a 0.11 release? we have plenty of updates anyway.

unfortunately, because ants hasn't been versioned consistently (now they are), we cannot use versioning to switch between interfaces.

**Comment by gerddie** [comment]
@satra - depends on how much changed, i.e. how backward compatible would this new release be?

**Comment by gerddie** [comment]
Just a ping to ask if anything is happening with this problem. 

As pointed out above, the problem is specifically introduced if the ANTs version and nipype are installed from the neurodebien repositories. Since Debian package dependencies can be quite easily defined, a patch that fixes this issue could be applied only within the python-nipype package and dependencies could be set that that right version of ANTs is installed from the repo.  Hence an ANTs version dependent switch between Interfaces would not be necessary. 

many thanks, 
Gert

**Comment by satra** [comment]
@gerddie - versioning is being added to ants - but this will not be backwards compatible. regarding nipype support for the existing ants in neurodebian, would it be possible to try the current master against the existing ants in neurodebian? if that works, we can take the changes in the ants tree and patch against 0.10.0

@chrisfilo - time to release 0.11 ?

**Comment by blakedewey** [comment]
I have a PR that corrects at one small difference with the new ANTS versions (different CLI option for N4BiasFieldCorrection) that should be merged before this goes through to help compatibility. Unfortunately, I am rebuilding my test distro and cannot make the necessary changes myself. See #1096.
