### ISSUE TITLE
Test errors from norm `axis=` argument

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipype#1104]
The buildbots are giving errors like this:

```
======================================================================
ERROR: Failure: TypeError (norm() got an unexpected keyword argument 'axis'
Interface ErrorMap failed to run. )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/osx-10.8/nipype-py2_7-osx-10_8/build/venv/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/Users/buildslave/osx-10.8/nipype-py2_7-osx-10_8/build/venv/lib/python2.7/site-packages/nipype/algorithms/tests/test_errormap.py", line 44, in test_errormap
    result = errmap.run()
  File "/Users/buildslave/osx-10.8/nipype-py2_7-osx-10_8/build/venv/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/Users/buildslave/osx-10.8/nipype-py2_7-osx-10_8/build/venv/lib/python2.7/site-packages/nipype/algorithms/metrics.py", line 548, in _run_interface
    errvector = np.linalg.norm(diffvector, axis=1)
TypeError: norm() got an unexpected keyword argument 'axis'
Interface ErrorMap failed to run. 
```

e.g. http://nipy.bic.berkeley.edu/builders/nipype-py2.7-osx-10.8/builds/428/steps/shell_8/logs/stdio

I believe the `axis` keyword to `npl.norm` reached numpy at 1.8, and some of the buildbots have earlier numpies.

**Comment by oesteban** [comment]
Yep, that's the reason. We could define an strategy with versions of packages, if there's not one already (see https://github.com/nipy/nipype/pull/1090#issuecomment-94812119, where I have a similar issue).

Maybe with numpy.linalg.norm it would be safer to overwrite the function if numpy < 1.8 (or even include a switch in the interface with errors). But for some other packages that are growing fast (i.e. dipy) we need a more effective strategy.

**Comment by djarecka** [comment]
@oesteban numpy 1.8 is already almost 4 years old, should we change the requirements and close the issue?

**Comment by oesteban** [comment]
Totally. I'd vote for going up to numpy-1.11 (latest stable version that comes with conda). @satra, @chrisfilo ?

**Comment by chrisfilo** [comment]
I don't see why not.

**Comment by satra** [comment]
i thought about it and then reverted back to debian jessie - i had a pull request almost ready to go!

perhaps we can ask for @yarikoptic thoughts here.

**Comment by oesteban** [comment]
I think nipype got over the original issue of numpy < 1.8. Feel free to reopen this issue, or a new one for what specific version of numpy we should require.
