### ISSUE TITLE
output file placement in iterable workflows

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1108]
I am currently using [this interface](https://github.com/TheChymera/chyMRI/blob/fe680dd38321bad2fadf58292b98f961bba24cb5/extra_interfaces.py) in [this workflow](https://github.com/TheChymera/chyMRI/blob/fe680dd38321bad2fadf58292b98f961bba24cb5/preprocessing.py). It works nicely, but places my files under folders like:

```
/home/chymera/data/dc.rs/export_ME/preproc/_dcm_dir_..home..chymera..data..dc.rs..export_ME..dicom..4457..1..EPI../dcm_to_nii
```

This doesn't look particularly nice. How can I change what path is appended for each of the iterable values?

**Comment by mwaskom** [comment]
How are you setting iterables? I don't see you doing that in either file.

**Comment by TheChymera** [comment]
@mwaskom sorry, I had omitted to push my latest commit. Please have a look again.

**Comment by mwaskom** [comment]
I gather your data dirs are parameterized by some kind of subject id? What I would do in your specific case is to change your DcmToNii interface to have a "base data directory" input and a "subject id" input. Then set iterables on the latter with the list of subject IDs and have the `_run_interface` logic put those two inputs together to get the actual path. That way, your workflow will end up writing out paths that are organized by subject id.

In general I would handle this sort of thing with an IdentityInterface that defines subject ids in the workflow.

**Comment by TheChymera** [comment]
nk you for your advice, indeed the IdentityInterface seems like a great tool. I have implemented it in my workflow, as seen [here](https://github.com/TheChymera/chyMRI/blob/bb1a93cf198c0271341e0ae489ade6f449a7abba/preprocessing.py). But I keep getting crashes like this:

```
File: crash-20150521-153003-chymera-datasource.a0.pklz
Node: metaflow.datasource.a0
Working directory: /tmp/tmp1E4tYE/metaflow/_subject_id_4457/datasource


Node inputs:

base_directory = <undefined>
field_template = <undefined>
ignore_exception = False
raise_on_empty = True
sort_filelist = True
subject_id = 4457
template = source_pattern
template_args = {'struct': [['subject_id', 'anatomical']], 'func': [['subject_id', 'EPI']]}



Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1009, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1080, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/io.py", line 546, in _list_outputs
    raise TypeError(e.message + ": Template %s failed to convert with args %s" % (template, str(tuple(argtuple))))
TypeError: not all arguments converted during string formatting: Template /tmp/tmp1E4tYE/metaflow/_subject_id_4457/datasource/source_pattern failed to convert with args ('4457', 'anatomical')
Interface DataGrabber failed to run. 
```

why can't it use my args? I made sure they are both strings :-/

**Comment by satra** [comment]
the template should be a string template - see examples 3/4 or the more realistic use case here:

http://nipy.org/nipype/users/grabbing_and_sinking.html#datagrabber

**Comment by TheChymera** [comment]
@satra that's actually the guide I was following. My template is a string afaict:

```
source_pattern="/home/chymera/data/dc.rs/export_ME/dicom/%s/1/%s/"
```

**Comment by mwaskom** [comment]
You might want to use [`SelectFiles`](http://nipy.org/nipype/users/select_files.html) instead, which is a lot more straightforward than `DataGrabber` and only slightly less flexible. Should be fine for your usecase.

**Comment by TheChymera** [comment]
Actually, I find that considerably less clear and well-explained than datagrabber :-/

**Comment by mwaskom** [comment]
OK. Good luck with your code.

**Comment by TheChymera** [comment]
Thanks for your help again, my aforementioned error turns out to have been due to a typo.
