### ISSUE TITLE
Connect DataGrabber to a stacker node

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1109]
I am trying to use an IdentityInterface and DataGrabber to better manage multiple subject data (as suggested [here](https://github.com/nipy/nipype/issues/1108#issuecomment-104077029)). I am trying to connect the DataGrabber output to my stacker node as seen [in this workflow](https://github.com/TheChymera/chyMRI/blob/d723b8f2dbda7c79b8e9287430ae7f4c9262f5c3/preprocessing.py#L55).

The workflow executes nicely, but it does not do anything except create a few dirs with what seems to be none of my data inside, e.g.:

```
chymera@zenbookhost ~/data/dc.rs/export_ME/preproc/_subject_id_4460/datasource $ ls
_0xb13fb2d756358ad227b89520a458b90f.json  _inputs.pklz  _node.pklz  _report  result_datasource.pklz
```

I am guessing the connection doesn't work? how can I make it work? [The guide I am following](http://miykael.github.io/nipype-beginner-s-guide/howToBuildAPipeline.html) does not really give any good examples for this.

In a perhaps unrelated matter, my workflow also throws this crash report:

```
chymera@zenbookhost ~/src/chyMRI $ nipype_display_crash crash-20150521-170432-chymera-dcm_to_nii.a0.pklz 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/nipype_display_crash", line 85, in <module>
    debug, args.directory)
  File "/usr/lib/python-exec/python2.7/nipype_display_crash", line 17, in display_crash_files
    crash_data = loadcrash(crashfile)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/filemanip.py", line 381, in loadcrash
    return loadpkl(infile)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/filemanip.py", line 402, in loadpkl
    return cPickle.load(pkl_file)
ImportError: No module named extra_interfaces
```

which makes absolutely no sense, since the module is there and can be successfully used, as soon as I [disconnect the IdentityInterface/DataGrabber part](https://github.com/TheChymera/chyMRI/blob/46fcb24dfe4058570f6b213900f61675181a5ac4/preprocessing.py).

**Comment by TheChymera** [comment]
Strangely enough, this works fine if I only want to connect one of the two DataGrabber outputs to my stacker. As seen [here](https://github.com/TheChymera/chyMRI/blob/9f2bfd010cb7513589c970749ccb532407e0b42c/preprocessing.py).

**Comment by chrisfilo** [comment]
Is "extra_interfaces" part of your custom code?

PS Please use neurostars.org in the future

**Comment by TheChymera** [comment]
@chrisfilo yes, [extra_interfaces](https://github.com/TheChymera/chyMRI/blob/9f2bfd010cb7513589c970749ccb532407e0b42c/extra_interfaces.py) is part of my code and currently includes a single interface, which uses [a single custom function](https://github.com/TheChymera/chyMRI/blob/9f2bfd010cb7513589c970749ccb532407e0b42c/functions_preprocessing.py).

**Comment by TheChymera** [comment]
@chrisfilo any ideas? I created [a corresponding question](http://neurostars.org/p/3082/) on neurostars.org, if you prefer to answer there :)

**Comment by effigies** [comment]
@TheChymera Please reopen if this is still an issue.
