### ISSUE TITLE
Workflow resume functionality

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1112]
Hello, does nipype have any smart way of automatically skipping a node from the workflow, if it was previously executed correctly and the data is still there?

I am asking because I would like to integrate the dicom to nifti conversion into my workflow, but since it is such a time consuming step it would be cool if nipype would skip the conversion node, if the nifti data is already there.

If there is no such functionality in nipype, do you have any suggestions of how I can implement the checks manually (I was thinking just check for the expected nifti file names? But that can be rather non-trivial if I have e.g. multi-echo dicoms).

**Comment by chrisfilo** [comment]
This is built into Nipype and works out of the box without having to change anything. It works by looking at input files (be default checking their size and and timestamp, but you can change that to hash of the file content) and checking if they changed since last execution. If not the Node will not rerun, but previously computed outputs will be passed on to the next step.

**Comment by satra** [comment]
nipype automatically skips any nodes whose inputs have not changed.

**Comment by TheChymera** [comment]
thanks for the answer.

> but you can change that to hash of the file content) and checking if they changed since last execution

how can I do this?

**Comment by chrisfilo** [comment]
http://nipy.org/nipype/users/config_file.html#execution - see hash_method

**Comment by spanta28** [comment]
So after I run nipype, I usually am removing all the tmp files, logs it creates. So do I need to save any specific log file etc, for nipype resume functionality to run as expected on the previous data.

**Comment by effigies** [comment]
If you delete the working directory, you will not be able to resume.
