### ISSUE TITLE
nipype.interfaces.dcm2nii.Dcm2nii() leaves a config.ini after running

### ISSUE THREAD

**Issue by dmd** [nipy/nipype#1115]
When `nipype.interfaces.dcm2nii.Dcm2nii()` is run, it creates a `config.ini` in its working directory, because of the call to `_gen_filename() in nipype/interfaces/dcm2nii.py`.

It would be polite for it to clean up after itself rather than leaving this file in place.

**Comment by blakedewey** [comment]
This should be closed by merging in #1132.

**Comment by blakedewey** [comment]
Closed with #1132.
