### ISSUE TITLE
spm realign with jobtype='write'

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#1120]
Hi,
I don't succeed in using spm.realign with jobtype='write'. It seems to me that the problem is due to the type of in_files which should be a list of filenames (and not a list of list of filenames as for jobtype='estimate' or 'estwrite').

Thanks for the help

**Comment by djarecka** [comment]
@salma1601 is this is still an issue with current nipype? Please share your code if you still experience the problem. I've just run one workflow with `realign` and `jobtype="write"` and it worked ok.

**Comment by djarecka** [comment]
@salma1601 I'm closing this issue for now, please feel free to reopen.
