### ISSUE TITLE
'Modal' inputs

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1135]
Some inputs (i.e. those indicating the number of threads) should not be taken into account when checking if interface is up-to-date in a workflow. For instance, if I run an interface with nthreads=2 and then re-run the workflow but nthreads changed to 4 in the second run, the node should not be executed again, since the result should be equally valid.

Is this feature implemented already?

**Comment by satra** [comment]
we usually use the metadata `nohash=True` to indicate that the input should not be used for calculating the hash. it should be documented on the interface specifications page.

https://github.com/nipy/nipype/blob/master/nipype/interfaces/base.py#L536

**Comment by oesteban** [comment]
Ok, thanks, I should have checked on documentation before asking.
