### ISSUE TITLE
Documentation and testing for contrast functions in FSL 5.0.7+

### ISSUE THREAD

**Issue by poldrack** [nipy/nipype#1140]
Since ContrastMgr was deprecated in FSL 5.0.7+ (and won't work because the necessary corrections file is no longer generated by FILMgls), the ContrastMgr function should test for FSL version and handle this situation more gracefully.  This issue should also be documented more thoroughly in the documentation.

**Comment by satra** [comment]
@poldrack - we should improve the documentation.

regarding the check, yes contrast manager should have a version check that raises a DeprecationError for FSL 5.0.7+

for an example of how this is used see the openfmri script, which uses this workflow:

https://github.com/nipy/nipype/blob/master/nipype/workflows/fmri/fsl/estimate.py#L65
https://github.com/nipy/nipype/blob/master/nipype/workflows/fmri/fsl/estimate.py#L135
