### ISSUE TITLE
meica.py interface

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1147]
Hello, I would like to write an interface for [AFNI's meica.py](http://afni.nimh.nih.gov/pub/dist/doc/program_help/meica.py.html). As the name suggests this is a python script, but it is written so as to be interfaced with via the command line. The script includes some input checking functionality, so it does more than just call another function.

Should I wrap it using the `CommandLine` rather than the `BaseInterface` class?

**Comment by satra** [comment]
yes - `CommandLine` would be most appropriate for this.

**Comment by TheChymera** [comment]
thank you :)

**Comment by dangom** [comment]
@TheChymera did you finish your `meica.py` wrapper implementation? I can't seem to find it anywhere on the documentation - so I assume it's not been added to nipype?

**Comment by TheChymera** [comment]
@dangom I have a [working draft in SAMRI](https://github.com/TheChymera/SAMRI/blob/master/samri/pipelines/nipype_based/extra_interfaces.py#L627). Haven't tested it much, and won't be using it personally, so this is on hold any may remain so for a long time :-/. If you want to try and merge it into nipype, I'd be grateful, though!

**Comment by dangom** [comment]
@TheChymera Thanks for the quick answer =) The draft looks awesome.

**Comment by TheChymera** [comment]
Happy you like it! Let me know if you get it merged so that I can remove it from SAMRI.
