### ISSUE TITLE
BUG: Registration interface failed multi-modal

### ISSUE THREAD

**Issue by hjmjohnson** [nipy/nipype#1175]
Registration interface was failing to support multimodal input when they are given.
    
    ex)
    nipype:
      antsWF.inputs.fixed_image=['fixed_t1.nii.gz',
                                 'fixed_t2.nii.gz']
      antsWF.inputs.moving_image=['moving_t1.nii.gz',
                                  'moving_t2.nii.gz']
    
    corresponding correct commandline:
      --metric MI[\
          fixed_t1.nii.gz,\
          moving_t1.nii.gz,\ ...
      --metric MI[\
        fixed_t2.nii.gz,\
        moving_t2.nii.gz,\ ...

**Comment by oesteban** [comment]
Fixed in #1176
