### ISSUE TITLE
Typo in capture of Matlab Error pklz

### ISSUE THREAD

**Issue by gciccarelli3** [nipy/nipype#1190]
When a nipype wrapper of a matlab function crashes, at the end, I get a printout like below where the first character of the file name is trimmed.

Standard error:
MATLAB code threw an exception:
Permission denied
File:/om/user/xxx/git/voice/audio/praatPitch/praatPitch.m
Name:/om/user/xxx/git/voice/audio/praatPitch/wrapper_praatPitch.m
Line:47
File:om/scratch/Mon/xxx/nipype16/wf/_idx_33/pitch/pyscript.m
Name:praatPitch
Line:119
File:rapper_praatPitch  <========================= First character trimmed ===========
Name:pyscript

**Comment by satra** [comment]
@gr21783 - i believe these are errors from within MATLAB. nipype is simply reporting the output that MATLAB provides. to test, go to the working directory, open matlab and run the pyscript.m file.

**Comment by satra** [comment]
did you verify these are matlab issues?

**Comment by gr21783** [comment]
No, I couldn't recreate the error.

On Sun, Aug 30, 2015 at 10:28 PM, Satrajit Ghosh <notifications@github.com>
wrote:

> did you verify these are matlab issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/nipype/issues/1190#issuecomment-136236467>.
>



-- 
MIT VoiceUp:  Self Understanding through Vocal Analytics (that's the idea
anyway)
web:  voicesurvey.mit.edu
email:  voice_survey@mit.edu
facebook: VoiceUp_MIT
twitter:  @VoiceUp_MIT
play store:
https://play.google.com/store/apps/details?id=edu.mit.voicesurvey.androidapplication&hl=en

**Comment by djarecka** [comment]
please feel free to reopen if this is still an issue with a current version of nipype
