### ISSUE TITLE
Unable to install latest nipype version

### ISSUE THREAD

**Issue by mick-d** [nipy/nipype#1193]
After cloning the latest version of nipype on github, the installation fails:

```
$ sudo python setup.py install
/usr/local/nipype/nipype/__init__.py:57: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'nipype/interfaces/camino2trackvis/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/cmtk/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/diffusion_toolkit/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/dipy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/elastix/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/freesurfer/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/fsl/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mipav/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mne/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mrtrix/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/nipy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/nitime/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/script_templates/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/brains/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/diffusion/tractography/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/filtering/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/legacy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/registration/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/segmentation/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/utilities/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/filtering/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/legacy/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/legacy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/quantification/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/registration/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/segmentation/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/spm/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/vista/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/bedpostxout/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/dicomdir/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/tbss_dir/__init__.py' not found (or not a regular file)
error: can't copy 'nipype/testing/data/tbss_dir': doesn't exist or not a regular file
```

**Comment by mick-d** [comment]
I'm stumped. I installed the latest version on two servers. I got that error on one but not on the other. All dependencies were installed in the same way, and all permissions are the same.

**Comment by satra** [comment]
could you try cloning to a clean directory?

**Comment by chrisfilo** [comment]
We install the dev version on CircleCI every day without issues, although
we do:

pip install -e .

in the root of the source code to automatically install all the
dependencies.

**Comment by mick-d** [comment]
I cloned it in a clean directory and it got stuck again at:
`error: can't copy 'nipype/testing/data/tbss_dir': doesn't exist or not a regular file`

**Comment by satra** [comment]
this is triggered by this line:

https://github.com/nipy/nipype/blob/master/setup.py#L422

but there is a file in that directory. could you try what chris suggested? also which platform are you on?

**Comment by mick-d** [comment]
I am using Ubuntu 12.04.5 LTS. I still do not understand what is happening.

`pip install -e git://github.com/nipy/nipype.git#egg=nipype` works but this is still very strange and not really they way I planned to set up nipype on that server

**Comment by satra** [comment]
@mick-d - the vagrant file boots up a ubuntu 12.04 vm. could you try it in a vm to see if you can isolate the problem?

**Comment by mick-d** [comment]
@satra Hi Satra, I couldn't try in a vm but installing the latest version on a totally different server (Mount Sinai), i got stuck with a similar error as I described above with my server:
`error: can't copy 'nipype/testing/data/bedpostxout': doesn't exist or not a regular file`

**Comment by mvdoc** [comment]
Hey @satra, I get the same error on our server running Debian wheezy after `python setup.py install`. Using `pip install -e .` as @chrisfilo suggested works.

**Comment by satra** [comment]
@mick-d , @mvdoc - this sounds like a weird setuptools, distutils version issue. @mick-d is using python 2.7 which should have been fine (we stopped support for 2.6 and earlier).

could you try doing: `python setup_egg.py install` ?

**Comment by mvdoc** [comment]
`python setup_egg.py install` returns the same error. We have python 2.7.3 installed. Updating setuptools didn't help.

```
...
package init file 'nipype/testing/data/dicomdir/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/tbss_dir/__init__.py' not found (or not a regular file)
error: can't copy 'nipype/testing/data/bedpostxout': doesn't exist or not a regular file
```

**Comment by chrisfilo** [comment]
I have one more person running into this, but I can't replicate this myself.

**Comment by umeboshi7** [comment]
Encountered the same issue running from an Enthough Canopy virtual environment (CentOS release 6.5 ). 
pip -e worked, though I'm still puzzled about this.

**Comment by satra** [comment]
@mick-d or @umeboshi7 - could either of you test this with an updated setuptools? i wouldn't have expect it under canopy, which is a lot more recent that ubuntu 12.04LTS. i suspect that the version of setuptools is having an impact here.

**Comment by umeboshi7** [comment]
I've udpated setuptools,  but I'm still getting the same error.
Here's the output:

<pre><code>ume@login01:~/Enthought/Canopy_64bit $ easy_install ~/installed/nipy-nipype-0.11.0-154-g1a6a3e1.tar.gz 
Processing nipy-nipype-0.11.0-154-g1a6a3e1.tar.gz
Writing /tmp/easy_install-RA_Wbq/nipy-nipype-1a6a3e1/setup.cfg
Running nipy-nipype-1a6a3e1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RA_Wbq/nipy-nipype-1a6a3e1/egg-dist-tmp-4CxHhm
/home/ume/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.12.0-dev' to '0.12.0.dev0'
package init file 'nipype/interfaces/script_templates/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/bedpostxout/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/dicomdir/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/tbss_dir/__init__.py' not found (or not a regular file)
warning: no files found matching 'README'
warning: no files found matching 'THANKS'
warning: no files found matching 'doc/documentation.zip'
package init file 'nipype/interfaces/script_templates/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/bedpostxout/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/dicomdir/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/tbss_dir/__init__.py' not found (or not a regular file)
error: Setup script exited with error: can't copy 'nipype/testing/data/dicomdir': doesn't exist or not a regular file <code><pre>

**Comment by satra** [comment]
hi folks - can someone who is having the error on debian/ubuntu try the following and let me know if this works - note this is for python 2.x:

`pip install https://dl.dropbox.com/s/fdgbxffhwdwkgay/nipype-0.12.0_gee871ba.dev-py2-none-any.whl`

i'm going to look into `python setup.py install` on debian shortly.

**Comment by umeboshi7** [comment]
<pre><code>Successfully installed nipype-0.12.0-gee871ba.dev<code><pre>
Success!!

**Comment by satra** [comment]
thanks @umeboshi7  (@mvdoc and @mick-d could you try the following` as well).

another test:

uninstall nipype completely (may have to repeat `pip uninstall nipype` a few times)

download and unzip this branch: https://github.com/satra/nipype/tree/fix/debian_setup_issue

https://github.com/satra/nipype/archive/fix/debian_setup_issue.zip

and then do a: `python setup.py install`

**Comment by umeboshi7** [comment]
Got an error:

<pre><code>
/home/ume/installed/nipype-fix-debian_setup_issue/nipype/__init__.py:66: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
/act/canopy-1.5.2/appdata/canopy-1.5.2.2785.rh5-x86_64/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
...
...
...
copying nipype/testing/data/tract_data.Bfloat -> build/lib/nipype/testing/data
copying nipype/testing/data/bvals -> build/lib/nipype/testing/data
copying nipype/testing/data/timeDesign.mat -> build/lib/nipype/testing/data
error: can't copy 'nipype/testing/data/dicomdir': doesn't exist or not a regular file
<code><pre>

**Comment by satra** [comment]
@umeboshi7 - thank you.

**Comment by mvdoc** [comment]
@satra I don't know what changed on our server (most probably upgraded debian), but running both `python setup.py install` and `python setup_egg.py install` with master works for me, and I can't seem to replicate the error.

**Comment by satra** [comment]
@umeboshi7 - i think i have found the culprit, so could you please repeat the test

uninstall nipype completely (may have to repeat pip uninstall nipype a few times)

download and unzip this branch: 

https://github.com/satra/nipype/archive/fix/debian_setup_issue.zip

and then do a: python setup.py install

**Comment by umeboshi7** [comment]
It's working now.
Just let me know if you'd like me to run other tests, ok?
Thanks.
<pre><code>running install_scripts
...
...
...
copying build/scripts-2.7/nipype2boutiques -> /home/ume/Enthought/Canopy_64bit/User/bin
copying build/scripts-2.7/nipype_display_crash -> /home/ume/Enthought/Canopy_64bit/User/bin
copying build/scripts-2.7/nipype_cmd -> /home/ume/Enthought/Canopy_64bit/User/bin
changing mode of /home/ume/Enthought/Canopy_64bit/User/bin/nipype2boutiques to 755
changing mode of /home/ume/Enthought/Canopy_64bit/User/bin/nipype_display_crash to 755
changing mode of /home/ume/Enthought/Canopy_64bit/User/bin/nipype_cmd to 755
running install_egg_info
Writing /home/ume/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nipype-0.12.0_dev-py2.7.egg-info
<code><pre>
