### ISSUE TITLE
Failing node crashes entire workflow

### ISSUE THREAD

**Issue by m-guggenmos** [nipy/nipype#1197]
Although `stop_on_first_crash` and `stop_on_first_rerun` are set to `False`, my workflow crashes on the first unsuccessful node:

https://gist.github.com/monade/331bc9308ce575d70326

**Comment by satra** [comment]
are the remaining nodes dependent on that node? according to the output the workflow ran and reported the crash that occurred.

**Comment by mgxd** [comment]
@m-guggenmos feel free to open this if needed
