### ISSUE TITLE
model.SpecifySPMModel weird behavior

### ISSUE THREAD

**Issue by MartinPerez** [nipy/nipype#1198]
When there is only one event for a given condition for a given run. SpecifySPMModel will create the session_info file with the correct total number of onsets across runs for a condition, but it will ignore the durations when only one event is reported, leading to less total number of durations. Which will of course crash spm.Level1Design due to non matching total number of onsets and durations.

**Comment by satra** [comment]
@MartinPerez - are you specifying durations as shown in this example (note double brackets).

http://nipy.org/nipype/interfaces/generated/nipype.algorithms.modelgen.html#id1

**Comment by satra** [comment]
it also looks like this may be the source of the bug:

https://github.com/nipy/nipype/blob/3444b7588a1dea15675dc8a4f5be5f8b753adbd8/nipype/algorithms/modelgen.py#L478

**Comment by satra** [comment]
actually it appears to be fine:

```
    info = [Bunch(conditions=['cond1'], onsets=[[2]], durations=[[1]]),
            Bunch(conditions=['cond1'], onsets=[[3]], durations=[[1]])]
```

generates:

```
{'regress': [], 'cond': [{'onset': [2.0], 'duration': [1.0], 'name': 'cond1'}], 'hpf': 128.0, 'scans': '/tmp/test1.nii'}, {'regress': [], 'cond': [{'onset': [3.0], 'duration': [1.0], 'name': 'cond1'}], 'hpf': 128.0, 'scans': '/tmp/test2.nii'}
```

**Comment by MartinPerez** [comment]
I didnt pass the double brackets.... it works well with [2.0, 2.0] for example

**Comment by satra** [comment]
this is what i am getting with your inputs, which seems right - i'm using the current nipype master:

```
{'regress': [], 'cond': [{'onset': [2.0, 3.0], 'duration': [1.0, 1.0], 'name': 'cond1'},
{'onset': [2.0], 'duration': [1.0], 'name': 'cond2'}], 'hpf': 128.0, 'scans': '/test1.nii'},
{'regress': [], 'cond': [{'onset': [2.0, 3.0], 'duration': [1.0, 1.0], 'name': 'cond1'},
{'onset': [2.0, 4.0], 'duration': [1.0, 1.0], 'name': 'cond2'}], 'hpf': 128.0, 'scans': 'test2.nii'}
```

**Comment by MartinPerez** [comment]
i will retest and reinstall the master...

**Comment by MartinPerez** [comment]
@satra I confirm that the bug remains, with the release version and the current master of the development version.  

This is an session_info example of one of the categories when I create onsets = [20 , 40] and durations = [1, 2] for all conditions for 3 concatenated runs: {'onset': [20.0, 40.0, 348.5, 368.5, 677.0, 697.0], 'duration': [1.0, 2.0, 1.0, 2.0, 1.0, 2.0], 'name': '22'}. 

But when I create onsets = [20] and durations = [1] for all conditions in three concatenated runs this is what i get for the same example condition:  {'duration': [1.0], 'onset': [20.0, 348.5, 677.0], 'name': '22'}

As you can see the duration vector is returned only with the value of the first run, but all the values for the following concatenated runs were ommited for some reason. Basically this only affects the concatenated runs and not the first one.

**Comment by MartinPerez** [comment]
I will look in the code and try to fix this. Will post a branch with the fix as soon as I can :).
