### ISSUE TITLE
"parentheses" vs "curly brackets" m-file syntax for SPM should be defined in the interface not in base

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#12]
The way it is done right now limits extensibility (imagine someone inheriting from our SPMCommand and trying to set m-file style).

**Comment by djarecka** [comment]
is anyone working on it? I'm not sure if the last @satra commit was related to the original issue.

**Comment by djarecka** [comment]
will close it for now, please reopen if needed.
