### ISSUE TITLE
spm.EstimateModel fails for bayesian estimation

### ISSUE THREAD

**Issue by MartinPerez** [nipy/nipype#1211]
Traceback (most recent call last):
  File "pipelines/glm_sub_analysis_bayesian.py", line 281, in <module>
    delayed(glm_sub_analysis_bayesian)(*args) for args in pipe_args)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 660, in __call__
    self.retrieve()
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 543, in retrieve
    raise exception_type(report)
joblib.my_exceptions.JoblibAttributeError: JoblibAttributeError
___________________________________________________________________________
Multiprocessing exception:
    ...........................................................................
/media/mfpgt/MainDataDisk/PHD_research/FMRI_analysis/structrep1/pipelines/glm_sub_analysis_bayesian.py in <module>()
    276     # results = [results]
    277     # for args in pipe_args:
    278     #     glm_sub_analysis(*args)
    279 
    280     results = Parallel(n_jobs=n_proc, verbose=5)(
--> 281                      delayed(glm_sub_analysis_bayesian)(*args) for args in pipe_args)
    282 
    283     # pipe_args = []
    284     # for result in results:
    285     #     m = models_id.index(result[2])

...........................................................................
/usr/lib/python2.7/dist-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=5), iterable=<generator object <genexpr>>)
    655             if pre_dispatch == "all" or n_jobs == 1:
    656                 # The iterable was consumed all at once by the above for loop.
    657                 # No need to wait for async callbacks to trigger to
    658                 # consumption.
    659                 self._iterating = False
--> 660             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=5)>
    661             # Make sure that we get a last message telling us we are done
    662             elapsed_time = time.time() - self._start_time
    663             self._print('Done %3i out of %3i | elapsed: %s finished',
    664                         (len(self._output),

    ---------------------------------------------------------------------------
    Sub-process traceback:
    ---------------------------------------------------------------------------
    AttributeError                                     Fri Sep 11 23:39:51 2015
PID: 27466                                    Python 2.7.6: /usr/bin/python
...........................................................................
/media/mfpgt/MainDataDisk/PHD_research/FMRI_analysis/structrep1/pipelines/glm_sub_analysis_bayesian.py in glm_sub_analysis_bayesian(sub_id='002', task_id='001', model_id='001', runs=['pipelines/preprocessing/sub002/task001/run001_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run002_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run003_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run004_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run005_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run006_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run007_cr_bold.nii', 'pipelines/preprocessing/sub002/task001/run008_cr_bold.nii'], move_regres=['pipelines/preprocessing/sub002/task001/run001_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run002_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run003_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run004_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run005_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run006_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run007_realig_param.txt', 'pipelines/preprocessing/sub002/task001/run008_realig_param.txt'], mask='pipelines/preprocessing/sub002/highres001_brain_seg_gm.nii')
    185                            bases={'hrf': {'derivs': [1, 1]}},
    186                            timing_units='secs',
    187                            interscan_interval=TR,
    188                            mask_image=mask)
    189     results = level1estimate(spm_mat_file=results.outputs.spm_mat_file,
--> 190                              estimation_method={'Bayesian': 1})
    191 
    192     return [sub_id, task_id, model_id, results, subject_info]
    193 
    194 

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/caching/memory.pyc in __call__(self=PipeFunc(nipype.interfaces.spm.model.EstimateMod...1/pipelines/glm_sub_analysis_bayesian/nipype_mem), **kwargs={'estimation_method': {'Bayesian': 1}, 'spm_mat_file': '/media/mfpgt/MainDataDisk/PHD_research/FMRI_anal...l1Design/7039127335e9a3ba549a2f8b0b7d0eb7/SPM.mat'})
     77         node = Node(interface, name=job_name)
     78         node.base_dir = os.path.join(self.base_dir, dir_name)
     79 
     80         cwd = os.getcwd()
     81         try:
---> 82             out = node.run()
     83         finally:
     84             # node.run() changes to the node directory - if something goes wrong
     85             # before it cds back you would end up in strange places
     86             os.chdir(cwd)

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/pipeline/engine.pyc in run(self=0ccf45fb224506e3b4ac8e43f3e4d745, updatehash=False)
   1423             self.write_report(report_type='preexec', cwd=outdir)
   1424             savepkl(op.join(outdir, '_node.pklz'), self)
   1425             savepkl(op.join(outdir, '_inputs.pklz'),
   1426                     self.inputs.get_traitsfree())
   1427             try:
-> 1428                 self._run_interface()
   1429             except:
   1430                 os.remove(hashfile_unfinished)
   1431                 raise
   1432             shutil.move(hashfile_unfinished, hashfile)

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/pipeline/engine.pyc in _run_interface(self=0ccf45fb224506e3b4ac8e43f3e4d745, execute=True, updatehash=False)
   1533     def _run_interface(self, execute=True, updatehash=False):
   1534         if updatehash:
   1535             return
   1536         old_cwd = os.getcwd()
   1537         os.chdir(self.output_dir())
-> 1538         self._result = self._run_command(execute)
   1539         os.chdir(old_cwd)
   1540 
   1541     def _save_results(self, result, cwd):
   1542         resultsfile = op.join(cwd, 'result_%s.pklz' % self.name)

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/pipeline/engine.pyc in _run_command(self=0ccf45fb224506e3b4ac8e43f3e4d745, execute=True, copyfiles=True)
   1659                 fd = open(cmdfile, 'wt')
   1660                 fd.writelines(cmd + "\n")
   1661                 fd.close()
   1662                 logger.info('Running: %s' % cmd)
   1663             try:
-> 1664                 result = self._interface.run()
   1665             except Exception, msg:
   1666                 self._result.runtime.stderr = msg
   1667                 raise
   1668 

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/interfaces/base.pyc in run(self=<nipype.interfaces.spm.model.EstimateModel object>, **inputs={'estimation_method': {'Bayesian': 1}, 'ignore_exception': False, 'mfile': True, 'spm_mat_file': '/media/mfpgt/MainDataDisk/PHD_research/FMRI_anal...ateModel/0ccf45fb224506e3b4ac8e43f3e4d745/SPM.mat', 'use_v8struct': True})
   1020                         platform=platform.platform(),
   1021                         hostname=getfqdn(),
   1022                         version=self.version)
   1023         try:
   1024             runtime = self._run_wrapper(runtime)
-> 1025             outputs = self.aggregate_outputs(runtime)
   1026             runtime.endTime = dt.isoformat(dt.utcnow())
   1027             timediff = parseutc(runtime.endTime) - parseutc(runtime.startTime)
   1028             runtime.duration = timediff.days * 86400 + timediff.seconds + \
   1029                 timediff.microseconds/100000.

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/interfaces/base.pyc in aggregate_outputs(self=<nipype.interfaces.spm.model.EstimateModel object>, runtime=Bunch(cwd='/media/mfpgt/MainDataDisk/PHD_researc...timateModel failed to run. ",), version='8.5236'), needed_outputs=None)
   1091             return None
   1092 
   1093     def aggregate_outputs(self, runtime=None, needed_outputs=None):
   1094         """ Collate expected outputs and check for existence
   1095         """
-> 1096         predicted_outputs = self._list_outputs()
   1097         outputs = self._outputs()
   1098         if predicted_outputs:
   1099             _unavailable_outputs = []
   1100             if outputs:

...........................................................................
/usr/local/lib/python2.7/dist-packages/nipype-0.11.0_g8d624a4.dev-py2.7.egg/nipype/interfaces/spm/model.pyc in _list_outputs(self=<nipype.interfaces.spm.model.EstimateModel object>)
    224         else:
    225             mask = os.path.join(pth, 'mask.img')
    226         outputs['mask_image'] = mask
    227         spm = sio.loadmat(self.inputs.spm_mat_file, struct_as_record=False)
    228         betas = []
--> 229         for vbeta in spm['SPM'][0, 0].Vbeta[0]:
    230             betas.append(str(os.path.join(pth, vbeta.fname[0])))
    231         if betas:
    232             outputs['beta_images'] = betas
    233         if spm12:

AttributeError: 'mat_struct' object has no attribute 'Vbeta'
Interface EstimateModel failed to run. 
___________________________________________________________________________
make: *** [analyze] Error 1

**Comment by YukunQu** [comment]
Did you find the solution for this?
