### ISSUE TITLE
any clue why nosetests might demand having X DISPLAY?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#1217]
```
$> DISPLAY= PYTHONPATH=/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages MPLCONFIGDIR=/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/build nosetests  nipype    
Unable to access the X Display, is $DISPLAY set properly
```

**Comment by chrisfilo** [comment]
No idea. Could you try with debug?

**Comment by oesteban** [comment]
I think this is very related (or duplicated) to https://github.com/nipy/nipype/issues/1178

But we couldn't reproduce the situation. It must be related to some interfaces using tvtk.

**Comment by yarikoptic** [comment]
ok -- thanks -- known, thus closing, commented https://github.com/nipy/nipype/issues/1178#issuecomment-140783016
