### ISSUE TITLE
It does not work on Python 3.4

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1220]
Hi,
I put this post http://neurostars.org/p/3426/ regarding this.

Cheers,
Alex

**Comment by chrisfilo** [comment]
I believe @satra already started working on this: https://github.com/nipy/nipype/pull/1173 but I'm sure he would appreciate a helping hand.

**Comment by alexsavio** [comment]
Thanks for the reply @chrisfilo. :)
I spoke with @satra yesterday.
I am planning to adapt nipype to Python 3 anyway, I would like to check with the developers and users to see what is the best option so the PR is successful. :)
I would like you to help me deciding whether to use `python-future` or `six`.
Any opinion?
Thanks.

Cheers,
Alex

**Comment by satra** [comment]
@alexsavio - how about giving it a shot with `future`:

http://python-future.org/faq.html#relationship-between-python-future-and-other-compatibility-tools

i found future a lot better instrumented than six, and we don't care about those early python 2 versions.

**Comment by satra** [comment]
i also closed the other pull request so we can start fresh from current master.

**Comment by alexsavio** [comment]
For me it is the best option, it will look more like Python 3. 
Decision made: `future`. I will do a PR asap.

**Comment by bcipolli** [comment]
@alexsavio were you able to make any progress on this?

**Comment by alexsavio** [comment]
hi @bcipolli, I opened a PR #1221 some time ago. I made the mistake of doing it on the official repository when it was not ready yet. Please have a look, I have an open question there.

**Comment by alexsavio** [comment]
I am still working on it.

**Comment by bcipolli** [comment]
Is this fixed? We still had some failures on Windows that we weren't able to debug. Has a test run @ circle.ci passed on python 3.x?

**Comment by alexsavio** [comment]
Not so long ago I found a bug: #1288
I haven't been able to fully check @satra's suggestion yet, but will do it this week.
AFAIK circle.ci on python3 still has problems. I wish I knew how to help more.

**Comment by bcipolli** [comment]
Can we keep this issue open until those issues are resolved?

**Comment by alexsavio** [comment]
I guess so, also #1253 has not been merged yet...

**Comment by bcipolli** [comment]
#1253 doesn't even work haha. OK, hope someone can re-open until we have things properly working.

**Comment by chrisfilo** [comment]
Sorry - I closed this one because it's quite vague (it does not refer to any particular error in contrasts to #1288). I guess we can close it when #1253 is merged.

**Comment by oesteban** [comment]
I think this issue is outdated, feel free to reopen if I'm wrong.
