### ISSUE TITLE
fixed_image and moving_image have same description in ants.Registration docstring

### ISSUE THREAD

**Issue by dohmatob** [nipy/nipype#1223]
https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/registration.py#L21
In the documentation of the `fixed_image` param of ants.Registration, it's said "... image to which transformation will be applied..". I think this should be "... template / target image ...". In fact, it seems the `fixed_image` and `moving_image` params were mistakenly giving exactly the same documentation in the doctstring.

**Comment by satra** [comment]
@dohmatob - thanks for the check will update shortly.

**Comment by dohmatob** [comment]
OK @satra.
