### ISSUE TITLE
spm.EstimateContrast output not coherent with help() documentation

### ISSUE THREAD

**Issue by MartinPerez** [nipy/nipype#1226]
the output con_images and spmT_images also return ess_images and spmF_images respectively. From the documentation it would be expected that ess images and spmF files are only included in their outputs. Should this motivate a documentation change? or is there a mistake in the intended output?

**Comment by djarecka** [comment]
Hi @MartinPerez, can you please point to the website with incomplete description?

**Comment by MartinPerez** [comment]
Hi @djarecka this was a long time ago, might not even be relevant anymore, I am closing this.
