### ISSUE TITLE
Invalid shebang in pypi installs

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1227]
When I install nipy from pypi:

```
[chrisgor@sherlock-ln02 ~]$ pip install nipype
Collecting nipype
  Using cached nipype-0.11.0-py2-none-any.whl
Installing collected packages: nipype
Successfully installed nipype-0.11.0
```

The shbang is set incorrectly:

```
[chrisgor@sherlock-ln02 ~]$ head `which nipype_display_crash`
#!/home/travis/miniconda/envs/testenv/bin/python
"""Displays crash information from Nipype crash files. For certain crash files,
one can rerun a failed node in a temp directory.

Examples:

nipype_display_crash crashfile.pklz
nipype_display_crash crashfile.pklz -r -i
nipype_display_crash crashfile.pklz -r -i
```

When I install the same version from github:

```
[chrisgor@sherlock-ln02 ~]$ pip install https://github.com/nipy/nipype/archive/0.11.0.zip
Collecting https://github.com/nipy/nipype/archive/0.11.0.zip
  Downloading https://github.com/nipy/nipype/archive/0.11.0.zip
     | 3.5MB 42.0MB/s
Installing collected packages: nipype
  Running setup.py install for nipype
Successfully installed nipype-0.11.0
```

It is set correctly:

```
[chrisgor@sherlock-ln02 ~]$ head `which nipype_display_crash`
#!/share/PI/russpold/software/anaconda/bin/python
"""Displays crash information from Nipype crash files. For certain crash files,
one can rerun a failed node in a temp directory.

Examples:

nipype_display_crash crashfile.pklz
nipype_display_crash crashfile.pklz -r -i
nipype_display_crash crashfile.pklz -r -i
```

**Comment by jpellman** [comment]
+1

**Comment by satra** [comment]
removed the wheel package from pypi. should work now - while we figure out what's wrong with the travis wheel deployment.

**Comment by matthew-brett** [comment]
To have the scripts install correctly with setuptools, the shebang line for the script should be just `#!python` not `#!/usr/bin/env python` as currently.

**Comment by chrisfilo** [comment]
What's the difference?

**Comment by matthew-brett** [comment]
I can't find a good reference right now, but I believe setuptools (therefore pip) looks for `#!python` when bundling up a script into - for example - a wheel.  It leaves it as is, and then replaces it with the correct path to Python when installing from - for example - a wheel.  That's how a script installed from a wheel gets the correct Python path in its shebang line.

**Comment by satra** [comment]
@matthew-brett - thank you. in nipy all the scripts start with `#!/user/bin/env python`. is there a reason why it works there? or is it because you manually build a wheel and upload to pypi, whereas here we were asking travis to deploy to pypi?

**Comment by matthew-brett** [comment]
Yes, now I check, built wheels seem to do the right thing with `#!/usr/bin/env python`.  Hmm.  Maybe an Anaconda / pip interaction?

**Comment by satra** [comment]
perhaps it's a little more complicated. on my osx, if i build bdist_wheel, it builds fine and i can install it in a different linux server with the correct path. perhaps it's an issue with travis.

**Comment by matthew-brett** [comment]
Why not try the `#!python` shebang and see?

**Comment by satra** [comment]
@matthew-brett - we can try with the next release candidate.

**Comment by chrisfilo** [comment]
This has just regressed. After installing 0.12.0rc1 scripts have 

   #!/home/travis/miniconda2/envs/testenv/bin/python

shebang

**Comment by oesteban** [comment]
Could it be related to the fact that we use both distutils and setuptools? Could we switch to setuptools only (see recommendations here: https://packaging.python.org/current/)?

**Comment by satra** [comment]
@oesteban - would be worthwhile moving to pure setuptools. would also make setup.py simpler.

**Comment by mgxd** [comment]
@satra @chrisfilo could we close this now with the switch to pytest?

**Comment by satra** [comment]
this was addressed by uploading a wheel to pypi separately and not using travis to do `bdist_wheel`.
