### ISSUE TITLE
Nipype Beginner's Guide Normalize Example Error

### ISSUE THREAD

**Issue by AlphaJi** [nipy/nipype#1244]
I'm very new to nipype and neuroimaging. Recently, I run the Normalize Example from Nipype Beginner's Guide(http://miykael.github.io/nipype-beginner-s-guide/normalize.html).

There're 3 ways in this tutorial.

1. ANTs' complete normalization.

2. ANTs' partial normalization.

3. SPM's normalization.

In my case, No.2 and No.3 methods are OK. But when I run ANTs' complete normalization, I got the following error:

 

151004-02:18:12,335 workflow INFO:
     Executing: warpmean.a5 ID: 91
151004-02:18:12,342 workflow ERROR:
     ['Node warpmean.a5 failed to run on host lab-Computing.']
151004-02:18:12,342 workflow INFO:
     Saving crash info to /media/lab/jizhe_sdb4/Jizhe/nipype_tutorial/crash-20151004-021812-lab-warpmean.a5.pklz
151004-02:18:12,342 workflow INFO:
     Traceback (most recent call last):
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 369, in _send_procs_to_workers
    jobid].hash_exists()
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1292, in hash_exists
    hashed_inputs, hashvalue = self._get_hashval()
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1463, in _get_hashval
    self._get_inputs()
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1523, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1271, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/home/lab/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1768, in validate
    value = super(MultiPath, self).validate(object, name, newvalue)
  File "/home/lab/anaconda/lib/python2.7/site-packages/traits/trait_types.py", line 2201, in validate
    return TraitListObject( self, object, name, value )
  File "/home/lab/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 2309, in __init__
    raise excp
TraitError: Each element of the 'transforms' trait of an ApplyTransformsInputSpec instance must be an existing file name, but a value of '/' <type 'str'> was specified.
Error setting node input:
Node: warpmean
input: transforms
results_file: /media/lab/jizhe_sdb4/Jizhe/nipype_tutorial/workingdir_fMRI_example_norm_ants_complete/normflow/_subject_id_sub006/mergexfm/result_mergexfm.pklz
value: ['/', '/media/lab/jizhe_sdb4/Jizhe/nipype_tutorial/workingdir_fMRI_example_norm_ants_complete/normflow/_subject_id_sub006/convert2itk/affine.txt']

Anyone got any idea? Thanks!

**Comment by chrisfilo** [comment]
Are you using the latest version of nipype? How is the "transforms" input
of ApplyTransforms set in your code?

**Comment by AlphaJi** [comment]
Yeah, I'm using the latest version 0.11.0 of nipype. What do you mean "how is the "transforms" input of ApplyTransforms?
Do you mean this code?
warpmean = Node(ApplyTransforms(args='--float',
                                input_image_type=3,
                                interpolation='Linear',
                                invert_transform_flags=[False, False],
                                num_threads=1,
                                reference_image=template,
                                terminal_output='file'),
                name='warpmean')

**Comment by chrisfilo** [comment]
have a look at the updates to the beginner guide I made to solve this issue

**Comment by AlphaJi** [comment]
Thanks very much, it's OK now.

**Comment by miykael** [comment]
Hey @chrisfilo, thanks for the corrections. And @AlphaJi, thanks for pointing this out.
