### ISSUE TITLE
artifact detect error

### ISSUE THREAD

**Issue by jianhounj** [nipy/nipype#1246]
Hi all,
I'd like to specify the threshold to use to detect translation (rotation)- related outliers and I used the following codes:

from nipype.algorithms.rapidart import ArtifactDetect
ad = ArtifactDetect()
ad.inputs.realigned_files = 'wua20121108_101950RestMultiModesub3s002a001.nii'
ad.inputs.realignment_parameters = 'rp_a20121108_101950RestMultiModesub3s002a001.txt'
ad.inputs.parameter_source = 'SPM'
ad.inputs.zintensity_threshold = 2.5
ad.inputs.rotation_threshold = 0.02
ad.inputs.translation_threshold = 1
ad.inputs.use_differences = [True, False]
ad.inputs.mask_type = 'spm_global'
ad.run()

However, I got an error message which read ArtifactDetect requires a value for input 'use_norm' because one of norm_threshold is set. 
How could I do it in the right way? 
Thanks in advance!
Jian Hou

**Comment by satra** [comment]
@jianhounj - i think this will fix it - essentially there is a default value for `use_norm`

if you do the following before you call run, it should execute.

```python
from nipype.interfaces.base import Undefined
ad.inputs.use_norm = Undefined
```

**Comment by jianhounj** [comment]
Hi Satra,
Thank you very much for your help, it works.
Best regard.
Jian Hou
