### ISSUE TITLE
Return code: -11 Interface Label2Vol failed to run ERROR

### ISSUE THREAD

**Issue by smrym** [nipy/nipype#1250]
Hi there,

I'm a new user of nipype. My research group is currently using the software to create a neuroimaging pipeline which we plan on using to track the progression of Alzheimer's Disease. I'm trying to use the Label2Vol freesurfer interface to push labels from freesurfer space to our subjects' original T1 space but I'm not able to get it to run. The command itself works fine on my local machine but when I wrap the interface in a node, this is what I get:

 

151014-10:26:31,737 workflow INFO:
     Executing node aseg2raw in dir: /tmp/tmpUj4qzA/aseg2raw
151014-10:26:31,767 workflow INFO:
     Running: mri_label2vol --regheader /scratch/o/olegm/olegm/2015/test_waj/aseg.mgz --seg /tmp/tmpUj4qzA/aseg2raw/aseg.mgz --temp /scratch/o/olegm/olegm/2015/test_waj/rawavg.mgz --o /tmp/tmpUj4qzA/aseg2raw/aseg_vol.nii.gz
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Number of labels: 0
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Annot File:      (null)
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Template Volume: /scratch/o/olegm/olegm/2015/test_waj/rawavg.mgz
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Outut Volume: /tmp/tmpUj4qzA/aseg2raw/aseg_vol.nii.gz
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Registration File: (null)
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Fill Threshold: 0
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Label Vox Vol:  1
151014-10:26:37,56 interface INFO:
     stdout 2015-10-14T10:26:37.056101:ProjType:       (null)
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:ProjTypeId:     0
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:ProjStart:      0
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:ProjStop:       0
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:ProjDelta:      0.1
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Subject:  (null)
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Hemi:     (null)
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:UseNewASeg2Vol:  1
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:DoLabelStatVol  0
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:LabelCodeOffset  0
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:setenv SUBJECTS_DIR /scratch/o/olegm/olegm/subjects
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:$Id: mri_label2vol.c,v 1.34.2.5 2012/06/08 17:31:03 greve Exp $
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:Template RAS-to-Vox: --------
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:-0.985   0.000   0.000   128.000;
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:-0.000  -0.000  -0.985   128.000;
151014-10:26:37,57 interface INFO:
     stdout 2015-10-14T10:26:37.056101:-0.000   0.833  -0.000   98.000;
151014-10:26:37,58 interface INFO:
     stdout 2015-10-14T10:26:37.056101: 0.000   0.000   0.000   1.000;
151014-10:26:40,197 interface INFO:
     stdout 2015-10-14T10:26:40.197818:Template Voxel Volume: 1.23773
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818:nHits Thresh: 0
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818:Computing registration based on header
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818:RegMat: --------
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 1.000   0.000   0.000  -0.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   1.000   0.000   0.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   0.000   1.000   0.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   0.000   0.000   1.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818:Label RAS-to-Vox: --------
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818:-0.985   0.000   0.000   128.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   0.000  -0.985   128.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   0.833   0.000   98.000;
151014-10:26:40,198 interface INFO:
     stdout 2015-10-14T10:26:40.197818: 0.000   0.000   0.000   1.000;
151014-10:26:41,251 interface INFO:
     stdout 2015-10-14T10:26:41.251470:ASeg2Vol: Building LUT
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    aseg2raw.run()
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/interfaces/freesurfer/base.py", line 125, in run
    return super(FSCommand, self).run(**inputs)
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1447, in _run_interface
    self.raise_exception(runtime)
  File "/home/o/olegm/olegm/opt/pip/env/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1376, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
mri_label2vol --regheader /scratch/o/olegm/olegm/2015/test_waj/aseg.mgz --seg /tmp/tmpUj4qzA/aseg2raw/aseg.mgz --temp /scratch/o/olegm/olegm/2015/test_waj/rawavg.mgz --o /tmp/tmpUj4qzA/aseg2raw/aseg_vol.nii.gz
Standard output:
Number of labels: 0
Annot File:      (null)
Template Volume: /scratch/o/olegm/olegm/2015/test_waj/rawavg.mgz
Outut Volume: /tmp/tmpUj4qzA/aseg2raw/aseg_vol.nii.gz
Registration File: (null)
Fill Threshold: 0
Label Vox Vol:  1
ProjType:       (null)
ProjTypeId:     0
ProjStart:      0
ProjStop:       0
ProjDelta:      0.1
Subject:  (null)
Hemi:     (null)
UseNewASeg2Vol:  1
DoLabelStatVol  0
LabelCodeOffset  0
setenv SUBJECTS_DIR /scratch/o/olegm/olegm/subjects
$Id: mri_label2vol.c,v 1.34.2.5 2012/06/08 17:31:03 greve Exp $
Template RAS-to-Vox: --------
-0.985   0.000   0.000   128.000;
-0.000  -0.000  -0.985   128.000;
-0.000   0.833  -0.000   98.000;
 0.000   0.000   0.000   1.000;
Template Voxel Volume: 1.23773
nHits Thresh: 0
Computing registration based on header
RegMat: --------
 1.000   0.000   0.000  -0.000;
 0.000   1.000   0.000   0.000;
 0.000   0.000   1.000   0.000;
 0.000   0.000   0.000   1.000;
Label RAS-to-Vox: --------
-0.985   0.000   0.000   128.000;
 0.000   0.000  -0.985   128.000;
 0.000   0.833   0.000   98.000;
 0.000   0.000   0.000   1.000;
ASeg2Vol: Building LUT
Standard error:

Return code: -11
Interface Label2Vol failed to run.

I've tried searching online but I haven't found anything. I have no idea what Return code -11 means. I really need to get this pipeline up and running so we can take our research to the next stage. What am I missing?

Any help would be greatly appreciated!!! Thanks in advance.

Thanks,

Maryam

**Comment by satra** [comment]
that return code is from the freesurfer tool, and likely a segmentation fault.

you can try running the command line directly

`mri_label2vol --regheader /scratch/o/olegm/olegm/2015/test_waj/aseg.mgz --seg /tmp/tmpUj4qzA/aseg2raw/aseg.mgz --temp /scratch/o/olegm/olegm/2015/test_waj/rawavg.mgz --o /tmp/tmpUj4qzA/aseg2raw/aseg_vol.nii.gz`

but it seems the error may come from `Number of labels: 0`

**Comment by smrym** [comment]
Thanks very much for looking into this so quickly! I ran it on the command line directly and yes it does indeed seem to be a segmentation fault. But I don't see how number of labels: 0 is a problem? Because I thought labels/annotation files/seg files were mutually exclusive inputs for Label2Vol, and I am providing it the aseg file as input...

**Comment by satra** [comment]
it's unlikely, unless the aseg file is corrupted. if not, you may want to post on the freesurfer list.

**Comment by smrym** [comment]
Okay, thanks again for your help!
