### ISSUE TITLE
Writing ANTs scripts in nipype

### ISSUE THREAD

**Issue by blakedewey** [nipy/nipype#1252]
I use a couple of the ANTs scripts on a regular basis (brain extraction, template creation). I know we have already created wrappers for most of them, but have we ever considered porting some of them to niype as workflows? It seems like they have a lot of boilerplate with parallel processes that we could handle very well (especially since my template creation just passed the 4 day mark). We couldn't replicate the XGrid functionality that they have. This might be a good way to pick out their "current and best" and open it up to people to use in their nipype work.

**Comment by djarecka** [comment]
Hi @blakedewey, is this something that you still consider worth doing? Has anyone been working on it?

**Comment by blakedewey** [comment]
I don't know if there is strong interest anymore. My workflows have deviated quite a bit from these scripts, just over years of customization, but I suppose there could still be interest.

**Comment by djarecka** [comment]
closing this for now, if anyone is still interested in it a new issue can be open
