### ISSUE TITLE
nipype_display_crash not working

### ISSUE THREAD

**Issue by nakohli** [nipy/nipype#1254]
Hi,

I have the `0.11.0` version of nipype installed on my machine. On running `nipype_display_crash` on the terminal, I get the following error:

`/home/travis/miniconda/envs/testenv/bin/python: bad interpreter: No such file or directory`

I am not sure where it is finding `travis` from since that is not my machine name. It seems to have hardcoded the python location as far as I am able to understand.

Could you let me know how this can be fixed ?

**Comment by oesteban** [comment]
I think this is duplicated of https://github.com/nipy/nipype/issues/1227
