### ISSUE TITLE
slicer cmd line tools not working

### ISSUE THREAD

**Issue by mrjeffs** [nipy/nipype#1257]
hello nipypers, just got the skinny from steve pieper about how slicer now sorts out paths and env variables. when i try to use the nipype to slicer CLI functionality i get the same lib not found errors as in the terminal. he sent these 2 links to update how slicer now handles this issue:
http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Launcher
http://www.na-mic.org/Bug/view.php?id=3212
How can this be integrated into nipype so slicer CLIs can work as documented?
jeff

**Comment by djarecka** [comment]
Hi @mrjeffs, sorry that you didn't get any answer sooner. Please let us know if you still have this question.

**Comment by djarecka** [comment]
@mrjeffs - I'm closing this issue now, but please feel free to reopen
