### ISSUE TITLE
Changing node directories within a workflow

### ISSUE THREAD

**Issue by smrym** [nipy/nipype#1258]
Hello,
I'm trying to run a workflow in nipype to process MRI data for our neuroimaging pipeline. I'm trying to modify an existing structure that was set up by one of the members of our research group who unfortunately no longer works with us. The new nodes that I'm defining in our workflow end up executing outside our working directory because I am not connecting them to the nodes that are first to be executed. Is there a way of changing their working directory within the workflow?

Any help would be highly appreciated!

Thanks 
Maryam

**Comment by satra** [comment]
nodes in a workflow will always run within the base directory of the workflow. if the base directory is not set, it will run in a temp directory.

**Comment by smrym** [comment]
Oh sorry, I should've specified. The way our workflow has been set up, all the nodes are executed within a certain directory inside our base directory. So when I try to set up a new node it is executed within our base directory but not in the directory that all the other nodes are being run in. When I'm trying to connect the new nodes to the old ones, I'm getting an error. Is there a way around this problem?
