### ISSUE TITLE
Setting up Nipype's IdentityInterface and SelectFiles node for database with multiple subjects and scans

### ISSUE THREAD

**Issue by smrym** [nipy/nipype#1265]
Hi,

So I have been trying to configure nipype's identityinterface and the datagrabber/selectfiles node to pick up data from our database's specific structure. Specifically, I have to extract T1, T2 and DTI images for each of our subjects from the database. Roughly, the structure is as follows:

base_directory/subj001/T1/scan_date1/*/*.dcm
base_directory/subj001/T1/scan_date2/*/*.dcm
base_directory/subj001/T2/scan_date1/*/*.dcm
base_directory/subj001/T2/scan_date2/*/*.dcm 
base_directory/subj001/DTI/scan_date1/*/*.dcm
base_directoy/subj001/DTI/scan_date2/*/*.dcm

base_directory/subj002/T1/scan_date/*/*.dcm
base_directory/subj002/T2/scan_date/*/*.dcm
base_directory/subj002/DTI/scan_date/*/*.dcm

 and so on. So as you can see, we sometimes have multiple scans for each subject while other times we just have a single scan. Each scan series has to be processed together by our nipype workflow, so that subj001's T1, T2 and DTI for scan_date1 will be processed together and stored in a separate folder, and the same subj001's T1, T2 and DTI for scan_date2 should be processed and stored in a separate folder etc.

I'm not sure how to do this with the selectfiles node. If anyone has any suggestions, I'd be interested to hear them. Any help would be greatly appreciated.

Thanks,
Maryam

**Comment by oesteban** [comment]
Hi @smrym , did you get to solve your question by yourself?.

In any case, our apologies for not answering until now. It's really hard to find time for maintenance and support.

**Comment by mwaskom** [comment]
This kind of question might get a better response on https://neurostars.org, where it will be seen by other users who might be able to answer (whereas people reading issues are mostly only developers).

**Comment by oesteban** [comment]
+1
Indeed https://neurostars.org has a greater reach out and is a more appropriate forum for these questions. Please post the question in neurostars if it's still an open problem.
