### ISSUE TITLE
`future` package import

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1271]
Building the live version (https://github.com/nipy/nipype/tree/923fa055cd809829326c2c0c64a83de95f94c389) fails on my machines with:

`RuntimeError: Cannot import package "future" - is it installed?` 

I believe [this check](https://github.com/nipy/nipype/blob/master/setup.py#L274) is to blame. Are you sure you are not referring to `__future__` with the underscores?

Version 0.11.0 by comparison builds just fine.

**Comment by satra** [comment]
the current dev version adds a dependency on `python-future`

**Comment by TheChymera** [comment]
but it seems to me the module name is still `__future__`, no?
https://pypi.python.org/pypi/future

**Comment by satra** [comment]
not quite. the `__future__` is from python, the additions are in `builtins`, `future` and other modules.

**Comment by ImmanuelSamuel** [comment]
I am getting the same error.

**Comment by TheChymera** [comment]
@ImmanuelSamuel  Same error as mine. What distribution are you on?

**Comment by ImmanuelSamuel** [comment]
I am using anaconda3

**Comment by ImmanuelSamuel** [comment]
clean install cleared the error

**Comment by alexsavio** [comment]
Hi @TheChymera are you still having problems? Can I close this?
