### ISSUE TITLE
memory allocation error

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1274]
As part of a workflow I am getting this error:

```
Standard error:
terminate called after throwing an instance of 'itk::MemoryAllocationError'
what():  /var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/ITKv4-install/include/ITK-4.9/itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
Return code: -6
Interface ApplyTransforms failed to run. 
```

Any idea what I can try to do about it?

**Comment by blakedewey** [comment]
This looks like it is because you don't have enough free RAM to load the image into. Is this a large image file or do you have a small amount of free RAM available to ITK? For a linux system, typing `free -m` will give an output of the free memory available (in megabytes).

**Comment by TheChymera** [comment]
Yes, I think that might be it - just before stuff crashes, I end up with only ~200MB of my 30 GB free....

What can I do about this? If I run the commands sequentially from the command line, I have more than enough memory to go through everytjing. I guess my multithreading is to blame. but I would have expecited nipype to take my memory into consideration when spawning all those paralell nodes - how can I tell ti to go paralell but be careful at this step?

**Comment by blakedewey** [comment]
Because nipype has no idea how much memory a task will take it cannot monitor that. If you use a task management system such as SGE or PBS, you can specify memory requirements that SGE or PBS will take into account, but `MultiProc` has no such mechanisms.

**Comment by TheChymera** [comment]
@blakedewey can I turn multiproc off fot his step and only this step? alternatively, can I tell nipype to re-run nodes that failed because of lack of memory?

**Comment by blakedewey** [comment]
Unfortunately, no. You can rerun the entire workflow manually and it will only rerun the failed nodes/subnodes. However, since you are using ANTs, you could try setting num_threads in each of your ANTs nodes to 2 or 3 and then dividing the n_procs in your workflow by the same amount. ANTs is multithreaded so it will speed up the ANTs commands but not allocate any more memory.

**Comment by TheChymera** [comment]
@blakedewey  Am I correct to assume that this would restrict the number of processors used by all other nodes that do not take a `num_threads` argument?

**Comment by blakedewey** [comment]
Yes. Then you would be restricted to the n_procs parameter.

**Comment by TheChymera** [comment]
@blakedewey the [class I am using](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/resampling.py#L209), does not have a `num_thread` attribute. What can I do?

**Comment by blakedewey** [comment]
Actually, it does! It is inherited from the ANTSCommandInputSpec class.

**Comment by TheChymera** [comment]
ah, ok, thanks :) I'll test this out tomorrow.

**Comment by TheChymera** [comment]
Ok, this worked. Wow, I have to say, ANTs sure needs a lot of memory to apply those transformations!
