### ISSUE TITLE
Where is the `crashdumpdir` config parameter?

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1277]
Hi,

In this file: http://nipy.org/nipype/users/tutorial_103.html, you mention a `crashdumpdir` parameter, but the reference to the documentation is broken.
Does this parameter still exist? 
How can be documentation be corrected?

**Comment by blakedewey** [comment]
The `crashdumpdir` parameter is a part of the workflow config. It is not normally specified in the config file (although maybe it could be?). I normally use:
`workflow.config['execution']['crashdump_dir'] = os.path.join(workflow.base_dir, workflow.name)`
When creating my workflows as it puts my crash files into my workflow directory.

**Comment by alexsavio** [comment]
Thanks @blakedewey!
