### ISSUE TITLE
String to float in Python3

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1288]
I am using fsl.ImageStats to calculate the mean value of a masked region in an image.

When I run it in one core, i.e., `wf.run()`, it works perfectly. However, when I try to run with 
`wf.run("MultiProc", plugin_args={"n_procs": n_cpus})`, I get a conversion error:

```
ValueError: could not convert string to float: "b'2593.792524"
Interface ImageStats failed to run. 
```
This seems to be bytes conversion to unicode done wrongly somewhere. My main question is: what is the difference when running with `MultiProc`? Or why is the `runtime` argument different when running with `MultiProc`?

The pklz file in this case is useless (no clue why), I can't debug it, `nipype_display_crash` only displays the traceback.
A .pklz file is here: https://www.dropbox.com/s/q6e873yt29l3yar/crash-20151208-210258-alexandre-mean_value.a020.pklz?dl=1

Can anyone help me? Maybe @bcipolli can help me, we were working on this together.

```
File: /home/alexandre/data/ftlad/wd/main_workflow/log/crash-20151208-210258-alexandre-mean_value.a020.pklz
Node: main_workflow.spm_mrpet_preproc.intensity_norm_gm.mean_value.a020
Working directory: /home/alexandre/data/ftlad/wd/main_workflow/spm_mrpet_preproc/intensity_norm_gm/_session_id_session_0_subject_id_ap_1959/mean_value


Node inputs:

args = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
ignore_exception = False
in_file = /home/alexandre/data/ftlad/wd/main_workflow/spm_mrpet_preproc/_session_id_session_0_subject_id_ap_1959/rbvpvc/rpet_fdg_rbv_pvc.nii.gz
mask_file = /home/alexandre/data/ftlad/wd/main_workflow/spm_anat_preproc/_session_id_session_0_subject_id_ap_1959/new_segment/c1anat_hc_corrected.nii
op_string = -M -k %s
output_type = NIFTI_GZ
split_4d = <undefined>
terminal_output = stream



Traceback: 
Traceback (most recent call last):
  File "/home/alexandre/Software/nipype/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/alexandre/Software/nipype/nipype/pipeline/engine.py", line 1430, in run
    self._run_interface()
  File "/home/alexandre/Software/nipype/nipype/pipeline/engine.py", line 1540, in _run_interface
    self._result = self._run_command(execute)
  File "/home/alexandre/Software/nipype/nipype/pipeline/engine.py", line 1666, in _run_command
    result = self._interface.run()
  File "/home/alexandre/Software/nipype/nipype/interfaces/base.py", line 1046, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/alexandre/Software/nipype/nipype/interfaces/fsl/utils.py", line 575, in aggregate_outputs
    out_stat.append([float(val) for val in values])
  File "/home/alexandre/Software/nipype/nipype/interfaces/fsl/utils.py", line 575, in <listcomp>
    out_stat.append([float(val) for val in values])
ValueError: could not convert string to float: "b'1903.459336"
Interface ImageStats failed to run.
```

**Comment by bcipolli** [comment]
You are running Python 3? If so, any chance you could try with Python 2 and report the results?

**Comment by alexsavio** [comment]
Thanks @bcipolli.
The first error I get is: 
'''
TraitError: The 'base_directory' trait of a DataSinkInputSpec instance must be a directory name, but a value of u'/home/alexandre/data/ftlad/out_tst' <type 'unicode'> was specified.
'''

**Comment by bcipolli** [comment]
Yes, exactly--looks like the Python 2/3 compatibility code is failing in both cases (2 and 3). I wouldn't be able to take a look until next week; is it something you could debug?

**Comment by alexsavio** [comment]
Thanks @bcipolli. Yes, I will keep looking at this.
I made a short test. I guess this should work, right? I mean, passing unicode instead of str.
```
#!/usr/bin/env python

from nipype.interfaces.io import DataSink

datasink = DataSink(parameterization=False,
                                 base_directory=(u'/home/trash'))
```

**Comment by alexsavio** [comment]
One bug seems to be in the `fast_validate` type argument in case where a File or Directory don't exist and maybe also in the base class of `BaseFile` and `BaseDirectory`.

https://github.com/nipy/nipype/blob/master/nipype/interfaces/traits_extension.py#L83
https://github.com/nipy/nipype/blob/master/nipype/interfaces/traits_extension.py#L172

I tried many options using `from ..external.six import string_types` but also `future` `builtins`, I could not find one solution that worked for both Python 2 and 3.

How much faster is the `fast_validate`? X'D

**Comment by satra** [comment]
@alexsavio - there seems to be a few different issues here. for your original issue, would you mind checking this branch?

https://github.com/satra/nipype/tree/fix/use_current_prov

i just submitted this commit: https://github.com/satra/nipype/commit/678c3f1b459828e1e35d4f8cea367ce64850243a

**Comment by alexsavio** [comment]
hi @satra, thanks for that. I had to wait for Monday to access the data to try this again. Sadly your branch also spat the same error for me.

It is strange because when I run it without any MultiProc plugin, it runs fine.

If you look at the value the exception gives, the unpaired quotes are strange:
```
ValueError: could not convert string to float: "b'2595.743099"
```

**Comment by satra** [comment]
@alexsavio - would it be possible to create a small self-contained example for this and share it via dropbox or some such? that would help me debug this. i'm pretty positive this is one of those strange unicode vs bytes (that's what the b stands for) cases that needs to be cleaned up. essentially, the fslstats interface is reading the output from subprocess and converting it to floats.

**Comment by alexsavio** [comment]
hi @satra, thanks for that.
With this was enough to see the error: 
https://www.dropbox.com/s/msk3xdw90cvrx9p/nipype_issue1288_test.tar.gz?dl=1

Thanks,
Alex

**Comment by alexsavio** [comment]
This has been solved, testing nipype/master. Thanks!
