### ISSUE TITLE
question on MRtrix2TrackVis

### ISSUE THREAD

**Issue by xixizhao** [nipy/nipype#1300]
Hi, I have a problem when I try to convert my Mrtrix .tck file to TrackVis .trk file. I ran the following lines:

import nipype.interfaces.mrtrix as mrt
tck2trk = mrt.MRTrix2TrackVis()
tck2trk.inputs.in_file = '/data/newxi/123.tck'
tck2trk.inputs.image_file = '/data/newxi/data.nii'
tck2trk.run()

and then something bad occurs.
It reports like following:

151216-22:41:53,853 interface INFO:
	 Reading header data...
151216-22:41:53,854 interface INFO:
	 ...adding "/data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/encoding_invX.b" to header for key "DW_scheme"
151216-22:41:53,854 interface INFO:
	 ...adding "3" to header for key "downsample_factor"
151216-22:41:53,854 interface INFO:
	 ...adding "0.25" to header for key "fod_power"
151216-22:41:53,854 interface INFO:
	 ...adding "0.1" to header for key "init_threshold"
151216-22:41:53,854 interface INFO:
	 ...adding "8" to header for key "lmax"
151216-22:41:53,854 interface INFO:
	 ...adding "6.72211" to header for key "max_angle"
151216-22:41:53,854 interface INFO:
	 ...adding "200.83" to header for key "max_dist"
151216-22:41:53,855 interface INFO:
	 ...adding "500000" to header for key "max_num_attempts"
151216-22:41:53,855 interface INFO:
	 ...adding "5000" to header for key "max_num_tracks"
151216-22:41:53,855 interface INFO:
	 ...adding "1" to header for key "max_seed_attempts"
151216-22:41:53,855 interface INFO:
	 ...adding "1000" to header for key "max_trials"
151216-22:41:53,855 interface INFO:
	 ...adding "iFOD2" to header for key "method"
151216-22:41:53,855 interface INFO:
	 ...adding "10" to header for key "min_dist"
151216-22:41:53,855 interface INFO:
	 ...adding "0.15" to header for key "output_step_size"
151216-22:41:53,855 interface INFO:
	 ...adding "0" to header for key "rk4"
151216-22:41:53,855 interface INFO:
	 ...adding "4" to header for key "samples_per_step"
151216-22:41:53,855 interface INFO:
	 ...adding "1" to header for key "sh_precomputed"
151216-22:41:53,855 interface INFO:
	 ...adding "/data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/CSD_FOD_l8.nii" to header for key "source"
151216-22:41:53,856 interface INFO:
	 ...adding "0.15" to header for key "step_size"
151216-22:41:53,856 interface INFO:
	 ...adding "0" to header for key "stop_on_all_include"
151216-22:41:53,856 interface INFO:
	 ...adding "0.1" to header for key "threshold"
151216-22:41:53,856 interface INFO:
	 ...adding "1430663656.6225910187" to header for key "timestamp"
151216-22:41:53,856 interface INFO:
	 ...adding "0" to header for key "unidirectional"
151216-22:41:53,856 interface INFO:
	 ...adding "seed nodif_brain_mask.nii.gz" to header for key "roi"
151216-22:41:53,856 interface INFO:
	 ...adding "include /data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/ROIL.nii.gz" to header for key "roi"
151216-22:41:53,856 interface INFO:
	 ...adding "include /data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/ROIL.nii.gz" to header for key "roi"
151216-22:41:53,856 interface INFO:
	 ...adding "mask /data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space/nodif_brain_mask.nii.gz" to header for key "roi"
151216-22:41:53,856 interface INFO:
	 ...adding "mask /data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space/nodif_brain_mask.nii.gz" to header for key "roi"
151216-22:41:53,856 interface INFO:
	 ...adding "Float32LE" to header for key "datatype"
151216-22:41:53,857 interface INFO:
	 ...adding ". 1152" to header for key "file"
151216-22:41:53,857 interface INFO:
	 ...adding "5000" to header for key "count"
151216-22:41:53,857 interface INFO:
	 ...adding "127516" to header for key "total_count"
151216-22:41:53,857 interface INFO:
	 Reached the end of the header!
151216-22:41:53,857 interface INFO:
	 Identifying the number of points per tract...
151216-22:41:54,147 interface INFO:
	 MRTrix Header:
151216-22:41:54,147 interface INFO:
	 {'roi': 'mask /data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space/nodif_brain_mask.nii.gz', 'max_dist': '200.83', 'file': '. 1152', 'threshold': '0.1', 'DW_scheme': '/data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/encoding_invX.b', 'output_step_size': '0.15', 'max_num_attempts': '500000', 'downsample_factor': '3', 'source': '/data/nodexi/task/ADHD20150210/results_bet02/ADHD2/010002/native_space_tracking/CSD_FOD_l8.nii', 'step_size': '0.15', 'method': 'iFOD2', 'rk4': '0', 'min_dist': '10', 'init_threshold': '0.1', 'timestamp': '1430663656.6225910187', 'samples_per_step': '4', 'offset': 1152, 'fod_power': '0.25', 'stop_on_all_include': '0', 'max_angle': '6.72211', 'count': 5000, 'max_seed_attempts': '1', 'max_num_tracks': '5000', 'sh_precomputed': '1', 'total_count': '127516', 'max_trials': '1000', 'datatype': 'Float32LE', 'lmax': '8', 'unidirectional': '0'}
151216-22:41:54,147 interface INFO:
	 Applying transformation from scanner coordinates to /data/newxi/data.nii
Traceback (most recent call last):
  File "MRtrix2TrackVistest", line 5, in <module>
    tck2trk.run()
  File "/usr/lib/pymodules/python2.7/nipype/interfaces/base.py", line 946, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib/pymodules/python2.7/nipype/interfaces/mrtrix/convert.py", line 220, in _run_interface
    transformed_streamlines = transform_to_affine(streamlines, trk_header, affine)
  File "/usr/lib/pymodules/python2.7/nipype/interfaces/mrtrix/convert.py", line 41, in transform_to_affine
    streams = move_streamlines(streams, rotation)
NameError: global name 'move_streamlines' is not defined
Interface MRTrix2TrackVis failed to run. 

Hoping for your reply.

**Comment by oesteban** [comment]
Hi @xixizhao, in order to run that conversion you will also need to install dipy. Dipy contains the function ```move_streamlines``` causing the trouble. From your output:

```
NameError: global name 'move_streamlines' is not defined
```

**Comment by xixizhao** [comment]
Thanks a lot, it works.
