### ISSUE TITLE
"JitterNode" that delays writing output

### ISSUE THREAD

**Issue by mattcieslak** [nipy/nipype#1315]
Hi everyone,

I've been running nipype on a cluster that doesn't have any other users yet.  One issue I'm running into is that since all the jobs finish at roughly the same time, the datasinks and nodes that write out big files all try to write to an nfs mount at the same time.  This tends to make writes very slow and causes the nfs mount to behave erratically.  Would it make sense to put these interfaces into a node that waits a random amount of time before writing?  I tried something like this:

``` python
from nipype.pipeline.engine import Node
import time
import random

class JitterNode(Node):
    def __init__(self,interface,name,sleepmin=5,sleepmax=300,
            sleepexact=None, **kwargs):
        super(JitterNode,self).__init__(interface,name,**kwargs)
        if sleepexact is None:
            self.sleeptime = random.randint(sleepmin,sleepmax)
        else:
            self.sleeptime = sleepexact

    def _run_command(self, execute, copyfiles=True):
        """sleeps prior to delegating to the superclass."""
        print "sleeping", self.sleeptime
        time.sleep(self.sleeptime)
        return super(JitterNode, self)._run_command(execute, copyfiles)

```

When put into a serial pipeline

``` python
import nipype.interfaces.utility as util     
import nipype.pipeline.engine as pe          

infosource = pe.Node(interface=util.IdentityInterface(fields=["subject_id"]),
                    name="infosource")
infosource.iterables = [("subject_id",["a","b","c","d"])]

def dumb_function(input_subject):
    print input_subject

dumb_node = JitterNode(interface=util.Function(
        input_names=["input_subject"],
        output_names=["nothing"],
        function=dumb_function),name="dumb_node", sleepexact=30)
flow = pe.Workflow(name="test_flow")

flow.connect([(infosource,dumb_node,[("subject_id", "input_subject")])])
```

it behaves as expected: `%timeit flow.run()` shows `1 loops, best of 3: 2min per loop`  but when running in parallel it takes longer than expected: `%timeit flow.run(plugin="MultiProc",plugin_args={'n_procs':4})` I get `1 loops, best of 3: 1min per loop`.  I thought this should be around 30sec per loop since that's what I set the sleep time to in the node constructor. 

Is this the best way to try to spread out disk writes or have I missed something simpler elsewhere?  

Thanks in advance

**Comment by djarecka** [comment]
@satra @oesteban do you have any thoughts regarding this issue?

**Comment by effigies** [comment]
@mattcieslak Please open a PR if you're interested in contributing this.
