### ISSUE TITLE
FLIRT interface does not allow setting apply_xfm with uses_qform option

### ISSUE THREAD

**Issue by brennerd11** [nipy/nipype#1317]
Hi all,

the FLIRT interface does not allow to set _apply_xfm =True_ in conjunction with _uses_qform=True_ as _apply_xfm_ requires _in_matrix_file_
Anyways this should be possible as apply_xfm and uses_qform (without providing an additional matrix file) together allow resampling one image to the reference space just by utilizing the affine matrix stored in the header (see also http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT/FAQ).
I am unsure what the best way would be to fix that - just remove the _required=['in_matrix_file']_ from apply_xfm? Or is there a way to set require one of two inputs?

Cheers,

Daniel

**Comment by mwaskom** [comment]
There's also the [`nipype.fsl.ApplyXfm`](http://www.mit.edu/~satra/nipype-nightly/interfaces/generated/nipype.interfaces.fsl.preprocess.html#applyxfm) interface. I'm not sure if it will work better for you, but might be worth trying.

**Comment by brennerd11** [comment]
Thanks for the hint! I was not aware of that.
But unfortunately the ApplyXfm interface has the same issue - requires “in_matrix_file” when “apply_xfm” is True (default) which does not allow the comibation of only -usesqform and -applyxfm.

**Comment by danella** [comment]
I am having a similar problem. I need to register my fieldmap to my EPI (using flirt or ApplyXfm) to use in FUGUE - and am unable to do it because of this glitch. Any fixes or ways around this? Thanks!

**Comment by mgxd** [comment]
@brennerd11 @danella this should be fixed in the above PR, sorry about the delay!
