### ISSUE TITLE
fsl.utils.smooth "fwhm" argument is mis-labeled

### ISSUE THREAD

**Issue by poldrack** [nipy/nipype#1323]
the argument labeled "fwhm" is translated into "-kernel gauss %f -fmean" but according to the help for fslmaths:

 -kernel gauss  <sigma>    : gaussian kernel (sigma in mm, not voxels)

Thus, the argument appears to specify sigma rather than FWHM.  I would propose fixing this argument to compute the appropriate sigma based on a specified FWHM, and adding a new flag to directly specify sigma.  should also make clear in function documentation that this is specified in mm and not voxels

**Comment by poldrack** [comment]
actually - might be best to create a new argument called "FWHM" that behaves correctly, and then either deprecate the older incorrect "fwhm" argument or leave it in place and make clear in documentation that it is incorrect.  I would prefer the former.

**Comment by mwaskom** [comment]
I think it already behaves the way you're describing, but the logic is in the `_format_arg` method:

https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/utils.py#L175

**Comment by poldrack** [comment]
gotcha - then perhaps documentation should be updated so that it doesn't suggest that the argument is passed directly to -kernel gauss

**Comment by poldrack** [comment]
will close and create a new issue re: documentation
