### ISSUE TITLE
documentation of fsl.utils.Smooth

### ISSUE THREAD

**Issue by poldrack** [nipy/nipype#1324]
documentation says:

fwhm: (a float)
        flag: -kernel gauss %f -fmean, position: 1

when it should note that the value is passed after transforming from fwhm to sigma

**Comment by mwaskom** [comment]
This might be a broader issue really, as quite a few interfaces reformat the nipype arguments somehow before passing them to the underlying command. If memory serves, showing the actual argstring in the help is a more recent development and probably wasn't anticipated by the original `_format_arg` pattern. Maybe the answer is a general metadata field that will allow `_format_arg` logic to be described in the help?
