### ISSUE TITLE
EpiReg FSL - bug? 

### ISSUE THREAD

**Issue by sdesimoni** [nipy/nipype#1325]
Hi - apologies if this question is not very clear - I am quite new to Nipype/Python
I am trying to use the fsl.EpiReg option in a script but I keep getting the following error:
AttributeError: 'NoneType' object has no attribute 'get'

This is my node: 
epireg = Node(fsl.EpiReg(), name='epireg')
epireg.inputs.output_type = 'NIFTI_GZ'
epireg.inputs.out_base = 'epi2struct'
epireg.inputs.no_fmapreg = False
epireg.inputs.ignore_exception = True

This is the command that it runs: 
epi_reg --epi=/group/.../relCBF_001_v1.nii.gz --t1=/group/.../T1_001_v1.nii.gz --t1brain=/group/.../brainmask_warped_out.nii.gz --out=epi2struct

What is weird is that it creates the correct output files but if I try to pass the out_file to another node or to the datasink I get the error described above.

Is this due to a bug within epireg itself or how other nodes deal with its output? Importantly, is there a solution to this? 

Any information/advice on this would be greatly appreciated!! Apologies if this problem has been addressed before but I couldn't find any information on it! Thanks for your help.
Sara

**Comment by chrisfilo** [comment]
I believe this might be fixed in current master branch could you try it?

	pip uninstall nipype && pip install http://github.com/nipy/nipype/archive/master.zip

**Comment by sdesimoni** [comment]
Hi Chris,

Thanks very much for getting back to me and for sending me the master.zip file. Apparently this change has actually been implemented in our newer version of Nipype, and I am still getting the following error:

 Running: epi_reg --epi=/group/DREAM/temp/001_v1/relCBF_001_v1.nii.gz --t1=/group/DREAM/temp/001_v1/T1_001_v1.nii.gz --t1brain=/group/DREAM/temp/001_v1/brainmask_warped_out.nii.gz --out=epi2struct
160118-17:18:55,501 workflow INFO:
	 [Job finished] jobname: epireg.a0 jobid: 1
160118-17:18:55,504 workflow INFO:
	 Submitting 1 jobs
160118-17:18:55,504 workflow INFO:
	 Executing: datasink.a0 ID: 2
160118-17:18:55,510 workflow ERROR:
	 ['Node datasink.a0 failed to run on host brodmann39.med.ic.ac.uk.']
160118-17:18:55,527 workflow INFO:
	 Saving crash info to /scratch/sdesimoni/NIPYPE/Scripts/crash-20160118-171855-sdesimoni-datasink.a0.pklz
160118-17:18:55,527 workflow INFO:
	 Traceback (most recent call last):
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 369, in _send_procs_to_workers
    jobid].hash_exists()
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1289, in hash_exists
    hashed_inputs, hashvalue = self._get_hashval()
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1460, in _get_hashval
    self._get_inputs()
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1515, in _get_inputs
    output_value = results.outputs.get()[output_name]
AttributeError: 'NoneType' object has no attribute 'get'

I will however send on the .zip file to my colleague to see if this is different to what we have. But if you have any suggestions on the error above and why it may be happening if the current version is correct that would be great!
Thanks again for your help.
Sara

**Comment by chrisfilo** [comment]
Could you show the contents of `_report/report.rst` for the  `epireg` node?

Also did you install it with the command line I gave you? What does
`nipype.__nipype__` say?

**Comment by sdesimoni** [comment]
This is what the report says:

Node: epireg (fsl)
==================

 Hierarchy : ASL_preproc.epireg
 Exec ID : epireg.a0

Original Inputs
---------------

* args : <undefined>
* echospacing : <undefined>
* environ : {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
* epi : /group/DREAM/temp/001_v1/relCBF_001_v1.nii.gz
* fmap : <undefined>
* fmapmag : <undefined>
* fmapmagbrain : <undefined>
* ignore_exception : True
* no_clean : <undefined>
* no_fmapreg : <undefined>
* out_base : epi2struct
* output_type : NIFTI_GZ
* pedir : <undefined>
* t1_brain : /group/DREAM/temp/001_v1/brainmask_warped_out.nii.gz
* t1_head : /group/DREAM/temp/001_v1/T1_001_v1.nii.gz
* terminal_output : allatonce
* weight_image : <undefined>
* wmseg : <undefined>

Unfortunately I cannot uninstall/reinstall nipype myself as our lab's computer cluster is maintained by one of my colleagues. However I will pass that information on and see if it makes a difference

**Comment by sdesimoni** [comment]
Execution Inputs
----------------

* args : <undefined>
* echospacing : <undefined>
* environ : {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
* epi : /group/DREAM/temp/001_v1/relCBF_001_v1.nii.gz
* fmap : <undefined>
* fmapmag : <undefined>
* fmapmagbrain : <undefined>
* ignore_exception : True
* no_clean : <undefined>
* no_fmapreg : <undefined>
* out_base : epi2struct
* output_type : NIFTI_GZ
* pedir : <undefined>
* t1_brain : /group/DREAM/temp/001_v1/brainmask_warped_out.nii.gz
* t1_head : /group/DREAM/temp/001_v1/T1_001_v1.nii.gz
* terminal_output : allatonce
* weight_image : <undefined>
* wmseg : <undefined>

**Comment by chrisfilo** [comment]
what about the outputs from the report?

**Comment by sdesimoni** [comment]
Sorry there isn't any more text in the _report file

Do you mean this:

nipype_display_crash result_epireg.pklz 
Traceback (most recent call last):
  File "/share/apps/anaconda/bin/nipype_display_crash", line 88, in <module>
    debug, args.directory)
  File "/share/apps/anaconda/bin/nipype_display_crash", line 22, in display_crash_files
    if 'node' in crash_data:
TypeError: argument of type 'InterfaceResult' is not iterable

**Comment by sdesimoni** [comment]
But it does create the appropriate outputs: 
epi2struct_fast_wmedge.nii.gz             
epi2struct.nii.gz

**Comment by chrisfilo** [comment]
This is weird - your previous log suggests that datasink failed not epireg.
I'm surprised that the outputs are not listed (which happens when the node
fails). Could you run this with Linear plugin so we could see what is going
on (it also seem you are submitting jobs).

**Comment by sdesimoni** [comment]
Sure, I will run that now and let you know the output. And yes I am running the following through a bash script:
python /home/sdesimoni/scratch/NIPYPE/Scripts/test_epireg.py

Thanks again for helping out, I am definitely a novice!

**Comment by sdesimoni** [comment]
Ok so this is what I get in the terminal step-by-step:

160118-19:02:22,760 workflow INFO:
	 ['check', 'execution', 'logging']
160118-19:02:22,773 workflow INFO:
	 Running serially.
160118-19:02:22,774 workflow INFO:
	 Executing node selectfiles.a0 in dir: /home/sdesimoni/scratch/NIPYPE/temp/FSJ16_working_dir2/ASL_preproc/_subject_id_001_v1/selectfiles
160118-19:02:22,808 workflow INFO:
	 Executing node epireg.a0 in dir: /home/sdesimoni/scratch/NIPYPE/temp/FSJ16_working_dir2/ASL_preproc/_subject_id_001_v1/epireg
160118-19:02:22,849 workflow INFO:
	 Running: epi_reg --epi=/group/DREAM/temp/001_v1/relCBF_001_v1.nii.gz --t1=/group/DREAM/temp/001_v1/T1_001_v1.nii.gz --t1brain=/group/DREAM/temp/001_v1/brainmask_warped_out.nii.gz --out=epi2struct
160118-19:02:23,136 interface INFO:
	 stdout 2016-01-18T19:02:23.136479:Running FAST segmentation
160118-19:11:00,135 interface INFO:
	 stdout 2016-01-18T19:11:00.134803:FLIRT pre-alignment
160118-19:11:06,817 interface INFO:
	 stdout 2016-01-18T19:11:06.816982:Running BBR
160118-19:15:37,386 interface INFO:
	 stdout 2016-01-18T19:15:37.386116:Applying POWELL correction
160118-19:15:37,386 interface INFO:
	 stdout 2016-01-18T19:15:37.386579:finit, fend, fextrap = 0.454715 , 0.452048 , 0.449684
160118-19:15:41,596 interface INFO:
	 stdout 2016-01-18T19:15:41.596115:fval = 0.439689
160118-19:15:54,108 interface INFO:
	 stdout 2016-01-18T19:15:54.108089:Applying POWELL correction
160118-19:15:54,108 interface INFO:
	 stdout 2016-01-18T19:15:54.108089:finit, fend, fextrap = 0.439689 , 0.42142 , 0.418713
160118-19:15:58,74 interface INFO:
	 stdout 2016-01-18T19:15:58.074209:fval = 0.417156
160118-19:16:16,747 interface INFO:
	 stdout 2016-01-18T19:16:16.747279:0.415302 0.999711 -0.014920 -0.018842 0.000000 0.015743 0.998893 0.044333 0.000000 0.018160 -0.044617 0.998839 0.000000 -4.043543 7.310624 -1.206454 1.000000 
160118-19:16:28,120 workflow ERROR:
	 ['Node datasink.a0 failed to run on host brodmann39.med.ic.ac.uk.']
160118-19:16:28,131 workflow INFO:
	 Saving crash info to /scratch/sdesimoni/NIPYPE/Scripts/crash-20160118-191628-sdesimoni-datasink.a0.pklz
160118-19:16:28,131 workflow INFO:
	 Traceback (most recent call last):
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1324, in run
    self._get_inputs()
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1515, in _get_inputs
    output_value = results.outputs.get()[output_name]
AttributeError: 'NoneType' object has no attribute 'get'

160118-19:16:28,132 workflow INFO:
	 ***********************************
160118-19:16:28,132 workflow ERROR:
	 could not run node: ASL_preproc.datasink.a0
160118-19:16:28,133 workflow INFO:
	 crashfile: /scratch/sdesimoni/NIPYPE/Scripts/crash-20160118-191628-sdesimoni-datasink.a0.pklz
160118-19:16:28,133 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/home/sdesimoni/scratch/NIPYPE/Scripts/test_epireg.py", line 110, in <module>
    ASL.run(plugin='Linear')
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 701, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 89, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

The _report is the same as before (no output info).

**Comment by sdesimoni** [comment]
Hi, my colleague installed the version of nipype you sent and unfortunately I still get the same error: 
Traceback (most recent call last):
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 293, in run
    self._get_inputs()
  File "/share/apps/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _get_inputs
    output_value = results.outputs.get()[output_name]
AttributeError: 'NoneType' object has no attribute 'get'

Could this be caused by the fact that datasink hasn't been updated with the changes applied to epireg? does that make sense?

**Comment by chrisfilo** [comment]
I'm not sure what is going on. Could you share the full source code of your
pipeline or a minimal example replicating this error?

**Comment by sdesimoni** [comment]
#!/usr/bin/env python

# PIPELINE FOR ASL ANALYSIS #

from os.path import join as opj

import HelperInterfaces
import nipype.interfaces.utility as util
import nipype.interfaces.fsl as fsl
import nipype.interfaces.freesurfer as freesurfer
from nipype.pipeline.engine import Workflow, Node
from nipype.interfaces.io import SelectFiles, DataSink



# Defining list of subjects you want to run the pipeline on (InfoSource).
# This assumes that your functional and structural scans are in the same folder
# named subject_id

subject_list = ['001_v1']
infosource = Node(interface=util.IdentityInterface(fields=['subject_id']), name="infosource")

infosource.iterables = ('subject_id', subject_list)

# Select Files-This selects files which include the tag of 'relCBF' or 'T1'
templates = {'func': '/group/DREAM/temp/{subject_id}/*relCBF*',
             'anat': '/group/DREAM/temp/{subject_id}/*T1*',
             'strip': '/group/DREAM/temp/{subject_id}/*brainmask*'}

selectfiles = Node(SelectFiles(templates), name='selectfiles')

# Location of the experiment folder

experiment_dir = '/home/sdesimoni/scratch/NIPYPE/'
output_dir = opj(experiment_dir, 'temp/FSJ16_output_dir2/')
working_dir = opj(experiment_dir, 'temp/FSJ16_working_dir2/')

# -----------------------------------------------------------------------------------------------------#
# DATA SINK & WORKFLOW
# -----------------------------------------------------------------------------------------------------#
datasink = Node(DataSink(base_directory=experiment_dir,
                         container=output_dir),
                name='datasink')

# initialise workflow

ASL = Workflow(name='ASL_preproc')
ASL.base_dir = opj(experiment_dir, working_dir)

# -----------------------------------------------------------------------------------------------------#
# PROCESSING NODES
# -----------------------------------------------------------------------------------------------------#

# USE EPI_REG to transform ASL Scan to T1 space
epireg = Node(fsl.EpiReg(), name='epireg')
epireg.inputs.output_type = 'NIFTI_GZ'
epireg.inputs.out_base = 'epi2struct'
epireg.inputs.ignore_exception = True

# -----------------------------------------------------------------------------------------------------#
# CONNECT NODES
# -----------------------------------------------------------------------------------------------------#
ASL.connect([
    # GET INPUT FROM STUDY DIRECTORIES & SELECT
    (infosource, selectfiles, [('subject_id', 'subject_id')]),

    # PASS ASL and stripped T1 TO FLIRT
    (selectfiles, epireg, [('func', 'epi')]),
    (selectfiles, epireg, [('anat', 't1_head')]),
    (selectfiles, epireg, [('strip', 't1_brain')]),


])

# -----------------------------------------------------------------------------------------------------#
# CONNECT NODES TO DATA SINK FOR STORAGE
# -----------------------------------------------------------------------------------------------------#

ASL.connect([

                (epireg, datasink, [('out_file', 'ASL_T1space')]),

])

# SUBSTITUTIONS

datasink.inputs.substitutions = [('_subject_id_', '')]

###################################################################################
# Run workflow
###################################################################################
ASL.write_graph('ASL', graph2use='hierarchical')
ASL.run('MultiProc', plugin_args={'n_procs': 2})

**Comment by sdesimoni** [comment]
This is just a shortened version of what I was hoping to run. This hopefully just tests the epireg node

**Comment by sdesimoni** [comment]
Hello - could I just check that the version of nipype you sent is definitely the current and latest version available? 
Thanks,
Sara

**Comment by chrisfilo** [comment]
Yes.

Do you get this error even if you remove DataSink from your pipeline? Does
the _report/report.rst for epireg include outputs then?

**Comment by djarecka** [comment]
@sdesimoni - are you still getting the error with the current version of nipype?

**Comment by djarecka** [comment]
I'm closing the issue for now, please feel free to reopen if you still get this error.
