### ISSUE TITLE
prov - unlisted dependency?

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1336]
I am trying to install the current live version of nipype, but it fails with:

```
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/__init__.py:66: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
Traceback (most recent call last):
  File "setup.py", line 277, in <module>
    pkg_chk('prov', PROV_MIN_VERSION)
  File "setup.py", line 199, in package_check
    raise RuntimeError(msgs['missing'] % pkg_name)
RuntimeError: Cannot import package "prov" - is it installed?
```

Th key part being the last line. 

is [this](https://pypi.python.org/pypi/prov) the "prov" that is meant there? Is it absolutely required? If no, how does one nstall it without prov - if yes, maybe it should be listed [here](http://nipy.org/nipype/users/install.html#dependencies)?

**Comment by satra** [comment]
@TheChymera - indeed the docs should be updated automatically when we change our dependencies. 

it is listed in requirements.txt and setup.py in the source. it is absolutely required.

**Comment by TheChymera** [comment]
ok, the build works if prov is installed. Thank you.
