### ISSUE TITLE
ants.Registration output transform order

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1343]
ants.Registration outputs transforms in the same order as the were specified in the inputs, but input of ants.ApplyTransforms expects the transforms in revers order (even for forward transformation). Our example in docstrings for ApplyTransforms are misleading (affine is followed by a warp not other way around).

See here for an example of inverse transform in which affine is specified on the command line first followed by a warp and the are applied in the reverse order http://sourceforge.net/p/advants/discussion/840261/thread/2a8d0397/?limit=25#549c/8771

**Comment by satra** [comment]
@chrisfilo - do you think it's misleading because people don't use it that way? someone does need to know how applytransforms works to apply it.

for example the ants openfmri example does apply it properly.

https://github.com/nipy/nipype/blob/master/examples/fmri_ants_openfmri.py#L239

**Comment by chrisfilo** [comment]
The problem arises when someone is not using a composite transform and connects outputs of ants. Registration directly to ants.ApplyTransforms. The transforms will not be applied in the right way since the order is wrong.

We can either inform people about this quirk or try to reverse the order of either ants.Registration output or ants.ApplyWarp input. This would however break backwards compatibility.

**Comment by satra** [comment]
ants recommends composite transforms though.

**Comment by hjmjohnson** [comment]
I agree that ants recommends using composite transforms.  This is difficult and one must realize that both orderings of the transform orderings could be "obvious" depending on your perspective.  I do think that providing documentation to describe how applytransforms works is a good idea, and that nipype should represent the interface in as close to the same way as applytransform does.  I would be very hesitant to have nipype provide a different interface in the hopes of "making it easier" to link tools together.

=== Just my 2 cents, feel free to ignore.

**Comment by chrisfilo** [comment]
The examples and docstrings have already been improved in #1345. Is there any other place we would like to have this warning?

**Comment by djarecka** [comment]
@chrisfilo @hjmjohnson @satra do you still want to add some warnings or can we close it?

**Comment by djarecka** [comment]
I'm closing it for now, please reopen if this is still an issue
