### ISSUE TITLE
AttributeError: 'module' object has no attribute 'write_dot'

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1350]
I am trying to run [this pipeline](https://github.com/TheChymera/chyMRI/blob/f4b9469189623c9f23c6338099ec2ed856333673/glm.py) and I am getting this error message:

```
/usr/lib64/python2.7/site-packages/nipy/labs/glm/glm.py:9: FutureWarning: Module nipy.labs.utils.routines deprecated, will be removed
  from ..utils import mahalanobis
/usr/lib64/python2.7/site-packages/nipype/interfaces/nipy/model.py:18: FutureWarning: Module nipy.labs.glm deprecated, will be removed. Please use nipy.modalities.fmri.glm instead.
  import nipy.labs.glm.glm as GLM
/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py:419: UserWarning: Input tr requires inputs: slice_times
  warn(msg)
/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py:419: UserWarning: Input slice_info requires inputs: slice_times
  warn(msg)
160205-22:03:39,570 workflow INFO:
         Creating detailed dot file: /home/chymera/NIdata/ofM.dr/FSL_GLM_work/graph_detailed.dot
Traceback (most recent call last):
  File "glm.py", line 166, in <module>
    fsl_glm(workflow_base="~/NIdata/ofM.dr/", functional_scan_type="7_EPI_CBV", structural_scan_type="T2_TurboRARE>", experiment_type="<ofM>", omit_ID=["20151027_121613_4013_1_1"])
  File "glm.py", line 162, in fsl_glm
    pipeline.write_graph(graph2use="flat")
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 558, in write_graph
    format=format, simple_form=simple_form)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/utils.py", line 905, in export_graph
    nx.write_dot(pklgraph, outfname)
AttributeError: 'module' object has no attribute 'write_dot'
```

It seems to be due to [this line](https://github.com/TheChymera/chyMRI/blob/f4b9469189623c9f23c6338099ec2ed856333673/glm.py#L162). And if I cmment it, the pipeline works. This happens both with release `0.11.0` and with the live nipype version from github. I have matplotlib. Any ideas what might be the problem?

**Comment by mwaskom** [comment]
`nx` is `NetworkX`, but for `write_dot` to work you need either `pygraphviz` or `pydot` installed, as per [here](https://networkx.github.io/documentation/latest/examples/pygraphviz/write_dotfile.html). Do you have one of those libraries?

**Comment by TheChymera** [comment]
@mwaskom I have:

*`networkx-1.11`
*`pydot-1.0.28-r2`
*`pygraphwiz-1.3.1`

MAybe I need pydotplus instead? Prov uses it for testing.

**Comment by polosecki** [comment]
Same issue here in nipype when using ```write_graph``` with the following libraries installed:
graphviz (0.4.9)
pygraphviz (1.3.1)
pydot (1.0.28)
networkx (1.11)
Error can be also reproduced by typing:
```
import networkx as NX
G=NX.grid_2d_graph(5,5)  # 5x5 grid
NX.write_dot(G,"grid.dot")
```
which produces the error
```
Traceback (most recent call last):

  File "<ipython-input-4-742fbc2aa48b>", line 1, in <module>
    NX.write_dot(G,"grid.dot")

AttributeError: 'module' object has no attribute 'write_dot'
```

**Comment by mwaskom** [comment]
Not sure what the problem is, but it doesn't sound like a nipype issue per se.

**Comment by satra** [comment]
this example suggests that the above should work:

https://networkx.github.io/documentation/latest/examples/pygraphviz/write_dotfile.html

perhaps its a version issue with networkx, we should track this down.

**Comment by polosecki** [comment]
Yes, it does seems as if, even though Python recognizes all the packages as installed, somehow networkx doesn't acknowledge it and that affects nipype. I tried uninstalling and reinstalling all these packages, which happens successfully, but doesn't correct the issue. 
All suggestions are welcome.
Thank you!

**Comment by mwaskom** [comment]
I would suggest opening an issue with networkx, as it is likely that they will be able to help you debug the problem.

**Comment by polosecki** [comment]
I just opened an issue on networkx, but in the meantime I found a workaround that I thought worth sharing:
1-Install pydotplus (i.e. ```pip install pidotplus```)
2-In nipype/pipeline/utils.py replace line 905 ```nx.write_dot(pklgraph, outfname)``` by ```nx.drawing.nx_pydot.write_dot(pklgraph, outfname)```
Now my dot files are generated just fine.

**Comment by polosecki** [comment]
It seems my workaround is the way to go for networkx-1.11 and later
https://github.com/networkx/networkx/issues/1984

**Comment by satra** [comment]
@polosecki - could you please submit a PR that implements your work around after a version check on networkx?

**Comment by polosecki** [comment]
@satra I was meaning to do it but didn't quite know how since I had never contributed to a larger project. I'm happy that nipype is the first one. PR submitted! :)

**Comment by TheChymera** [comment]
So pydotplus is a mandatory (in as far as one wants dot files) nipype dependency now, yes?

**Comment by polosecki** [comment]
Yes, since it is imported in the networkx.drawing function called by nipype's write_graph.

**Comment by SebastianoF** [comment]
Same issue, polosecki's suggestion worked fine for me.

> 1-Install pydotplus (i.e. pip install pidotplus)
> 2-In nipype/pipeline/utils.py replace line 905 nx.write_dot(pklgraph, outfname) by nx.drawing.nx_pydot.write_dot(pklgraph, outfname)
> Now my dot files are generated just fine.

**Comment by pinkesh** [comment]
Thanks polosecki your solution works for me

**Comment by jolespin** [comment]
Was this fixed? I just encountered this error as well with version 1.11

**Comment by cast42** [comment]
Usign nx.nx_pydot.write_dot(G, 'tree.dot') works for me 
nx.__version__
'2.0'
