### ISSUE TITLE
Create and post user survey

### ISSUE THREAD

**Issue by satra** [nipy/nipype#1354]

**Comment by chrisfilo** [comment]
Let's keep it extremely simple and use Wiki Survey with the following seed ideas:

- Add graphical user interface
- Make the syntax simpler
- Make debugging easier
- Help with installing dependencies (FSL, SPM, AFNI etc.)
- Create tutorial videos
- Add more workflows
- Add more examples
- Add interactive execution reports

I've created an example here: http://www.allourideas.org/nipype. Please add more ideas in the comments.

**Comment by satra** [comment]
nice!

**Comment by chrisfilo** [comment]
Good to distribute?

**Comment by oesteban** [comment]
+1

**Comment by satra** [comment]
sure go ahead.
