### ISSUE TITLE
Dcumentation for SpaceTimeRealigner slice_time input

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1369]
Hi, I think we should add some documentation for the `slice_time` input for the SpaceTimeRealigner interface.

Some may seem self-esplanatory, but I can't figure out what `asc_alt_half` or `asc_alt_siemens` is supposed to be:

I think the slice time conventions can be nicely exemplified on a set of 6 slices:

* 'asc_alt_2' - `[0,2,4,1,3,5]`
* 'asc_alt_2_1' - `[1,3,5,0,2,4]`
* 'asc_alt_half' - **?????????**
* 'asc_alt_siemens' - **?????????**
* 'ascending' - `[0,1,2,3,4,5]`
* 'desc_alt_2' - `[5,3,1,4,2,0]`
* 'desc_alt_half' - **??????????**
* 'descending' - `[5,4,3,2,1,0]`

Can you help me fill in the gaps?

**Comment by cni-md** [comment]
It's defined in nipy:
[https://github.com/nipy/nipy/blob/baede9043717149093673e86c29c92b2be4a20a6/nipy/algorithms/slicetiming/timefuncs.py]
asc_alt_siemens = _derived_func('asc_alt_siemens', st_odd0_even1) = 
Ascend alternate starting at slice 0 for odd, slice 1 for even `n_slices

asc_alt_half = Ascend alternate, where alternation is by half the volume
