### ISSUE TITLE
Rename interface can only use symlinks

### ISSUE THREAD

**Issue by billbrod** [nipy/nipype#1387]
The `utility.Rename` interface calls `utility.copyfile` to rename the files passed to it, however it always uses a symlink and doesn't allow the user to specify whether they would rather copy the file instead. I'm working on a CIFS filesystem, where symlinks are not allowed (at least, users are not allowed to create them; calling `os.symlink` always returns `[Errno 95] Operation not supported`), and so this prevents me from being able to use the Rename interface.

**Comment by effigies** [comment]
As a stop-gap, you can use f3d1c9b57d5dc76ace6a98c8fac8c0e15e0a8967. I'm pretty sure that should work, but let me know.

**Comment by billbrod** [comment]
Yup, that fix works perfectly. Thanks!
