### ISSUE TITLE
dcm2nii → dcm2niix

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nipype#1389]
We have found _dcm2nii_ is unable to convert some recent Philips DICOM files. Those files can be converted using _dcm2niix_ instead.

I suggest adding _dcm2niix_ to Nipype.

Because _dcm2niix_ is not yet mature software and does not support all the proprietary formats supported by _dcm2nii_, I don't think `dcm2nii` should be changed to `dcm2niix` in [nipype/interfaces/dcm2nii.py](https://github.com/nipy/nipype/blob/master/nipype/interfaces/dcm2nii.py). Should we provide a duplicate interface for _dcm2niix_? Add an option to switch between _dcm2nii_ and _dcm2niix_?

**Comment by satra** [comment]
@DimitriPapadopoulos - i think dcm2niix should be a separate interface. we have found some instabilities in dcm2niix where it won't convert any of our dicoms!

**Comment by DimitriPapadopoulos** [comment]
I totally agree both programs should be available, as I said _dcm2niix_ is not yet mature.

I was thinking of two options:
* Keep the same interface with an additional option to switch between `dcm2nii` (by default) and `dcm2niix` (only when the relevant option is used).
* Provide a new specific interface. Might be better indeed since _dcm2nii_ has options such as `-a` that seem to be missing from _dcm2niix_.

**Comment by satra** [comment]
a new specific interface is better in this case.

**Comment by cni-md** [comment]
You need a specific interface. The std output is different and the parser for e.g. bvec, bval will fail.
I tried to build a dcm2niix interface to be used with heudiconv. But dcm2niix -s will convert only one file. You can not convert a list of files needed by heudiconv. :( Convert all files in a dir is fine.

**Comment by DimitriPapadopoulos** [comment]
One could imagine copying the relevant files to a temp dir to convert a subset of a dir. I don't know if it's worth the overhead though.

**Comment by satra** [comment]
@mgxd is building an interface for this, which he says is almost ready for a PR.

**Comment by mgxd** [comment]
I've submitted a PR - let me know what you guys think

**Comment by neurolabusc** [comment]
As a general comment, dcm2nii is mature, stable and a known entity, so if it works for you that is great. I do think it would be great for developers to consider supporting dcm2niix. I am spread very thin on the time I have for development, so dcm2nii is pretty much in limbo and the new features like JPEG2000 support, unequal slice distances, tilted acquisitions, etc will only appear in dcm2niix. The new code is leaner and easier for me to maintain. I realize it behaves differently, and it does not attempt to support the legacy formats that predate DICOM (e.g. proprietary Elscint, GE and Siemens formats from more than a decade ago). 

I also think as leading edge developers you could provide me with any examples that give you the impression that dcm2niix is not mature. The issue Satra refers to (ability to convert files without a valid Part 10 header) has been addressed in the latest version:
  https://github.com/neurolabusc/dcm2niix/issues/15

**Comment by cni-md** [comment]
I checked the dcm2niix interface with Philips data. With inputs.source_dir it's working fine except bvec, bval. 
outputs.bval and bvec are undefined.

As mentioned above dcm2niix can handle one file only (or a dir)
converter.inputs.source_names = ['functional_1.dcm', 'functional_2.dcm']
converter.inputs.single_file = False
converter.run()
-> ValueError: need more than 3 values to unpack
Interface Dcm2niix failed to run.

Only converter.inputs.single_file = True is working. For me "source_files" is missleading. I prefer "source_file"

**Comment by neurolabusc** [comment]
Hello,
 1.) Are you saying that dcm2niix does not create the bvec/bval files or are you saying that the files are created but the python outputs are undefined? If the former, I would like to see an example of your DTI files, note that oval and bvec files are only generated if there is variability in these values (e.g. you will not get a file if you convert a single slice, or a single B=0 volume). I do not have a Philips system, but have tested dcm2niix with both PAR/REC and DICOM data from several sites available here:
  https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging

2.) Like dcm2nii, dcm2niix will either convert a single file if you provide the "-s y" parameter, or it will convert all the images in a specified directory. Therefore, I would expect you only need to provide a single source name, and it will convert all the files.

3.) If your problems are with my software, it would be great to know the version (e.g. 22Aug2016) and the operating system you are using (OSX, Linux, Windows).

**Comment by cni-md** [comment]
Hello @neurolabusc,
at 1.) dcm2niix itself is working fine, but you changed the stdout naming. With my PR the nipype interface is catching the bvecs, bvals again. Everything is fine.

at 2.) This has changed from dcm2nii -> dcm2niix. heudiconv assume that a list of files is also fine, but this is not the case. Therefore, major changes has to be done to use dcm2niix for heudiconv. dcm2niix is very fast so converting all files and drop the unneeded might be an option. But nevertheless, the command has to be changed from
convert <list of dicom files> to
convert <dir of dicom files> and cherry pick.

at 3.) It's not a problem of your software, but if you can implement the old behaviour (converting a list of files) it would help a lot.

**Comment by neurolabusc** [comment]
OK, I have created a new version on GitHub (30Apr2016) that allows you to specify multiple files to convert
  ./dcm2niix -b y ~/tst ~/tst2
However, there is one caveat: unless you are converting single files (-s y), it makes sense that each file you specify is in a separate folder, as the software attempts to convert all the DICOM files it can find in the path provided. For example consider two DICOM files in the same folder : img01.dcm and img02.dcm. The following command will convert both of them
  ./dcm2niix -b y ~/tst/img01.dcm
and this will convert both of them twice
  ./dcm2niix -b y ~/tst/img01.dcm ~/tst/img02.dcm

**Comment by cni-md** [comment]
Thanks a lot. I wrote a dcm2niix interface for heudiconv.
[https://github.com/cni-md/heudiconv.git](heudiconv)
I link all files of one scan to a tmpdir and call dcm2niix "source_dir" to convert one scan selectively.

**Comment by neurolabusc** [comment]
OK, that would work. Alternatively, you should simply be able to call "-s y" to convert a single image, which would typically save time relative to copying files to a tmpdir (assuming you have fast write speeds to the source directory).
