### ISSUE TITLE
SpecifyModel does not support 3D files (lists of lists of files) in sparse mode.

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#139]
Maybe we should discourage usage of 3D files in general?

**Comment by djarecka** [comment]
are you saying that this description is wrong? do yu want to remove it? https://github.com/nipy/nipype/blob/master/nipype/algorithms/modelgen.py#L210

**Comment by effigies** [comment]
Closing. Please open a new issue if this is still a problem.
