### ISSUE TITLE
No module named aniso2iso

### ISSUE THREAD

**Issue by venpopov** [nipy/nipype#1395]
I have followed the installation tutorial from http://miykael.github.io/nipype-beginner-s-guide/installation.html and everything worked out until the final stage of testin nipype. I got the following error:

No module named aniso2iso

I see that this is a module within dipy.align I can import dipy.align just fine, but nnot dipy.align.aniso2iso. I haven't tried to use nipype yet, but I'm wondering if this will be a serious  cause of concern and also how might I be able to fix it. I tried upgrading dipy with pip but it says that it is up to date.

**Comment by chrisfilo** [comment]
Those errors should be fixed in nipype master. Could you try it?

`pip uninstall nipype; pip install https://github.com/nipy/nipype/archive/master.zip`

**Comment by venpopov** [comment]
Worked perfectly, thanks!

**Comment by venpopov** [comment]
Btw, I just reproduced the error when install nipype on a cluster environment with CentOS (my system is Ubuntu), so it is not os specific. Fixed it again in the same way, but saying that just in case it is useful.

**Comment by chrisfilo** [comment]
Thanks for the info. We should release soon!
