### ISSUE TITLE
sorted list of exec nodes?

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1404]
Hi,

Why do you use sorted in this line?
https://github.com/nipy/nipype/blob/master/nipype%2Fpipeline%2Fengine%2Fworkflows.py#L693

If I use a connect with an auxiliary function, e.g.:
`(params, stc, [(("slice_order", sum_one), "slice_order"),]),`

I get this error:
`TypeError('unorderable types: tuple() < str()',)`

Can't sort tuples against strings.

I removed the `sorted` because it doesn't make sense here and it works.

**Comment by satra** [comment]
@alexsavio - this looks like a bug. in fact would be good to add this as a test and fix it.
