### ISSUE TITLE
[ENH] terminal_output as output

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1407]
While addressing #1406 and #1398, I've found that the `terminal_output` is not mapped to any output when set to `'file'`.

I don't know if this was intended as a feature, but I see it more like an error. Moreover, we have the `StdOutCommandLine` that workarounds this behaviour.

What is the rationale behind maintaining these two ways to do the same thing? Would joining them together make sense? Or maybe `StdOutCommandLine` should disappear in favor of a `CommandLine` that provides one output (currently named `out_file` for the `StdOutCommandLine`) when `terminal_output = 'file'`?

I would implement whatever you see it is the best solution to this issue because it blocks me in finishing the two above-mentioned issues.

**Comment by satra** [comment]
terminal output can be stderr or stdout or both. we could add automatically add an output to the CommandLine class to link it to the file, but we need to decide whether it should be both, or separate or merged (in which, case whether merged in order of output or separately). 

unlike many bioinformatics tools which simply output on the terminal, most neuroimaging tools don't, so we never considered the output to be sent to another program. this output is stored in the provenance file, which is also not sent as an output. 

if we have a good way of controlling needed output and sending it along, that would be a welcome PR.

**Comment by hjmjohnson** [comment]
Proposal:

terminal_output = 'file'  # Both stdout & stderr
terminal_output = 'file_stdout_stderr'  # Both stdout & stderr
terminal_output = 'file_stdout'  #stdout
terminal_output = 'file_stderr'  #stderr

**Comment by satra** [comment]
@hjmjohnson - where stdout and stderr are combined, would this be in temporal order, separate sections, or do we picked one?

**Comment by oesteban** [comment]
And something like:

- ```terminal_output = 'file'``` Generates 1 file with both outputs merged (combined) in temporal order, as Popen gives it to you if you point them to the same file. 
- ```terminal_output = 'file_stdout_stderr'``` Generates 2 files with one output each.
- ```terminal_output = 'file_stdout'``` Generates only 1 file for stdout
- ```terminal_output = 'file_stderr'``` Generates only 2 file for stderr

**Comment by oesteban** [comment]
up!

**Comment by chrisfilo** [comment]
+1
