### ISSUE TITLE
Tests fail when fusefat is not installed

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1408]
This line causes the crash of Popen https://github.com/nipy/nipype/blob/master/nipype/testing/utils.py#L62 when running tests without fusefat installed.

**Comment by chrisfilo** [comment]
We should probably detect fusefat and skip the test if not installed.

**Comment by effigies** [comment]
We detect a failure of fusefat, but not an absence. Pushing a candidate fix...
