### ISSUE TITLE
Support for processors accross multiple nodes in a cluster environment?

### ISSUE THREAD

**Issue by venpopov** [nipy/nipype#1414]
I've been using nipype on a cluster environment with a PBS scheduler. I don't use the nipype PBS plugin, because it creates many many tasks and a lot of them get queued even though there are resources available. Instead, I use the multiproc pluging and request the same number of processors for a single job from the scheduler. This has worked fine when using only a single computing node (e.g. use 10 CPUs on a single node), but it (possibly) failed when I tried to run it on multiple computing nodes. 

So my nipype script requests 30 procs with:
metaflow.run(plugin='MultiProc', plugin_args={'n_procs': 30})

And my pbs script requests 10 procs on each of 3 nodes for the nipype job:
# PBS -l nodes=3:ppn=10

The job crashed with the error that I'm using more processors than dedicated, and the support staff told me that my script may note support computing on multiple nodes. Is that the case with nipype? And can I do anything about it, aside from trying to use the PBS plugin, or to split my processing in separate files by groups of subjects?

Or the failure might have been due to something else entirely, but I'd just like to know if MultiProc works over CPUs on different computing nodes?

**Comment by satra** [comment]
@venpopov - indeed almost no imaging software supports multinode-multicore jobs.

multiproc is great for a single node with multiple cores so `#PBS -l nodes=1:ppn=10` would work together with {'n_procs': 30}

you can use ipython/jupyter to reserve processes across nodes and then use the nipype plugin for ipython.

could you give us a few more details on why the standard PBS plugin is not working for you? feel free to ping us on: gitter.im/nipy/nipype

**Comment by venpopov** [comment]
The PBS doesn't work for me because every time, even if the system isn't
used by anyone else, a couple of my jobs will get deferred, which will
prevent a lot of the pipeline from running. For example, 2 of the 17
selectfiles jobs do not run and get deferred, and then everything that
depends on them has to wait. I've found no systematic reason why some jobs
get deferred (the message I get is "job is deferred.  Reason:  RMFailure"),
and until we figure out how to solve this, we are using MultiProc as a
shortcut.



--
Ven Popov
Ph.D. Student
Department of Psychology
Center for the Neural Basis of Cognition
Carnegie Mellon University
web: venpopov.com

**Comment by satra** [comment]
thanks @venpopov - we will work on additional control schemes for workflows and subworkflows, but these will be incorporated during the summer.

one relatively quick hack you could look into is not to expand each node of the workflow, but instead treat it as an executable unit with an execution plugin consideration. this will imply disabling graph flattening at the outer workflow level and relying on `workflow.run()` for each `node`.

**Comment by venpopov** [comment]
I found out that I can avoid the problem by
specifying metaflow.config['execution']['poll_sleep_duration'] = 60
Probably the PBS scheduler "didn't like" frequent jobs submission. (For)
Now everything runs smoothly.

--
Ven Popov
Ph.D. Student
Department of Psychology
Center for the Neural Basis of Cognition
Carnegie Mellon University
web: venpopov.com
