### ISSUE TITLE
autorecon1 depends on SimpleITK

### ISSUE THREAD

**Issue by cni-md** [nipy/nipype#1431]
I am trying to run the FS create_reconall_workflow but I got stucked at the
`import SimpleITK as sitk` in autorecon1.py
SimpleITK is only available for windows and mac. easy_install did not work under Debian Jessy. 
git clone git://itk.org/SimpleITK.git, cmake..., make is still running but why?

The only use I found:
`img = sitk.ReadImage(t1)
size = img.GetSize()`

2h pain with installation for img.GetSize? :(

**Comment by effigies** [comment]
I think that particular call to SimpleITK can be replaced with `nibabel.load(t1).shape`. The one in [workflows/smri/freesurfer/utils.py](https://github.com/nipy/nipype/blob/8cde742/nipype/workflows/smri/freesurfer/utils.py#L496-L510) seems a little less straightforward, as it's not immediately obvious what Get/SetOrigin are doing under the hood.
