### ISSUE TITLE
json vs. simplejson

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1443]
In this commit https://github.com/nipy/nipype/commit/7cd42b3e all json calls were changed to simplejson. I guess this was part of the effort to support python 3.4. However, I don't see the reason why json would not work in most of the cases. Could you develop a bit more on that, @bcipolli @satra?

Thanks a lot!

**Comment by bcipolli** [comment]
@oesteban thanks for the question! `json` always outputs unicode string values; `simplejson` switches between bytes in py27 and unicode in py3+. This was a better fit for the dual compatibility we set up, so went with `simplejson`. Nothing more or less than that! :)

**Comment by oesteban** [comment]
Awesome, thanks!!
