### ISSUE TITLE
Dcm2nii creates a config.ini file in the input or current directory

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nipype#1448]
As a sequel to #1115, shouldn't the `config.ini`file be created in the output directory instead of the input or current directory?
Not sure which one is used by `Dcm2nii` but it can happen that both of these directories are read-only.

**Comment by mgxd** [comment]
I believe dcm2nii's default is to create in your home directory, we could potentially patch this up. However, I'd recommend using `dcm2niix`, which reads the config file from your home directory. Feel free to open this if needed
