### ISSUE TITLE
Shim warning when using IPython >= 4.0.0

### ISSUE THREAD

**Issue by jpellman** [nipy/nipype#1451]
One of our C-PAC users came across the following deprecation warning during their pipeline run:

> /clusterdata/apps/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
> 
>   "You should import from ipykernel or jupyter_client instead.", ShimWarning)
> 
> /clusterdata/apps/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
> 
>   "You should import from ipyparallel instead.", ShimWarning)

I was able to determine  that this is because, starting in IPython 4.0.0, the IPython developers have chosen to separate IPython.parallel and IPython.kernel into separate packages.  Is there some way that nipype could take this into account by determining if the IPython version number is >= 4.0.0, stopping execution if so (and the packages are not installed), and warning users to download these two packages (or some other appropriate behavior)?  If the packages are installed, the new import statements could be used instead.

**Comment by hjmjohnson** [comment]
I too am getting this warning:


12:36 $ git grep IPython.kernel
nipype/pipeline/plugins/ipythonx.py:    from IPython.kernel.contexts import ConnectionRefusedError
nipype/pipeline/plugins/ipythonx.py:            name = 'IPython.kernel.client'
✔ /Shared/pinc/sharedopt/20160202/RHEL6/NEP-11/NIPYPE [master|✚ 1] 
12:36 $ ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead

**Comment by satra** [comment]
submitted a set of fixes in #1451.
