### ISSUE TITLE
Cannot create sane design matrix with nipype.interfaces.fsl.Level1Design

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1455]
I am using [this test script](https://github.com/TheChymera/chyMRI/blob/8743f8d3fb6429de5a024ae0e4f8150afab4751a/tests.py) to preview my design matices for a first-level workflow. The design matrices I get with either `gamma` or `dgamma` on [this row](https://gist.github.com/TheChymera/4b91313f7da843f125593b2369149e1e#file-tests-py-L41) look like this:

![figure](https://cloud.githubusercontent.com/assets/950524/14819993/e5cf6f14-0bc4-11e6-8601-4ce5be9a3c6f.png)

If I try to set that row to `level1design.inputs.bases = {'none': None}` (as the docstring suggests I could), I get the following error:

```
Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1466, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1500, in _run_interface
    self.raise_exception(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1424, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
feat_model run0 
Standard output:
Not enough data in /home/chymera/src/chyMRI/tests/test_model_wf/level1design/ev_s1_0_1.txt
Standard error:

Return code: 1
Interface FEATModel failed to run. 
```

I would like to know how I can get a design matrix that does not have a massive undershoot towards the beginning. I can imagine that element greatly degrades my model's performance, as it'S impossible for my signal to create an undershoot *before* it occurs.

**Comment by satra** [comment]
@TheChymera - FSL generates high-pass filtered design matrices. so the image you are looking at is the effect of convolution with an HRF and then high pass filtering.

**Comment by TheChymera** [comment]
It seems the negative gaussian (?) that is added to the swpikes can be deactivated by changing the following rows in the `run0.fsf` file taken ans an input by `FEATModel()` from 

```
# Apply temporal filtering (EV 1)
set fmri(tempfilt_yn1) 1
```

to 

```
# Apply temporal filtering (EV 1)
set fmri(tempfilt_yn1) 0
```

The design matrix I get after doing that (manually, as it seems Nipype has no binding for it) looks like this:
![figure](https://cloud.githubusercontent.com/assets/950524/14821499/41b52c82-0bcb-11e6-8a08-6756e01b92b1.png)

So it seems FSL:

* Tries to keep the integral of each regressor null
* Applies a negative gaussian(?) to "catch" possible low-frequency signals which are in-phase with the regressor.

@satra you're suggesting this is normal behaviour, yes? Does anybody here know why he regressor should be kept null, and why it makes sense to assume that the high-pass filtering is applied at the GLM level rather than in the preprocessing?

**Comment by mwaskom** [comment]
If you have filtered your data, then you also need to filter your design.

**Comment by TheChymera** [comment]
Ah, I think I understand now, this is not to substitute preprocessing, but to complement it. High-pass filtering will add that negative low-frequency dent to high-frequency signals, as it removes whatever part of them is contributed to by a low frequency component.

However, for the sake of reference, the behaviour I was initially looking to obtain is indeed accessible via nipype. By setting:

```
specify_model.inputs.high_pass_filter_cutoff = 0
```

I get a design matrix like:

![figure](https://cloud.githubusercontent.com/assets/950524/14822556/70c8ffa4-0bcf-11e6-8993-bed1a89f9f81.png)
