### ISSUE TITLE
Nipype with pymvpa fails on the cluster

### ISSUE THREAD

**Issue by dpaniukov** [nipy/nipype#1456]
Hello, I have an issue with nipype on SGE cluster. I have nipype installed with anaconda and pyvmpa installed with anaconda. I attached my scripts. The main script I run is the SL_runner.py by passing "8 SVM_mc Subject001" to it from the job file (also attached). 

It gives me an error:
160421-08:28:30,546 workflow ERROR:
['Node searchlight_run.a0 failed to run on host compute-14-5.local.']
160421-08:28:30,547 workflow INFO:
Saving crash info to /lustre/scratch/dpanyuko/RuleSwitch/SL_8SVM_mccrashdumps/crash-20160421-082830-dpanyuko-searchlight_run.a0.pklz
160421-08:28:30,547 workflow INFO:
Traceback (most recent call last):
  File "/lustre/work/apps/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/lustre/work/apps/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
    self._run_interface()
  File "/lustre/work/apps/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 2334, in _run_interface
    updatehash=updatehash))
  File "/lustre/work/apps/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 2239, in _collate_results
    (self.name, '\n'.join(msg)))
Exception: Subnodes of node: searchlight_run failed:
Subnode 0 failed
Error:
instancemethod expected at least 2 arguments, got 0
Interface Function failed to run. 

160421-08:29:30,612 workflow INFO:
***********************************
160421-08:29:30,612 workflow ERROR:
could not run node: wf.searchlight_run.a0
160421-08:29:30,612 workflow INFO:
crashfile: /lustre/scratch/dpanyuko/RuleSwitch/SL_8SVM_mccrashdumps/crash-20160421-082830-dpanyuko-searchlight_run.a0.pklz
160421-08:29:30,612 workflow INFO:
***********************************

It works on my home ubuntu installation, but exactly the same script (path changed) does not work on the cluster. 

Any help will be appreciated. 
[Archive.zip](https://github.com/nipy/nipype/files/237006/Archive.zip)

**Comment by mgxd** [comment]
@dpaniukov 

Have you tried running the workflow with `workflow.run(plugin='SGE')`?

You can find more info on using plugins [here](http://nipy.org/nipype/users/plugins.html).

**Comment by dpaniukov** [comment]
I tried, but it takes infinite (?) time to finish a task. It splits my scripts into jobs from nodes:
1. main job
2. node1
3. node2
etc.
But in runs only the main job for like 6 hours and never starts a next node. The searchlight I am trying to run takes about 2-3 hours.

**Comment by dpaniukov** [comment]
It seems to be an issue with ppocess module, and does not relate to nipype.
