### ISSUE TITLE
Could not import extension readthedocs_ext.readthedocs

### ISSUE THREAD

**Issue by ostanley** [nipy/nipype#1457]
Trying to run `make check-before-commit` before submitting pull request but running into this issue:

`
Extension error:
Could not import extension readthedocs_ext.readthedocs (exception: No module named readthedocs_ext.readthedocs)
make[1]: *** [htmlonly] Error 1
make[1]: Leaving directory '/path/nipype/doc'
make: *** [html] Error 2
`

It is part of the make html section but I have not found a good solution. I assume its a missing dependency but I have sphinx and rtd.

Any thoughts?

Thanks,

Olivia

**Comment by satra** [comment]
@ostanley - this will install it - we are using it for 
`pip install https://github.com/rtfd/readthedocs-sphinx-ext/archive/master.zip`

however i just submitted a PR which should allow testing without requiring that extension.

**Comment by ostanley** [comment]
That worked thanks! Also glad to hear it won't be an issue in the future. :)
