### ISSUE TITLE
smri_fsreconall.py tutorial not working with my own data; Interface Function failed to run

### ISSUE THREAD

**Issue by rpalmeida** [nipy/nipype#1472]
Hi, 
I've adapted the smri_fsreconall.py tutorial to work with my own data but it seems that I've found a bug.
# here is my code:
import os
#import re
import nipype.pipeline.engine as pe
import nipype.interfaces.io as nio
from nipype.workflows.smri.freesurfer import create_reconall_workflow
from nipype.interfaces.freesurfer.utils import MakeAverageSubject
from nipype.interfaces.utility import IdentityInterface

work_dir = '/Users/Raquel/Desktop/DATA'
print 'The working directory is: ' + work_dir + '\n'
dcm_folder =  work_dir + '/ADNI_DATA_nii'
print 'The raw data directory is: ' + dcm_folder + '\n'
#recon_all_folder = work_dir + '/recon_all'
#print 'After applying RECON-ALL the data will be in: ' + recon_all_folder + '\n'
base_folder =  work_dir + '/workdir'
print 'The base directory is: ' + base_folder + '\n'

# Assign the workflow directory

workflow_dir = os.path.abspath('workflow_dir')
if not os.path.isdir(workflow_dir):
    os.mkdir(workflow_dir)

# Define the workflow directories

subject_list = os.listdir(dcm_folder)
#subject_list=[os.path.basename(x) for x in glob.glob(dcm_folder + '/*')] #Generates subject list and drops path from list
print subject_list
data_dir = os.path.abspath(dcm_folder)
print data_dir
subjects_dir = os.path.abspath('recon_all')
print subjects_dir
if not os.path.exists(subjects_dir):
    os.mkdir(subjects_dir)
    

wf = pe.Workflow(name="l1workflow")
wf.base_dir = os.path.join(workflow_dir, 'workdir')

# Create inputspec

#Set up iteration over subjects
inputspec = pe.Node(interface=IdentityInterface(['subject_id']),
                    name="inputspec")
inputspec.iterables = ("subject_id", subject_list)

# Grab data

datasource = pe.Node(interface=nio.DataGrabber(infields=['subject_id'],
                                               outfields=['struct']),
                        name='datasource')
datasource.inputs.base_directory = data_dir
datasource.inputs.template = '*'
datasource.inputs.field_template = {'struct': '%s/MP*/2*/S*/*.nii.gz'}
datasource.inputs.template_args = {'struct': [['subject_id']]}
datasource.inputs.subject_id = subject_list
datasource.inputs.sort_filelist = True

wf.connect(inputspec, 'subject_id', datasource, 'subject_id')

# Run recon-all

recon_all = create_reconall_workflow()
recon_all.inputs.inputspec.subjects_dir = subjects_dir

wf.connect(datasource, 'struct', recon_all, 'inputspec.T1_files')
wf.connect(inputspec, 'subject_id', recon_all, 'inputspec.subject_id')

#Make average subject

average = pe.JoinNode(interface=MakeAverageSubject(),
                      joinsource="inputspec",
                      joinfield="subjects_ids",
                      name="average")
average.inputs.subjects_dir = subjects_dir

wf.connect(recon_all, 'postdatasink_outputspec.subject_id', average, 'subjects_ids')

wf.run("MultiProc", plugin_args={'n_procs': 4})

# Here is the log file:

File: /Users/Raquel/Python/crash-20160512-004117-Raquel-Robust_Template.a2.pklz
Node: l1workflow.ReconAll.AutoRecon1.Robust_Template.a2
Working directory: /Users/Raquel/Python/workflow_dir/workdir/l1workflow/ReconAll/AutoRecon1/_subject_id_002_S_0413/Robust_Template

Node inputs:

function_str = def createTemplate(in_files, out_file):
    import os
    import shutil
    if len(in_files) == 1:
        print("WARNING: only one run found. This is OK, but motion correction " +
              "cannot be performed on one run, so I'll copy the run to rawavg " +
              "and continue.")
        shutil.copyfile(in_files[0], out_file)
        intensity_scales = None
        transforms = None
    else:
        from nipype.interfaces.freesurfer import RobustTemplate
        # if multiple T1 scans are given
        intensity_scales = [os.path.basename(f.replace('.mgz', '-iscale.txt')) for f in in_files]
        transforms = [os.path.basename(f.replace('.mgz', '.lta')) for f in in_files]
        robtemp = RobustTemplate()
        robtemp.inputs.in_files = in_files
        robtemp.inputs.average_metric = 'median'
        robtemp.inputs.out_file = out_file
        robtemp.inputs.no_iteration = True
        robtemp.inputs.fixed_timepoint = True
        robtemp.inputs.auto_detect_sensitivity = True
        robtemp.inputs.initial_timepoint = 1
        robtemp.inputs.scaled_intensity_outputs = intensity_scales
        robtemp.inputs.transform_outputs = transforms
        robtemp.inputs.subsample_threshold = 200
        robtemp.inputs.intensity_scaling = True
        robtemp.run()
        intensity_scales = [os.path.abspath(f) for f in robtemp.outputs.scaled_intensity_outputs]
        transforms = [os.path.abspath(f) for f in robtemp.outputs.transform_outputs]
        out_file = robtemp.outputs.out_file
    out_file = os.path.abspath(out_file)
    return out_file, intensity_scales, transforms

ignore_exception = False
in_files = ['/Users/Raquel/Python/workflow_dir/workdir/l1workflow/ReconAll/AutoRecon1/_subject_id_002_S_0413/T1_prep/mapflow/_T1_prep0/001.mgz', '/Users/Raquel/Python/workflow_dir/workdir/l1workflow/ReconAll/AutoRecon1/_subject_id_002_S_0413/T1_prep/mapflow/_T1_prep1/002.mgz', '/Users/Raquel/Python/workflow_dir/workdir/l1workflow/ReconAll/AutoRecon1/_subject_id_002_S_0413/T1_prep/mapflow/_T1_prep2/003.mgz', '/Users/Raquel/Python/workflow_dir/workdir/l1workflow/ReconAll/AutoRecon1/_subject_id_002_S_0413/T1_prep/mapflow/_T1_prep3/004.mgz']
out_file = rawavg.mgz

Traceback: 
Traceback (most recent call last):
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 989, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/Users/Raquel/anaconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 447, in _run_interface
    out = function_handle(**args)
  File "<string>", line 29, in createTemplate
AttributeError: 'RobustTemplate' object has no attribute 'outputs'
Interface Function failed to run.

**Comment by oesteban** [comment]
I guess you really want to do this:

```
iface_result = robtemp.run()
out_file = iface_result.outputs.out_file
```

**Comment by rpalmeida** [comment]
I can see that on the log.... but where do I put that, in order for the workflow to work?

**Comment by oesteban** [comment]
It seems this code is inside the function ```createTemplate```. So, wherever it is defined.

**Comment by satra** [comment]
@rpalmeida - can you check if the fixed function works?

**Comment by rpalmeida** [comment]
Hi, I'm still having a problem...
I've started running the workflow on Wednesday (two days ago) and since then it got stuck at:
`Executing node CA_Register.a1 in dir: /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon2/_subject_id_011_S_4120/CA_Register
160525-15:22:12,723 workflow INFO:
	 Running: mri_ca_register -align-after -mask /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_011_S_4120/Copy_Brainmask/brainmask.mgz -nobigventricles -T /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon2/_subject_id_011_S_4120/Align_Transform/talairach.lta /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon2/_subject_id_011_S_4120/CA_Normalize/norm.mgz /Applications/freesurfer/average/RB_all_2008-03-26.gca talairach.m3z`

here is the crash file:
```
File: /Users/raquelalmeida/Documents/Python/crash-20160525-142925-raquelalmeida-Robust_Template.a0.pklz
Node: l1workflow.ReconAll.AutoRecon1.Robust_Template.a0
Working directory: /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/Robust_Template


Node inputs:

function_str = def createTemplate(in_files, out_file):
    import os
    import shutil
    if len(in_files) == 1:
        # if only 1 T1 scan given, no need to run RobustTemplate
        print("WARNING: only one run found. This is OK, but motion correction " +
              "cannot be performed on one run, so I'll copy the run to rawavg " +
              "and continue.")
        shutil.copyfile(in_files[0], out_file)
        intensity_scales = None
        transforms = None
    else:
        from nipype.interfaces.freesurfer import RobustTemplate
        # if multiple T1 scans are given run RobustTemplate
        intensity_scales = [os.path.basename(f.replace('.mgz', '-iscale.txt')) for f in in_files]
        transforms = [os.path.basename(f.replace('.mgz', '.lta')) for f in in_files]
        robtemp = RobustTemplate()
        robtemp.inputs.in_files = in_files
        robtemp.inputs.average_metric = 'median'
        robtemp.inputs.out_file = out_file
        robtemp.inputs.no_iteration = True
        robtemp.inputs.fixed_timepoint = True
        robtemp.inputs.auto_detect_sensitivity = True
        robtemp.inputs.initial_timepoint = 1
        robtemp.inputs.scaled_intensity_outputs = intensity_scales
        robtemp.inputs.transform_outputs = transforms
        robtemp.inputs.subsample_threshold = 200
        robtemp.inputs.intensity_scaling = True
        robtemp_result = robtemp.run()
        # collect the outputs from RobustTemplate
        out_file = robtemp_result.outputs.out_file
        intensity_scales = [os.path.abspath(f) for f in robtemp_result.outputs.scaled_intensity_outputs]
        transforms = [os.path.abspath(f) for f in robtemp_result.outputs.transform_outputs]
    out_file = os.path.abspath(out_file)
    return out_file, intensity_scales, transforms

ignore_exception = False
in_files = ['/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep0/001.mgz', '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz', '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep2/003.mgz', '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep3/004.mgz', '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep4/005.mgz']
out_file = rawavg.mgz



Traceback: 
Traceback (most recent call last):
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/Users/raquelalmeida/anaconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 496, in _run_interface
    raise out
RuntimeError: Command:
mri_robust_template --satit --average 1 --fixtp --mov /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep0/001.mgz /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep2/003.mgz /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep3/004.mgz /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep4/005.mgz --inittp 1 --iscale --noit --template rawavg.mgz --iscaleout 001-iscale.txt 002-iscale.txt 003-iscale.txt 004-iscale.txt 005-iscale.txt --subsample 200 --lta 001.lta 002.lta 003.lta 004.lta 005.lta
Standard output:
$Id: mri_robust_template.cpp,v 1.37.2.2 2012/10/10 19:59:06 mreuter Exp $

--satit: Will estimate SAT iteratively!
--average: Using method 1 for template computation.
--fixtp: Will map everything to init TP!
--mov: Using /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep0/001.mgz as movable/source volume.
--mov: Using /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz as movable/source volume.
--mov: Using /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep2/003.mgz as movable/source volume.
--mov: Using /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep3/004.mgz as movable/source volume.
--mov: Using /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep4/005.mgz as movable/source volume.
    Total: 5 input volumes
--inittp: Using TP 1 as target for initialization
--iscale: Enableing intensity scaling!
--noit: Will output only first template (no iterations)!
--template: Using rawavg.mgz as template output volume.
--iscaleout: Will perform intensity scaling and output results
--subsample: Will subsample if size is larger than 200 on all axes!
--lta: Will output LTA transforms
reading source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep0/001.mgz'...
converting source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep0/001.mgz' to bspline ...
MRItoBSpline degree 3
reading source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz'...
converting source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz' to bspline ...
MRItoBSpline degree 3
reading source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep2/003.mgz'...
converting source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep2/003.mgz' to bspline ...
MRItoBSpline degree 3
reading source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep3/004.mgz'...
converting source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep3/004.mgz' to bspline ...
MRItoBSpline degree 3
reading source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep4/005.mgz'...
converting source '/Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep4/005.mgz' to bspline ...
MRItoBSpline degree 3
Standard error:
ERROR: MultiRegistration::loadMovables: images have different voxel sizes.
  Currently not supported, maybe first make conform?
  Debug info: size(1) = 1, 1, 1.2   size(0) = 1, 1, 1
MultiRegistration::loadMovables: voxel size is different /Volumes/LaCie/RaquelAlmeida/workflow_dir/workflow_dir/l1workflow/ReconAll/AutoRecon1/_subject_id_006_S_4150/T1_prep/mapflow/_T1_prep1/002.mgz.

Return code: 251
Interface RobustTemplate failed to run. 
Interface Function failed to run.
```

Is this related with the bug I reported?
Thanks for your help.
Raquel

**Comment by rpalmeida** [comment]
@dgellis90 @satra, any thoughts?

**Comment by dgellis90** [comment]
This is a different issue. It says the voxel size is different for the
002.mgz image. Does this data get past the robust template stage with
recon-all run from the command line?

**Comment by rpalmeida** [comment]
Hi,
I've tested the recon-all directly in the command line but with .dcm instead of .nii. It takes about 9h for each image, but it runs with out any problem. I have almost 3000 images this is why I was trying to use parallel processing. It will be faster, right?
Do you believe this is a problem of the dcm2nii conversion, or is it something else?
In the mean time will test directly with de nii files, just to be sure.

**Comment by cni-md** [comment]
@rpalmeida  For speeding up things I use freesurfer.interface.reconall with freesurfer-dev (6.0) and the -parallel flag.
reconall -3T -cm -parallel ....

**Comment by satra** [comment]
@cni-md - the parallel option there does basic parallelization. while this workflow does more, it won't help unless you have tens of thousands of cores for that many images. (ps. i would recommend rerunning all recons run using freesurfer-dev-6 after they release in a few weeks. there has been a lot of changes throughput the dev process.)

@rpalmeida - depending on your cluster your best option to run freesurfer on that many images is to simply use 1 core per recon. if your cluster is large, you can go upto 4 cores per recon. (it's also quite crazy how many times people run freesurfer on ADNI images, just because ADNI doesn't allow distributing the freesurfer recons!)

regarding the question @dgellis90 asked, it seems that in your example a single recon is getting multiple images.

have you tested recon-all with something like this:

`recon-all -subjid foo -all -i T1_1.nii.gz -i T1_2.nii.gz`

@dgellis90 - have you tested the workflow with a dual input setting such as above?

**Comment by mwaskom** [comment]
@rpalmeida Do you have 3000 anatomical scans? Or 3000 dicom files? You don't need to feed each individual dicom file to a separate recon-all instance, if you are starting with dicoms, you pass it just one file from each scan, and it will try to figure out the other files that go along with. If you're converting a single dicom frame to a nifti and trying to run recon-all on that, it might be the source of your problem. Double-check that the nifti file actually looks like a complete anatomical image.

**Comment by satra** [comment]
@mwaskom - knowing she is working with ADNI, i think she has about 3k images.

**Comment by mwaskom** [comment]
Ah! Well then I would...definitely try to parallelize that.

**Comment by dgellis90** [comment]
@satra yes. I've tested the workflow with multiple T1 scans, but the images I used all had the same spacing. Does recon-all work if the input T1 scans have different spacing?

**Comment by satra** [comment]
thanks @dgellis90 - i've asked the freesurfer folks about differing resolutions.

**Comment by rpalmeida** [comment]
Hi everyone,
Any idea of how far away is a "few weeks" for the freesurfer 6.0 release?

@mwaskom - I'm using ANDI data and I do have 3k anatomical images and about 3k times 170 dicoms. 

@satra -  You said that "it seems that in your example a single recon is getting multiple images"
In each subject folder I have multiple scans (each scan is in a different folder, since they are done in different occasions). I need to do one recon per scan, not one recon with various scans. This means that my input is: 
`recon-all -subjid foo -all -i T1_1.nii.gz` and not `recon-all -subjid foo -all -i T1_1.nii.gz -i T1_2.nii.gz`.

@dgellis90 - Is the workflow identifying the nifti files in each subject folder as different inputs for the same recon? If so how do I change that?
Why do I need to convert the dicoms to a nifti file in order to use this workflow?

Thank you all,
Raquel

**Comment by dgellis90** [comment]
@rpalmeida - The error message shows that there were five input volumes. My guess is that your datasource node is finding all of the scans for one subject and passing them to the workflow together. You most likely need to modify your datasource node so that only one T1 at a time is given to the input 'T1_files'  in the workflow. Also, you will need to pass a unique subject_id to the workflow for each scan so that the workflow can write the output files to a unique folder in the subjects directory.

**Comment by satra** [comment]
@rpalmeida and @dgellis90 - the freesurfer folks confirmed that freesurfer cannot use files with different spatial resolutions currently.

but from this conversation it looks like these were different time points for each participant, and should have been processed individually anyway.

**Comment by rpalmeida** [comment]
Hi guys, 

I ended up changing the data grabber to get the image_id and not the subject_id. I even tried with both but I realised that I was mixing images with subjects...

What I wanted to say is that I managed to process 6 images (2 for one subject and 4 for one other) in about 16h, instead of the 8-9h i was taking by processing one at a time!

Thank you all so much for the help,
Raquel
