### ISSUE TITLE
JistIntensityMp2rageMasking interface incompatible with current CBS Tools release

### ISSUE THREAD

**Issue by juhuntenburg** [nipy/nipype#1473]
For the command underlying the interface mipav.JistIntensityMp2rageMasking the parameter names have changed in the current CBS Tools release, which makes the interface fail. I meant to do a PR but then saw the mipav/developer.py file is autogenerated and should not be be edited. 

These would be the required changes:
https://github.com/nipy/nipype/compare/master...juhuntenburg:fix/cbstools_params

**Comment by juhuntenburg** [comment]
Hi, any news on if these changes will be integrated? Should i make a PR? We are using the mipav interfaces for one of our main pipelines at the institute and it would be great for new users to get around using local nipype clones. Or is there anything speaking against integrating them?
Thank you!

**Comment by chrisfilo** [comment]
Please make a pr. We should merge this.
