### ISSUE TITLE
Clean up logging and config system

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#148]
Currently config can be set up by:
nipype.cfq
~/.nipype.cfg

Additionally some values (those used by nodes with exception of logging) can be set in config field in workflow. For example:

workflow.config = {'execution': {'hash_method':'timestamp'}}

Logging level can be, however, set only in .cfg files. This should be rethought and consolidated.

**Comment by djarecka** [comment]
closing for now, please update the info and open a new issue if this is still an issue
