### ISSUE TITLE
nose tests hang in Python 3, OS X

### ISSUE THREAD

**Issue by shoshber** [nipy/nipype#1480]
The nosetest command given in the install tutorial (http://nipy.org/nipype/users/install.html#testing-the-install) hangs indefinitely on my computer when running in python 3. No error messages or any indication that something is wrong. The tests run in python 2.7 perfectly.

OS and version: Mac OS X 10.9.5
Nipype version: most recent pull from nipype/master
Output of nipype.get_info(): 
`>>> nipype.get_info()
{'sys_version': '3.4.4 |Anaconda custom (x86_64)| (default, Jan  9 2016, 17:30:09) \n[GCC 4.2.1 (Apple Inc. build 5577)]', 'sys_executable': '/Users/shoshanaberleant/anaconda3/bin/python', 'scipy_version': '0.17.0', 'networkx_version': '1.11', 'traits_version': '4.5.0', 'nibabel_version': '2.0.2', 'pkg_path': '/Users/shoshanaberleant/Documents/Stanford/code/nipype/nipype', 'commit_source': 'repository', 'sys_platform': 'darwin', 'commit_hash': b'b2b5155', 'numpy_version': '1.9.3'}
`

output (verbosity=4) pre-keyboard interrupt:
[tempnipypetests.txt](https://github.com/nipy/nipype/files/273448/tempnipypetests.txt)
output (verbosity=4 post-keyboard interrupt: 
[temptailnipypetests.txt](https://github.com/nipy/nipype/files/273555/temptailnipypetests.txt)

**Comment by mgxd** [comment]
this should now be fixed in latest version
