### ISSUE TITLE
antsBrainExtraction interface creates and deletes the masks?

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1486]
I configure my brain extraction node thus:

```
functional_skullstrip = pe.Node(interface=ants.segmentation.BrainExtraction(), name="functional_skullstrip")
functional_skullstrip.inputs.dimension = 3
functional_skullstrip.inputs.brain_template = "/home/chymera/NIdata/templates/ds_QBI_chr.nii.gz"
functional_skullstrip.inputs.brain_probability_mask = "/home/chymera/NIdata/templates/ds_QBI_chr_bin.nii.gz"
```

the resulting command is:

```
antsBrainExtraction.sh -a /mnt/data/NIdata/ofM.dr/level1/bruker_preprocessing/_condition_ofM_aF_subject_4008/_scan_type_7_EPI_CBV/functional_FAST/corr_10_mean_restore.nii.gz -m /mnt/data/NIdata/ofM.dr/level1/bruker_preprocessing/_condition_ofM_aF_subject_4008/_scan_type_7_EPI_CBV/functional_skullstrip/ds_QBI_chr_bin.nii.gz -e /home/chymera/NIdata/templates/ds_QBI_chr.nii.gz -d 3 -s nii.gz -o highres001
```

Note how the probability mask is not used directly, but copied into the node directory. It also magically vanished by the end of the execution, so I cannot determine whether the mask used was indeed the one I specified. Does the interface perhaps manipulate it somehow (rigid transform, perhaps?)?

I looked at the source code of the interface, paticulary [this part](https://github.com/nipy/nipype/blob/bb0013f9b0a7bad701bcf9224798c8f81e09edc7/nipype/interfaces/ants/segmentation.py#L621). But I can't tell what is going on - if anything `copyfile` is set to False...

**Comment by satra** [comment]
this is discussed in the nipype config document. the following setting should disable removing any unnecessary files post execution.

workflow.config['execution']['remove_unnecessary_outputs'] = False

you can also look at the commandline output of the node to see how things are being used.

**Comment by TheChymera** [comment]
> you can also look at the commandline output of the node to see how things are being used.

is there any other command line info available from the node than what I posted above (from `command.txt`)? I don't understand how/why NiPype copies my mask file before it generates the command line statement.

**Comment by oesteban** [comment]
Files are copied right before execution of the interface:

https://github.com/nipy/nipype/blob/bb0013f9b0a7bad701bcf9224798c8f81e09edc7/nipype/pipeline/engine/nodes.py#L614-L615

Regarding the info of a node after execution, these can be useful:

  - `_0x<hash>.json` : lists inputs / outputs
  - `_report/report.rst`: includes lots of information
