### ISSUE TITLE
import nipype executes test.py within current dir.

### ISSUE THREAD

**Issue by pehses** [nipy/nipype#1495]
A month ago, every analysis I was running suddenly started to open a matplotlib scatterplot first (I had to close the figure before the analysis would continue). It turns out that at some point before, I created a 'test.py'-file inside my analysis-directory and every first 'import nipype' command within a python-file/ipython-session now executes this file. It took me a while to figure this out since I completely forgot about creating the test.py file. Is this intended behavior?

Steps to reproduce:
1) create a test.py file, e.g. with a print statement
2) open an ipython session in the same directory and 'import nipype' (importing a submodule will show the same result)

Workaround: delete/move/rename test.py

**Comment by mgxd** [comment]
@pehses I think this was fixed when updating our test-suite, I haven't been able to replicate since. If this is still happening, feel free to open the issue again
