### ISSUE TITLE
Getting started: nipype for dummies. Step 1. Testing nipype

### ISSUE THREAD

**Issue by Koenevandijk** [nipy/nipype#1496]
Hi there, nipype newbe here.

I'm using linux (Red Hat 6.6) and have a terminal window in bash. I would like to try to use nipype as wrapper to call some other tools (fsl, freesurfer, spm) to process anatomical and functional MRI data.

I had nipype installed inside anaconda-4.0.0:

vandik01@amrndhl456:TEST_NIPYPE$ls /nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/*nipy*
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipy_3dto4d
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipy_4d_realign
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipy_4dto3d
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipy_diagnose
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipype2boutiques
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipype_cmd
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipype_display_crash
/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/bin/nipy_tsdiffana

I have a test subject with structural and functional MRI data ready:
vandik01@amrndhl456:TEST_NIPYPE$ls -1 
Sub0001_Ses1_Scan_01_ANAT1.nii.gz
Sub0001_Ses1_Scan_02_BOLD1.nii.gz
Sub0001_Ses1_Scan_03_BOLD2.nii.gz

I have the latest version of fsl:
vandik01@amrndhl456:TEST_NIPYPE$which fsl
/hpc/grid/wip_cmg_nsru/QM-IandE-MRI/SOFTWARE/fsl/5.0.9/bin/fsl

I'm at this "Beginner's guide":
http://nipy.org/nipype/quickstart.html

And followed the link to "Dissecting Nipype Workflows": 
http://slideviewer.herokuapp.com/url/raw.github.com/nipy/nipype/master/examples/nipype_tutorial.ipynb?theme=sky

During "Step 1: Testing nipype":

=============
import nipype

# Comment the following section to increase verbosity of output
nipype.config.set('logging', 'workflow_level', 'CRITICAL')
nipype.config.set('logging', 'interface_level', 'CRITICAL')
nipype.logging.update_logging(nipype.config)

nipype.test(verbose=0) # Increase verbosity parameter for more info
=============

The first step is fine: 
import nipype

Then I get this:
vandik01@amrndhl456:TEST_NIPYPE$nipype.config.set('logging', 'workflow_level', 'CRITICAL')
bash: syntax error near unexpected token `'logging','

MY QUESTION:
Can someone tell me what's going on? 
Would you perhaps have another set of step by step instructions on how to get started? 

Thanks for any advice/pointers!

**Comment by miykael** [comment]
Hi @Koenevandijk,

I'm not really sure but does the error "bash: syntax error near unexpected token 'logging','" mean that you run the command `nipype.config.set('logging', 'workflow_level', 'CRITICAL')` in bash? As much as I know, the test code should be run in a python environment. Does it work if you run:
```
python -c "import nipype; nipype.config.set('logging', 'workflow_level', 'CRITICAL'); nipype.config.set('logging', 'interface_level', 'CRITICAL'); nipype.logging.update_logging(nipype.config); nipype.test(verbose=0)"
```

To your second question, a beginner's guide that you might find helpful is http://miykael.github.io/nipype-beginner-s-guide/index.html, also listed under http://nipy.org/nipype/quickstart.html. Good luck.

**Comment by Koenevandijk** [comment]
Hi @miykael, 
Thanks for your helpful comment and *very* helpful beginners guide. I was not aware of this intro to nipype that includes an amazingly complete description of the practicalities of fMRI data acquisitions and analysis! 

Your comment that I should run the commands "in a python environment" helped a lot (I had missed that). 
Cheers

open up an IPython environment (open a
terminal and start IPython with the command ipython)

**Comment by miykael** [comment]
Thanks for the nice feedback. And I'm happy to hear that my comment helped you with your error. I personally recommend to learn Nipype within a python environment.
But you said that you eventually want to use nipype as a wrapper, directly from bash. For this check this page out http://nipy.org/nipype/users/nipypecmd.html. It shows you how to use nipype directly from the command line.
Please don't forget to close this issue if your problem is solved. Thanks, and good luck.

**Comment by Koenevandijk** [comment]
Advice taken: I'll get started within a python environment and then go to calling a pipeline from the command line as step 2.

Two quick follow-up questions (not sure if I should open a new "issue" or not):

1.  When I run the nipype.test (as in the first box on page 43 in your guide under TEST YOUR SYSTEM) I get a couple of errors that look like this:

IOError: Input "bar" is mutually exclusive with input "foo", which is already set

I might tackle this later because point 2 below seems more problematic.


2. During the same test I also get:

ERROR: Failure: IOError ([Errno 13] Permission denied: '/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/python/anaconda-4.0.0/lib/python2.7/site-packages/nipype/testing/data/von_errmap.nii.gz')

I had nipype installed by our IT guys in space where others on our systems can potentially also use it. This is space where I do not have write access. 

Do you think that that's a problem? 

Thanks again,

**Comment by miykael** [comment]
i) `IOError: Input "bar" is mutually exclusive with input "foo", which is already set` doesn't seem to be too bad. Once the whole testing is finished you should get a summary output, like described on page 43. In my case, right now I get something like this:
```
EnvironmentError: Can not find Xvfb. Please install it and try again.
...
AttributeError: 'PolyDataWriter' object has no attribute 'set_input_data'
...
ImportError: No module named aniso2iso
----------------------------------------------------------------------
Ran 13387 tests in 152.125s

FAILED (SKIP=14, errors=4)
Out[1]: <nose.result.TextTestResult run=13387 errors=4 failures=0>
```
Those are only errors, which can be ignored if you don't use the corresponding tools. The failures are more important to take care off.

ii) Hmm... It seems that the test run tries to change or write the file ``von_errmap.nii.gz``. And your error seems to be a clear issue of admin rights.
Nipype itself doesn't need to write anything to the nipype package folder, as far as I know. This seems to be a specific issue with the test function.
I think the best option for you is to just go for it and try to use Nipype as you want to use it. You will find out fast enough if you're missing any relevant dependencies.

Good luck.

**Comment by Koenevandijk** [comment]
Excellent advice! thanks,
