### ISSUE TITLE
networkx.exception.NetworkXError: Graph has no nodes or edges

### ISSUE THREAD

**Issue by YSanchezAraujo** [nipy/nipype#1503]
I'm getting a  networkx error when trying to run a fmri level 2 script. Error only appeared after I updated my python packages, but I'm not sure really. 

This is the command used for running it: 

    srun python /om/user/ysa/scripts/l2_check/l2_check.py -o /om/user/ysa/bild/data/l2_test/output_dir -t 1 -d /om/user/ysa/bild/data -l1 /om/user/ysa/bild/data/first_level/output_dir -w /om/user/ysa/bild/data/l2_test/working_dir -p 'SLURM' --plugin_args "dict(sbatch_args='-N1 -c2 --mem=10G')" --sleep 2 -f ols
    

and the error: 

     /om/user/ysa/fmri_env/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client  instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    /om/user/ysa/fmri_env/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
       "You should import from ipyparallel instead.", ShimWarning)
    160608-19:30:23,931 workflow INFO:
	     ['check', 'execution', 'logging']
    160608-19:30:23,945 workflow INFO:
	     Running in parallel.
    Traceback (most recent call last):
      File "/om/user/ysa/scripts/l2_check/l2_check.py", line 309, in <module>
        wf.run(args.plugin, plugin_args=eval(args.plugin_args))
      File "/om/user/ysa/fmri_env/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 701, in run
        runner.run(execgraph, updatehash=updatehash, config=self.config)
      File "/om/user/ysa/fmri_env/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 225, in run
        self._generate_dependency_list(graph)
      File "/om/user/ysa/fmri_env/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 434, in _generate_dependency_list
    nodelist=self.procs)
      File "/om/user/ysa/fmri_env/lib/python2.7/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
    networkx.exception.NetworkXError: Graph has no nodes or edges
     srun: error: node050: task 0: Exited with exit code 1

and finally the script it uses: 

https://github.com/YSanchezAraujo/openfmri/blob/master/group_level/l2_check.py

potentially this can be useful: 

    In [1]: import pkg_resources

    In [2]: pkg_resources.get_distribution("networkx").version
    Out[2]: '1.11'

    In [3]: 

    In [3]: pkg_resources.get_distribution("scipy").version
    Out[3]: '0.17.1'

    In [4]: pkg_resources.get_distribution("nipype").version
    Out[4]: '0.11.0'

**Comment by satra** [comment]
are you sure this line is being called: 

https://github.com/YSanchezAraujo/openfmri/blob/master/group_level/l2_check.py#L244

**Comment by YSanchezAraujo** [comment]
ah i see. I should not trust old untouched commands. task in the command is set to 1 `-t 1` but my `contrasts.txt` only had task2 specified.

**Comment by AmanAmir** [comment]
Hello 
I am new to python and pylayers and trying to run the example simulation for ray tracing transmission channel simulation and get this error
File "/home/FE/memon/anaconda3/lib/python3.7/site-packages/networkx/convert_matrix.py", line 765, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")

NetworkXError: Graph has no nodes or edges
The problem is with the L.Build() command.
Any help on how to run this ?

**Comment by effigies** [comment]
Hi @AmanAmir, I think they'll probably be better equipped to help you at https://github.com/pylayers/pylayers/.
