### ISSUE TITLE
psutils stopps pipeline

### ISSUE THREAD

**Issue by cni-md** [nipy/nipype#1532]
Hi,
I had the problem, that heudiconv -c dcm2niix was working on my office PC but not on the server. On the server the process dcm2niix was in sleepmode (status S+) and nothing happend.

Changing
convertnode.inputs.terminal_output = 'allatonce' to 'stream' solved this problem.

In addition interfaces.freesurfer.reconall stopped working too with psutils installed. No error message only a frozen output during the smoothing after approx 1h.

newest nipype, psutils 4.3.0

Joerg

**Comment by satra** [comment]
@joerg - thanks for the feedback. we will have to look into this.

could you please let us know what OS just so we have a record of this.

**Comment by cni-md** [comment]
Debian 6.0 64bit AMD

Thanks

**Comment by satra** [comment]
@cni-md - if you uninstall psutils, does it work fine?

**Comment by cni-md** [comment]
Yes. python-psutils to be more clear. That's what I did.

Am 14. Juli 2016 01:53:37 MESZ, schrieb Satrajit Ghosh <notifications@github.com>:

**Comment by carolFrohlich** [comment]
Please tell us what pipeline are you using, then we can debug the problem. Is it a nipype freesurfer pipeline or you own pipeline?

**Comment by cni-md** [comment]
Back from vacation. I use the nipype  interfaces.freesurfer.reconall interface in my pipeline.

recon_all = pe.Node(interface=fs.ReconAll(), name='recon_all')
recon_all.inputs.subjects_dir = os.environ['SUBJECTS_DIR']
recon_all.inputs.use_T2 = True
recon_all.inputs.flags = '-3T -cm -parallel'

It is running fine without the python-psutils installed. With psutils it hangs like heudiconv.

**Comment by satra** [comment]
@ccraddock and @carolFrohlich - it would be good to get this resolved.

**Comment by carolFrohlich** [comment]
Thanks! We'll run the pipeline and debug the problem.
