### ISSUE TITLE
Update TravisCI tests to use the docker image

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1537]
Depends on #1536

**Comment by mgxd** [comment]
#1815

**Comment by oesteban** [comment]
Docker images are too big for travis, I don't know if we are still interested on this...

**Comment by djarecka** [comment]
Somehow related: i have on my TODO list to check [tox](https://pypi.python.org/pypi/tox). I understand that once you create python environments you can use them both locally and on Travis. Do you have any thoughts on this? Would it be useful?

**Comment by mgxd** [comment]
@djarecka isn't it better to build the environment every time - that way if there is a new version of a dependency we can check to see if we can support it? also closing this issue, feel free to open if needed

**Comment by djarecka** [comment]
@mgxd - tox is used to test new version of software. My understanding is that you ask for specific Python interpreters and libraries in a similar way as in Travis file. 
In my comment I wasn't clear, but I meant that you simply can easily build the environment (based on the tox file) also  locally on your computer, so it might be useful for debugging I guess.  
However, for now I gave up, would have to learn more how to integrate it with no python packages, and it looks like people are happy without it ;-)
