### ISSUE TITLE
Update CircleCI tests to use the docker image

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1538]
Depends on #1536

**Comment by oesteban** [comment]
Ok, apparently the test ```python ~/nipype/tools/run_examples.py  test_spm Linear workflow3d workflow4d``` is working locally in my desktop. Once I'm sure all the tests work, I'll update ```circle.yml```.

**Comment by satra** [comment]
so there is a little issue with building the images on dockerhub. matlab command runtime has it's own libcurl which is overwriting the system curl package through LD_LIBRARY_PATH.

so we may want to think about allowing users to enable MCR through a script, instead of making it default.

**Comment by chrisfilo** [comment]
Why not just temporarily unsetting LD_LIBRARY_PATH when you perform the
download?

**Comment by oesteban** [comment]
Since we were not setting the ```LD_LIBRARY_PATH``` (even though it was instructed by the matlab installation), I have tried disabling it. It works fine this way.

**Comment by oesteban** [comment]
This is already in place
