### ISSUE TITLE
Cannot view .pklz crash files

### ISSUE THREAD

**Issue by brownsarahm** [nipy/nipype#1542]
I get the following error when I run nipype_display_crash

-bash: /usr/local/anaconda/bin/nipype_display_crash: /home/travis/miniconda/envs/testenv/bin/python: bad interpreter: No such file or directory

it appears there's a manually set local directory somewhere

**Comment by chrisfilo** [comment]
Seems like a duplicate of #1227 :/

**Comment by oesteban** [comment]
OMG :(

**Comment by satra** [comment]
@brownsarahm - would you mind doing the following and let me know if you still have the issue. this shouldn't be happening with current nipype release.

`pip install --upgrade nipype`

**Comment by mgxd** [comment]
this should be fixed
