### ISSUE TITLE
Unable to import afni module

### ISSUE THREAD

**Issue by santiallende** [nipy/nipype#1544]
Hi,
When importing afni in a Jupyter Notebook with `import nipype.interfaces.afni as afni` it returns an error: No module named afni.

I am able to run afni from the terminal so the PATH is correct. What else could be going on? Other imported interfaces work just fine.

**Comment by oesteban** [comment]
Hi @santiallende, it does not look like you've got a problem with AFNI installation. This is about nipype.

How did you install it?

Could you also do ```python -c "import nipype; nipype.__version__"```?

**Comment by santiallende** [comment]
Hi @oesteban, thank you for replying.

I downloaded it based on instructions [here](http://miykael.github.io/nipype-beginner-s-guide/installation.html) with `pip install nipype`. The path is: "~/anaconda2/lib/python2.7/site-packages/nipype-0.12.0rc1-py2.7.egg/nipype"   

`python -c "import nipype; nipype.__version__"` returned: 0.12.0-rc1

**Comment by satra** [comment]
@santiallende - could you try upgrading to the current release?

`pip install --upgrade nipype`

**Comment by santiallende** [comment]
Thanks for your reply, @satra.

It was unable to upgrade: `OSError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype'
Storing debug log for failure in /Users/Santi/.pip/pip.log`

**Comment by satra** [comment]
@santiallende - it looks like you used anaconda to install it first, but in this case it seems that pip is being called from the system python. perhaps your anaconda environment is not initialized.

**Comment by oesteban** [comment]
Yep, and if you still want to stick with conda, probably the best choice is using the new conda-forge installation. It is pretty straightforward to use (http://nipype.readthedocs.io/en/latest/users/install.html#using-conda)

**Comment by miykael** [comment]
I've updated my [beginner's guide](http://miykael.github.io/nipype-beginner-s-guide/installation.html#nipype) so that it points to the conda-forge installation first. I hope to further improve the installation description once the new tutorial is up.

**Comment by santiallende** [comment]
Thank you all for your help! I installed nipype through the conda-forge channel and the AFNI interface now imports.
