### ISSUE TITLE
Python 2.7 incompatibilities in nipype.utils.*

### ISSUE THREAD

**Issue by lebedov** [nipy/nipype#1545]
Several lines are only compatible with Python 3, e.g., [onetime.py#L20](https://github.com/nipy/nipype/blob/master/nipype/utils/onetime.py#L20), [tmpdirs.py#L1](https://github.com/nipy/nipype/blob/master/nipype/utils/tmpdirs.py#L1), [config.py#L13](https://github.com/nipy/nipype/blob/master/nipype/utils/config.py#L13), [logger.py#L1](https://github.com/nipy/nipype/blob/master/nipype/utils/logger.py#L1)

**Comment by oesteban** [comment]
Isn't ```builtins``` provided by ```future```?

**Comment by lebedov** [comment]
Hm..yes it is - the `future` package in my Python environment wasn't importable for some reason. Reinstalling the latter fixed the problem.
