### ISSUE TITLE
Convenience method to print required binaries

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1553]
I am trying to find a way to reduce the size of docker images, since they are huge and for running the tests in circle and travis we would benefit a lot from it.

What do you think of a new method _ala_ ```write_graph``` that would print a list of the _cmd of all the inputs and (possibly) the software package they belong? (we would produce a list of unique hits)

This way, we could build a minimal image for tests narrowing down the problem to also including the linked libraries.

**Comment by satra** [comment]
@oesteban - some of this info is covered in the provenance output, which we taking a much closer look at now (https://docs.google.com/document/d/1OjdvKyjSuLXoPrmH18SPj2Fe1bvkomQjowY7TG-F8MQ/edit). but this is also an ongoing discussion on another project - @yarikoptic can chime in - so hopefully we can converge on a solution.

**Comment by satra** [comment]
@oesteban - for the moment i would suggest taking a look at reprozip or cdepack. should work fine for linux.
