### ISSUE TITLE
Make docker images thinner and use tags

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1558]
The current versioning of docker images is not appropriate. We should aim at having only one docker image name ```nipype/nipype``` for the _production_ images (with all the software written in #1536) and use tags to identify the images:
```
nipype/nipype:py2.7
nipype/nipype:py3.4
nipype/nipype:py3.5
```

For tests, I would propose to have one ```nipype/nipype_tests```. That would include 6 tags for running the matrix of tests that we currently have in travis, and one tag for circle.

This would also fix this issue: #1552.

WDYT @satra ?

**Comment by satra** [comment]
sounds good - we should also try to minimize the images. i'm looking into some of that - but may not happen immediately.

**Comment by oesteban** [comment]
yes, I also have that in mind. That's why I think we should split between a fully-fledged _production_ image (that can be large because all the tools we want in it), but thin images for testing.

Currently I'm stuck with travis because of the size of the images.

**Comment by oesteban** [comment]
Images narrowed down from ~6GB to ~2GB

**Comment by oesteban** [comment]
I think this can be closed
