### ISSUE TITLE
 Failed doctest test for nipype.interfaces.bru2nii.Bru2 and others

### ISSUE THREAD

**Issue by justin-torok** [nipy/nipype#1567]
Hi,

I'm new to Nipype and neural image processing.  After downloading some of the requisite packages and imaging software, I installed Nipype using pip install on 8/2/16 and ran the test suggested on the installation page: 'python -c "import nipype; nipype.test()"'.  I encountered 4 errors, which I have put in the attached file.  I'm also attaching the output of nipype.get_info().  I use Ubuntu 14.04 and MATLAB R2016a, and have installed SPM12, FreeSurfer v5.3.0, and FSL v4.1.

I haven't tried to run any pipelines yet, but I'd like to try to correct these errors now before I run into issues down the line.  Any help would be greatly appreciated.

Thanks,
Justin

[08-04-16_getinfo_output.txt](https://github.com/nipy/nipype/files/404610/08-04-16_getinfo_output.txt)
[08-02-16_nosetest_output.txt](https://github.com/nipy/nipype/files/404611/08-02-16_nosetest_output.txt)

**Comment by oesteban** [comment]
Hi @justin-torok, did you manage to run any pipelines? I think the nipype.test() failed because it is running in the installation folder, but your install seems to be alright.

**Comment by justin-torok** [comment]
Thanks for getting back to me.  I closed the issue because it appears that
things are working OK on my system so far, though a few of the nose tests
still fail.  If I run into a critical error, I'll make a note of it.

-Justin
