### ISSUE TITLE
Incorrect exception handling syntax in base plugin module

### ISSUE THREAD

**Issue by jvarada** [nipy/nipype#1575]
https://github.com/nipy/nipype/blob/9d793c1d32ee71636d07a3fe98c7d725034e889a/nipype/pipeline/plugins/base.py#L148

Syntax is incompatible with python 3.

**Comment by oesteban** [comment]
Good catch!. It is also unnecessary since ```e``` is not used and the exception is retrieved right after with the ```exc_info```. I'll be very happy to merge the PR when you send it.
