### ISSUE TITLE
Convenient load of settings from JSON file at interface creation

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1578]
It'd be great if we could create interfaces in this fashion:

```
reg = ants.Registration(from_file='settings.json')
```

where settings.json contains, for instance, something in this vein:

```
{
    "dimension": 3,
    "number_of_iterations": [ [ 50 ], [ 20 ] ],
    "use_histogram_matching": [ true, true ],
    "sampling_percentage": [ 0.2, 0.2 ],
    "metric": [ "Mattes", "Mattes" ],
    "winsorize_lower_quantile": 0.015,
    "metric_weight": [ 1.0, 1.0 ],
    "shrink_factors": [ [ 4 ], [ 1 ] ],
    "radius_or_number_of_bins": [ 64, 64 ],
    "winsorize_upper_quantile": 0.998,
    "sampling_strategy": [ "Random", "Random" ],
    "initial_moving_transform_com": 0,
    "convergence_threshold": [ 1e-07, 1e-08 ],
    "collapse_output_transforms": true,
    "convergence_window_size": [ 20, 10 ],
    "sigma_units": [ "mm", "mm" ],
    "transform_parameters": [ [ 0.5 ], [ 0.1 ] ],
    "transforms": [ "Translation", "Rigid" ],
    "use_estimate_learning_rate_once": [ true, true ],
    "smoothing_sigmas": [ [ 10.0 ], [ 2.0 ] ]
}
```

These parameters would nicely act as defaults for the interface, enabling to test an interface without too much verbosity and modifying one parameter at a time.

WDYT?

**Comment by oesteban** [comment]
@satra @chrisfilo any objections to this?

**Comment by satra** [comment]
@oesteban - as long as this is used to simply update the parameters of the interface it would be great. i would like to stay away from config files as alternate inputs (for example, like FNIRT). if all you are thinking is writing out or reading in the inputs from a json file, that would be completely fine with me. since the nipype inputs structure is a dictionary it should be easy to add that to inputspec base class, so you can do:

```
reg.load_inputs_from_json('parameter_set.json')
reg.save_inputs_from_json('parameter_set.json')
```

perhaps with better function names!

**Comment by oesteban** [comment]
This should be relatively easy and the aim clear enough. Do you want to take on it, @shoshber ? Can I help you to touch base on it easy?

**Comment by shoshber** [comment]
I don't see why not, though @satra, can you clarify what you mean by "config files as alternate inputs"? I have never used FNIRT.

Regardless, I wouldn't be able to get to it until next week at the earliest

**Comment by satra** [comment]
ah there are some programs that do `program_name --config=config_file --other_parameters` in this case one really needs to know the form of the config file to know what parameters really went in. i just didn't want us to add a config input option. so no `reg.inputs.config = config.json`

**Comment by shoshber** [comment]
ah, I guess I don't understand the original proposal. Is @oesteban proposing a new way of declaring interfaces? We already do that with Traits, right? Is this better?

**Comment by oesteban** [comment]
@satra, currently I implemented it with the functions you proposed, but also with the ```from_file``` field. I can pull that away, but I think it is pretty convenient. Let me know if you still prefer not to add that.
