### ISSUE TITLE
'mm' option in cluster interface does not seem to work

### ISSUE THREAD

**Issue by egorananyev** [nipy/nipype#1579]
Hi all,

I'm having an issue with the Cluster interface to output coordinates in mm instead of voxel coordinates.

```
# Running cluster to extract p-values:
cl = fsl.Cluster()
cl.inputs.threshold = .95
cl.inputs.in_file = curPFile
cl.inputs.out_localmax_txt_file = curContrName + '_p.txt'
cl.inputs.use_mm = True # this doesn't seem to work
res = cl.run()
```

The following is the output of **print cl.cmdline** command:

> cluster --in=/home/egor/Dropbox/Projects/md/dti/results_2016-08-13/tbss12-bal/tbss_FA_comp12_tfce_corrp_tstat3.nii.gz --olmax=tbss_FA_comp12_tstat3_p.txt --thresh=0.9500000000

Running an equivalent command (with the --mm option) from the Terminal does the trick.

Thanks!
--Egor

**Comment by oesteban** [comment]
Confirmed, will merge when tests passed. Thanks for reporting @egorananyev .
