### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by navotnaor** [nipy/nipype#1583]
Hi all, 

I'm newbie to using Nipype in particular and Linux in general, so please be forgiven :)
I'm trying a code that used to work until, it didn't... 

i run the crash report and i'm getting the following error:
ImportError: No module named builtins

and the source of that error is:
 from .registration import ANTS, Registration
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/ants/registration.py" 

Nipype info is:
{'nibabel_version': '2.0.2', 'networkx_version': '1.8.1', 'numpy_version': '1.8.2', 'sys_platform': 'linux2', 'sys_version': '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]', 'commit_source': 'archive substitution', 'commit_hash': 'e63e055', 'pkg_path': '/usr/lib/python2.7/dist-packages/nipype', 'sys_executable': '/usr/bin/python', 'traits_version': '4.1.0', 'scipy_version': '0.13.3'}

Can anyone help me figure out what am i doing wrong here? Is it possible that this is caused by an unclean installation of Nipype or something similar to that?

Thanks!

**Comment by mgxd** [comment]
could you try updating future with `pip install future --upgrade`?

**Comment by mgxd** [comment]
@navotnaor has this been resolved?
