### ISSUE TITLE
New CompCor interface

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1594]
Create a new interface (under algorithm.misc ?) for the calculation of the [Component Based Noise Correction Method (CompCor)](http://dx.doi.org/10.1016%2Fj.neuroimage.2007.04.042) on r-fMRI.

The code is already here in nipype: 
  - https://github.com/nipy/nipype/blob/master/nipype/workflows/rsfmri/fsl/resting.py
  -  https://github.com/nipy/nipype/blob/c389d5d4c0f1eb5ff321de5553f815d1fb6fcc47/examples/rsfmri_vol_surface_preprocessing_nipy.py

So this issue would include updating both workflow and example to use the new interface.

- [x] implement
   - [x] CompCor
      - [x] remove regression residuals
   - [x] tCompCor
      - [x] threshold param
   - [x] aCompcor alias
- [x] use TSNR
   - [x] refactor TSNR
   - [x] move TSNR back into misc.py
   - [x] use in compcor.py
- [x] use interface in https://github.com/nipy/nipype/blob/master/nipype/workflows/rsfmri/fsl/resting.py
- [ ] use interface in https://github.com/nipy/nipype/blob/c389d5d4c0f1eb5ff321de5553f815d1fb6fcc47/examples/rsfmri_vol_surface_preprocessing_nipy.py
   - [x] refactor
   - [ ] runthrough
- [x] fix ups
   - [x] doctest
   - [x] use tempfile in test_tsnr.py
   - [x] explicit relative imports
   - [x] boolean flag for regress_poly

**Comment by chrisfilo** [comment]
Big thumbs up!

**Comment by chrisfilo** [comment]
It would be a "pure python" interface similar to https://github.com/nipy/nipype/blob/master/nipype/algorithms/icc.py#L25

**Comment by satra** [comment]
the function implemented in the resting workflow assumes that something else computes the voxel mask over which the PCA is implemented. this allows the `a` and `t` pieces to be taken care of by other functions/workflows. for example, `fast` is used to get the tissue classes. i would keep that separation for this interface. you can then build a sequence of nodes for aCompCor and tCompCor.

**Comment by shoshber** [comment]
are you saying that computing the `t` mask (top 2% tSTDs) is already implemented somewhere? That would be great

**Comment by shoshber** [comment]
In the paper, after the components are computed, they are applied using a GLM analysis with an AR(1) model for the additive noise component. There are many options in nipype for doing a GLM. The examples above use fsl.FilterRegressor and fsl.GLM, but there is also freesurfer.GLMFit, which has a parameter for using AR1. Which interface is preferred?

**Comment by chrisfilo** [comment]
I would not incorporate applying of the components into this interface -
this step usually combines regressors coming from multiple sources in
addition to CompCor (motion, task design, physiological recordings etc). If
you need this for testing I would go with FSL or something from statmodels.

**Comment by shoshber** [comment]
Oh good, I was leaning that way myself

**Comment by shoshber** [comment]
In the paper, they find the tSTD "after the removal of low-frequency nuisance terms (e.g., linear and quadratic drift)."

Can I assume, if the input is an already-aligned image, that this processing has already been done? If not, how does one determine the "low-frequency nuisance terms"?

**Comment by satra** [comment]
@shoshber - in the resting state workflow, the TSNR node takes care of this

**Comment by shoshber** [comment]
ok, I will assume it is already done

**Comment by chrisfilo** [comment]
Have look here:
https://github.com/nipy/nipype/pull/1599#issuecomment-245180703

On Tue, Sep 6, 2016 at 11:24 PM, Shoshana Berleant <notifications@github.com

**Comment by shoshber** [comment]
I can't get the example .py file to run (https://github.com/nipy/nipype/issues/1616), so I can't test my refactoring.

**Comment by shoshber** [comment]
closed with https://github.com/nipy/nipype/pull/1599
