### ISSUE TITLE
Fixing freesurfer utils MRIsConvert

### ISSUE THREAD

**Issue by alexvicegrab** [nipy/nipype#1595]
In nipype/interfaces/freesurfer/utils.py

line 854 should be fixed to actually include the .asc datatype, by substituting:

    out_datatype = traits.Enum("ico", "tri", "stl", "vtk", "gii", "mgh", "mgz",

with:

    out_datatype = traits.Enum("asc", "ico", "tri", "stl", "vtk", "gii", "mgh", "mgz",

Otherwise "asc" format is not supported.

Thank you!

**Comment by oesteban** [comment]
Hi @alexvicegrab, thanks for reporting. It'll be available right after tests pass :)
