### ISSUE TITLE
Submit coveralls results from CircleCI

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1602]
(per discussion with @chrisfilo last week)

Since tests in CircleCI are more comprehensive, we might expect more accurate statistics from these tests, is that correct?

Additionally, it seems that coveralls is sending multiple updates from travis (failing to merge the results from the test matrix in travis into one outcome).

(TODO after #1572 is merged)

**Comment by shoshber** [comment]
I believe we've replaced coveralls with codecov
