### ISSUE TITLE
CircleCI around 4h is a bit excessive

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1611]
What would be a good solution for you?
- subsample data
- remove duplicity (py27, py35) of  the fmri_spm_nested examples and exercise them only in py27 (versus the other examples which are run in py35).
- remove examples / reconsider what we want to include

**Comment by shoshber** [comment]
In a recent successful build, this command:
`$ docker run -v /etc/localtime:/etc/localtime:ro -v ~/examples:/root/examples:ro -v ~/scratch:/scratch -w /scratch nipype/nipype_test:py35 /usr/bin/run_examples.sh fmri_spm_dartel Linear /root/examples/ level1`

took more than twice as long to complete (72 minutes) as the other commands

**Comment by chrisfilo** [comment]
When this will be merged https://github.com/nipy/nipype/pull/1609 we should
get a better understanding of how much coverage we gain from those tests.

**Comment by oesteban** [comment]
I think CircleCI has started to bounce our builds https://circleci.com/gh/oesteban/nipype/292

**Comment by chrisfilo** [comment]
Doubt it:

"run_examples.sh fmri_spm_nested MultiProc /root/examples/ level1 took more
than 10 minutes since last output"

Question is why it didn't print anything for 10 minutes.

**Comment by mgxd** [comment]
#1769 closes
