### ISSUE TITLE
Conditional keep outputs

### ISSUE THREAD

**Issue by ashgillman** [nipy/nipype#1612]
I have developed some interfaces that work with Interfiles, which are a two (or three) part file. One (or two) header(s) and one data file.

Currently, to prevent deletion of the data files I have to pass every file around twice, so I have `inputs.in1_header`, `inputs.in1_data`, etc. Whereas for these filetypes, if the header is required, the data file is always required. It would be great if I could specify in the `output_spec` that if `out` is a required output, the node should also not delete a file with the same name but a different extension that I could specify.

Similarly, I have an interface that takes a pattern as an input, rather than a list. If I want to pass an output that is actually a file pattern to this input, it would be good if I could keep files matching that pattern (e.g., `output_%d.hv`). This is a bit trickier, because it is arbitrary what type of pattern to use. My current workaround is either specify the pattern and the list as an output, and point the list somewhere so it is kept, or disabling cleaning for the Node.

Maybe you could specify a lambda in the output trait that matches files to keep? Or would this create pickling errors?

I'd be happy to help out with this, if it is something that the developers want.

Cheers

**Comment by oesteban** [comment]
Quick question - Have you tried the ```keep_inputs``` and the ```remove_unnecessary_outputs``` options (see http://nipype.readthedocs.io/en/latest/users/config_file.html)?

**Comment by satra** [comment]
@ashgillman - perhaps you can add to things here:

https://github.com/nipy/nipype/blob/master/nipype/utils/filemanip.py#L317

and here:

https://github.com/nipy/nipype/blob/master/nipype/utils/filemanip.py#L336

**Comment by ashgillman** [comment]
Yes to `remove_unnecessary_outputs`, and I imagine it should also work with `keep_inputs`. But it would be nice to have these conditional on whether the other output is actually used.

**Comment by ashgillman** [comment]
@satra Wow, I haven't come across those bits of code in my searches so far. That looks very similar to what I need.

**Comment by mgxd** [comment]
@ashgillman did the PR clear this issue up?

**Comment by ashgillman** [comment]
Yes, the important part at least.

For anyone interested, you can add to the related filetypes with:

```
nipype.utils.filemanip.related_filetype_sets.extend([
    ('.avh', '.hv', '.v'),
])
```

(but only as of master and presumably the next 0.13 releasse)
