### ISSUE TITLE
fix up rsfmri_vol_surface_preprocessing_nipy.py

### ISSUE THREAD

**Issue by shoshber** [nipy/nipype#1616]
It doesn't run in the canonical docker image or in my environment. It depends on a package called dcmstack that is not on pip (?)

**Comment by chrisfilo** [comment]
You can find this package here: https://github.com/moloney/dcmstack

Many more examples depend on various pieces of software and data that are not included in the "canonical docker" container. I'm not sure if we want to blow it up by installing everything that the examples depend on.

**Comment by shoshber** [comment]
Ah, in that case, documentation would help--I didn't know where to find dcmstack. It is also missing the dicom package--I presume it's somewhere on github? (Couldn't find it when I searched)

**Comment by chrisfilo** [comment]
pip install pydicom

On Sun, Sep 11, 2016 at 8:37 PM, Shoshana Berleant <notifications@github.com

**Comment by shoshber** [comment]
They are installed, now it throws up a new error. I think it just hasn't been run/tested in a while. I will update the issue title to more accurately describe the issue.
'''
Traceback (most recent call last):
  File "examples/rsfmri_vol_surface_preprocessing_nipy.py", line 1024, in <module>
    wf = create_resting_workflow(args)
  File "examples/rsfmri_vol_surface_preprocessing_nipy.py", line 974, in create_resting_workflow
    wf = create_workflow(**kwargs)
  File "examples/rsfmri_vol_surface_preprocessing_nipy.py", line 590, in create_workflow
    realign.inputs.slice_times = slice_times
  File "/home/ubuntu/anaconda3/envs/python2nipype/lib/python2.7/site-packages/traits-4.5.0-py2.7-linux-x86_64.egg/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'slice_times' trait of a SpaceTimeRealignerInputSpec instance must be a list of items which are a float or u'asc_alt_2' or u'asc_alt_2_1' or u'asc_alt_half' or u'asc_alt_siemens' or u'ascending' or u'desc_alt_2' or u'desc_alt_half' or u'descending', but a value of None <type 'NoneType'> was specified.
'''

**Comment by satra** [comment]
@shoshber - that particular workflow is one i'm converting for bids-apps from this repo (https://github.com/gablab/openfmri/tree/master/resting_state). 

it requires a few things to run:

- current nipy dev
- ants > 2.1.0
- freesurfer
- fsl preferably >=5.0.9

also does the example you are testing on actually contain freesurfer data and does it only have 14 slices per volume?

thanks for testing these things.

**Comment by shoshber** [comment]
The data is downloaded from the nipype: http://nipype.readthedocs.io/en/0.12.0/users/pipeline_tutorial.html

Honestly I don't know how to tell if the data has freesurfer data--I've just been cobbling together the command from the comments in the file. Maybe you could send me the command you are using in your development?

Sounds like you are already on the ball with this one. Could you tell me

**Comment by shoshber** [comment]
update--in the compcor pr #1599 I started refactoring this to use the compcor interface but didn't finish/test it. So maybe that will be something to think about. I'm closing this issue for now.
