### ISSUE TITLE
Automate retries in travis/circleci

### ISSUE THREAD

**Issue by shoshber** [nipy/nipype#1622]
Ideally, tests should be 100% deterministic. However, in practical terms, there are some situations that cannot be controlled for, for example when network issues prevent a `pip install` during setup. In these cases, a simple retry will often fix the issue without manual intervention.

Implementing this would require some thinking, as we definitely do not want blind retrying on real bugs!

**Comment by chrisfilo** [comment]
Something like this could work: http://unix.stackexchange.com/a/82602 I would only use it for set up/download steps not the tests themselves.

**Comment by oesteban** [comment]
It'd be interesting when building the docker images, some times conda fails when fetching packages. Do you think it is best inside the Dockerfile or outside wrapping the docker build?
