### ISSUE TITLE
Signal extraction interface

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1628]
It's common to extract time series averaged over a tissue class or a brain region. Such signals could be used to perform:

- global signal regression (average over the whole brain)
- white matter and CSF signal regression (averaged over voxels belonging to the same tissue class)
- graph based analysis (average over voxels belonging to the same parcel)

It would be good to have a dedicated interface to perform such signal extractions. The interface would take:
- 4D file with fMRI data
- 3D label image (with 0 denoting background) or 4D file with probability maps
- a vector of class labels (as long as there are labels in the label image or in case the label image is 4D as long as the number of volumes in the 4D file with probability maps)

The output would be a .tsv file with as many columns as there were labels and as many rows as there were timepoints in the fMRI input data.

In addition we can consider adding an extra column "global" with mean signal across all labels.

[nilearn.input_data.NiftiLabelsMasker](http://nilearn.github.io/modules/generated/nilearn.input_data.NiftiLabelsMasker.html) can be very useful in implementing this Interface.

- [x] simplest case
- [x] 4D probability maps/partial voluming input
- [x] extra "global" column

**Comment by satra** [comment]
this sounds like a python equivalent of an mri_segstats interface. it may be nice to just clone that in python. also keep in mind that most of these stat generating interfaces can also (optionally) take into account partial voluming.

**Comment by oesteban** [comment]
@satra - wouldn't the _4D probability maps_ take into account the partial voluming?

**Comment by shoshber** [comment]
@satra what do you mean by cloning mri_segstats? You mean re-implementing? Or writing it as a FreeSurfer interface that calls mri_segstats behind the scenes?

**Comment by chrisfilo** [comment]
I think reimplementing this in python was what @satra meant by "cloning". FreeSurfer is a big dependency for such a simple functionality. In addition we can add some functionality in the future - for example using the first eigenvector instead of the mean.

**Comment by chrisfilo** [comment]
I had some more discussions about the probabilistic tissue maps, and it seems more common for those to come as a set 3D files instead of a single 4D file. This is how FSL FAST outputs them for example. This is how we defined them in BIDS Derivatives a while ago (see https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.6wlyh7diehqc).

I would vote for adding support for a list of 3D maps as the input for label_image. It's probably more common than the 4D case.

**Comment by shoshber** [comment]
> I would vote for adding support for a list of 3D maps as the input for label_image. It's probably more common than the 4D case.

Sure, that should be easy to do. For future reference, is it usually the case that an input that takes a 4D file should also support a list of 3D files?

**Comment by chrisfilo** [comment]
It differs from one case to another.

On Sun, Sep 18, 2016 at 2:17 PM, Shoshana Berleant <notifications@github.com

**Comment by shoshber** [comment]
[  ] threshold the map sums
