### ISSUE TITLE
dipy EstimateResponseSH crashes without input in_mask

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#1632]
Hi,
I am trying to use nipype to do some caching with dipy but I have some problems 
``` Python
from nipype.caching import Memory
from nipype.interfaces import dipy as ndp

dti = memory.cache(ndp.EstimateResponseSH)
out_dti =  dti(in_file=warped_hardi_filename,
               in_bval=bval_filename,
               in_bvec=bvec_filename,
               in_evals=evals_filename)
```
throws the following error
>/home/salma/anaconda2/lib/python2.7/site-packages/nipype/interfaces/dipy/reconstruction.pyc in _run_interface(self, runtime)
    214             msk[msk < 0] = 0
    215         else:
--> 216             msk = np.ones(imref.get_shape())
    217 
    218         data = img.get_data().astype(np.float32)
NameError: global name 'imref' is not defined

**Comment by mgxd** [comment]
this should be fixed with #1633 , if you run into further issues with that interface feel free to reopen this issue
