### ISSUE TITLE
Need for a development branch

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1641]
I think that lately there is a lot of activity in our project (which is really good!) and it is true that maybe some changes are going too quickly into master.

Could we re-think our current version control protocol so that we have a dev branch where we can have PRs testing without merging into master? The refactoring plans we have also point to do something like this.

Only when we are close to release we would merge that dev branch into master.

WDYT?

**Comment by blakedewey** [comment]
This is a good article about different flow styles that could be considered.

https://about.gitlab.com/2014/09/29/gitlab-flow/

**Comment by oesteban** [comment]
Yeah, that's a good reference. We could also use the release branch we have, which is (I think) the same as the production branch in that article, if we prefer to keep master as a development branch

**Comment by blakedewey** [comment]
That could work. The problem I had with that model was the instinct to "pull from master" is broken as that would get you the development branch. However, that is what people are getting now anyways, so maybe the point is moot.

**Comment by satra** [comment]
actually i would keep our current process and make sure that we keep improving our CI framework. we have mostly maintained that master is ready for deployment and we should keep that model. 

what we can do is a separate release branch to simplify releasing.
