### ISSUE TITLE
CHANGES file should be updated for each PR

### ISSUE THREAD

**Issue by blakedewey** [nipy/nipype#1658]
Just putting in an issue for visibility. We have had a lot of PRs merged recently and quite a few do not update the CHANGES file to reflect the PR. Just keep it in mind if you are doing a review!

**Comment by satra** [comment]
+1 - we have been sloppy about this.

**Comment by oesteban** [comment]
BTW, we've been sloppy about this again lately.

**Comment by mgxd** [comment]
@oesteban I agree - let's keep this in mind going forward
