### ISSUE TITLE
[QUESTION] Freesurfer terminal_output

### ISSUE THREAD

**Issue by mgclark** [nipy/nipype#1660]
I would like to silence the terminal output of interfaces/freesurfer/preprocess ReconAll -- is this possible? Setting ReconAll().inputs.terminal_output was not effective (and does not appear to be in the input spec for ReconAll?) Do I set terminal_output elsewhere? Should I add terminal_output to ReconAllInputSpec?

Potentially relevant PR: #1070

**Comment by satra** [comment]
@mgclark - `ReconAll` is derived from `CommandLine` and therefore should inherit all the inputs including terminal output, as noted in the online documentation or if you do ReconAll.help().

this didn't show me any output in the terminal:

```
from nipype.interfaces.freesurfer import ReconAll
ra = ReconAll()
ra.inputs.T1_files = '/software/data/studyforrest-data-structural/sub-01/anat/sub-01_T1w.nii.gz'
ra.inputs.subjects_dir = '/tmp/test_fs'
ra.inputs.terminal_output = 'file'
ra.run()
```

**Comment by mgclark** [comment]
Aha -- my error was using `os.system(ra.cmdline)` (instead of `ra.run()`) to execute the process. The `os.system()` method does not benefit from the `terminal_output` functionality. Thanks for the help @satra!
