### ISSUE TITLE
IdentityInterface mandatory inputs does not behave as expected

### ISSUE THREAD

**Issue by shoshber** [nipy/nipype#1666]
```
>>> idi = nipype.interfaces.IdentityInterface(fields=['asdf'], mandatory_inputs=True)
>>> idi.inputs.traits(mandatory=True)
{}
>>> idi.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/nipype/nipype/interfaces/base.py", line 1083, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/ubuntu/nipype/nipype/interfaces/base.py", line 1154, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/home/ubuntu/nipype/nipype/interfaces/utility.py", line 97, in _list_outputs
    raise ValueError(msg)
ValueError: IdentityInterface requires a value for input 'asdf' because it was listed in 'fields'.                     You can turn off mandatory inputs checking by passing mandatory_inputs = False to the constructor.
Interface IdentityInterface failed to run.

```

**Comment by chrisfilo** [comment]
You set `mandatory_inputs=True` you did not set the inputs listed in `fields`, the interface failed to run. Isn't his the expected behavior?

**Comment by satra** [comment]
ps. also as a quick note in the traits, only the presence or absence of the keyword counts rather than the value of the keyword. as in `mandatory=True` and `mandatory=False` i believe have the same effect of making that input mandatory. we currently check this with `make specs`, but perhaps can simply be avoided. the primary goal of not allowing `mandatory=False` is that the explicit nature doesn't help in this case and we did not want to turn every input to have that keyword.

**Comment by shoshber** [comment]
@chrisfilo I was referring to the results of `idi.inputs.traits(mandatory=True)`. I should have made that clearer.
@satra that is extremely unintuitive behavior--@oesteban had recommended using `traits(mandatory=True)` to find mandatory inputs, so I'm not the only one with this confusion! Is there a preferred way to get all mandatory inputs of a Node/Interface?

**Comment by satra** [comment]
@shoshber - sorry there are two notions of mandatory being tossed around here.

the `IdentityInterface` has a special check for mandatory inputs. 
https://github.com/nipy/nipype/blob/master/nipype/interfaces/utility.py#L89

it does not actually set a metadata field for each trait: https://github.com/nipy/nipype/blob/master/nipype/interfaces/utility.py#L79

but uses the list_outputs function to check the mandatory nature of things. 

this is why `idi.inputs.traits(mandatory=True)` doesn't work.

pps. when i was referring to `mandatory=True` it was specifically for interfaces that actually have that metadata. when nipype started there were a lot of issues with dynamic traits that didn't behave as expected, and we had to work around them. it's possible that those issues are no longer around and we should be making changes
