### ISSUE TITLE
Nipype and logging module of Python 2.7

### ISSUE THREAD

**Issue by sabfon** [nipy/nipype#1667]
I have also posted the question on Neurostars (http://neurostars.org/p/4239/).
I need to use Nipype for a program that I'm writing, but I've noticed a strange behavior when I import Nipype and the Python logging module together.
I'll try to explain my problem with more details.

```
import logging

if __name__ == '__main__':
    logging.basicConfig(filename='/path/log', level=logging.INFO)
    logging.warning('This is a Warning!')

```

With this simple piece of code, I obtain a log file containing the message "This is a warning".
If I import Nipype the situation changes.

```
import nipype
import logging

if __name__ == '__main__':
    logging.basicConfig(filename='/path/log', level=logging.INFO)
    logging.warning('This is a Warning!')
```

The log file is not created anymore and the program prints the message on the console. 

I've also tried something like 
`config.update_config({'logging': {'log_directory': '/path/log', 'log_to_file': True}})`

The problem is only for Python 2.7 (it works as expected on Python 3) and I'm using nipype 0.12.1.
I don't know if is a bug or maybe I'm doing something wrong and stupid.

Thank you for the help.

**Comment by mgxd** [comment]
@sabfon I see you've tried updating the config - have you also tried updating [nipype's logging](http://nipype.readthedocs.io/en/0.12.1/users/config_file.html#enabling-logging-to-file)? 
```
from nipype import config, logging
config.update_config({'logging': {'log_directory': '/path/log',
                                  'log_to_file': True}})
logging.update_logging(config)
```

**Comment by sabfon** [comment]
```
from nipype import config
from nipype import logging as nipype_logging
import logging as python_logging
import os

if __name__ == '__main__':

    config.update_config({'logging': {'log_directory': os.getcwd(), 'log_to_file': True}})
    nipype_logging.update_logging(config)


    python_logging.basicConfig(filename='/Users/sabfon/log', level=python_logging.INFO)
    python_logging.warning('hello')
```

I've tried this code, but still the python logging module doesn't work properly and starts to print everything on the console.

**Comment by mgxd** [comment]
@sabfon this is really a case of defining logger's basicConfig first. Since nipype is also defining this when it's imported, you'll need to set this before importing nipype - however, this will disable the nipype logs.
```
import logging
logging.basicConfig(filename='/Users/sabfon/log', level=logging.INFO)
import nipype
```

**Comment by anbai106** [comment]
@mgxd 
In nipype, the link that you gave is not so clear to create a log file, for example, in python, after we create the log file, we can use logging.info, logging.warning to write, but in nipype, how do we write and by default, you will create a pypeline.log, how can we define the name of the log file??? it is rally not very clear...

**Comment by mgxd** [comment]
@anbai106 
You can enable nipype's logging simply with the following block of code:
```
from nipype import config, logging
config.update_config({'logging': {'log_directory': '/path/to/where/you/want/log',
                                  'log_to_file': True}})
logging.update_logging(config)
```
This turns on nipype's logger that tracks at three levels:
- workflow_level
- filemanip_level
- interface_level
and outputs a log file named `pypeline.log` (As of now, I believe you can't define the name of the log file, but you can specify which directory it should go to).

If you want to log anything else inside your script, you should follow my post above.

**Comment by anbai106** [comment]
@mgxd 
Thanks for your rapid response, I think the name of the log is not a big deal, the post that you offered is this:

`import logging
logging.basicConfig(filename='/Users/sabfon/log', level=logging.INFO)
import nipype`

This does not suit for my case, cuz i am logging some information from some other log files, and write them inside the summary.log in a Nipype Node(Function node, so I have to import it inside the function), so I cant not import logging before import nipype, I think this is really a bug, not so convenient to use...

Look forward to hearing from you soon
Thanks in advance

**Comment by satra** [comment]
@mgxd - can you look into using two separate loggers, one nipype's logger and the other an additional logger from a remote script?

**Comment by mgxd** [comment]
@anbai106 
```
from nipype import config, logging, Node, Workflow, Function, IdentityInterface, Merge, Select
import os

def main():
	""" This will make the nipype log file (pypeline.log) """
	config.update_config({'logging': {'log_directory': os.getcwd(), 'log_to_file': True}})
	logging.update_logging(config)

	wf = Workflow(name='loggerwf', base_dir='.')
	info = Node(IdentityInterface(fields=['num']),
				name='inputnode')
	info.inputs.num = 10

	merge = Node(Merge(2), name='merger')
	merge.inputs.in2 = 20
	wf.connect(info, 'num', merge, 'in1')

	def write_to_log(nums):
		""" Make new Handler (hdlr) for separate logging """
		import logging
		root = logging.getLogger()
		hdlr = logging.FileHandler(filename='/path/to/log/file')
		root.addHandler(hdlr)
		logging.warning('Running inside workflow')
		for num in nums:
			logging.warning('The number is %d'%num)
		root.removeHandler(hdlr)
		return nums

	tolog = Node(Function(input_names=['nums'],
						  output_names=['nums'],
						  function=write_to_log),
				 name='logfunc')
	wf.connect(merge, 'out', tolog, 'nums')

	getnum = Node(Select(), name='getfirst')
	getnum.inputs.index = [0]
	wf.connect(tolog, 'nums', getnum, 'inlist')

	output = Node(IdentityInterface(fields=['out']), name='outputnode')
	wf.connect(getnum, 'out', output, 'out')

	eg = wf.run()

if __name__ == '__main__':
	main()
```

Take a look at this example if you want to log within a workflow - in a custom function I make a new FileHandler and write out to it. Nipype's pypeline.log is also logging, but there is no overlap between the two loggers.
