### ISSUE TITLE
nipype nosetests documentation broken

### ISSUE THREAD

**Issue by satra** [nipy/nipype#1670]
either we have to ask everyone to do their tests using docker containers, or we need to ensure the relevant nose components are present. for @djarecka and myself running the tests with instructions in the docs gave unicode errors.

a `pip install doctest-ignore-unicode` fixed the issue. based on our new setup.py perhaps we should update the install docs.

i've asked @djarecka to look into py.test conversion and support as part of her learning nipype.

**Comment by oesteban** [comment]
Ok, so the extra component doc (https://github.com/nipy/nipype/blob/master/nipype/info.py#L159) needs ```doctest-ignore-unicode```. We also will want to add the package to ```requirements.txt``` for readthedocs to build, most probably.

I've also found out that nipype.testing requires ```nose```. However, it is not installed if you do not request the "test" extra. I think we should try not to import anything from nipype.testing (only within test files). There is a problem here with nipype.testing.data (some examples will try to import from that).

**Comment by djarecka** [comment]
In my case `pip install doctest-ignore-unicode` generates other errors, e.g. '.nii.gz' vs u'.nii.gz'.  I'm testing using `nosetests --with-doctest nipype`.

**Comment by satra** [comment]
@djarecka: the current command looks something like this, which is quite different from what's in the docs.

```
python -W once:FSL:UserWarning:nipype `which nosetests` --with-doctest --with-doctest-ignore-unicode --logging-level=DEBUG --verbosity=3 nipype
```

**Comment by djarecka** [comment]
@satra : ok, much better now!
