### ISSUE TITLE
Two inline functions ValueError exception message

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1684]
Hi,

I think I can improve the error message that comes out when you have two inline functions in series. This message is here: https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/utils.py#L655

First, I would like to understand why the indices of the split are [6:-1] ? It doesn't make sense to me and the output is wrong.

Second, would you mind if I add the destnode and srcnode names to this message?

**Comment by satra** [comment]
@alexsavio - that looks like ancient code. please feel free to add a test and a corrected form. you can make the message as informative as possible since this happens during workflow construction.
