### ISSUE TITLE
AFNItoNIFTI not in documentation

### ISSUE THREAD

**Issue by tsalo** [nipy/nipype#1685]
The AFNI util [AFNItoNIFTI](https://github.com/nipy/nipype/blob/591226cd956c38c185854e9d2860ba26e2b2d025/nipype/interfaces/afni/utils.py#L72) isn't showing up in the [documentation](http://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.interfaces.afni.utils.html). Is it maybe ignoring things that start with AFNI or something, so it won't catch AFNICommand and other private classes?

**Comment by satra** [comment]
indeed:

https://github.com/nipy/nipype/blob/master/tools/build_interface_docs.py#L43

**Comment by tsalo** [comment]
Would your preference be to change the name of the class to something like ConvertAFNItoNIFTI or to just leave it out of the documentation?

**Comment by satra** [comment]
it should not be left out of the documentation. the options are:

1. change the name
2. change the pattern

if this is a new interface, perhaps changing name is easier. if this is an older interface and backward compatibility is required, then changing the pattern should be more appropriate.

**Comment by tsalo** [comment]
The interface has been around for awhile, so I've changed the pattern from 'AFNI' to 'AFNICommand' in #1687.
