### ISSUE TITLE
Mismatch for out_type 'nii.gz' between MRIConvert and Binarize

### ISSUE THREAD

**Issue by mvdoc** [nipy/nipype#1695]
Hi all,
MRIConvert fails if `out_type='nii.gz'` (it wants `='niigz'`) while `'nii.gz'` seems to be fine for the other freesurfer interfaces I used. Is there any reason for this? Or can I go ahead and make a PR?

thanks!

**Comment by satra** [comment]
@mvdoc - it would be great if you can take a look. there are a couple of weird things there:

https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/preprocess.py#L364

i think that mri_convert may have it's own notion of output type:

https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/preprocess.py#L368

**Comment by blakedewey** [comment]
I believe this is because `mri_convert` does not technically have a compressed nifti output. You must specify `nii` for a combined nifti header and image, then specify an output file with the extension `.nii.gz` to create a compressed nifti.

**Comment by mgxd** [comment]
@mvdoc closing this but feel free to open again if needed
