### ISSUE TITLE
[BUG] "No module named configparser" when using nipype w/ future 0.16

### ISSUE THREAD

**Issue by jpellman** [nipy/nipype#1699]
When importing nipype with future 0.16 (released 10/27/16) I get the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-feb2fc727b0b> in <module>()
----> 1 import nipype

/usr/local/bin/miniconda/envs/cpac100/lib/python2.7/site-packages/nipype/__init__.py in <module>()
      9                    STATUS as __status__,
     10                    __version__)
---> 11 from .utils.config import NipypeConfig
     12 config = NipypeConfig()
     13 from .utils.logger import Logging

/usr/local/bin/miniconda/envs/cpac100/lib/python2.7/site-packages/nipype/utils/config.py in <module>()
     13 from builtins import object
     14 
---> 15 import configparser
     16 from json import load, dump
     17 import os

ImportError: No module named configparser
```

When I downgrade to future 0.15.2, this error no longer occurs.

**Comment by oesteban** [comment]
I think this could be duplicated of #1697.

Can you test if installing configparser this is solved?

**Comment by jpellman** [comment]
Isn't configparser part of the Python standard library?  Is there any reason why it wouldn't be included by default with Python / would need to be installed?

**Comment by oesteban** [comment]
Yes, but it is one of those that change between python 2 and 3. Installing the package configparser we get the Python 3 interface to work in python 2.

**Comment by jpellman** [comment]
Right, but wouldn't it also mean that you would have two copies of configparser?  I mean it certainly works but it seems a little redundant.  It also doesn't explain why when I downgraded from future 0.16 to future 0.15.2 the issue disappeared.

Furthermore, the lines [here](https://github.com/nipy/nipype/blob/a746633d72d3e861a4b1a52038dd40a590792e24/nipype/utils/config.py#L15-L16) should prevent the "No module named configparser" error from being thrown in the first place, since they would create an alias for Python 2's "ConfigParser" named "configparser".  Overall, this really looks like a regression in future of some sort or a change in usage for standard_library in the new version.

**Comment by oesteban** [comment]
I was to suggest that it could be future adding the wrapper to configparser...

I agree: python 2/3 adds a lot of verbosity, and more worryingly, it is going to stay for a while. I don't see when python 2.x will be deprecated for good. On the other hand, I don't think it'd be a good idea to stick with 2.x.

Can we say that this issue/question is answered?

**Comment by jpellman** [comment]
Hi @oesteban ,

Just to clarify, when you say that you can remove the configparser dependency, you mean add the configparser dependency right?  The 0.16 update to future removed the configparser alias that is created by standard_library in favor of using the backported configparser, so the backported configparser would be a dependency you would need to add for people using future>=0.16.  If you use older versions of future the alias is still there and the NipypeConfig code runs perfectly without doing a separate install of the backported configparser.

**Comment by jpellman** [comment]
Actually, I'm not certain that adding the backported configparser as a dependency won't cause issues for people running  older versions of future.  In the release notes the future developers noted that having the backported configparser installed alongside future caused clashes/compatibility issues.

**Comment by mgxd** [comment]
@jpellman is this still an problem with current master?

**Comment by chrisfilo** [comment]
BTW I fixed listed this dependency in conda-forge. I should install cleanly
when getting it via conda.

On Wed, Mar 8, 2017 at 10:52 AM, Mathias Goncalves <notifications@github.com
