### ISSUE TITLE
bug with IPython plugin

### ISSUE THREAD

**Issue by Yuan-fang** [nipy/nipype#1701]
With IPython plugin initiated and ipcluster start --n=4 set successfully in the shell terminal, the script breaks up after a while and print error messages below:
--------------------------------
```
         Saving crash info to /nfs/h1/workingshop/swap/zhaoyuanfang/crash-20161103-145042-zhaoyuanfang-skullstripping.a0.npz
161103-14:50:42,458 workflow INFO:
         Traceback (most recent call last):
  File "/usr/local/neurosoft/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 234, in run
    result = self._get_result(taskid)
  File "/usr/local/neurosoft/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/ipython.py", line 75, in _get_result
    result, traceback, hostname = self.taskmap[taskid].get()
  File "/usr/local/neurosoft/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 118, in get
    raise self._exception
RemoteError: EngineError(Engine '601e765d-53dd-461c-90d5-3c351078403f' died while running task u'4f1457b1-82e4-4234-88c6-5f88051e39ad')
```
------------------------------------

After some line by line debug, to my surprise I found if I switch the sequence of two lines of code, the script would run successfully. The two lines after sequence switching was line37 and line 38. I printed the block below:
 ---------------------------------------------------------
```
 29     def bet_skullstripping(head_fs,brain_fs,frac_list):
 30 
 31     import os
 32 
 33     brain_frac = []
 34     template_dir = '/usr/local/neurosoft/fsl5.0.1/data/standard/'
 35     MNI1mm = os.path.join(template_dir,'MNI152_T1_1mm.nii.gz')
 36     MNImask = os.path.join(template_dir,'MNI152_T1_1mm_first_brain_mask.nii.gz')
 37     os.system('flirt -in '+ head_fs + ' -ref ' + MNI1mm + ' -out head_fs2mni -omat        tmp_head_fs2mni.mat')
 38     os.system('fslmaths ' + brain_fs + ' -abs -bin brain_fs_mask')
 39     os.system('convert_xfm -omat tmp_mni2head_fs.mat -inverse tmp_head_fs2mni.mat')
 40     for frac in frac_list:
 41         os.system('bet head_fs2mni tmp '+'-m -f '+'%.1f' %(frac))
 42         os.system('fslmaths tmp_mask -mas ' + MNImask + ' tmp_mask')
 43         os.system('flirt -in tmp_mask -ref '+ head_fs + ' -applyxfm -init tmp_mni2head_fs.mat \
 44                 -out brain_fsl_mask -paddingsize 0.0 -interp nearestneighbour')
 45         os.system('fslmaths brain_fsl_mask -mul brain_fs_mask -bin -mul ' + head_fs + ' ' + \
 46                 'brain_f%i' %(frac*10))
 47         brain_frac.append(os.path.abspath('brain_f%i.nii.gz' %(frac*10)))
 48         
 49 
 50     return brain_frac[0], brain_frac[1]
```
-------------------------------------

I don't know if this was a bug. But it's really strange because line 37 and line 38 are not dependent so I suppose the sequence of the two line shouldn't have an effect. The script can run successfully with PluginName = Linear in the workflow engine, no matter the sequence of the two lines.

**Comment by blakedewey** [comment]
I would really suggest rewriting this as a workflow so that the IPython plugin can be effective here. There are FSL interfaces available. Also, it is generally bad practice to utilize os.system, as it has very limited functionality. If you were to run this, I would suggest at least utilizing subprocess.call.

**Comment by Yuan-fang** [comment]
Thank you blakedewey. I changed the os.system parts with subprocess call and the script seemed more steady. 
I would like to use FSL interfaces, but I dislike defining too many nodes for simple fslmaths, which can be implemented  in the shell with just one simple line of script. Do you have any idea on this?
Thanks.

**Comment by blakedewey** [comment]
Glad it helped! In terms of interfaces, you get a lot of benefit for using them! That is the whole point of Nipype, as I'm sure you know. By having each piece in a Node/Interface, you get the benefit of all of the Nipype code. Things like error and runtime reporting and the ability to restart workflows after a failure. Lots of the interfaces have simple command line structures, but simplifying the command line is only one benefit. You could write an entire script of subprocess calls and it would probably be pretty short, but it would be difficult to read as well. It is of course up to you, just a few things to think about!

**Comment by mgxd** [comment]
@Yuan-fang feel free to open this issue if needed
