### ISSUE TITLE
make sure nipype test runs without docker

### ISSUE THREAD

**Issue by satra** [nipy/nipype#1705]
although we are using docker for testing, we really need to make sure that the following works on py 27 and 35

```
import nipype
nipype.test()
```

**Comment by shoshber** [comment]
is `nipype.test()` really the canonical test command? I've been using `make test` and various modifications of `python -W once:FSL:UserWarning:nipype $(NOSETESTS) --with-doctest --with-doctest-ignore-unicode --logging-level=DEBUG --verbosity=3 nipype`

**Comment by satra** [comment]
it should be, but we are hopefully revamping all of this by the move to `py.test`.

the reason we use docker on circle is to ensure that we can check what went wrong easily by rerunning the same exact environment locally and also ensure that the proper dependencies are in place across the various interfaces we support.

for most users, they should simply be able to install  nipype and call `nipype.test()`

**Comment by satra** [comment]
as developers, we can run the other variants, but even that i'd likely to simplify.

**Comment by djarecka** [comment]
I've missed that you're using `nipype.test()`, so unfortunately didn't change this in my PR. Can I ask why do you want to keep this option for testing? it's not enough to run`make tests` or simply `py.test nipype`?

**Comment by djarecka** [comment]
@satra : shall we close it?

**Comment by satra** [comment]
fixed via py.test updates
