### ISSUE TITLE
Broken down for neurostar.org

### ISSUE THREAD

**Issue by anbai106** [nipy/nipype#1720]
Hello:
I just want to know if the websit of neurostar has been corrupt? because from my lab or my home, I can not access it...
Thanks in advance

**Comment by satra** [comment]
@anbai106 - it is down and we have likely lost a lot of the data.

please post any issues here on github.

**Comment by oesteban** [comment]
We should update the README though (there are a couple of paragraphs about neurostars). I'll reopen this issue as a remainder to do so.
