### ISSUE TITLE
OMP_NUM_THREADS is set default to 1 for all nodes because of AFNI interfaces

### ISSUE THREAD

**Issue by bpinsard** [nipy/nipype#1728]
I have problem having multi-threaded (numpy MKL) code running on multiple cores when launched through nipype, but not outside nipype.
The faulty line here changes environment variable, thus affecting all other interface, even when submitted through plugin such as SGE:
https://github.com/nipy/nipype/blob/a746633d72d3e861a4b1a52038dd40a590792e24/nipype/interfaces/afni/base.py#L165

I temporarily circumvented it, but how should it be changed?

Thanks.

**Comment by chrisfilo** [comment]
Good catch. To contain the change to one interface I would suggest replacing this line with:

`self.inputs.environ['OMP_NUM_THREADS'] = str(self.num_threads)`
