### ISSUE TITLE
ants.BrainExtraction - offer intermediate results as outputs

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1729]
Particularly, it would be very interesting to expose (maybe subjected to boolean flags):

- The input image after removing bias field (N4ITK)
- The transforms of the inner registration step
- The results of the inner registration step
- The results of segmentation with atropos

**Comment by chrisfilo** [comment]
It's also running atropos - brain segmentation.

**Comment by oesteban** [comment]
Added one more item

**Comment by chrisfilo** [comment]
Closed by #1742
