### ISSUE TITLE
make sure that pytest is properly installed in the docker containers

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#1737]
Right now in order to run pytest within nipype_test containers, one has to:

    conda install pytest
    pip install pytest-raisesregexp
    conda install pytest-cov	
    conda install click

CircleCI works fine since builds new containers using current `requirements.txt` (that covers pytest installation).

The description from testing_nipype.rst  should be tested with new containers. 

Some of the dockerfiles, i.e. docker/nipype_test/Dockerfile_py27 and docker/nipype_test/Dockerfile_bas (can't see where this one is being used), contain `pip install nose-cov doctest-ignore-unicode configparser`. It might be good to include all test requirements in one place, either in all Dockerfiles for testing containers or in the requirements.txt file.

**Comment by oesteban** [comment]
I think this is quite tested now, and we are about to move on to neurodocker. But feel free to reopen if I'm wrong.
