### ISSUE TITLE
Non integer indexing into boxcar modelgen

### ISSUE THREAD

**Issue by gciccarelli3** [nipy/nipype#1748]
### Summary
Warning with non integer slice into array

### Actual behavior
nipype/algorithms/modelgen.py:663
 VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  boxcar[(1.0 * 1e3 / dt):(2.0 * 1e3 / dt)] = 1.0

### Expected behavior
No warnings.

### How to replicate the behavior
import numpy as np
a = np.arange(3)
a[0.5]

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info())"`
Unable to execute command.

**Comment by mgxd** [comment]
fixed in #1808
