### ISSUE TITLE
To consider: add retry check in the File trait (workflows more tolerant to NFS delays)

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1750]
I am gauging the interest in this idea.

### Summary
In NFS systems, sometimes files are not synchronized fast enough and workflows may fail when propagating the outputs of a node into the inputs of the next.

### Actual behavior
The File trait with metadata ```exists=True``` only checks once, instantly, when the interface is run or the command line queried.

### Expected behavior
Modulated by a nipype config setting, add retries to the File trait validation with a certain delay. This way nipype will be more tolerant to NFS delays.

### How to replicate the behavior
N/A

### Platform details:
Nipype workflow running in any platform with a base_dir in an NFS mount.

**Comment by satra** [comment]
@oesteban - this is what the timeout setting in the execution config is for.

**Comment by oesteban** [comment]
@satra - you mean ```job_finished_timeout``` ? We are using the linear plugin, and it crashes for this reason (file not found). Then you check yourself and the files are there.

**Comment by satra** [comment]
indeed. yes the linear plugin does not use that flag, but could be augmented to do the same thing that's done in the parallel execution plugin.

**Comment by shoshber** [comment]
What about building a retry mechanism for node failures?

**Comment by chrisfilo** [comment]
Seems relevant: http://stackoverflow.com/a/3206187/616300

**Comment by oesteban** [comment]
@satra I've been looking at the `job_finished_timeout` and only found this use: https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/base.py#L527

We are seeing these synchronization problems at two points:

- when checking traits (the original reason for opening this issue)
- when moving the `_unfinished.json` to finished `.json` here: https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/nodes.py#L370 (see the poldracklab/mriqc issue that Chris attached).

I don't think the `job_finished_timeout` is currently covering these, right?

**Comment by chrisfilo** [comment]
Definitely not in MultiProc.

**Comment by oesteban** [comment]
Yep, that would affect any plugin, virtually. I think Joke was running mriqc with Linear.

**Comment by chrisfilo** [comment]
I'm saying that `job_finished_timeout` only influences SGE like plugins and most likely solves NFS sync issues for them. From what I see in the code changing `job_finished_timeout` currently does not influence, Linear or MultiProc.

**Comment by satra** [comment]
@oesteban - with linear or multiproc there shouldn't be any file sync issue as the files are local (even if mounted via nfs)

is there any possibility that two jobs were started on the same data and in the same working directory?

**Comment by oesteban** [comment]
@satra - this has happened to two different people, running on two different HPCs. The likelihood that two or more jobs were run at the same time is minimal.

Best case scenario, `shutil.move` is not NFS safe, and the remove operation may not be atomic.

Worst case scenario: may nipype be running two processes in parallel somehow?

**Comment by oesteban** [comment]
http://stackoverflow.com/a/3716361 - I wonder if C's `rename` is being used in NFS.

**Comment by satra** [comment]
@oesteban - but unlike multinode race conditions, there is only one client here, so atomicity shouldn't come into play.

i have seen that error before but under one of two considerations:

1. the same job triggered by two different workflows.
2. mulitproc spawning multiple jobs

are you positive this was seen with linear and there was no other workflow running using that basedir?

**Comment by chrisfilo** [comment]
My suspicion is that they were sharing a workdir.

**Comment by oesteban** [comment]
> **shutil.move(src, dst)**
> Recursively move a file or directory (src) to another location (dst).
>
> If the destination is an existing directory, then src is moved inside that directory. If the destination already exists but is not a directory, it may be overwritten depending on os.rename() semantics.
> 
> If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied (using shutil.copy2()) to dst and then removed.

Judging by the traces we are getting, it is using the `shutil.copy2()` path here. Meaning: does not use `os.rename()` -> it is not considered the same filesystem.

**Comment by oesteban** [comment]
@satra:

> 1. the same job triggered by two different workflows.
> 2. mulitproc spawning multiple jobs
>
> are you positive this was seen with linear and there was no other workflow running using that basedir?

Ref. 1: maybe our trick of pulling all the nodes in the "workflow_enumerator" basket is causing the problem, could it be possible @chrisfilo ?

Ref. 2: I'm not sure about that. I'd feel safer about this with the traits problem, but not for this other race condition. I'll dig in a little.

**Comment by oesteban** [comment]
@satra, I think @chrisfilo found the issue yesterday and it looks like you are right. We have managed to build a very edge case were we make nipype try to run a node multiple times when it is not necessary.

We've done this by placing a *data source* in the middle of the graph of a workflow that is expanded with iterables, inside another workflow expanded as well.

This is not a nipype issue, but it would be nice if we could identify these repeated and identical nodes in the graph in order to make sure they are run only once, WDYT?

**Comment by chrisfilo** [comment]
In our case (as @satra predicted) it was multiple nipype instances using the same working directory and attempting to run a Node with the same name. I don't think we can easily identify such situations in Nipype engine...

**Comment by satra** [comment]
@chrisfilo - you are correct. given all the different plugins, it's really hard to identify this situation. 

but perhaps we can do a few specific things to see if it can help. directory creations are atomic operations, so one possibility is to have a node crash or wait if the output directory exists and has an unfinished json. these checks can obviously run into race conditions across nodes.

we can also consider running a socket listener that registers node actions.
