### ISSUE TITLE
bug: doc str: ants fixed vs moving description

### ISSUE THREAD

**Issue by gciccarelli3** [nipy/nipype#1759]
### Summary
Doc strings for moving img and fixed img help are identical.  I think only one of the images has the transformation applied to it.

### Expected behavior
I think the moving image is the image that is warped and the fixed image is the space to which the moving image is warped.

From pg 4 of the ants pdf doc:
"The moving image will be deformed to match the fixed image."
http://stnava.github.io/ANTsDoc/

### How to replicate the behavior
See line:  https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/registration.py
22 and 26

    fixed_image = InputMultiPath(File(exists=True), mandatory=True,
                                 desc=('image to apply transformation to (generally a coregistered '
                                       'functional)'))
    moving_image = InputMultiPath(File(exists=True), argstr='%s',
                                  mandatory=True,
                                  desc=('image to apply transformation to (generally a coregistered '
                                        'functional)'))

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info())"`

**Comment by mgxd** [comment]
also mentioned in #1223 - I'll make a quick fix
