### ISSUE TITLE
Load SPM 12 batch

### ISSUE THREAD

**Issue by himito** [nipy/nipype#1775]
Hello,

I would like to know if it is possible to load a spm batch file to configure the pre-processing pipeline.

Thank you in advance,

Best,
Jaime

**Comment by satra** [comment]
@himito - currently it is not possible to automatically convert an spm batch into a nipype pipeline. however, looking at the batch file, it should be mostly straightforward to construct the corresponding nipype pipeline.

going the other way, each nipype spm command does right out a batch file that could be used in matlab/spm.

**Comment by himito** [comment]
Thank you so much for your answer
