### ISSUE TITLE
ecc_pipeline discrepency in intensities

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#1787]
### Summary
ecc_pipeline change intensity range for non B0 scans

### Actual behavior
I have a raw diffusion image with B0 scan intensities around 1000 and other scans around 200.
After the ecc_pipeline, the B0 scan intensities have the same range while the other scans are between 0 and 1  

### Expected behavior
I expected the range of the scans to remain comparable to the raw image

### How to replicate the behavior
```Python
from nipype.workflows.dmri.fsl.artifacts import ecc_pipeline 
ecc = ecc_pipeline()
ecc.inputs.input_node.in_file = '4d_dwi.nii.gz'
ecc.inputs.input_node.in_bval = 'bval'
ecc.inputs.input_node.in_mask = 'brain_mask.nii.gz'
ecc.run()
```
### Platform details:
{'nibabel_version': '2.1.0', 'networkx_version': '1.11', 'numpy_version': '1.12.0', 'sys_platform': 'linux2', 'sys_version': '2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'commit_hash': u'a4d1e07', 'pkg_path': '/home/salma/anaconda2/lib/python2.7/site-packages/nipype', 'sys_executable': '/home/salma/anaconda2/bin/python', 'traits_version': '4.6.0', 'scipy_version': '0.18.1'}

**Comment by mmromero** [comment]
I am having exactly the same problem.

**Platform details:**
{'nibabel_version': '2.2.1', 'commit_hash': '%h', 'scipy_version': '1.0.0', 'sys_executable': '/Users/miguel/anaconda/bin/python', 'traits_version': '4.6.0', 'commit_source': 'archive substitution', 'networkx_version': '2.1', 'numpy_version': '1.14.0', 'nipype_version': '1.0.0', 'pkg_path': '/Users/miguel/anaconda/lib/python3.5/site-packages/nipype', 'sys_platform': 'darwin', 'sys_version': '3.5.4 | packaged by conda-forge | (default, Dec 18 2017, 06:40:48) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]'}

**Comment by djarecka** [comment]
@salma1601 , @mmromero any chance you can point me to some data files I can use to reproduce the issue?

**Comment by mmromero** [comment]
Hi @djarecka. I am just using a standard 4D volume. For what I saw, the problem comes from [dwi_flirt](https://github.com/nipy/nipype/blob/c28dbd458e5916d9d30b8c43bcac79d917934e40/nipype/workflows/dmri/fsl/artifacts.py#L568), where each volume (including the b0) is equalized for FLIRT, then the original b0 are [merged](https://github.com/nipy/nipype/blob/c28dbd458e5916d9d30b8c43bcac79d917934e40/nipype/workflows/dmri/fsl/artifacts.py#L586) to the equalized dwi causing the issue.

**Comment by salma1601** [comment]
@djarecka From what I remember, the problem came from `exposure.equalize_adapthist` because I commented out this line https://github.com/nipy/nipype/blob/master/nipype/workflows/dmri/fsl/utils.py#L802
and the following one as a workaround for this error. I didn't go more in trying to debug
