### ISSUE TITLE
MNIBiasCorrection failed if out_file is undefined

### ISSUE THREAD

**Issue by fcoldrain** [nipy/nipype#1800]
### Summary
When running freesurfer's MNIBiasCorrection in a workflow, it rasies an error if out_file is undefined. I believe if out_file is undefined, the output filename should have been something like 'subject_id_nucorrect.nii.gz' rather than raising an error.

### Actual behavior
Node inputs:

args = <undefined>
distance = <undefined>
environ = {u'SUBJECTS_DIR': '/Applications/freesurfer/subjects'}
ignore_exception = False
in_file = /Users/xxx/Documents/xxx/xxx_1.nii.gz
iterations = 1
mask = <undefined>
no_rescale = <undefined>
out_file = <undefined>
protocol_iterations = <undefined>
shrink = <undefined>
stop = <undefined>
subjects_dir = /Applications/freesurfer/subjects
terminal_output = stream
transform = <undefined>

Traceback: 
Traceback (most recent call last):
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/interfaces/freesurfer/base.py", line 126, in run
    return super(FSCommand, self).run(**inputs)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1086, in run
    outputs = self.aggregate_outputs(runtime)
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1157, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/nipype/interfaces/freesurfer/preprocess.py", line 1437, in _list_outputs
    outputs["out_file"] = os.path.abspath(self.inputs.out_file)
  File "/Users/xxx/anaconda/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/xxx/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: '_Undefined' object has no attribute 'startswith'
Interface MNIBiasCorrection failed to run. 

### Temporary Solution 
Defining out_file = 'corrected.nii.gz' solved the problem, at the cost of losing identity information supplied from the input filename. 

This problem occurs in other freesurfer interface in nipype as well, e.g. freesurfer.Normalize().
I think this is the same issue as https://github.com/nipy/nipype/issues/383. Would it be possible to fix it and check if this is some thing common in the freesurfer interfaces? Thanks very much!

**Comment by mgxd** [comment]
@fcoldrain I believe this was intentionally implemented - we try to wrap each interface exactly as it is when run in the command line. AFAIK, outvol is a required flagged argument for `mri_nu_correct.mni`

**Comment by satra** [comment]
@mgxd - could you check by adding `mandatory=True` for `out_file`. it seems to have the necessary pieces to base it on infile:

https://github.com/nipy/nipype/blob/61978adaa3a2a1aeb4b13facfe1bc6fde38ed7fe/nipype/interfaces/freesurfer/preprocess.py#L1470

**Comment by satra** [comment]
@fcoldrain - could you please try out @mgxd's branch and see if it resolves your issue.

@mgxd - could you please add an additional doctest that resembles the issue.

**Comment by satra** [comment]
@fcoldrain and @mgxd - i'm not sure there is any error currently. @mgxd - the mandatory keyword is unnecessary for this.

```ipython
In [7]: from nipype.interfaces.freesurfer import MNIBiasCorrection
In [8]: mni = MNIBiasCorrection()
In [9]: mni.inputs.in_file = 'README.md'
In [10]: mni.cmdline
Out[10]: 'mri_nu_correct.mni --i README.md --o README_output.md'
```
am i missing something.

**Comment by mgxd** [comment]
@satra the command is correct, but the output wasn't being extracted properly. I've corrected this in the PR

**Comment by satra** [comment]
@mgxd - the fix in this case is to remove the `_list_outputs` function and rely on the base function to use `namesource` and `template`:

```
--- a/nipype/interfaces/freesurfer/preprocess.py
+++ b/nipype/interfaces/freesurfer/preprocess.py
@@ -1536,11 +1536,6 @@ class MNIBiasCorrection(FSCommand):
     input_spec = MNIBiasCorrectionInputSpec
     output_spec = MNIBiasCorrectionOutputSpec
 
-    def _list_outputs(self):
-        outputs = self._outputs().get()
-        outputs["out_file"] = os.path.abspath(self.inputs.out_file)
-        return outputs
-
```

it does look like several of the freesurfer interfaces can be improved using this pattern. but each one will need to be tested as well. since we actually don't run external interfaces within nipype, i would suggest making a separate test repo and start putting external tests in.

you can make the above change here to make this interface work and do the test repo separately with nipype as a git subrepo to ensure that you are creating tests for a specific version of nipype.

**Comment by fcoldrain** [comment]
@satra and @mgxd - I have tested the method of removing _list_outputs function and can confirm that my workflow now works with no error raised. I agree that other freesurfer interface may be improved in this pattern, and I am happy to help with the test if needed.

By the way, I run the above test without having the 'genfile=True' in 

out_file = File(argstr="--o %s", name_source=['in_file'], genfile=True,
                    name_template='%s_output', hash_files=False, keep_extension=True,
                    desc="output volume. Output can be any format accepted by mri_convert. " +
                    "If the output format is COR, then the directory must exist.")

and my workflow worked, so not sure what 'genfile=True' does.

**Comment by satra** [comment]
@fcoldrain - we replaced `genfile` with more automation `namesource/template` so technically genfile should be obsoleted as we fix interfaces.
