### ISSUE TITLE
small typos in testing_python.py

### ISSUE THREAD

**Issue by umeboshi7** [nipy/nipype#1816]
In the examples for Docker at https://github.com/nipy/nipype/blob/master/doc/devel/testing_nipype.rst:

- docker build command : missing argument ('.')
- docker run command : run_pytest.sh should be run_pytests.sh

**Comment by mgxd** [comment]
perhaps this can be included in #1815

**Comment by oesteban** [comment]
Sorry I missed this, I'll fix it asap.
