### ISSUE TITLE
DVARS calculation is incorrect

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1821]
Current implementation of DVARS is missing some important steps:

- normalization to % signal change
- squaring of the differences before taking their sum

The code needs to be carefully revised and corrected. Here is a nice summary of other DVARS implementations: http://czarrar.github.io/checking-on-dvars/

**Comment by oesteban** [comment]
I'd keep current implementation as an option though, since it replicates the implementation from T. Nichols.

The default option would be the revised version with normalization and squared differences.

**Comment by chrisfilo** [comment]
@oesteban You are correct - current implementation does indeed follow @nicholst and uses standard deviation to calculate the square root of the mean square temporal difference. In other words this line from @nicholst:


`fslstats -t $Tmp-Diff       -k $Tmp-MeanBrain -S > $Tmp-DiffSD.dat`

http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/scripts/fsl/DVARS.sh

Is represented in nipype codebase as:

`dvars_nstd = func_diff.std(axis=0)`

https://github.com/nipy/nipype/blob/master/nipype/algorithms/confounds.py#L665

However, I am not convinced that calculating standard deviation across voxels for each volume of diff sequence is equivalent to calculating the square root of the mean square temporal difference. Standard deviation is the root square of the mean squared difference from the mean. In other words using standard deviation here would only work if and only if the mean value in each volume of the diff sequence was 0 which I don't think can be guaranteed and is often not true. It seems that the bug from the original code was replicated in our implementation. Maybe @nicholst can clarify if my reasoning is correct.

**Comment by chrisfilo** [comment]
One more thought: even if you do intensity normalization (make sure the mean/median value for each volume in the original timeseries is the same) it does not guarantee that the mean temporal difference (t0 - t1) would be zero. The same way two sample t-test and paired t-test do not always yield the same results.

**Comment by chrisfilo** [comment]
@nicholst corrected his original script https://twitter.com/ten_photos/status/833236998987001856
