### ISSUE TITLE
SPM realign outputs different to SPM

### ISSUE THREAD

**Issue by himito** [nipy/nipype#1841]
Hello,

When I realign .nii files in SPM 12, there is a .mat file also as output. However, this file is not generated in the working directory when I execute Nipype.

Could you help to clarify that, please,

Thank you in advance.

**Comment by chrisfilo** [comment]
Did you try turning off the option 'remove_unecessary_outputs' to false in
your config?

**Comment by himito** [comment]
Thank you so much !

**Comment by VolkmarGlauche** [comment]
As a side note:
During realignment, SPM stores updated header information for each original volume (i.e. the original volumes are modified, even in the case of Realign&Reslice). In 3D-NIFTI, this update is applied to the original NIFTI headers. In 4D-NIFTI, there is only one header for the whole image series. Therefore, SPM creates a .mat file to store per-volume realignment information. For SPM, this information is transparently applied whenever the realigned 4D-NIFTI is accessed. Other tools will most likely not use this information, and may therefore exhibit different behaviour when operating on SPM realigned (but not resliced) 3D vs. 4D data.

**Comment by satra** [comment]
thanks @VolkmarGlauche  - as a side note to the side note:

when use inside a workflow, nipype makes copies of the original data into the working directory of the node to make sure the original data are never touched. but this is not true if the interface is used outside a workflow.

**Comment by himito** [comment]
Thank you @VolkmarGlauche and @satra for your explanations :) I really appreciate them :)

**Comment by himito** [comment]
Sorry for re-opening this issue, but I have a problem with the .mat files generated by realign.

There is a way (in the workflow) to copy the .mat files generated by realign into the working folder of another node ? Because if a run the pyscript with (spm matlab output) and without the *.mat files, the results are different. 

Thank  you in advance
