### ISSUE TITLE
Can't run nipype commands pycharm

### ISSUE THREAD

**Issue by reznida** [nipy/nipype#1852]
### Summary
Cannot execute different nipype commands such as Automask and 3dAutoTcorrelate using pycharm
### Actual behavior
I downloaded nipype without anaconda and I get no errors while importing, yet when I ran some commands I get the following error:

IOError: command '3dAutomask' could not be found on host MYHOSTNAME
Interface Automask failed to run.

any suggestions??

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

**Comment by chrisfilo** [comment]
Do you have AFNI installed and added to your PATH?

**Comment by reznida** [comment]
I installed AFNI and now struggling with the PATH adding - should I add it to ~/.bash_profile file?
If so, what are the lines that I should add?

**Comment by reznida** [comment]
Solved!

I added these two following lines to my bash_profile file

echo 'export PATH=$PATH:$HOME/abin' >> .profile 
echo 'export DYLD_FALLBACK_LIBRARY_PATH=$HOME/abin' >> .profile 
. .profile 

Thanks!
