### ISSUE TITLE
Moving input data path

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1855]
### Summary
Sometimes I need to move my data to another place.

### Actual behavior
I am not sure if there is any script to do this.
I am assuming that there is no choice to ask nipype to not check the paths of the input files and only the hash?

### Expected behavior
Be able to move the input data and have the working directory paths changed.
I suggest add a `nipypecli migrate` command that edits the paths in all the node .json files in a given working directory.

**Comment by satra** [comment]
you can set the following argument to the workflow `run` function : `updatehash=True`

but you have to be careful that those inputs have not actually changed.
