### ISSUE TITLE
Nipype installation test failure

### ISSUE THREAD

**Issue by milesseidel** [nipy/nipype#1864]
### Summary
Hello, I'm attempting to install and test nipype on a mac running macOS Sierra 10.12.3. I have installed Anaconda and ran the following lines in the terminal:

$ conda config --add channels conda-forge
$ conda install nipype
$ python -c "import nipype; nipype.test()"

Help is much appreciated - I could really use some assistance. Thanks,

Miles

### Actual behavior
I get the following output error:

======================================================================================= test session starts ========================================================================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/milesseidel, inifile:
collected 586 items

anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/confounds.py ....
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/mesh.py .
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/metrics.py .....
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/misc.py ..........
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/modelgen.py .......
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/algorithms/rapidart.py ....
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/caching/memory.py ..
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/interfaces/base.py .....
anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/interfaces/bru2nii.py .F

============================================================================================= FAILURES =============================================================================================
_____________________________________________________________________________ [doctest] nipype.interfaces.bru2nii.Bru2 _____________________________________________________________________________
UNEXPECTED EXCEPTION: TraitError("The trait 'input_dir' of a Bru2InputSpec instance is an existing directory name, but the path  'brukerdir' does not exist.",)
Traceback (most recent call last):

  File "/Users/milesseidel/anaconda/lib/python3.5/doctest.py", line 1321, in __run
    compileflags, 1), test.globs)

  File "<doctest nipype.interfaces.bru2nii.Bru2[2]>", line 1, in <module>

  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/interfaces/traits_extension.py", line 183, in validate
    self.info_text, value))

traits.trait_errors.TraitError: The trait 'input_dir' of a Bru2InputSpec instance is an existing directory name, but the path  'brukerdir' does not exist.

/Users/milesseidel/anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype/interfaces/bru2nii.py:44: UnexpectedException
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 1 failed, 39 passed in 3.72 seconds ================================================================================

### Expected behavior
I expected all tests to pass.

### How to replicate the behavior
$ conda config --add channels conda-forge
$ conda install nipype

Then (output copy pasted)
$ python -c "import nipype; nipype.test()"

Or (output in txt attached)
$ nosetests --with-doctest nipype

This second call gives the output in the attached .txt file. Unlike the first test, it runs to completion, with the following final summary.
[output_from_nipype_test.txt](https://github.com/nipy/nipype/files/820334/output_from_nipype_test.txt)

----------------------------------------------------------------------
Ran 1973 tests in 37.397s

FAILED (errors=219, failures=1)

### Platform details:
$ python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"

{'sys_platform': 'darwin', 'traits_version': '4.6.0', 'nibabel_version': '2.1.0', 'scipy_version': '0.18.1', 'numpy_version': '1.12.0', 'pkg_path': '/Users/milesseidel/anaconda/lib/python3.5/site-packages/nipype-0.13.0_g07a75a6.dev-py3.5.egg/nipype', 'commit_source': 'installation', 'networkx_version': '1.11', 'sys_version': '3.5.2 |Anaconda 4.3.0 (x86_64)| (default, Jul  2 2016, 17:52:12) \n[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]', 'commit_hash': '07a75a6', 'sys_executable': '/Users/milesseidel/anaconda/bin/python'}

**Comment by satra** [comment]
@milesseidel - this issue has been fixed in the current master branch. you can upgrade to this by doing:

`pip install --upgrade https://github.com/nipy/nipype/archive/master.zip`

we will be releasing a new version shortly.

**Comment by milesseidel** [comment]
### Summary

@satra Thanks for the reply. I get the following installation error (full output displayed). Perhaps I tried too early, before the new version has been released?

$ pip install --upgrade https://github.com/nipy/nipype/archive/master.zip

Collecting https://github.com/nipy/nipype/archive/master.zip
  Downloading https://github.com/nipy/nipype/archive/master.zip (4.1MB)
    100% |████████████████████████████████| 4.1MB 190kB/s
Requirement already up-to-date: nibabel>=2.0.1 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: networkx>=1.7 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: numpy>=1.6.2 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: python-dateutil>=1.5 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: scipy>=0.11 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: traits>=4.6 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: future>=0.15.2 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: simplejson>=3.8.0 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: prov>=1.4.0 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: click>=6.6.0 in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: funcsigs in ./anaconda/lib/python3.5/site-packages (from nipype==0.13.0.dev0)
Requirement already up-to-date: configparser in ./anaconda/lib/python3.5/site-packages/configparser-3.5.0-py3.5.egg (from nipype==0.13.0.dev0)
Collecting pytest>=3.0 (from nipype==0.13.0.dev0)
  Downloading pytest-3.0.6-py2.py3-none-any.whl (172kB)
    100% |████████████████████████████████| 174kB 2.8MB/s
Requirement already up-to-date: decorator>=3.4.0 in ./anaconda/lib/python3.5/site-packages (from networkx>=1.7->nipype==0.13.0.dev0)
Requirement already up-to-date: six>=1.5 in ./anaconda/lib/python3.5/site-packages (from python-dateutil>=1.5->nipype==0.13.0.dev0)
Requirement already up-to-date: lxml in ./anaconda/lib/python3.5/site-packages (from prov>=1.4.0->nipype==0.13.0.dev0)
Requirement already up-to-date: rdflib>=4.2.1 in ./anaconda/lib/python3.5/site-packages (from prov>=1.4.0->nipype==0.13.0.dev0)
Collecting setuptools (from pytest>=3.0->nipype==0.13.0.dev0)
  Downloading setuptools-34.3.1-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 1.9MB/s
Requirement already up-to-date: py>=1.4.29 in ./anaconda/lib/python3.5/site-packages (from pytest>=3.0->nipype==0.13.0.dev0)
Requirement already up-to-date: isodate in ./anaconda/lib/python3.5/site-packages (from rdflib>=4.2.1->prov>=1.4.0->nipype==0.13.0.dev0)
Requirement already up-to-date: pyparsing in ./anaconda/lib/python3.5/site-packages (from rdflib>=4.2.1->prov>=1.4.0->nipype==0.13.0.dev0)
Collecting appdirs>=1.4.0 (from setuptools->pytest>=3.0->nipype==0.13.0.dev0)
  Downloading appdirs-1.4.2-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->pytest>=3.0->nipype==0.13.0.dev0)
  Downloading packaging-16.8-py2.py3-none-any.whl
Installing collected packages: appdirs, packaging, setuptools, pytest, nipype
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
  Found existing installation: pytest 3.0.5
    Uninstalling pytest-3.0.5:
      Successfully uninstalled pytest-3.0.5
  Found existing installation: nipype 0.13.0-g07a75a6.dev
    Uninstalling nipype-0.13.0-g07a75a6.dev:
      Successfully uninstalled nipype-0.13.0-g07a75a6.dev
  Running setup.py install for nipype ... done
Successfully installed appdirs-1.4.2 nipype-0.13.0.dev0 packaging-16.8 pytest-3.0.6 setuptools-34.3.1
Traceback (most recent call last):
  File "/Users/milesseidel/anaconda/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/milesseidel/anaconda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg'

**Comment by satra** [comment]
@milesseidel - that's a weird one. which version of anaconda do you have?

**Comment by milesseidel** [comment]
$ anaconda –V

anaconda Command line client (version 1.6.0)

**Comment by milesseidel** [comment]
@satra 
$ python -V
Python 3.5.2 :: Anaconda 4.3.0 (x86_64)

**Comment by satra** [comment]
@milesseidel - could you please try the following: `conda update pip` and then try the pip install command again?

**Comment by milesseidel** [comment]
@satra After updating pip with conda nipype, pip was able to successfully install. However, when I rerun the installation tests I get the following (identical to initial problem):

$ python -c "import nipype; nipype.test()"
=============================================== test session starts ================================================
platform darwin -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/milesseidel, inifile:
collected 586 items

anaconda/lib/python3.5/site-packages/nipype/algorithms/confounds.py ....
anaconda/lib/python3.5/site-packages/nipype/algorithms/mesh.py .
anaconda/lib/python3.5/site-packages/nipype/algorithms/metrics.py .....
anaconda/lib/python3.5/site-packages/nipype/algorithms/misc.py ..........
anaconda/lib/python3.5/site-packages/nipype/algorithms/modelgen.py .......
anaconda/lib/python3.5/site-packages/nipype/algorithms/rapidart.py ....
anaconda/lib/python3.5/site-packages/nipype/caching/memory.py ..
anaconda/lib/python3.5/site-packages/nipype/interfaces/base.py .....
anaconda/lib/python3.5/site-packages/nipype/interfaces/bru2nii.py .F

===================================================== FAILURES =====================================================
_____________________________________ [doctest] nipype.interfaces.bru2nii.Bru2 _____________________________________
UNEXPECTED EXCEPTION: TraitError("The trait 'input_dir' of a Bru2InputSpec instance is an existing directory name, but the path  'brukerdir' does not exist.",)
Traceback (most recent call last):

  File "/Users/milesseidel/anaconda/lib/python3.5/doctest.py", line 1321, in __run
    compileflags, 1), test.globs)

  File "<doctest nipype.interfaces.bru2nii.Bru2[2]>", line 1, in <module>

  File "/Users/milesseidel/anaconda/lib/python3.5/site-packages/nipype/interfaces/traits_extension.py", line 183, in validate
    self.info_text, value))

traits.trait_errors.TraitError: The trait 'input_dir' of a Bru2InputSpec instance is an existing directory name, but the path  'brukerdir' does not exist.

/Users/milesseidel/anaconda/lib/python3.5/site-packages/nipype/interfaces/bru2nii.py:44: UnexpectedException
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 1 failed, 39 passed in 4.41 seconds ========================================


$nosetests --with-doctest nipype
See output file
[outputfile.txt](https://github.com/nipy/nipype/files/823059/outputfile.txt)

**Comment by oesteban** [comment]
@milesseidel could you please paste in the output of:
```
pip freeze
```
Thanks!

**Comment by milesseidel** [comment]
@osteban Here's the output. Let me know if you need any other info or have suggestions.

$ pip freeze
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.6.0
anaconda-navigator==1.4.3
appdirs==1.4.2
appnope==0.1.0
appscript==1.0.1
argcomplete==1.0.0
astroid==1.4.9
astropy==1.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.3
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
Bottleneck==1.2.0
cffi==1.9.1
cGraph==0.1
chardet==2.3.0
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.7
conda==4.2.13
conda-build==2.0.2
configobj==5.0.6
configparser==3.5.0
contextlib2==0.5.4
cryptography==1.7.1
cycler==0.10.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datashape==0.5.4
decorator==4.0.11
dill==0.2.5
dipy==0.11.0
docutils==0.13.1
dynd==0.7.3.dev1
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.12
Flask-Cors==3.0.2
funcsigs==1.0.2
future==0.16.0
gevent==1.2.1
graphviz==0.5.2
greenlet==0.4.11
h5py==2.6.0
HeapDict==1.0.0
idna==2.2
imagesize==0.7.1
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isodate==0.5.4
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
lazy-object-proxy==1.2.2
llvmlite==0.15.0
locket==0.2.0
lxml==3.7.3
MarkupSafe==0.23
matplotlib==2.0.0
mistune==0.7.3
mock==2.0.0
mpmath==0.19
multipledispatch==0.4.9
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.2.0
nbpresent==3.0.2
networkx==1.11
nibabel==2.1.0
nipy==0.4.1
nipype==0.13.0.dev0
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numba==0.30.1
numexpr==2.6.1
numpy==1.12.0
numpydoc==0.6.0
odo==0.5.0
openpyxl==2.4.1
packaging==16.8
pandas==0.19.2
partd==0.3.7
pathlib2==2.2.0
patsy==0.4.1
pbr==2.0.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.9
prov==1.5.0
psutil==5.0.1
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pydicom==0.9.9
pydotplus==2.0.2
pyflakes==1.5.0
Pygments==2.1.3
pylint==1.6.4
pyOpenSSL==16.2.0
pyparsing==2.2.0
pytest==3.0.6
python-dateutil==2.6.0
pytz==2016.10
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.3
qtconsole==4.2.1
QtPy==1.2.1
rdflib==4.2.2
redis==2.10.5
requests==2.12.4
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.18.1
seaborn==0.7.1
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.5.1
spyder==3.1.2
SQLAlchemy==1.1.5
statsmodels==0.6.1
sympy==1.0
tables==3.3.0
terminado==0.6
toolz==0.8.2
tornado==4.4.2
traitlets==4.3.1
traits==4.6.0
unicodecsv==0.14.1
virtualenv==15.1.0
wcwidth==0.1.7
Werkzeug==0.11.15
widgetsnbextension==1.2.6
wrapt==1.10.8
xlrd==1.0.0
XlsxWriter==0.9.6
xlwings==0.10.2
xlwt==1.2.0
xvfbwrapper==0.2.9

**Comment by satra** [comment]
@milesseidel - closed via #1866
