### ISSUE TITLE
[ENH] Sphinx extension to render workflows

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1873]
Hi @satra, could you take a quick look on this: http://mriqc.readthedocs.io/en/latest/workflows.html ?

That workflow picture was generated automatically from the docstring using this sphinx extension. For generating the graph, I only had to do this in the docstring:

```
.. workflow ::
    import os.path as op
    from mriqc.workflows.anatomical import anat_qc_workflow
    datadir = op.abspath('data')
    wf = anat_qc_workflow([op.join(datadir, 'sub-001/anat/sub-001_T1w.nii.gz')],
                          settings={'bids_dir': datadir,
                                    'output_dir': op.abspath('out')})
```

For simpler workflows this could be a one-liner.

I'm still working out some things (e.g. being able to pass the graph type you want to use, the hires version which is currently not accesible with write_graph, etc).

But I think it'd be very cool if people had this option to document their workflows easily. To use that, you would only need to add the extension to the sphinx ```conf.py```.

WDYT?

**Comment by satra** [comment]
i'm wondering whether we could use this: http://viz-js.com/

then we get rid of the graphviz dependency completely.

**Comment by oesteban** [comment]
If we generate svgs with viz-js, it would be transparent to the sphinx extension, so I guess so :)
