### ISSUE TITLE
fmri_spm_auditory

### ISSUE THREAD

**Issue by ankita940** [nipy/nipype#1877]
i am new to nipy. i was learning pipeline using frmi_spm_auditory code from ur github page. i am getting this error in my crash file when i am running it. please help.
From my understanding its giving error since cant found spm on its path but I checked its there.
I run these commands:
import nipype.interfaces.spm as spm
spm.Info.version()

its giving this output-
{u'name': u'SPM12',
u'path': u'/home/ankita/spmsoft/spm12',
u'release': u'6906'}

Crash file produced:

File: crash-20170310-011734-ankita-realign.a0-db81fe36-9277-4276-99e1-f6b77617e2b3.pklz
Node: level1.firstlevel.preproc.realign.a0
Working directory: /home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign

Node inputs:

fwhm = 
ignore_exception = False
in_files = ['/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_016.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_017.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_018.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_019.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_020.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_021.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_022.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_023.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_024.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_025.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_026.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_027.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_028.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_029.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_030.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_031.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_032.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_033.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_034.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_035.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_036.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_037.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_038.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_039.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_040.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_041.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_042.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_043.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_044.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_045.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_046.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_047.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_048.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_049.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_050.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_051.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_052.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_053.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_054.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_055.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_056.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_057.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_058.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_059.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_060.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_061.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_062.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_063.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_064.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_065.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_066.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_067.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_068.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_069.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_070.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_071.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_072.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_073.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_074.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_075.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_076.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_077.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_078.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_079.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_080.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_081.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_082.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_083.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_084.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_085.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_086.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_087.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_088.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_089.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_090.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_091.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_092.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_093.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_094.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_095.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_096.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_097.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_098.img', '/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/fM00223_099.img']
interp = 
jobtype = estwrite
matlab_cmd = 
mfile = True
out_prefix = r
paths = 
quality = 
register_to_mean = 
separation = 
use_mcr = 
use_v8struct = True
weight_img = 
wrap = 
write_interp = 
write_mask = 
write_which = [2, 1]
write_wrap =

Traceback: 
Traceback (most recent call last):
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
node.run(updatehash=updatehash)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
self.runinterface()
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in runinterface
self.result = self.run_command(execute)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in runcommand
result = self._interface.run()
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
runtime = self.runwrapper(runtime)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in runwrapper
runtime = self.runinterface(runtime)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 311, in runinterface
results = self.mlab.run()
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
runtime = self.runwrapper(runtime)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1660, in runwrapper
runtime = self.runinterface(runtime)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/matlab.py", line 149, in runinterface
self.raise_exception(runtime)
File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1618, in raise_exception
raise RuntimeError(message)
RuntimeError: Command:
matlab -nodesktop -nosplash -nodesktop -nosplash -singleCompThread -r "addpath('/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign');pyscript_realign;exit"
Standard output:
MATLAB is selecting SOFTWARE OPENGL rendering.

                        < M A T L A B (R) >
              Copyright 1984-2016 The MathWorks, Inc.
               R2016b (9.1.0.441655) 64-bit (glnxa64)
                         September 7, 2016
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

Executing pyscript_realign at 10-Mar-2017 01:17:31:
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: 40480989
Operating System: Linux 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

MATLAB Version 9.1 (R2016b)
Simulink Version 8.8 (R2016b)
Antenna Toolbox Version 2.1 (R2016b)
Audio System Toolbox Version 1.1 (R2016b)
Bioinformatics Toolbox Version 4.7 (R2016b)
Communications System Toolbox Version 6.3 (R2016b)
Computer Vision System Toolbox Version 7.2 (R2016b)
Control System Toolbox Version 10.1 (R2016b)
Curve Fitting Toolbox Version 3.5.4 (R2016b)
DSP System Toolbox Version 9.3 (R2016b)
Database Toolbox Version 7.0 (R2016b)
Embedded Coder Version 6.11 (R2016b)
Filter Design HDL Coder Version 3.1 (R2016b)
Fixed-Point Designer Version 5.3 (R2016b)
Fuzzy Logic Toolbox Version 2.2.24 (R2016b)
Global Optimization Toolbox Version 3.4.1 (R2016b)
HDL Coder Version 3.9 (R2016b)
HDL Verifier Version 5.1 (R2016b)
Image Acquisition Toolbox Version 5.1 (R2016b)
Image Processing Toolbox Version 9.5 (R2016b)
Instrument Control Toolbox Version 3.10 (R2016b)
LTE System Toolbox Version 2.3 (R2016b)
MATLAB Coder Version 3.2 (R2016b)
MATLAB Report Generator Version 5.1 (R2016b)
Mapping Toolbox Version 4.4 (R2016b)
Model Predictive Control Toolbox Version 5.2.1 (R2016b)
Neural Network Toolbox Version 9.1 (R2016b)
Optimization Toolbox Version 7.5 (R2016b)
Parallel Computing Toolbox Version 6.9 (R2016b)
Partial Differential Equation Toolbox Version 2.3 (R2016b)
Phased Array System Toolbox Version 3.3 (R2016b)
RF Toolbox Version 3.1 (R2016b)
Robotics System Toolbox Version 1.3 (R2016b)
Robust Control Toolbox Version 6.2 (R2016b)
Signal Processing Toolbox Version 7.3 (R2016b)
SimRF Version 5.1 (R2016b)
Simscape Version 4.1 (R2016b)
Simscape Driveline Version 2.11 (R2016b)
Simscape Electronics Version 2.10 (R2016b)
Simscape Multibody Version 4.9 (R2016b)
Simulink 3D Animation Version 7.6 (R2016b)
Simulink Control Design Version 4.4 (R2016b)
Stateflow Version 8.8 (R2016b)
Statistics and Machine Learning Toolbox Version 11.0 (R2016b)
Symbolic Math Toolbox Version 7.1 (R2016b)
System Identification Toolbox Version 9.5 (R2016b)
WLAN System Toolbox Version 1.2 (R2016b)
Wavelet Toolbox Version 4.17 (R2016b)

Standard error:
MATLAB code threw an exception:
SPM not in matlab path
File:/home/ankita/Downloads/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/realign/pyscript_realign.m
Name:pyscript_realign
Line:6

Return code: 0
Interface MatlabCommand failed to run. 
Interface Realign failed to run.

**Comment by satra** [comment]
@ankita940 - are you running the workflow on the same machine where you are checking the spm version?

**Comment by ankita940** [comment]
Yes

**Comment by satra** [comment]
this is very weird. i can't see a reason why the two calls would be different. indeed, spm does not show up in the list of toolboxes from the matlab output. out of curiosity can you provide the output of:

`printenv | grep -i matlab`

and 

`printenv | grep -i nipype`

and in the python terminal:

```
from nipype import Node
from nipype.interfaces.matlab import MatlabCommand
node = Node(MatlabCommand(script='ver;'), name='matlab')
res = node.run()
print(res.runtime.stderr)
```

and

```
from nipype import Node, Function
def find_spm():
    from nipype.interfaces.spm import SPMCommand
    return SPMCommand().version
node = Node(Function(input_names=[], output_names=['version'], function=find_spm), name='finder')
res = node.run()
print(res.outputs.version)
```

**Comment by satra** [comment]
fixed the code above to do `res.runtime.stdout`

**Comment by ankita940** [comment]
output of commands u mentioned:
1) PATH=/usr/local/MATLAB/R2016b/bin:/usr/share/fsl/4.1/4.1/bin:/home/ankita/anaconda2/bin:/home/ankita/miniconda2/bin:/opt/c3d/bin:/opt/afni:/usr/share/fsl/5.0/bin:/usr/lib/fsl/5.0:/opt/c3d/bin:/opt/afni:/usr/share/fsl/5.0/bin:/opt/c3d/bin:/opt/afni:/usr/share/fsl/5.0/bin:/opt/c3d/bin:/opt/ants/bin:/opt/afni:/usr/share/fsl/5.0/bin:/opt/afni:/usr/share/fsl/5.0/bin:/opt/c3d/bin:/opt/ants/bin:/opt/afni:/usr/share/fsl/5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.7.0_121/bin:/usr/lib/jvm/jdk1.7.0_121/db/bin:/usr/lib/jvm/jdk1.7.0_121/jre/bin:/home/ankita/bin:/usr/local/java/jdk1.8.0_51/bin:/usr/lib/fsl/4.1

2) nothing just returned

3)By executing res = node.run() giving error as-

170311-00:43:19,199 workflow INFO:
	 Executing node matlab in dir: /tmp/tmpQy_r5l/matlab
170311-00:43:19,306 workflow INFO:
	 Running: matlab -nodesktop -nosplash -singleCompThread -r "addpath('/tmp/tmpQy_r5l/matlab');pyscript;exit"

4) while running res = node.run() line of code giving the following error:

170311-00:45:55,164 workflow INFO:
	 Executing node finder in dir: /tmp/tmprYmT9K/finder
170311-00:46:05,139 workflow INFO:
	 Runtime memory and threads stats unavailable

**Comment by satra** [comment]
@ankita940 - these are simply logging during the execution of the two run() commands. however, it's the output of the two print statements above that i need to see.

**Comment by ankita940** [comment]
okay sorry I thought its error

3) output of -  from nipype import Node
from nipype.interfaces.matlab import MatlabCommand
node = Node(MatlabCommand(script='ver;'), name='matlab')
res = node.run()
print(res.runtime.stdout)


170311-01:02:43,958 workflow INFO:
	 Executing node matlab in dir: /tmp/tmpyIsYzR/matlab
170311-01:02:44,3 workflow INFO:
	 Running: matlab -nodesktop -nosplash -singleCompThread -r "addpath('/tmp/tmpyIsYzR/matlab');pyscript;exit"
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                            < M A T L A B (R) >
                                                  Copyright 1984-2016 The MathWorks, Inc.
                                                   R2016b (9.1.0.441655) 64-bit (glnxa64)
                                                             September 7, 2016

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Executing pyscript at 11-Mar-2017 01:02:50:
Executing pyscript at 11-Mar-2017 01:02:50:
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: 40480989
Operating System: Linux 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.1         (R2016b)
Simulink                                              Version 8.8         (R2016b)
Antenna Toolbox                                       Version 2.1         (R2016b)
Audio System Toolbox                                  Version 1.1         (R2016b)
Bioinformatics Toolbox                                Version 4.7         (R2016b)
Communications System Toolbox                         Version 6.3         (R2016b)
Computer Vision System Toolbox                        Version 7.2         (R2016b)
Control System Toolbox                                Version 10.1        (R2016b)
Curve Fitting Toolbox                                 Version 3.5.4       (R2016b)
DSP System Toolbox                                    Version 9.3         (R2016b)
Database Toolbox                                      Version 7.0         (R2016b)
Embedded Coder                                        Version 6.11        (R2016b)
Filter Design HDL Coder                               Version 3.1         (R2016b)
Fixed-Point Designer                                  Version 5.3         (R2016b)
Fuzzy Logic Toolbox                                   Version 2.2.24      (R2016b)
Global Optimization Toolbox                           Version 3.4.1       (R2016b)
HDL Coder                                             Version 3.9         (R2016b)
HDL Verifier                                          Version 5.1         (R2016b)
Image Acquisition Toolbox                             Version 5.1         (R2016b)
Image Processing Toolbox                              Version 9.5         (R2016b)
Instrument Control Toolbox                            Version 3.10        (R2016b)
LTE System Toolbox                                    Version 2.3         (R2016b)
MATLAB Coder                                          Version 3.2         (R2016b)
MATLAB Report Generator                               Version 5.1         (R2016b)
Mapping Toolbox                                       Version 4.4         (R2016b)
Model Predictive Control Toolbox                      Version 5.2.1       (R2016b)
Neural Network Toolbox                                Version 9.1         (R2016b)
Optimization Toolbox                                  Version 7.5         (R2016b)
Parallel Computing Toolbox                            Version 6.9         (R2016b)
Partial Differential Equation Toolbox                 Version 2.3         (R2016b)
Phased Array System Toolbox                           Version 3.3         (R2016b)
RF Toolbox                                            Version 3.1         (R2016b)
Robotics System Toolbox                               Version 1.3         (R2016b)
Robust Control Toolbox                                Version 6.2         (R2016b)
Signal Processing Toolbox                             Version 7.3         (R2016b)
SimRF                                                 Version 5.1         (R2016b)
Simscape                                              Version 4.1         (R2016b)
Simscape Driveline                                    Version 2.11        (R2016b)
Simscape Electronics                                  Version 2.10        (R2016b)
Simscape Multibody                                    Version 4.9         (R2016b)
Simulink 3D Animation                                 Version 7.6         (R2016b)
Simulink Control Design                               Version 4.4         (R2016b)
Stateflow                                             Version 8.8         (R2016b)
Statistics and Machine Learning Toolbox               Version 11.0        (R2016b)
Symbolic Math Toolbox                                 Version 7.1         (R2016b)
System Identification Toolbox                         Version 9.5         (R2016b)
WLAN System Toolbox                                   Version 1.2         (R2016b)
Wavelet Toolbox                                       Version 4.17        (R2016b)
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: 40480989
Operating System: Linux 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.1         (R2016b)
Simulink                                              Version 8.8         (R2016b)
Antenna Toolbox                                       Version 2.1         (R2016b)
Audio System Toolbox                                  Version 1.1         (R2016b)
Bioinformatics Toolbox                                Version 4.7         (R2016b)
Communications System Toolbox                         Version 6.3         (R2016b)
Computer Vision System Toolbox                        Version 7.2         (R2016b)
Control System Toolbox                                Version 10.1        (R2016b)
Curve Fitting Toolbox                                 Version 3.5.4       (R2016b)
DSP System Toolbox                                    Version 9.3         (R2016b)
Database Toolbox                                      Version 7.0         (R2016b)
Embedded Coder                                        Version 6.11        (R2016b)
Filter Design HDL Coder                               Version 3.1         (R2016b)
Fixed-Point Designer                                  Version 5.3         (R2016b)
Fuzzy Logic Toolbox                                   Version 2.2.24      (R2016b)
Global Optimization Toolbox                           Version 3.4.1       (R2016b)
HDL Coder                                             Version 3.9         (R2016b)
HDL Verifier                                          Version 5.1         (R2016b)
Image Acquisition Toolbox                             Version 5.1         (R2016b)
Image Processing Toolbox                              Version 9.5         (R2016b)
Instrument Control Toolbox                            Version 3.10        (R2016b)
LTE System Toolbox                                    Version 2.3         (R2016b)
MATLAB Coder                                          Version 3.2         (R2016b)
MATLAB Report Generator                               Version 5.1         (R2016b)
Mapping Toolbox                                       Version 4.4         (R2016b)
Model Predictive Control Toolbox                      Version 5.2.1       (R2016b)
Neural Network Toolbox                                Version 9.1         (R2016b)
Optimization Toolbox                                  Version 7.5         (R2016b)
Parallel Computing Toolbox                            Version 6.9         (R2016b)
Partial Differential Equation Toolbox                 Version 2.3         (R2016b)
Phased Array System Toolbox                           Version 3.3         (R2016b)
RF Toolbox                                            Version 3.1         (R2016b)
Robotics System Toolbox                               Version 1.3         (R2016b)
Robust Control Toolbox                                Version 6.2         (R2016b)
Signal Processing Toolbox                             Version 7.3         (R2016b)
SimRF                                                 Version 5.1         (R2016b)
Simscape                                              Version 4.1         (R2016b)
Simscape Driveline                                    Version 2.11        (R2016b)
Simscape Electronics                                  Version 2.10        (R2016b)
Simscape Multibody                                    Version 4.9         (R2016b)
Simulink 3D Animation                                 Version 7.6         (R2016b)
Simulink Control Design                               Version 4.4         (R2016b)
Stateflow                                             Version 8.8         (R2016b)
Statistics and Machine Learning Toolbox               Version 11.0        (R2016b)
Symbolic Math Toolbox                                 Version 7.1         (R2016b)
System Identification Toolbox                         Version 9.5         (R2016b)
WLAN System Toolbox                                   Version 1.2         (R2016b)
Wavelet Toolbox                                       Version 4.17        (R2016b)



4) output of 
from nipype import Node, Function
def find_spm():
    from nipype.interfaces.spm import SPMCommand
    return SPMCommand().version
node = Node(Function(input_names=[], output_names=['version'], function=find_spm), name='finder')
res = node.run()
print(res.outputs.version)


170311-01:05:04,647 workflow INFO:
	 Executing node finder in dir: /tmp/tmp8OiL4D/finder
170311-01:05:15,20 workflow INFO:
	 Runtime memory and threads stats unavailable
None

**Comment by satra** [comment]
thanks @ankita940 - so clearly the matlab called from the node cannot find spm. if you could do this one last check - just copy and past the whole thing:

```python
from nipype import Node, Function
def find_spm():
    from nipype.interfaces.spm import SPMCommand
    return SPMCommand().version
node = Node(Function(input_names=[], output_names=['version'], function=find_spm), name='finder')
res = node.run()
print('CALL: spm checker directly')
print(find_spm())
print('CALL: spm checker via node')
print(res.outputs.version)
```

**Comment by ankita940** [comment]
Output of what you asked for:

170317-15:21:12,477 workflow INFO:
	 Executing node finder in dir: /tmp/tmp5I2tcH/finder
170317-15:21:58,948 workflow INFO:
	 Runtime memory and threads stats unavailable
CALL: spm checker directly
12.6906
CALL: spm checker via node
None

What should I do so that matlab can find spm in its path.Please guide.

**Comment by ankita940** [comment]
Hello @satra 
I have to do a project on this but I got stuck on this point because of the above issue. 
Please help me with the above issue.

**Comment by ankita940** [comment]
there was some problem with configuration and after resolving it worked .

Thank you
