### ISSUE TITLE
Looking for references on RapidART

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1897]
Hi, this is not about a bug.

I have used RapidART for one of my experiments and I am writing an article about it. I am looking for a paper which already used the motion and intensity statistics from RapidART to reject subjects from a fMRI experiment. 

Do you know if there is any? Could you please point me out to it?

Thank you!

**Comment by satra** [comment]
@alexsavio - it's been used in several papers and in the conn toolbox, but there is no direct paper for it. but the ideas are relatively simple and many other folks have now written papers on similar schemes. you could possibly cite the conn toolbox paper. funnily enough that's the algorithm that started the original nipype tools in 2008!

**Comment by satra** [comment]
for example, this is one of the earlier papers that used it: http://www.nature.com/neuro/journal/v10/n9/abs/nn1950.html

**Comment by alexsavio** [comment]
thank you @satra!
