### ISSUE TITLE
cannot import name NUMPY_MMAP

### ISSUE THREAD

**Issue by ankita940** [nipy/nipype#1898]
hi ,

while running spm_fmri_auditory data,
realign , coregister are working fine.
but when it reaches segementation it throws "cannot import name NUMPY_MMAP".

thank u.

P.S:  here is the content of the crash file.

File: crash-20170322-000050-ankita-normalize_func.a0-01a55623-d776-4eb2-a8f9-855304a29fcd.pklz
Node: level1.firstlevel.preproc.normalize_func.a0
Working directory: /home/ankita/preprocess/spm_auditory_tutorial/workingdir/level1/firstlevel/preproc/_subject_id_M00223/normalize_func

Node inputs:

DCT_period_cutoff = <undefined>
affine_regularization_type = <undefined>
apply_to_files = <undefined>
ignore_exception = False
jobtype = write
matlab_cmd = <undefined>
mfile = True
nonlinear_iterations = <undefined>
nonlinear_regularization = <undefined>
out_prefix = w
parameter_file = <undefined>
paths = <undefined>
source = <undefined>
source_image_smoothing = <undefined>
source_weight = <undefined>
template = <undefined>
template_image_smoothing = <undefined>
template_weight = <undefined>
use_mcr = <undefined>
use_v8struct = True
write_bounding_box = <undefined>
write_interp = <undefined>
write_preserve = <undefined>
write_voxel_sizes = <undefined>
write_wrap = <undefined>

Traceback: 
Traceback (most recent call last):
  File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 295, in run
    self._get_inputs()
  File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in _get_inputs
    value)
  File "/home/ankita/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/utils.py", line 440, in evaluate_connect_function
    *list(args))
  File "<string>", line 3, in get_vox_dims
ImportError: cannot import name NUMPY_MMAP

**Comment by mgxd** [comment]
Hi @ankita940, `NUMPY_MMAP` was added to the nipype package to check your version of numpy. This error should be solved by installing the latest version of nipype with:
`pip install --upgrade https://github.com/nipy/nipype/archive/master.zip`

**Comment by ankita940** [comment]
It worked.
Thanks for helping me out.
