### ISSUE TITLE
[BUG] antsBrainExtraction interface fails when $ANTSPATH is not defined, but exit code is 0

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1901]
### Summary
 antsBrainExtraction interface fails when $ANTSPATH is not defined, but exit code is 0

### How to replicate the behavior
The problem is the following
```
$ antsBrainExtraction.sh -h
we cant find the N4 program -- does not seem to exist. please (re)define $ANTSPATH in your environment.
$ echo $?
0
```
when nipype gets to check the output, since the exit code is zero, it breaks. We could check, at least, for this output message and reraise the message.

cc @rwblair .

**Comment by chrisfilo** [comment]
is this stdout or stderr?

**Comment by oesteban** [comment]
stdout
