### ISSUE TITLE
[ENH] additionnal afni interfaces

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#1904]
Hi nipype experts,

I started to add more afni interfaces: `3dUnifize`, `3dQwarp` and `3drefit`. Shall I do a PR to propose this addition ?

Thanks

**Comment by oesteban** [comment]
That'd be very much appreciated :)

**Comment by mgxd** [comment]
@salma1601 feel free to submit the other 2 as PRs

**Comment by salma1601** [comment]
>@salma1601 feel free to submit the other 2 as PRs

Yes of course, I already started working on `3dQwarp`. Needs some time because of the huge number of parameters :)

**Comment by oesteban** [comment]
@salma1601, please make sure you have a look on the partial implementation of 3dQwarp that @chrisfilo made: https://github.com/nipy/nipype/blob/592ce3afa793675d2848fbe9f10f0f9b46c504d7/nipype/interfaces/afni/preprocess.py#L2352-L2450

After we merge your PR, this `QwarpPlusMinus` should be derived from your interface.

**Comment by salma1601** [comment]
>After we merge your PR, this QwarpPlusMinus should be derived from your interface

Ok !
