### ISSUE TITLE
MCFLIRT does not generate mean_img

### ISSUE THREAD

**Issue by utooley** [nipy/nipype#1914]
### Summary
Nipype documentation in fsl.MCFLIRT.help() states that one of the out files of MCFLIRT can be a _mean_img_, but throws an error. _mcflirt --help_ does not show mean_img as a possible output.
### Actual behavior
No mean_img is able to be set as an InputSpec of MCFLIRT.
### How to replicate the behavior
Trying to set a name for the _mean_img_ output of MCFLIRT.
### Platform details:
{'numpy_version': '1.11.3', 'commit_source': 'archive substitution', 'nibabel_version': '2.2.0dev', 'scipy_version': '0.19.0', 'pkg_path': '/opt/conda/lib/python3.5/site-packages/nipype', 'sys_platform': 'linux', 'networkx_version': '1.11', 'traits_version': '4.6.0', 'sys_version': '3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'nipype_version': '0.13.0-dev', 'sys_executable': '/opt/conda/bin/python', 'commit_hash': '%h'}
0.13.0-dev

**Comment by oesteban** [comment]
Do you refer to the `-mean` flag of MCFLIRT? You need to set the input `mean_vol=True`

**Comment by satra** [comment]
ah yes `--meanvol` will register and generate the mean volume, but mcflirt doesn't generate this mean volume if default reference (0) is used or reffile/vol is used.

**Comment by satra** [comment]
perhaps we can add this to the docstring for mcflirt
