### ISSUE TITLE
nipy pipeline failure.

### ISSUE THREAD

**Issue by ankita940** [nipy/nipype#1922]
hi,

after installing matlab, spm ,nipy ,anaconda and fsl, when i am testing my pipeline i am getting the following error.

ankita@ankita-PC:~$ python -c "import nipype; nipype.test()"
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/ankita, inifile:
collecting 93 items / 1 errors
==================================== ERRORS ====================================
 ERROR collecting anaconda2/lib/python2.7/site-packages/nipype/algorithms/tests/test_auto_TSNR.py 
anaconda2/lib/python2.7/site-packages/nipype/algorithms/tests/test_auto_TSNR.py:2: in <module>
    from ...testing import assert_equal
E   ImportError: cannot import name assert_equal
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.48 seconds ============================

**Comment by mgxd** [comment]
Could you try updating nipype by typing into your terminal `pip install https://github.com/nipy/nipype/archive/master.zip`

**Comment by ankita940** [comment]
Hello @mgxd ,
It is still giving same error.

**Comment by mgxd** [comment]
@ankita940 I've edited my comment above to include `--upgrade`. If that doesn't work, I recommend clearing all installations of nipype and then reinstalling.

**Comment by mgxd** [comment]
@ankita940 are you still running into issues? If so, feel free to reopen this
