### ISSUE TITLE
Circle CI taking the unit-tests for passed when failed (again)

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#1933]
Only for the unittests, not for the smoketests.

Even though some tests fail (and it is correctly reported by the tests summary thanks to having the junit xml files in place), the build is taken for passing. Example: https://circleci.com/gh/nipy/nipype/2095?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

When I refactored this, CircleCI was showing these builds as failed (or I may have been tripping out). Now it seems it requires an explicit non-zero exit code.

**Comment by satra** [comment]
@oesteban - has this been addressed?

**Comment by oesteban** [comment]
nope, I'll take on this tonight, sorry about that
