### ISSUE TITLE
nipype 'multiproc' only running as single thread

### ISSUE THREAD

**Issue by isAarya** [nipy/nipype#1935]
Hi,

I having issues running nipype as a multiproc system. 
It only works if, I dont use the 'Multiproc' plugin

When I run the following code
`workflow.run(plugin='MultiProc', plugin_args={'n_procs':4})`

I get the following as error

![git_multiproc_error](https://cloud.githubusercontent.com/assets/21230063/24682463/39856f4c-19dd-11e7-8ede-9f96ebb8bc32.png)

Can someone provide an insight as to why this error is occuring.

Kind regards.
IA

My platform details is as follows,

```
{'scipy_version': '0.18.1', 'numpy_version': '1.11.1', 'commit_hash': "b'3abf131\\n'", 'sys_version': '3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'networkx_version': '1.11', 'pkg_path': '/data/lfs2/model-mie/pyScripts/anaconda3/lib/python3.5/site-packages/nipype', 'sys_platform': 'linux', 'traits_version': '4.5.0', 'nibabel_version': '2.0.2', 'sys_executable': '/data/lfs2/model-mie/pyScripts/anaconda3/bin/python'}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'nipype' has no attribute '_version_'
```

**Comment by oesteban** [comment]
Hi @isAarya,

I'm afraid you are looking at two different errors here. The first error is the typical result of trying to run an empty workflow. It means that for some reason, you did not add any nodes. If you run it with the Linear plugin (just `workflow.run()`) you should get the same. Please copy here the code of your workflow to diagnose.

Regarding the second, it seems that some error is going on. I think you've misspelled the `__version__` argument of nipype (two underscores before and after, not one).

please report the output of `python -c "import nipype; print(nipype.__version__)"`.

**Comment by mgxd** [comment]
@isAarya still running into problems?

**Comment by isAarya** [comment]
@mgxd Nipype is running fine now.  
My workflow was not empty, but I had not initialized any nodes. Hence the error.
But, when calling as linear plugin `workflow.run()`. It still ran with no errors. Hence, it threw me offtrack a bit.
But it is working now. 
Cheers
