### ISSUE TITLE
MRIsConvert combine_surfs function

### ISSUE THREAD

**Issue by tsalo** [nipy/nipype#1947]
`mris_convert` has a flag for combining surface files (`combine_surfs`), but the current interface doesn't allow for it. Since the current interface is just for converting between file types, and adding `combine_surfs` to MRIsConvert will require overhauling it a bit, I wanted to know whether it would be preferable to expand MRIsConvert or to create a new interface for the `combine_surfs` behavior specifically (something like MRIsCombine). Does anyone have a preference?

**Comment by effigies** [comment]
My personal feeling is that if you're willing to do the work, however you think best is fine. Just need not to break existing use.

**Comment by tsalo** [comment]
Thanks. I think it makes more sense to create a separate interface specifically for combining surfaces. Added in #1948.
