### ISSUE TITLE
setting 'in_file' trait as an Nibabel object 

### ISSUE THREAD

**Issue by jnecus** [nipy/nipype#1954]
### Summary

I have written my own function which returns a Nibabel object which is then fed into FSL FLIRT. However, I then get the following error:

> TraitError: The 'in_file' trait of a FLIRTInputSpec instance must be an existing file name, but a value of <nibabel.nifti1.Nifti1Image object at 0x7f2c9a739210> <class 'nibabel.nifti1.Nifti1Image'> was specified

### Original function
```
def resample_flair(t1w,flair):
    from nilearn.image import resample_to_img      
    return resample_to_img(flair,t1w)
```

### Attempts to get around this
In order to attempt to get around this I have tried returning the nifti image filename as so:
```

def resample_flair(t1w,flair):
    from nilearn.image import resample_to_img 
    img=resample_to_img(flait,t1w)    
    return img.get_filename()
```

However, I get the same error as before.

### Platform details:

> {'nibabel_version': '2.1.0', 'networkx_version': '1.11', 'numpy_version': '1.11.3', 'sys_platform': 'linux2', 'sys_version': '2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': u'archive substitution', 'commit_hash': '%h', 'pkg_path': '/home/joe/anaconda2/lib/python2.7/site-packages/nipype', 'sys_executable': '/home/joe/anaconda2/bin/python', 'traits_version': '4.6.0', 'scipy_version': '0.18.1'}
> 0.13.0-dev

**Comment by jnecus** [comment]
I managed to solve this by creating a temporary filename and exporting this. However, I wondered whether there was a more elegant way or doing this allowing me to pass a nibabel object to a node such as FSL's FLIRT?

**Comment by satra** [comment]
unfortunately not with the current nipype. we are looking into automatic conversion and storage for future versions.

also for FSL it would need to be converted to a file whether automatically or manually.
