### ISSUE TITLE
CompCor issues

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1982]
I am having issues with CompCor after this was merged https://github.com/nipy/nipype/pull/1968

First `mask_file` input of aCompCor does not work:

```
            Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 52, in _run_interface
    ReportCapableInterface, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py", line 378, in _run_interface
    self.inputs.mask_files = self.inputs.mask_files[0]
TypeError: '_Undefined' object does not support indexing
Interface ACompCorRPT failed to run. 
```

Secondly the high_variance_mask returned by tCompCor seems wrong
Before the PR was merged:
![image](https://cloud.githubusercontent.com/assets/238759/25562298/4ec3800c-2d37-11e7-8cd3-717aa2bf042f.png)

After the PR was merged:
![image](https://cloud.githubusercontent.com/assets/238759/25562304/6b85b200-2d37-11e7-95d4-fbdfa127ca0e.png)

This is the call to tcompcor in fmriprep https://github.com/poldracklab/fmriprep/blob/5e3ba02b515ba07c598fda7f4ad7b2bbbf7a8735/fmriprep/workflows/confounds.py#L180 As you can see it should be restricted by highly eroded brain mask which was the case before that PR was merged.

**Comment by satra** [comment]
@chrisfilo - it's possible that both are because the api has changed. you should now set `mask_files` and not `mask_file`.

@mgxd - the deprecation warning will only come online after we release 0.13.0. and i should have checked to see an on_trait_change that sets the other trait by default.

since these interfaces were not released as part of 0.12.0, i would now suggest removing the `mask_file` trait altogether.

**Comment by satra** [comment]
@chrisfilo - with regard to previous comment and removal of `mask_file` completely let us know. what @mgxd implemented in fact makes the interface more useful when one wants to use multiple masks.

**Comment by chrisfilo** [comment]
The second problem was observed after switching to the new names: mask_files and high_variance_masks.

**Comment by satra** [comment]
@chrisfilo - sorry taking a closer look.

**Comment by chrisfilo** [comment]
I had a closer look. It turns out I got confused in my testing - the wrong results happen only if `mask_file` input is set. If the new `mask_files` input is used the returned high_variance_mask is correct.

I am ok with `mask_file` being removed instead of trying to fix it.

**Comment by mgxd** [comment]
@chrisfilo good to hear!

**Comment by chrisfilo** [comment]
I wasn't the only one who run into this: https://neurostars.org/t/nipype-tcompcor-error/415

**Comment by mgxd** [comment]
it seems the `MapNode` bug is happening because of an interaction between the `super()` call from `TCompCor` to `CompCor` and the node's `outputs` field being populated with the defaults. One workaround would be to add the defaults within the `_run_interface` method, but that seems crude. 

```python
ipdb> self.outputs
Bunch(components_file='components_file.txt', header=<undefined>, high_variance_masks=<undefined>, ignore_exception=False, mask_files=<undefined>, mask_index=<undefined>, merge_method=<undefined>, num_components=6, realigned_file=<undefined>, regress_poly_degree=1, use_regress_poly=True)
```

@chrisfilo @satra any ideas?

**Comment by satra** [comment]
hold on there are several issues with that interface that i am now fixing.
