### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by dpisner453** [nipy/nipype#1988]
```
RuntimeError: Could not submit sbatch task for node imp_est
Command:
sbatch  -o /tmp/tmpuFQA21/PyNets_WORKFLOW/batch/slurm-%j.out -e /tmp/tmpuFQA21/PyNets_WORKFLOW/batch/slurm-%j.out -J imp_est.PyNets_WORKFLOW.dpisner /tmp/tmpuFQA21/PyNets_WORKFLOW/batch/batchscript_pyscript_20170501_013001_PyNets_WORKFLOW_imp_est.sh
Standard output:
-----------------------------------------------------------------
              Welcome to the Stampede Supercomputer              
-----------------------------------------------------------------

--> Submission error: all jobs must have a queue name specified with "-p"


Standard error:

Return code: 1
Interface CommandLine failed to run.
```

**Comment by oesteban** [comment]
Looks like you are not indicating the partition option (`-p`) when submitting your job.

Seems to me you are using the SLURM plugin, so you should define it there.

However, any additional info would be very much appreciated (starting with the nipype workflow you want to run).

**Comment by dpisner453** [comment]
Hm, I am running and testing the PyNets workflow in my github repo :) 

Problem Solved. Just needed to change the way I was specifying my sbatch arguments since I am running on a virtual login node with different allocation options...

Sorry for any confusion!
