### ISSUE TITLE
UnicodeEncodeError in Python3

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#1990]
### Summary
nipype/utils/tests/test_provenance.py::test_safe_encode fails.
It is a similar error as described in #1393, but I have it for Python3

### Actual behavior
The test gives: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
see full message: https://paste.pound-python.org/show/JTFNExgcXRMeoK75UkXJ/

### Expected behavior
the test should pass

### How to replicate the behavior
 pytest -v nipype/utils/tests/test_provenance.py 

Detailed instruction:
 - docker run -it --rm ubuntu:16.04
 - apt-get update
 - apt-get -f install
 - apt-get install git
 - apt-get install python3-pip
 - pip install -r requirements.txt (in nipype/)
 - python3 setup.py develop
 - pytest -v nipype/utils/tests/test_provenance.py

### Platform details:
Docker image ubuntu: 16.04 

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

>>> print(nipype.get_info())
{'scipy_version': '0.19.0', 'pkg_path': '/nipype/nipype', 'nipype_version': '0.13.0-g592ce3a.dev', 'commit_source': 'repository', 'sys_executable': '/usr/bin/python3', 'sys_platform': 'linux', 'networkx_version': '1.11', 'numpy_version': '1.12.1', 'sys_version': '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]', 'traits_version': '4.6.0', 'commit_hash': '592ce3a', 'nibabel_version': '2.1.0'}
>>> print(nipype.__version__)
0.13.0-g592ce3a.dev

### Execution environment

See "How to replicate the behavior"

**Comment by djarecka** [comment]
@satra just solved my problem :) 

The test passes if I export:

```
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
```

**Comment by Apon77** [comment]
> @satra just solved my problem :)
> 
> The test passes if I export:
> 
> ```
> export LANG=C.UTF-8
> export LC_ALL=C.UTF-8
> ```

This worked 🙂
