### ISSUE TITLE
niftyreg interface does not work with released version of tools

### ISSUE THREAD

**Issue by bennyrowland** [nipy/nipype#1995]
### Summary

The currently released version of niftyreg outputs its version string as the commit hash, but the interface in nipype seems to expect a standard major.minor.patch string, causing it to error with a ValueError: invalid version number

### How to replicate the behavior

Fresh docker debian, install niftyreg as detailed on CMIC website

```
RUN mkdir /opt/niftyreg-src && \
    mkdir /opt/niftyreg-build && \
    git clone git://git.code.sf.net/p/niftyreg/git /opt/niftyreg-src -b dev

WORKDIR /opt/niftyreg-build

RUN cmake -D CMAKE_BUILD_TYPE=Release /opt/niftyreg-src && \
    make && \
    make install
```

then install master version of nipype

```
# install dev version of nipype to include niftyreg
WORKDIR /opt
RUN git clone https://github.com/nipy/nipype.git
RUN pip install /opt/nipype
```

run following python code:
```
from nipype.interfaces import niftyreg
reg_aladin = niftyreg.RegAladin()
```

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

{'commit_source': 'installation', 'networkx_version': '1.11', 'scipy_version': '0.19.0',
 'sys_version': '3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) \n[G
CC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'nipype_version': '0.13.0-dev', 'pkg_path': '/opt
/conda/lib/python3.5/site-packages/nipype', 'commit_hash': 'e48c9c8', 'sys_platform': 'l
inux', 'sys_executable': '/opt/conda/bin/python', 'nibabel_version': '2.1.0', 'numpy_ver
sion': '1.12.1', 'traits_version': '4.6.0'}
0.13.0-dev

### Execution environment

Docker image openmrslab/openmrslab

**Comment by bennyrowland** [comment]
would be very helpful to get a comment from @byvernault about how to get a suitable version of niftyreg installed to work with this interface.

**Comment by mmodat** [comment]
Quick update. I updated and cleaned the git on sourceforge so that it only keeps the master and added a hook onto the active git repository so that it copies the master automatically to sourceforge.
I am in the process of regenerating/updating some of the basic documentation.

**Comment by bennyrowland** [comment]
Thanks @mmodat. For reference, I was able to get everything working from the cmiclabs git repo using the following docker commands 
```
# install cmake
WORKDIR /opt
RUN wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz

RUN tar xf /opt/cmake-3.8.1.tar.gz && \
    cd /opt/cmake-3.8.1 && \
    ./bootstrap --prefix=/opt/cmake && \
    make && make install

# install niftyreg
RUN mkdir /opt/niftyreg-src && \
    mkdir /opt/niftyreg-build && \
    git clone http://git@cmiclab.cs.ucl.ac.uk/mmodat/niftyreg.git /opt/niftyreg-src

WORKDIR /opt/niftyreg-build

RUN /opt/cmake/bin/cmake -D CMAKE_BUILD_TYPE=Release /opt/niftyreg-src && \
    make && \
    make install
```

I will leave the issue open in case anybody happens across it before the documentation is updated, but I now have everything I want working.

**Comment by oesteban** [comment]
I would suggest linking @bennyrowland's comment from nifty* documentation to describe how to use the niftyreg and closing this issue.
