### ISSUE TITLE
nipype 1.0.0 test fail

### ISSUE THREAD

**Issue by caixixixi** [nipy/nipype#2040]
=================================== FAILURES ===================================
_______________________ test_s3datagrabber_communication _______________________

tmpdir = local('/tmp/pytest-of-caixi/pytest-9/test_s3datagrabber_communicati0')

    @pytest.mark.skipif(noboto, reason="boto library is not available")
    def test_s3datagrabber_communication(tmpdir):
        dg = nio.S3DataGrabber(
            infields=['subj_id', 'run_num'], outfields=['func', 'struct'])
        dg.inputs.anon = True
        dg.inputs.bucket = 'openfmri'
        dg.inputs.bucket_path = 'ds001/'
        dg.inputs.local_directory = str(tmpdir)
        dg.inputs.sort_filelist = True
        dg.inputs.template = '*'
        dg.inputs.field_template = dict(func='%s/BOLD/task001_%s/bold.nii.gz',
                                        struct='%s/anatomy/highres001_brain.nii.gz')
        dg.inputs.subj_id = ['sub001', 'sub002']
        dg.inputs.run_num = ['run001', 'run003']
        dg.inputs.template_args = dict(
            func=[['subj_id', 'run_num']], struct=[['subj_id']])
>       res = dg.run()

/home/caixi/anaconda/lib/python2.7/site-packages/nipype/interfaces/tests/test_io.py:122: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/caixi/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py:1082: in run
    outputs = self.aggregate_outputs(runtime)
/home/caixi/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py:1153: in aggregate_outputs
    predicted_outputs = self._list_outputs()
/home/caixi/anaconda/lib/python2.7/site-packages/nipype/interfaces/io.py:872: in _list_outputs
    bkt_files = list(k.key for k in bkt.list())
/home/caixi/anaconda/lib/python2.7/site-packages/nipype/interfaces/io.py:872: in <genexpr>
    bkt_files = list(k.key for k in bkt.list())
/home/caixi/anaconda/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py:32: in bucket_lister
    encoding_type=encoding_type)
/home/caixi/anaconda/lib/python2.7/site-packages/boto/s3/bucket.py:474: in get_all_keys
    '', headers, **params)
/home/caixi/anaconda/lib/python2.7/site-packages/boto/s3/bucket.py:401: in _get_all
    body = response.read()
/home/caixi/anaconda/lib/python2.7/site-packages/boto/connection.py:409: in read
    self._cached_response = http_client.HTTPResponse.read(self)
/home/caixi/anaconda/lib/python2.7/httplib.py:573: in read
    return self._read_chunked(amt)
/home/caixi/anaconda/lib/python2.7/httplib.py:615: in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
/home/caixi/anaconda/lib/python2.7/socket.py:480: in readline
    data = self._sock.recv(self._rbufsize)
/home/caixi/anaconda/lib/python2.7/ssl.py:766: in recv
    return self.read(buflen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0x7f87d2e9fc80>, len = 1, buffer = None

    def read(self, len=1024, buffer=None):
        """Read up to LEN bytes and return them.
            Return zero-length string on EOF."""
    
        self._checkClosed()
        if not self._sslobj:
            raise ValueError("Read on closed or unwrapped SSL socket.")
        try:
            if buffer is not None:
                v = self._sslobj.read(len, buffer)
            else:
>               v = self._sslobj.read(len)
E               SSLError: (u'The read operation timed out\nInterface S3DataGrabber failed to run. ',)

/home/caixi/anaconda/lib/python2.7/ssl.py:653: SSLError
----------------------------- Captured stdout call -----------------------------
170520-06:43:55,599 boto ERROR:
	 Caught exception reading instance data
Traceback (most recent call last):
  File "/home/caixi/anaconda/lib/python2.7/site-packages/boto/utils.py", line 214, in retry_url
    r = opener.open(req)
  File "/home/caixi/anaconda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/caixi/anaconda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/caixi/anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/caixi/anaconda/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/caixi/anaconda/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
170520-06:43:55,639 boto ERROR:
	 Unable to read instance data, giving up

**Comment by mgxd** [comment]
@caixixixi can you ensure you have an updated version of `boto`? Wasn't able to replicate this on either python 2/3

**Comment by mgxd** [comment]
@caixixixi please open this issue if you continue running into this problem.
