### ISSUE TITLE
Listing Authors

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#2045]
I was prompted to look at the authors json file recently. It's really cool that we keep track of who contributes (and provide due credit), but it's plain to see that both the listing itself, as well as the order of authors is done manually.

While I have no objection to the people on the list and the order, wouldn't it be greater, easier (in the long run), and robuster if the list, or at least the order, could be determined automatically from the git history? Most probably this is better handled by a separate package, and not internally by the nipype code. But is there such a package?

@yarikoptic I seem to recall you're also interested in better ways to attribute code.

**Comment by satra** [comment]
@TheChymera - except for a couple of folks being re-ordered, it was done automatically :) i will post the script to tools soon. just has a few extra dependencies. 

the one bit that really required manual work was the mailmap file. the contributors-lines was created by a script that looked at git shortlog and lines (as opposed to commits). it was an assumption i used as better representative of contribution. surely such a system can be gamed, and ideally we would know a way to evaluate a contribution, but that's a very fuzzy area.

```python
import json
from fuzzywuzzy import fuzz, process
with open('contributors-lines.txt', 'rt') as fp:
    data = [' '.join(val.strip().split()[1:-1]) for val in fp.readlines() if '%' in val]
with open('.zenodo.json', 'rt') as fp:
    zenodo = json.load(fp)
zen_names = [' '.join(val['name'].split(',')[::-1]).strip() for val in zenodo['creators']]
name_matches = []
for ele in data:
    matches = process.extract(ele, zen_names, scorer=fuzz.token_sort_ratio, limit=2)
    if matches[0][1] > 80:
        #val = (ele, matches[0], zen_names.index(matches[0][0]))
        val = zenodo['creators'][zen_names.index(matches[0][0])]
    else:
        #val = (ele, matches, None)
        val = [ele]
        for match in matches:
            val.append(zenodo['creators'][zen_names.index(match[0])])
    name_matches.append(val)
zenodo['creators'] = name_matches
with open('zenodo.json', 'wt') as fp:
    fp.write(json.dumps(zenodo, indent=2, sort_keys=True))
```

**Comment by TheChymera** [comment]
I've been proposing line-based authorship listing for a while now and game-ablebility has always come up.


Given:

1. the low career utility of being a bit higher in the middle of the authors' list of some FOSS project
2. that common project dynamics usually result in crystal clear "important authorships" (first, multi-first, and last) - and that these can in doubt be manually fixed
3. that the current alternative involves lots of manual work and opens the way to a lot of project-political argument should (1) ever change

I doubt we should let gameability anxiety hold us back from doing more of this, relying more on it, and recommending it to other projects.

I'd really be stoked to help out with this functionality, but I do think it's better branched off into its own thing. Also, it would be cool if e.g. ORCID could be queried automatically.

**Comment by mgxd** [comment]
@TheChymera closing this - feel free to reopen if necessary
