### ISSUE TITLE
wrap a MATLAB script

### ISSUE THREAD

**Issue by rattar1989** [nipy/nipype#2050]
### Summary
Hi all,
I can not find any practical example re wrapping a matlab script. 
Could anyone please give a simple example on how to wrap a matlab script?
There is only one page explained about it which is not clear to me: http://nipype.readthedocs.io/en/latest/devel/matlab_interface_devel.html

for example how do you warp the following simple matlab script that computes Area of Polygon:
```
L = linspace(0,2.*pi,9); 
xv = 1.2*cos(L)';
yv = 1.2*sin(L)'; 
A = polyarea(xv,yv)
```
Thanks.

### Actual behavior
NA
### Expected behavior
NA
### How to replicate the behavior
NA
### Script/Workflow details
NA
Please put URL to code or code here (if not too long).

### Platform details:
NA
Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"
python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by anbai106** [comment]
You should use MatlabCommand interface, i did it before you create a Node to pass the parameters to your matlab script

**Comment by rattar1989** [comment]
@anbai106 Tnx for ur comment. do you mean the link above? I can not understand how to use it. can you please give me an example of using this wrapper?

**Comment by effigies** [comment]
What is `input` and what do you want to return as output?

**Comment by rattar1989** [comment]
@effigies just as an example suppose that in above matlab script: L (an array) is input and A (a number) is output.

**Comment by rattar1989** [comment]
Any feedback?

**Comment by effigies** [comment]
Hi sorry. I'm not super familiar with the Matlab interface, and a bit busy at just the minute. I'll have another look at this soon, but I wouldn't expect a better response before Tuesday.

**Comment by YSanchezAraujo** [comment]
I have an example [here](https://github.com/YSanchezAraujo/genus/blob/master/notebooks/bayes_analysis.ipynb) , the `bayes_reg.m` file looks like [this](https://github.com/YSanchezAraujo/genus/blob/master/scripts/bayes_reg.m)

In short, given your example you could do:
    
```python
import nipype.interfaces.matlab as Matlab
matlab = Matlab.MatlabCommand()
# below is where you add paths that matlab might require, this is equivalent to addpath()
matlab.inputs.paths = ['/some/path/here', '/you/can/add/many/paths']
matlab.inputs.script = """
L = linspace(0,2.*pi,9); 
xv = 1.2*cos(input)';
yv = 1.2*sin(input)'; 
A = polyarea(xv,yv) """
res = matlab.run()    
```    
One thing to note, if you need that output from `A` for example, you will need to explicit tell matlab where to save it, by supplying a full path (i believe a relative path won't work but you should test that), so your `matlab.inputs.script` might look like this:

```python
import nipype.interfaces.matlab as Matlab
save_path = "/where/you/want/to/save/output"
matlab = Matlab.MatlabCommand()
# below is where you add paths that matlab might require, this is equivalent to addpath()
matlab.inputs.paths = ['/some/path/here', '/you/can/add/many/paths']
matlab.inputs.script = """
L = linspace(0,2.*pi,9); 
xv = 1.2*cos(input)';
yv = 1.2*sin(input)'; 
A = polyarea(xv,yv);
save('{}','A');
 """.format(save_path)
res = matlab.run()    
```

**Comment by rattar1989** [comment]
@YSanchezAraujo Thanks so much for your help and examples.

Now, I can run an independent matlab code (.m file) using nipype in python.

Could you please let me know how I can run a .m file that inside the code there are calls to other .m files?

Thanks.

**Comment by YSanchezAraujo** [comment]
@rattar1989 if i understand you correctly that can be solved by adding the paths to those other `.m` files. And you do that either using the `matlab.inputs.paths` or inside the string or file that is assigned to `matlab.inputs.script` add a `addpath(genpath('/path/here'))` or simply `addpath('/path/here')`

**Comment by mgxd** [comment]
@rattar1989 feel free to open this issue if you have further questions

**Comment by rattar1989** [comment]
@YSanchezAraujo 
Hi, did you remove `bayes_reg.m` from github? 
It was a good example to follow.

**Comment by YSanchezAraujo** [comment]
@rattar1989 the repo was restructured so the links changed https://github.com/YSanchezAraujo/genus/blob/master/bayes/notebooks/variational_bayes.ipynb for the notebook and https://github.com/YSanchezAraujo/genus/blob/master/bayes/matlab/bayes_reg.m for the matlab script
