### ISSUE TITLE
Problem with singularity import: bad variable name

### ISSUE THREAD

**Issue by jokedurnez** [nipy/nipype#2064]
I'm having a problem with [this line](https://github.com/nipy/nipype/blob/master/docker/base.Dockerfile#L155) in the Dockerfile.

See [this discussion](https://github.com/singularityware/singularity/issues/719) on the singularity github.

**Comment by djarecka** [comment]
@jokedurnez : sorry for late answer. Do you still have problem with a Dockerfile?

**Comment by jokedurnez** [comment]
I got the container elsewhere, thanks.  But I'm not sure if this problem won't reappear for others.

**Comment by djarecka** [comment]
@satra - i read quickly your discussion with the singularity team, and I understand that this is between Docker and Singularity. can i close it for now, or you want to keep it open?

**Comment by satra** [comment]
we can close this. this has been addressed in neurodocker and the current neurodocker PR #2202 should fix this for nipype as well.
