### ISSUE TITLE
[BUG] orthogonalisation on/off

### ISSUE THREAD

**Issue by jokedurnez** [nipy/nipype#2073]
If there is a variable is orthogonalised wrt any other variable, then it should also be orthogonalised wrt EV0 (which is disturbingly not related to a variable 'EV0', but rather an on/off switch for all orthogonalisations).
I think this is the fix below, but I need to test it.  I wanted to document first.

https://github.com/jokedurnez/nipype/commit/366707a5c719d246aa54ec579d8ca12ab14bf3df

**Comment by jokedurnez** [comment]
Correlations before setting `set fmri(orthoX.0) 1`
![before](https://user-images.githubusercontent.com/7630327/27103924-416f3268-503f-11e7-8c90-cbe617c64326.png)
Correlations after setting `set fmri(orthoX.0) 1`
![after](https://user-images.githubusercontent.com/7630327/27103931-471c1898-503f-11e7-8a24-8a8e8e047a75.png)

**Comment by mgxd** [comment]
@jokedurnez thanks for this - will you be submitting a PR?

**Comment by jokedurnez** [comment]
Pff, I made a mess of my local clone and changes :-\ 
It will take me some time, but I'll try !
