### ISSUE TITLE
Do user-defined interfaces need `TraitedSpec` classes?

### ISSUE THREAD

**Issue by mwaskom** [nipy/nipype#2081]
There is a lot of boilerplate required to define an interface. From [the docs](http://nipype.readthedocs.io/en/latest/devel/cmd_interface_devel.html) a "simple" example of a custom Interface requires defining three classes:

```python
class ExampleInputSpec(TraitedSpec):
    input_volume = File(desc="Input volume", exists=True, mandatory=True)
    parameter = traits.Int(desc="some parameter")

class ExampleOutputSpec(TraitedSpec):
    output_volume = File(desc="Output volume", exists=True)

class Example(Interface):
    input_spec = ExampleInputSpec
    output_spec = ExampleOutputSpec
```

Is there a technical reason why the user has to define the input and output specs as classes, rather than let the user define dictionaries of inputs and output traits and have nipype define the classes internally? i.e.

```python

class Example(Interface):

    input_spec = dict(
        input_volume=File(desc="Input volume", exists=True, mandatory=True),
        parameter=traits.Int(desc="some parameter")
    )

    output_spec = dict(
        output_volume=File(desc = "Output volume", exists = True)
    )
```

**Comment by satra** [comment]
@mwaskom - it's so that we can derive classes and functionality. also the dict formulation won't support all the functionality that is basetraitedspec and traitedspec.

that being said we will revisit this in both our current push to traitlets and with API v2.

**Comment by mwaskom** [comment]
@satra I understand why it's useful to have them in nipype, my question is whether it's possible to let users specify dictionaries of inputs/outputs and have nipype create the TraitedSpec objects and inject the traits internally, to save users from writing unnecessary boilerplate. I've found that given the limitations of the `Function` interface it can be cleaner to define an `Interface` to do one-off things, but it's annoying to have to write three classes.

**Comment by satra** [comment]
@mwaskom - that's a fair point. i think we should rethink the user oriented design of nipype and minimize boilerplate where possible.

**Comment by mwaskom** [comment]
>  i think we should rethink the user oriented design of nipype and minimize boilerplate where possible.

:+1::+1::+1::+1::+1:

**Comment by mwaskom** [comment]
I'll try to take a stab at this. No promises, though.

**Comment by mwaskom** [comment]
See #2083 -- not battle-tested yet, but it was straightforward to implement a proof of principle.
