### ISSUE TITLE
How to wrap C++, R, java, or other scripts with Nipype?

### ISSUE THREAD

**Issue by rattar1989** [nipy/nipype#2101]
### Summary
I only found nipype wrappers for Matlab and Python codes. How is possible to directly wrap scripts written in other programming languages with nipype?

**Comment by effigies** [comment]
If there's a command-line program (usually will be for C++/Java), you can use [`CommandLine`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/base.py#L1622), which should be subclassed with a minimal interface. The basic pattern (also covered in the [developer guide](https://nipype.readthedocs.io/en/latest/devel/interface_specs.html#defining-an-interface-class) is as follows:

```Python
class MyCommandInputSpec(CommandLineInputSpec):
    ...

class MyCommandOutputSpec(TraitedSpec):
    ...

class MyCommand(CommandLine):
    _cmd = ...  # Some command in the PATH
    input_spec =  MyCommandInputSpec
    output_spec = MyCommandOutputSpec
```

For a recent contribution, see #2090. (They subclass from [`AFNICommand`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/afni/base.py#L148), which is just a subclass of `CommandLine` with some additional functionality common to AFNI programs.)

For scripting languages, you can fairly easily make a `CommandLine` subclass (similar to how [MATLAB](https://github.com/nipy/nipype/blob/master/nipype/interfaces/matlab.py) is wrapped). Here is the skeleton of one for `Rscript`:

```Python
class RScriptInputSpec(CommandLineInputSpec):
    script_file = File(exists=True, position=0)

class RScriptOutputSpec(TraitedSpec):
    ...

class RScript(CommandLine):
    _cmd = 'Rscript'
    input_spec = RScriptInputSpec
    output_spec = RScriptOutputSpec
```

You would use this like so:

```Python
>>> rscript = RScript(in_file='path/to/script.R', args='arg1 arg2 arg3')
>>> rscript.cmdline
'Rscript path/to/script.R arg1 arg2 arg3'
```

Without knowing more specifics, it's hard to go much beyond this, but hopefully this gets you moving in the right direction.

Feel free to ask for any help you need as you go.
