### ISSUE TITLE
pe.Node iterables with synchronise=True

### ISSUE THREAD

**Issue by anbai106** [nipy/nipype#2111]
Hi, 
I have a question(or maybe a bug):

I created a Node like this:
`    parallelsubjects = pe.Node(interface=niu.Function(input_names=['bids_directory', 'tsv'], output_names=['bids_ap_dwi', 'bids_ap_dwi_bvec', 'bids_ap_dwi_bval', 'bids_pa_dwi', 'bids_pa_dwi_bvec',
                                            'bids_pa_dwi_bval'], function=get_noddi_intput_fields), name='getNoddiFiles', synchronize=True)`  

   ` parallelsubjects.inputs.tsv = tsv` 
  `  list_tuple = []` 
   `  for i in xrange(len(bids_ap_dwi)):` 
      `      ls = []` 
       `      ls.append(bids_ap_dwi[i])` 
      `      ls.append(bids_ap_dwi_bvec[i])` 
       `     ls.append(bids_ap_dwi_bval[i])` 
       `      ls.append(bids_pa_dwi[i])` 
      `       ls.append(bids_pa_dwi_bvec[i])` 
       `      ls.append(bids_pa_dwi_bval[i])` 
      `        ls = tuple(ls)` 
       `       list_tuple.append(ls)` 
    ` parallelsubjects.iterables = [('bids_ap_dwi', 'bids_ap_dwi_bvec', 'bids_ap_dwi_bval', 'bids_pa_dwi', 'bids_pa_dwi_bvec', 'bids_pa_dwi_bval'),
                                  list_tuple]
`

But this gave me errors: 
`ValueError: The getNoddiFiles iterables is not a [(field, values)] list`

I debug it and the erros came from:
`    for item in iterables:`
        `try:`
          `  if len(item) != 2:`
             `   raise ValueError("The %s iterables is not a [(field, values)]"`
                             `   " list" % node.name)`

in the documentaion of Node, you gave an example for this fonctionality:

>             If this node's synchronize flag is set, then an alternate
            form of the iterables is a [fields, values] list, where
            fields is the list of iterated fields and values is the
            list of value tuples for the given fields, e.g.: ::

                node.synchronize = True
                node.iterables = [('frac', 'threshold'),
                                  [(0.5, True),
                                   (0.6, False)]]

I dont really see where the problem is, cuz the ` [('bids_ap_dwi', 'bids_ap_dwi_bvec', 'bids_ap_dwi_bval', 'bids_pa_dwi', 'bids_pa_dwi_bvec', 'bids_pa_dwi_bval'),
                                  list_tuple]` is exactly a [field, values] list

Can you help me???

Thanks in advance

Hao

**Comment by mgxd** [comment]
Hi Hao,

It looks like you are trying to define a function which outputs `['bids_ap_dwi', 'bids_ap_dwi_bvec', 'bids_ap_dwi_bval', 'bids_pa_dwi', 'bids_pa_dwi_bvec', 'bids_pa_dwi_bval']`, but iterates over these same values. Iterables are calculated at runtime, so this approach isn't currently supported.

Instead, I would recommend grabbing these values outside of a Nipype `Node`/`Workflow`, and then passing them into an `IdentityInterface`, and retrying the synchronize/iterable approach.

**Comment by satra** [comment]
@anbai106 - `iterables` refer to input fields.

**Comment by anbai106** [comment]
@mgxd @satra , thanks for your reply, actually, the reason I use Node.iterables with sychronise=True is to parallelize several subjects to a written workflow which just works for one subject, and I did it before for diffusion pipeline with **IdentityInterface** interface(it works), good to know iterables are calculated at runtime(can you clarify a little more about at runtime?), so basically you mean, we can just use **IdentityInterface** interface, with niu.Function, it dose not work?

**Comment by anbai106** [comment]
@mgxd , @satra I correct this error, actually, I call this function directly and use **IdentityInterface**, it works, but i have a new question about the path to the Workflow's base_dir:

If i set the nipype configuration as default, the pipeline will be dead because the path to each subject's base_dir will be more than 32 characters(http://nipype.readthedocs.io/en/latest/users/config_file.html), so I set:

>         
           from nipype import config
           cfg = dict(execution={'parameterize_dirs': False})
           config.update_config(cfg)

the pipeline works, but it will have a hash for each subject in the base_dir which is not ideal for me.

So my question is:
I create a list working_dir for all the subjects in the base_dir, and can I pass this list by iterables to the **base_dir** of  one-subjects pipeline seperately. Because before I defined it like this: wf.base_dir = working_dir, can I pass this **working_dir** from **Node** to **Workflow** implicitly?

**Comment by mgxd** [comment]
@anbai106 When you define `wf.base_dir`, it will build each `Workflow` step (either a `Node` or another `Workflow`) within that directory - this can get messy if you are overwriting every step to work within the same directory.

An easier way would be to group all of a subject's data inside a `DataSink` - if you already have each subject's ID in the scope of your function, it's as easy as calling
```python
sinker = nio.DataSink()
sinker.inputs.container = subject_id
```

**Comment by anbai106** [comment]
@mgxd yes, you are right, we dont care the identifier of the working directory, the datasink can find the subject if we give the subject_id for each sub-workflow.

Thanks very much, the pipeline works now in parallel.

**Comment by oesteban** [comment]
Seems like solved, but feel free to reopen if I'm wrong.
