### ISSUE TITLE
Old Nipype website 

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#2112]
I very often keep landing on an outdated text-only nipype page when I try to find nipype interface details directly through Google.

E.g. the first hit I get for “nipype slicetimer” is this: http://nipy.org/nipype/interfaces/generated/nipype.interfaces.fsl.preprocess.html

It's a bit confusing, and I believe even more so for people who need to consult the API more often.

**Comment by satra** [comment]
@TheChymera - we would need to remove our older references:

https://github.com/nipy/nipype/tree/gh-pages

i'm ok with doing it since we expect people in general to be using current docs. but there are likely many URLs in places that will break.

@chrisfilo - what do you think?

**Comment by chrisfilo** [comment]
Sounds like a plan - hopefully this will make google update their index.

**Comment by williford** [comment]
It would be nice if there were links to the new docs, especially for the high-profile pages, like fsl.preprocess.

One option would be using the jekyll redirects plugin:
https://help.github.com/articles/redirects-on-github-pages/

**Comment by satra** [comment]
closed by #2188
