### ISSUE TITLE
iterfield in MapNode can't be range (py3)

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2115]
### Summary
In py3 `range` is not a list, and if iterfield in `MapNode` is defined as `range` than entire range is send to the interface at once.  

### Script/Workflow details

```
from nipype import Function, MapNode

def square_func(x):
    print(x, type(x))
    return x ** 2

square = Function(["x"], ["f_x"], square_func)

square_node = MapNode(square, name="square", iterfield=["x"])

square_node.inputs.x = range(4)
res  = square_node.run()
```

### Actual behavior
print statement from `square_func` gives `range(0, 4) <class 'range'>`

### Expected behavior
print statement from `square_func` should give  `0 <class 'int'>`, etc.

**Comment by satra** [comment]
@djarecka - in py3 range is a generator if you do `list(range(4))` it should work fine.

**Comment by djarecka** [comment]
@satra - yes, I know, but my point was that it could be misleading. `MapNode` doesn't give any warnings just sent the entire object to the function. It shouldn't be changed within the `MapNode` class?

**Comment by satra** [comment]
yes, it should result in an exception in this case, since it's not doing the correct thing.
