### ISSUE TITLE
FreeSurferSource doesn't check subjects_dir

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2116]
### Summary
`FreeSurferSource` doesn't check `subjects_dir` is an existing path.

### How to replicate the behavior

```
from nipype.interfaces.io import FreeSurferSource
fs = FreeSurferSource()
fs.inputs.subjects_dir = 'path/to/no/existing/directory'
fs.inputs.subject_id = 'sub-01'
res = fs.run()
```

### Actual behavior
Doesn't give an error.

### Expected behavior
Should check if directory exists (and possibly if there are files for `subject_id` ?).

**Comment by effigies** [comment]
Seems reasonable to add `exists=True` to `subjects_dir`, but I'd think enforcing a valid subject ID would be more trouble than it's worth.
