### ISSUE TITLE
different error message from SPM interaces 

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2120]
### Summary
#1949 introduced `ImageFileSPM` that gives a nice error message, when input file is `nii.gz`, but `Realign` gives still the old error message " the path  '/data/ds000114/sub-03/func/sub-03_task-fingerfootlips_bold.nii.gz' does not exist."

### How to replicate the behavior
Compare these two codes:

```
from nipype.interfaces.spm import Smooth
smooth = Smooth(in_files='/existing/file.nii.gz')
smooth.run()
```

and

```
from nipype.interfaces.spm import Realign
realign = Realign(in_files='/existing/file.nii.gz')
realign.run()
```

### Actual behavior
The first code gives a nice error:
`TraitError: /existing/file.nii.gz is not included in allowed types: .img, .nii, .hdr`
the second gives:
`TraitError: Each element of the 'in_files' trait of a RealignInputSpec instance must be a list of items which are an existing file name or an existing file name, but a value of '/existing/file.nii.gz' <class 'str'> was specified.`

### Expected behavior

Both examples should give the same error.

**Comment by mgxd** [comment]
[`spm.RealignInputSpec.in_files`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/spm/preprocess.py#L122) is using way too many trait calls - it should really just be simplified similar to [`spm.SmoothInputSpec.in_files`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/spm/preprocess.py#L1100)

```
InputMultiPath(ImageFileSPM(exists=True), ...
```
