### ISSUE TITLE
antsApplyTransform does not accept identity transform.  Enhancement request.

### ISSUE THREAD

**Issue by bkraft4257** [nipy/nipype#2126]
### Summary

antsApplyTransforms interface does not accept the transform 'identity' unless it is a file.  This is a deviation from the antsApplyTransforms command line function.  This feature is very helpful when two images are in the same space and one needs to be resampled to the the other. 

It would be nice if AntApplyTransform interface would accept the keyword identity as a transform.

### Actual behavior

The following error message is thrown when 'identity' is used as a transform

traits.trait_errors.TraitError: The trait 'transforms' of an ApplyTransformsInputSpec instance is an existing file name, but the path  'identity' does not exist.

### Expected behavior

When identity is set as the antsApplyTransforms the input file is resampled as the output file. It would be nice if the nipype antsApplyTransform interface would mimic the command line behavior. 

Here is a command line example. 

antsApplyTransforms -d 3 -i input.nii.gz -o output.nii.gz  -r reference.nii.gz  -t identity

The transform identity does not exist but is a keyword that allows the input image to be resampled at the same resolution as the reference image. 

### How to replicate the behavior

Just run the script below. 

### Script/Workflow details

from nipype.interfaces.ants import ApplyTransforms
at = ApplyTransforms()
at.inputs.dimension = 3
at.inputs.transforms = ['identity']

### Platform details:

170725-09:39:41,251 workflow DEBUG:
	 networkx 1.4 dev or higher detected
{'nipype_version': '0.13.1', 'pkg_path': '/Applications/anaconda3/lib/python3.5/site-packages/nipype', 'commit_hash': '<not found>', 'networkx_version': '1.11', 'commit_source': '(none found)', 'numpy_version': '1.11.2', 'traits_version': '4.6.0', 'sys_platform': 'darwin', 'sys_executable': '/Applications/anaconda3/bin/python', 'nibabel_version': '2.1.0', 'sys_version': '3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) \n[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]', 'scipy_version': '0.17.1'}
0.13.1

### Execution environment
- My python environment outside container

**Comment by oesteban** [comment]
@bkraft4257 , is this `'identity'` argument documented somewhere? What is the first version it works?

**Comment by bkraft4257** [comment]
Nick Tustison told me about it when I was trying to resample one image to another image that were already registered.  It is also documented in the function's help (although rather obscurely).   

> antsApplyTransforms 
...
 -t, --transform transformFileName
           [transformFileName,useInverse]
          Several transform options are supported including all those defined in the ITK
          library in addition to a deformation field transform. The ordering of the
          transformations follows the ordering specified on the command line. **An identity
          transform is pushed onto the transformation stack.** Each new transform
          encountered on the command line is also pushed onto the transformation stack.
          Then, to warp the input object, each point comprising the input object is warped
          first according to the last transform pushed onto the stack followed by the
          second to last transform, etc. until the last transform encountered which is the
          identity transform. Also, it should be noted that the inverse transform can be
          accommodated with the usual caveat that such an inverse must be defined by the
          specified transform class
...

If you run the antsApplyTransform command without a transform (i.e. no -t) the identity transform will be applied.  You will receive a warning message but the image will be resampled. 

antsApplyTransforms -d 3 -i input.nii.gz -o output.nii.gz -r reference.nii.gz 

Using double precision for computations.
Input scalar image: input.nii.gz
Reference image: reference.nii.gz
=============================================================================
The composite transform comprises the following transforms (in order):
=============================================================================
**WARNING: No transforms found, using identify transform**
Default pixel value: 0
Interpolation type: LinearInterpolateImageFunction
Output warped image: out.nii.gz

It is a useful trick which I have used for the last 3-4 years.  I know it is supported in the current version 2.2 

As a workaround I just created an identity matrix text file and used it to perform the resampling. If you leave the transform option empty in the nipype the function will fail. 

ValueError: ApplyTransforms requires a value for input 'transforms'. For a list of required inputs, see ApplyTransforms.help()


Thanks for considering this request.  Nipype is a great product and I am truly grateful for all the work that has been put into it.

**Comment by oesteban** [comment]
> As a workaround I just created an identity matrix text file and used it to perform the resampling. If you leave the transform option empty in the nipype the function will fail.
Yes, I use this trick too.

I'm doubtful because this is not well documented (if Nick didn't tell you, I don't think a human being can interpret that functionality from the documentation in any possible way). But I agree this is very useful. @satra WDYT?

**Comment by oesteban** [comment]
Hi @bkraft4257, this is now on nipype/master, please reopen if it doesn't work as intended.

**Comment by kcho** [comment]
Hi, I have a question regarding 'identity' keyword.

I'm trying to add identity matrix transformation on top of other transformations.
And the command below works fine.
`antsApplyTransforms -d 3 -e 3 -i eddy_out.nii.gz \
    -r DTI_nodif.nii.gz \
    -o output.nii.gz \
    -t identity \
    -t Warp.nii.gz \
    -t GenericAffine.mat -v`

However, below does not work
`        at = ApplyTransforms()
        at.inputs.dimension = 3
        at.inputs.input_image_type = 3
        at.inputs.input_image = self.data_eddy_out
        at.inputs.reference_image = self.nodif_loc
        at.inputs.output_image = self.data_unwarpped
        at.inputs.transforms = ['identity', self.t1_to_dti_ants_warp, self.t1_to_dti_ants_mat_out]
        print(at.cmdline)
`



`-------------------------------------------------------------------------
TraitError                              Traceback (most recent call last)
<ipython-input-415-db7c70c0ae4a> in <module>()
      5 # prac.t1_to_dti_registration_c3d()
      6 # prac.ants_unwarping()
----> 7 prac.apply_ants_unwarping()

<ipython-input-414-a0a2c928fa9f> in apply_ants_unwarping(self)
    675         at.inputs.reference_image = self.nodif_loc
    676         at.inputs.output_image = self.data_unwarpped
--> 677         at.inputs.transforms = ['identity', self.t1_to_dti_ants_warp, self.t1_to_dti_ants_mat_out]
    678         print(at.cmdline)

/ccnc_bin/anaconda3/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    170         """
    171         raise TraitError( object, name, self.full_info( object, name, value ),
--> 172                           value )
    173 
    174     def full_info ( self, object, name, value ):

TraitError: The 'transforms' trait of an ApplyTransformsInputSpec instance must be a list of items which are an existing file name or 'identity', but a value of ['identity', '/Volumes/CCNC_4T/psyscan/data/PSYF05004/registration/ants1Warp.nii.gz', '/Volumes/CCNC_4T/psyscan/data/PSYF05004/registration/ants0GenericAffine.mat'] <class 'list'> was specified.`


Could you help with this please?

**Comment by oesteban** [comment]
What is the purpose of concatenating an identity transform at either side of the transform list? I do not think `antsApplyTransforms` would support that either (meaning, this is not a problem introduced by nipype)

**Comment by kcho** [comment]
hi @oesteban,
Thank you for the swift response. 
I've added `identity` at the end of transforms list to downsample the images. 
As I stated above, adding `identity` to the commandline `antsApplyTrnasforms` works just fine. Maybe I have to separate downsampling to another `antsApplyTrnasforms` if I want to use nipype ?

**Comment by satra** [comment]
@kcho - can you try out this branch? 

https://github.com/nipy/nipype/tree/fix/identity-transform

the trait was not appropriate for a list of transforms that includes identity.

```python
In [2]: at = ApplyTransforms()
In [6]: at.inputs.dimension = 3
In [7]: at.inputs.input_image_type = 3
In [8]: at.inputs.input_image = 't.nii'
In [9]: at.inputs.reference_image = 't.nii'
In [10]: at.inputs.output_image = 'foo.nii'
In [11]: at.inputs.transforms = ['t.nii', 'identity']
In [12]: print(at.cmdline)
antsApplyTransforms --default-value 0 --dimensionality 3 --float 0 --input t.nii --input-image-type 3 --interpolation Linear --output foo.nii --reference-image t.nii --transform t.nii --transform identity
```

**Comment by kcho** [comment]
@satra Thank you it's working now! Thank you so much

**Comment by oesteban** [comment]
The `identity` at the end should not make any difference, what do you get when you remove it (using `antsApplyTransforms` directly)?

The downsampling should happen anyways if you set the correct reference image.

**Comment by satra** [comment]
@oesteban - do you know if you set a reference image which is the same one used for registration, but was then resampled? i.e. the registration was computed for a higher-resolution image, but the target for antsApplyTransforms is a coarser resolution. i would think the identity transfer would help address that situation.

**Comment by oesteban** [comment]
`antsApplyTransforms` uses ITK transforms which happen in physical coordinates.

So the resampled image is evaluated at every point in the grid of the reference image. But, to compute the corresponding coordinates in the moving space, the first step is converting the index coordinates into physical coordinates.

Then the first step you apply is the identity. It basically does nothing.

**Comment by oesteban** [comment]
(I think we do not add any identity in FMRPREP and definitely change resolutions at many places)

**Comment by kcho** [comment]
@oesteban you're right. Taking the `identity` option still downsamples the images!! Thank you for letting me know this. @satra Yes, that's exactly what I wanted to do, but just found out that it still works without `identity` option ! Thanks anyway!!

**Comment by satra** [comment]
thanks @oesteban and @kcho - i will close the PR.
