### ISSUE TITLE
datasink with MapNode without creating subfolder does not work

### ISSUE THREAD

**Issue by anbai106** [nipy/nipype#2146]
Hi, nipype experts:

I have a problem when using datasink in MapNode, like this:

>   # get the information for datasinker.
    get_identifiers = pe.MapNode(niu.Function(
        input_names=['subject_id', 'caps_directory'], output_names=['base_directory', 'subst_tuple_list'],
        function=get_subid_sesid_t1_to_b0), name='get_subid_sesid_t1_2_b0', iterfield=['subject_id'])
    get_identifiers.inputs.caps_directory = caps_directory

  

>  ### datasink
>    datasink = pe.MapNode(nio.DataSink(), name='datasinker', iterfield=['base_directory', 'substitutions'])

Connecting the pipeline like this:
 

>     (inputnode,        get_identifiers, [('subject_id_list', 'subject_id')]),
>         (get_identifiers, datasink, [('base_directory', 'base_directory')]),
>         (get_identifiers, datasink, [('subst_tuple_list', 'substitutions')]),
>         (registration_t1_to_b0,        datasink, [('out_file', 't12b0.@out_registered_t1')]),
>         (registration_t1_to_b0,        datasink, [('out_matrix_file', 't12b0.@out_flirt_matrix')]),
>         (apply_flirt_registration,     datasink, [('out_file', 't12b0.@out_wm_mask_in_diffusion_mask')]),
>         (convert_flirt_to_mrtrix,      datasink, [('out_mrtrix_matrix', 't12b0.@out_mrtrix_matrix')]),
>         (desikan_in_diffusion_space,   datasink, [('out_deformed_image', 't12b0.@out_desikan_in_diffusion_space')]),
>         (destrieux_in_diffusion_space, datasink, [('out_deformed_image', 't12b0.@out_destrieux_in_diffusion_space')])

**.@** this will not create the subfolder like in my mapflow, but it did create this subfolder, any suggestions???

Thanks in advance

Hao

**Comment by anbai106** [comment]
Here is more details:

> _outputs : {'t12b0.@out_mrtrix_matrix': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/convert_flirt_to_mrtrix/mapflow/**_convert_flirt_to_mrtrix0**/mrtrix_matrix.mat'], 't12b0.@out_wm_mask_in_diffusion_mask': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/apply_flirt_registration/mapflow/_apply_flirt_registration0/sub-PREVDEMALS0010001BE_ses-M0_tissue-whitematter_binaryMask_flirt.nii.gz'], 't12b0.@out_desikan_in_diffusion_space': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/desikan_in_diffusion_space/mapflow/_desikan_in_diffusion_space0/desikan_deformed_image.nii.gz'], 't12b0.@out_flirt_matrix': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/registration_t1_to_b0/mapflow/_registration_t1_to_b00/sub-PREVDEMALS0010001BE_ses-M0_brainExtractedT1w_flirt.mat'], 't12b0.@out_registered_t1': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/registration_t1_to_b0/mapflow/_registration_t1_to_b00/sub-PREVDEMALS0010001BE_ses-M0_brainExtractedT1w_flirt.nii.gz'], 't12b0.@out_destrieux_in_diffusion_space': ['/Users/junhao.wen/test/NODDI/working_dir/noddi_postprocessing_pipeline/t1_b0_registration_pipeline/destrieux_in_diffusion_space/mapflow/_destrieux_in_diffusion_space0/destrieux_deformed_image.nii.gz']}

I think the problem is that under base_dir of datasink, it also creates subfolder **_convert_flirt_to_mrtrix0**  in the datasink container, that is not what I want

**Comment by anbai106** [comment]
Thought the solution, use:

> regexp_substitutions

**Comment by oesteban** [comment]
@anbai106 could you close the issue if that fixed your problem? Thanks and well done!
