### ISSUE TITLE
Node - Function issue

### ISSUE THREAD

**Issue by acamargofb** [nipy/nipype#2158]
I am trying to run a function inside a node.  I created the function and the node, and I am getting this error message:

Functions in connection strings have to be standalone.
They cannot be declared either interactively or inside
another function or inline in the connect string. Any
imports should be done inside the function
Interface Function failed to run. 

Do you know what is the meaning ?

Thanks a lot,

Aldo

**Comment by acamargofb** [comment]
I solve the problem,  I did so many things: 1) I used import like this:

imports = ['from lib.fileIO import load',
           'import numpy as np',
           'from lib.pcorrcoef_loop import pcorrcoef_loop'
]


and also, I deleted the print statement,

Now the code works :)

Aldo

**Comment by djarecka** [comment]
Hi Aldo, yes I just want to confirm that all imports have to be done within a function if you want to use it within a `Function` interface.
