### ISSUE TITLE
ENH: Give debugging hints in log files on crashes

### ISSUE THREAD

**Issue by williford** [nipy/nipype#2161]
Currently, the error logs say:

    Saving crash info to /path/name.pklz

I propose that the following be added:

    Saving crash info to /path/to/crash.pklz
    Run the following command to view: 
        nipypecli crash /path/to/crash.pklz

Discussion welcome. This is something I (or anyone else) could easily create a PR for, so this issue is mainly for discussion.

**Comment by mwaskom** [comment]
Maybe just print that hint once at the end of workflow execution when there were failures, instead of for every crashdump that gets saved (there are often cascading failures and so having 2 more lines in lots of places would decrease SNR in terms of figuring out what went wrong.
