### ISSUE TITLE
Multiple interface binaries handling

### ISSUE THREAD

**Issue by sulantha2006** [nipy/nipype#2175]
### Summary
How to handline multiple binaries installed in the system. Say if I have mulitple versions of ANTS installed in the system (2.1 and 2.2 in /opt/ants-2.1 and /opt/ants-2.2) and nipype just uses the one which is the first in $PATH variable. 
### Actual behavior
nipype just uses the one which is the first in $PATH variable. 
### Expected behavior
User should be able to specify the binary location in the command interface

Is this already implemented?

**Comment by satra** [comment]
@sulantha2006 - one can handle this by setting the environment variable with the appropriate path for a given interface/node. you don't have to have it be set by default in the system path although that's how most people run nipype workflows.

**Comment by mgxd** [comment]
@sulantha2006 feel free to reopen if needed
