### ISSUE TITLE
Modelgen SpecifyModel TypeError: apply_along_axis()

### ISSUE THREAD

**Issue by cni-md** [nipy/nipype#2181]
@effigies 
SpecifyModel rises an error with the new function from
commit cd49748be5d7a8201496548922d85f63bb4034dc

modelgen.py line 399ff

With numpy 1.8.2 I get
TypeError: apply_along_axis() got an unexpected keyword argument 'source'
Interface SpecifyModel failed to run

Joerg

**Comment by cni-md** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.apply_along_axis.html
kwargs : any
    Additional named arguments to func1d.
    New in version 1.9.0.

nipype require  numpy >= 1.6.2

**Comment by effigies** [comment]
I see. Thanks for finding this. I'll submit a PR to update the minimum numpy version.
