### ISSUE TITLE
How to use the nipype.interfaces.slicer.filtering.n4itkbiasfieldcorrection

### ISSUE THREAD

**Issue by Thatfreesky** [nipy/nipype#2183]
### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by oesteban** [comment]
I bet you want [`nipype.interfaces.ants.segmentation.N4BiasFieldCorrection`](http://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.ants/segmentation.html#n4biasfieldcorrection) - examples on the link. Please feel free to reopen if that didn't help or you have more specific questions.
