### ISSUE TITLE
ANTS interface: incorrect parameter passing in WarpTimeSeriesImageMultiTransform

### ISSUE THREAD

**Issue by piloubazin** [nipy/nipype#2192]
### Summary
when using WarpTimeSeriesImageMultiTransform.inputs.invert_affine = [1], the parameter passed to the corresponding ANTS command is ['-i'], and should instead be '-i' (as in WarpImageMutiTransfrom) in resampling.py

### Actual behavior
The command fails to run or to write with .cmdline
(TypeError: sequence item 0: expected string or Unicode, list found)

### Expected behavior
In [8]: wimt.cmdline
Out[8]: u'WarpTimeSeriesImageMultiTransform 4 my_fixed_time_series.nii.gz my_fixed_time_series_warped.nii.gz -R my_moving_image.nii.gz -i synAffine.txt synInverseWarp.nii.gz'

### How to replicate the behavior
just run WarpTimeSeriesImageMultiTransform with .inputs.invert_affine = [1]

### Script/Workflow details
l.89:                         series += ['-i'], -> series += '-i',

### Platform details:

{'nibabel_version': '2.1.0', 'sys_executable': '/usr/bin/python', 'networkx_version': '1.11', 'numpy_version': '1.11.1rc1', 'sys_platform': 'linux2', 'sys_version': '2.7.12+ (default, Sep 17 2016, 12:08:02) \n[GCC 6.2.0 20160914]', 'commit_source': u'repository', 'commit_hash': '3f8c8b1', 'pkg_path': '/mnt/drive/pilou/Code/github/src/nipype/nipype', 'nipype_version': u'1.0.0-dev+g3f8c8b1', 'traits_version': '4.6.0', 'scipy_version': '0.17.1'}
1.0.0-dev+g3f8c8b1

### Execution environment

Choose one
My python environment outside container

**Comment by djarecka** [comment]
Hi, thanks for reporting. I'm reading the code and I believe that changing `['-i']` to `-i` in [line 89](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/resampling.py#L89) shouldn't help, since [line 91](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/resampling.py#L89) would add a space between `-` and `i`. 

I might be wrong, never run this interface. Would you mind sharing the code for `wimt` so I can test it? The simplest examples I run didn't give me an error. 

What exactly do you get when you ask for `wimt.cmdline`?

**Comment by djarecka** [comment]
@chrisfilo : having problem with repeating the error, but wanted to ask if you really wanted to have `series += '-i'` (not `series += ['-i']`) in `WarpImageMultiTransform`, see [198](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/resampling.py#L198)

**Comment by chrisfilo** [comment]
I'm not 100% sure, but `series += ['-i']` does seem to make more sense.

**Comment by djarecka** [comment]
I was wrong. I missed the comma at the end, so python treats it as adding a list, I unified it in #2229. 

The reason why I didn't get any error earlier was that I provided wrong (i.e. out of range) index in `invert_affine` (see [test_WarpImageMultiTransform_invaffine_wrong](https://github.com/nipy/nipype/pull/2229/files#diff-38bf3bab86a173e2df23c603904727adR55) and [test_WarpTimeSeriesImageMultiTransform_invaffine_wrong](https://github.com/nipy/nipype/pull/2229/files#diff-38bf3bab86a173e2df23c603904727adR86))
