### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by mwaskom** [nipy/nipype#2194]
It looks like the travis build is failing on master: https://travis-ci.org/nipy/nipype/branches |  https://travis-ci.org/nipy/nipype/builds/274426849

And indeed my tests that depend on nipype master recently started failing too: https://travis-ci.org/mwaskom/lyman/builds/278793733

**Comment by effigies** [comment]
#2171 should be addressing this.

**Comment by mwaskom** [comment]
Got it. Seemed like a recent failure and didn't see a new PR/issue about it but didn't hunt around too deeply.

Feel free to close if you feel this is redundant with #2159 (or keep open if you think master failing deserves a more urgent issue).

**Comment by mwaskom** [comment]
Perhaps as a stopgap measure nipype could pin to a compatible version of networkx?

**Comment by effigies** [comment]
Proposed #2195. If that tests clean before #2171 issues are resolved, I think that's a good stopgap.
