### ISSUE TITLE
AFNI Qwarp output paths are incorrect

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#2221]
### Summary
output paths are not correct: current directory is always used as parent directory and `+tlrc` is appended even to nifti outputs

### How to replicate the behavior
``` Python
from nipype.interfaces import afni
a = afni.Qwarp()
a.inputs.in_file = '/tmp/in_file.nii.gz'
a.inputs.base_file = '/tmp/base_file.nii.gz'
a.inputs.out_file = '/tmp/warped.nii.gz'
res = a.run()
print(res.outputs.warped_source)
```
prints a wrong path
``` Python
In [20]:  /home/salma/CODE/nipype/warped14+tlrc.nii.gz
```

**Comment by oesteban** [comment]
Please note that the input spec for `out_file` defines both `name_source` and `genfile`. That needs be fixed. Attached comment on your PR. Thanks for spotting this.

**Comment by salma1601** [comment]
I am not sure I understand correctly but I removed the `genfile` from here https://github.com/nipy/nipype/blob/master/nipype/interfaces/afni/preprocess.py#L2883 and still have the same issue

**Comment by oesteban** [comment]
Hi @salma1601, `name_source` and `genfile` are two metadata you can use on input `File` traits to automatically generate names of outpute.

  - `genfile` is a legacy method. You set it `True` in the `File` metadata (meaning `name = File(genfile=True)`) and then, your interface must define a `_gen_filename()` method (the name may not be exact, I don't recall on top of my head).

  - `name_source` is the currently advised method. It requires you to define up to 3 metadata bits like so: `some_input = File(name_source=['other_input'], name_template='%s_suffix', output_name='some_output')`. This bit of code is saying *if `some_input` is not set, then create a new name reading the base name of the file in `other_input` format it through `name_template`, and use that new name to set the output `some_output`*. Default values for `name_template` and `output_name` are `%s_generated` and the input name (`some_input` in this case).

Therefore, `genfile` and `name_source` are mutually exclusive and should not be used together. I'll have a look to see why this is not working in your PR.

**Comment by oesteban** [comment]
Hi again, sorry, I can't see where you are trying removing `genfile`. Could you point me to this?

**Comment by salma1601** [comment]
I just removed the line `genfile=True`
```Python
out_file = File(argstr='-prefix %s',
                    name_template='%s_QW',
                    name_source=['in_file'],
                    genfile=True,
                    desc='out_file ppp'
'Sets the prefix for the output datasets.'
```
but this doesn't solve the issue.

**Comment by salma1601** [comment]
```Python
In [2]: a.cmdline
Out[2]: u'3dQwarp -base /tmp/base_file.nii.gz -source /tmp/in_file.nii.gz -prefix /tmp/warped.nii.gz'

In [3]: res.outputs
Out[3]: 

base_warp = <undefined>
source_warp = /home/salma/CODE/nipype/warped_WARP+tlrc.nii.gz
warped_base = <undefined>
warped_source = /home/salma/CODE/nipype/warped+tlrc.nii.gz
weights = <undefined>
```
what is wrong is that 
1) it is appending `+tlrc` to the filename 
2) it is using the current directory as a parent directory instead of the directory given in the command (\tmp)
so all the paths in the outputs do not exist
