### ISSUE TITLE
New terminal/log output is grammatically incorrect

### ISSUE THREAD

**Issue by mwaskom** [nipy/nipype#2250]
### Summary

I just pulled github master and see that there's some new, more informative, node-level terminal output. However, it doesn't fully account for the subtleties of English:

### Actual behavior

e.g. `Running node "crop_image" (a "ApplyMask" interface)`

### Expected behavior

e.g. `Running node "crop_image" (an "ApplyMask" interface)`

**Comment by satra** [comment]
perhaps we can be more programmatic and say: 

` Running node "crop_image" (interface nipype.interfaces.fsl.ApplyMask)`

this way we take out redundant interface names as well.

**Comment by satra** [comment]
or simply:

`Running node "crop_image" (nipype.interfaces.fsl.ApplyMask)`

**Comment by mwaskom** [comment]
I think that would be fine.
