### ISSUE TITLE
Issue with node name that starts with another node's name

### ISSUE THREAD

**Issue by williford** [nipy/nipype#2257]
I think the [line ~801 in util.py](https://github.com/nipy/nipype/edit/master/nipype/pipeline/engine/utils.py#L801) should be something like this:

            for node in graph_in.nodes():
                for src_id, edge_data in list(old_edge_dict.items()):
                    if node.itername.startswith(src_id + '.'):  # <-- add '.' to src_id
                        expansions[src_id].append(node)

For example, if the node "input" feeds into "input_files", the "input_files" can be included if you just test for node.itername.startswith(src_id). This change would prevent "input_files" from being included. 

Edit: removed last part of my comment.

**Comment by satra** [comment]
@williford - could you give us a brief example of workflow where this fails? the intent of having the period (`.`) was to prevent partial matches and workflows cannot have two nodes with the same name.

**Comment by williford** [comment]
@satra The ` + '.'` is what I'm suggesting to add, it currently isn't in the code. I'm saying that it should be added to prevent partial matches. Sorry for the confusion, I removed the second block of code in my first post.

The current version of code fails when "input" feeds into "input_files" and "input_files" is a JoinNode. Adding the period should fix that. I wasn't sure about posting a PR because I wasn't sure if adding a period would break anything else.

**Comment by satra** [comment]
thanks @williford - would you be able to give us a dummy example where this breaks? even editing this workflow as necessary would be sufficient: 

https://miykael.github.io/nipype_tutorial/notebooks/introduction_quickstart.html

i'm recollecting that @mgxd and i went over a PR to address this not too long back, so i just want to make sure we have a test addressing this scenario first before making any changes.

**Comment by effigies** [comment]
I was able to reproduce this:

```Python
from nipype import Workflow, Node, JoinNode
from nipype.interfaces.utility import Merge, Function


def sq(x):
    return x ** 2


wf = Workflow('wf')

square = Node(Function(function=sq), name='square')
square.iterables = ('x', [1, 2])

square_join = JoinNode(Merge(1, ravel_inputs=True),
                       name='square_join',
                       joinsource=square,
                       joinfield=['in1'])

wf.connect(square, 'out', square_join, "in1")

wf.run()
```

**Comment by williford** [comment]
Thanks @effigies! - and sorry I didn't get around to making the dummy example.
