### ISSUE TITLE
testing the install: base.py:1600: RuntimeError and others

### ISSUE THREAD

**Issue by cclairec** [nipy/nipype#2258]
### Summary
Hi nipype comunity!

I need your help! :) 
I followed the instructions on the developer webpage, meaning I did:
```
pip install -r requirements.txt
sudo python setup.py develop
```

So now I am testing the install (`sudo make tests`), and I have the following message at the end:
```
> ================================= 6 failed, 2587 passed, 225 skipped, 7 xfailed, 12 warnings in 106.69 seconds ==================================
> make: *** [Makefile:60: test-code] Error 1


The errors are:

> ============================================================== FAILURES ===============================================================
> _______________________________________________ [doctest] nipype.interfaces.bids_utils ________________________________________________
> 005 available interfaces are:
> 006 
> 007 BIDSDataGrabber: Query data from BIDS dataset using pybids grabbids.
> 008 
> 009 Change directory to provide relative paths for doctests
> 010 >>> import os
> 011 >>> import bids
> 012 >>> filepath = os.path.realpath(os.path.dirname(bids.__file__))
> 013 >>> datadir = os.path.realpath(os.path.join(filepath, 'grabbids/tests/data/'))
> 014 >>> os.chdir(datadir)
> UNEXPECTED EXCEPTION: OSError(2, 'No such file or directory')
> Traceback (most recent call last):
> 
>   File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
>     compileflags, 1) in test.globs
> 
>   File "<doctest nipype.interfaces.bids_utils[4]>", line 1, in <module>
> 
> OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/bids/grabbids/tests/data'
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/bids_utils.py:14: UnexpectedException
> _______________________________________ [doctest] nipype.interfaces.bids_utils.BIDSDataGrabber ________________________________________
> 058 
> 059     >>> from nipype.interfaces.bids_utils import BIDSDataGrabber
> 060     >>> from os.path import basename
> 061 
> 062     By default, the BIDSDataGrabber fetches anatomical and functional images
> 063     from a project, and makes BIDS entities (e.g. subject) available for
> 064     filtering outputs.
> 065 
> 066     >>> bg = BIDSDataGrabber()
> 067     >>> bg.inputs.base_dir = 'ds005/'
> UNEXPECTED EXCEPTION: TraitError(u"The trait 'base_dir' of a BIDSDataGrabberInputSpec instance is an existing directory name, but the path  'ds005/' does not exist.",)
> Traceback (most recent call last):
> 
>   File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
>     compileflags, 1) in test.globs
> 
>   File "<doctest nipype.interfaces.bids_utils.BIDSDataGrabber[3]>", line 1, in <module>
> 
>   File "/home/ccury/Codes/NipypeVisages/nipype/interfaces/traits_extension.py", line 187, in validate
>     class_of(object), self.info_text, value))
> 
> TraitError: The trait 'base_dir' of a BIDSDataGrabberInputSpec instance is an existing directory name, but the path  'ds005/' does not exist.
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/bids_utils.py:67: UnexpectedException
> ____________________________________________________ test_cmdline_profiling[0.5-3] ____________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-4/test_cmdline_profiling_0_5_3_0'), mem_gb = 0.5, n_procs = 3
> 
>     @pytest.mark.skipif(os.getenv('CI_SKIP_TEST', False), reason='disabled in CI tests')
>     @pytest.mark.parametrize("mem_gb,n_procs", [(0.5, 3), (2.2, 8), (0.8, 4), (1.5, 1)])
>     def test_cmdline_profiling(tmpdir, mem_gb, n_procs):
>         """
>         Test runtime profiler correctly records workflow RAM/CPUs consumption
>         of a CommandLine-derived interface
>         """
>         from nipype import config
>         config.set('execution', 'resource_monitor_frequency', '0.2')  # Force sampling fast
>     
>         tmpdir.chdir()
>         iface = UseResources(mem_gb=mem_gb, n_procs=n_procs)
> >       result = iface.run()
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/tests/test_resource_monitor.py:60: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1088: in run
>     runtime = self._run_interface(runtime)
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1654: in _run_interface
>     self.raise_exception(runtime)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <nipype.interfaces.tests.test_resource_monitor.UseResources object at 0x7f04a1dca710>
> runtime = Bunch(cmdline=u'/home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resourc...e RuntimeError occurred while running interface UseResources.',), version=None)
> 
>     def raise_exception(self, runtime):
>         raise RuntimeError(
>             ('Command:\n{cmdline}\nStandard output:\n{stdout}\n'
>              'Standard error:\n{stderr}\nReturn code: {returncode}').format(
> >                **runtime.dictcopy()))
> E       RuntimeError: Command:
> E       /home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resources -g 0.500000 -p 3
> E       Standard output:
> E       
> E       Standard error:
> E       
> E       Return code: 1
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1600: RuntimeError
> ____________________________________________________ test_cmdline_profiling[2.2-8] ____________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-4/test_cmdline_profiling_2_2_8_0'), mem_gb = 2.2, n_procs = 8
> 
>     @pytest.mark.skipif(os.getenv('CI_SKIP_TEST', False), reason='disabled in CI tests')
>     @pytest.mark.parametrize("mem_gb,n_procs", [(0.5, 3), (2.2, 8), (0.8, 4), (1.5, 1)])
>     def test_cmdline_profiling(tmpdir, mem_gb, n_procs):
>         """
>         Test runtime profiler correctly records workflow RAM/CPUs consumption
>         of a CommandLine-derived interface
>         """
>         from nipype import config
>         config.set('execution', 'resource_monitor_frequency', '0.2')  # Force sampling fast
>     
>         tmpdir.chdir()
>         iface = UseResources(mem_gb=mem_gb, n_procs=n_procs)
> >       result = iface.run()
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/tests/test_resource_monitor.py:60: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1088: in run
>     runtime = self._run_interface(runtime)
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1654: in _run_interface
>     self.raise_exception(runtime)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <nipype.interfaces.tests.test_resource_monitor.UseResources object at 0x7f04a33d4f90>
> runtime = Bunch(cmdline=u'/home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resourc...e RuntimeError occurred while running interface UseResources.',), version=None)
> 
>     def raise_exception(self, runtime):
>         raise RuntimeError(
>             ('Command:\n{cmdline}\nStandard output:\n{stdout}\n'
>              'Standard error:\n{stderr}\nReturn code: {returncode}').format(
> >                **runtime.dictcopy()))
> E       RuntimeError: Command:
> E       /home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resources -g 2.200000 -p 8
> E       Standard output:
> E       
> E       Standard error:
> E       
> E       Return code: 1
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1600: RuntimeError
> ____________________________________________________ test_cmdline_profiling[0.8-4] ____________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-4/test_cmdline_profiling_0_8_4_0'), mem_gb = 0.8, n_procs = 4
> 
>     @pytest.mark.skipif(os.getenv('CI_SKIP_TEST', False), reason='disabled in CI tests')
>     @pytest.mark.parametrize("mem_gb,n_procs", [(0.5, 3), (2.2, 8), (0.8, 4), (1.5, 1)])
>     def test_cmdline_profiling(tmpdir, mem_gb, n_procs):
>         """
>         Test runtime profiler correctly records workflow RAM/CPUs consumption
>         of a CommandLine-derived interface
>         """
>         from nipype import config
>         config.set('execution', 'resource_monitor_frequency', '0.2')  # Force sampling fast
>     
>         tmpdir.chdir()
>         iface = UseResources(mem_gb=mem_gb, n_procs=n_procs)
> >       result = iface.run()
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/tests/test_resource_monitor.py:60: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1088: in run
>     runtime = self._run_interface(runtime)
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1654: in _run_interface
>     self.raise_exception(runtime)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <nipype.interfaces.tests.test_resource_monitor.UseResources object at 0x7f04a1d98410>
> runtime = Bunch(cmdline=u'/home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resourc...e RuntimeError occurred while running interface UseResources.',), version=None)
> 
>     def raise_exception(self, runtime):
>         raise RuntimeError(
>             ('Command:\n{cmdline}\nStandard output:\n{stdout}\n'
>              'Standard error:\n{stderr}\nReturn code: {returncode}').format(
> >                **runtime.dictcopy()))
> E       RuntimeError: Command:
> E       /home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resources -g 0.800000 -p 4
> E       Standard output:
> E       
> E       Standard error:
> E       
> E       Return code: 1
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1600: RuntimeError
> ____________________________________________________ test_cmdline_profiling[1.5-1] ____________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-4/test_cmdline_profiling_1_5_1_0'), mem_gb = 1.5, n_procs = 1
> 
>     @pytest.mark.skipif(os.getenv('CI_SKIP_TEST', False), reason='disabled in CI tests')
>     @pytest.mark.parametrize("mem_gb,n_procs", [(0.5, 3), (2.2, 8), (0.8, 4), (1.5, 1)])
>     def test_cmdline_profiling(tmpdir, mem_gb, n_procs):
>         """
>         Test runtime profiler correctly records workflow RAM/CPUs consumption
>         of a CommandLine-derived interface
>         """
>         from nipype import config
>         config.set('execution', 'resource_monitor_frequency', '0.2')  # Force sampling fast
>     
>         tmpdir.chdir()
>         iface = UseResources(mem_gb=mem_gb, n_procs=n_procs)
> >       result = iface.run()
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/tests/test_resource_monitor.py:60: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1088: in run
>     runtime = self._run_interface(runtime)
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1654: in _run_interface
>     self.raise_exception(runtime)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <nipype.interfaces.tests.test_resource_monitor.UseResources object at 0x7f0505b94710>
> runtime = Bunch(cmdline=u'/home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resourc...e RuntimeError occurred while running interface UseResources.',), version=None)
> 
>     def raise_exception(self, runtime):
>         raise RuntimeError(
>             ('Command:\n{cmdline}\nStandard output:\n{stdout}\n'
>              'Standard error:\n{stderr}\nReturn code: {returncode}').format(
> >                **runtime.dictcopy()))
> E       RuntimeError: Command:
> E       /home/ccury/Codes/NipypeVisages/nipype/utils/tests/use_resources -g 1.500000 -p 1
> E       Standard output:
> E       
> E       Standard error:
> E       
> E       Return code: 1
> 
> /home/ccury/Codes/NipypeVisages/nipype/interfaces/base.py:1600: RuntimeError
> 
```
The code I use is from the 25th of october: https://github.com/cclairec/NipypeVisages.git
### Platform details:
I am using Fedora.

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

> NipypeVisages$ python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"
> fatal: No names found, cannot describe anything.
> {'nibabel_version': '2.2.0', 'sys_executable': '/usr/bin/python', 'networkx_version': '2.0', 'numpy_version': '1.12.1', 'sys_platform': 'linux2', 'sys_version': '2.7.13 (default, Sep  5 2017, 08:53:59) \n[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]', 'commit_source': u'repository', 'commit_hash': 'b61ad7b', 'pkg_path': 'nipype', 'nipype_version': u'1.0.0-dev', 'traits_version': '4.6.0', 'scipy_version': '0.19.1'}
> 1.0.0-dev

### Execution environment
I use Fedora 26:
64 bit
Intel® Core™ i7-3540M CPU @ 3.00GHz × 4 

Let me know if you need more informations ! 

Many thanks in advance for your time and help.

Cheers,
Claire.

**Comment by satra** [comment]
ah this is being fixed right now #2248

**Comment by satra** [comment]
this should not happen with current master. please reopen if necessary.

**Comment by cclairec** [comment]
Hi,

I have updated the master, but I still have some troubles with the tests. I only have 4 failures now, that's the good news.

Here they are:

> 
> ============================================================== FAILURES ==============================================================
> __________________________________________________________ test_provenance ___________________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-6/test_provenance0')
> 
>     def test_provenance(tmpdir):
>         out_dir = str(tmpdir)
>         metawf = pe.Workflow(name='meta')
>         metawf.base_dir = out_dir
>         metawf.add_nodes([create_wf('wf%d' % i) for i in range(1)])
>         eg = metawf.run(plugin='Linear')
>         prov_base = os.path.join(out_dir,
>                                  'workflow_provenance_test')
> >       psg = write_workflow_prov(eg, prov_base, format='all')
> 
> /home/ccury/Codes/NipypeVisages/nipype/pipeline/engine/tests/test_utils.py:337: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /home/ccury/Codes/NipypeVisages/nipype/pipeline/engine/utils.py:1280: in write_workflow_prov
>     prov_doc = ProvStore().add_results(result)
> /home/ccury/Codes/NipypeVisages/nipype/utils/provenance.py:427: in add_results
>     for key, value in list(get_info().items()):
> /home/ccury/Codes/NipypeVisages/nipype/__init__.py:47: in get_info
>     return _get_pkg_info(os.path.dirname(__file__))
> /home/ccury/Codes/NipypeVisages/nipype/pkg_info.py:88: in get_pkg_info
>     src, hsh = pkg_commit_hash(pkg_path)
> /home/ccury/Codes/NipypeVisages/nipype/pkg_info.py:56: in pkg_commit_hash
>     archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:811: in get
>     d)
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:384: in before_get
>     self._interpolate_some(parser, option, L, value, section, defaults, 1)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <backports.configparser.BasicInterpolation object at 0x7fe1d4024b50>
> parser = <backports.configparser.ConfigParser object at 0x7fe16f9e1890>, option = 'archive_subst_hash', accum = [], rest = '%h'
> section = 'commit hash', map = _ChainMap({}, OrderedDict([(u'archive_subst_hash', u'%h'), (u'install_hash', u'')]), OrderedDict())
> depth = 1
> 
>     def _interpolate_some(self, parser, option, accum, rest, section, map,
>                           depth):
>         rawval = parser.get(section, option, raw=True, fallback=rest)
>         if depth > MAX_INTERPOLATION_DEPTH:
>             raise InterpolationDepthError(option, section, rawval)
>         while rest:
>             p = rest.find("%")
>             if p < 0:
>                 accum.append(rest)
>                 return
>             if p > 0:
>                 accum.append(rest[:p])
>                 rest = rest[p:]
>             # p is no longer used
>             c = rest[1:2]
>             if c == "%":
>                 accum.append("%")
>                 rest = rest[2:]
>             elif c == "(":
>                 m = self._KEYCRE.match(rest)
>                 if m is None:
>                     raise InterpolationSyntaxError(option, section,
>                         "bad interpolation variable reference %r" % rest)
>                 var = parser.optionxform(m.group(1))
>                 rest = rest[m.end():]
>                 try:
>                     v = map[var]
>                 except KeyError:
>                     raise from_none(InterpolationMissingOptionError(
>                         option, section, rawval, var))
>                 if "%" in v:
>                     self._interpolate_some(parser, option, accum, v,
>                                            section, map, depth + 1)
>                 else:
>                     accum.append(v)
>             else:
>                 raise InterpolationSyntaxError(
>                     option, section,
>                     "'%%' must be followed by '%%' or '(', "
> >                   "found: %r" % (rest,))
> E               InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
> 
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:434: InterpolationSyntaxError
> -------------------------------------------------------- Captured stdout call --------------------------------------------------------
> 171029-20:08:39,838 workflow INFO:
> 	 Workflow meta settings: ['check', 'execution', 'logging']
> 171029-20:08:39,842 workflow INFO:
> 	 Running serially.
> 171029-20:08:39,842 workflow INFO:
> 	 Executing node meta.wf0.proc in dir: /tmp/pytest-of-ccury/pytest-6/test_provenance0/meta/wf0/_fwhm_0/proc
> 171029-20:08:39,846 workflow INFO:
> 	 Running node "proc" ("nipype.interfaces.utility.wrappers.Function").
> 171029-20:08:39,852 workflow INFO:
> 	 Executing node meta.wf0.proc2 in dir: /tmp/pytest-of-ccury/pytest-6/test_provenance0/meta/wf0/_fwhm_0/_fwhm_0/proc2
> 171029-20:08:39,855 workflow INFO:
> 	 Running node "proc2" ("nipype.interfaces.utility.wrappers.Function").
> __________________________________________________________ test_nipype_info __________________________________________________________
> 
>     def test_nipype_info():
>         exception_not_raised = True
>         try:
>             get_info()
>         except Exception as e:
>             exception_not_raised = False
> >       assert exception_not_raised
> E       assert False
> 
> /home/ccury/Codes/NipypeVisages/nipype/tests/test_nipype.py:9: AssertionError
> __________________________________________________________ test_provenance ___________________________________________________________
> 
>     def test_provenance():
>         ps = ProvStore()
>         from nipype.interfaces.base import CommandLine
>         results = CommandLine('echo hello').run()
> >       ps.add_results(results)
> 
> /home/ccury/Codes/NipypeVisages/nipype/utils/tests/test_provenance.py:18: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /home/ccury/Codes/NipypeVisages/nipype/utils/provenance.py:427: in add_results
>     for key, value in list(get_info().items()):
> /home/ccury/Codes/NipypeVisages/nipype/__init__.py:47: in get_info
>     return _get_pkg_info(os.path.dirname(__file__))
> /home/ccury/Codes/NipypeVisages/nipype/pkg_info.py:88: in get_pkg_info
>     src, hsh = pkg_commit_hash(pkg_path)
> /home/ccury/Codes/NipypeVisages/nipype/pkg_info.py:56: in pkg_commit_hash
>     archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:811: in get
>     d)
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:384: in before_get
>     self._interpolate_some(parser, option, L, value, section, defaults, 1)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <backports.configparser.BasicInterpolation object at 0x7fe1d4024b50>
> parser = <backports.configparser.ConfigParser object at 0x7fe16fa79890>, option = 'archive_subst_hash', accum = [], rest = '%h'
> section = 'commit hash', map = _ChainMap({}, OrderedDict([(u'archive_subst_hash', u'%h'), (u'install_hash', u'')]), OrderedDict())
> depth = 1
> 
>     def _interpolate_some(self, parser, option, accum, rest, section, map,
>                           depth):
>         rawval = parser.get(section, option, raw=True, fallback=rest)
>         if depth > MAX_INTERPOLATION_DEPTH:
>             raise InterpolationDepthError(option, section, rawval)
>         while rest:
>             p = rest.find("%")
>             if p < 0:
>                 accum.append(rest)
>                 return
>             if p > 0:
>                 accum.append(rest[:p])
>                 rest = rest[p:]
>             # p is no longer used
>             c = rest[1:2]
>             if c == "%":
>                 accum.append("%")
>                 rest = rest[2:]
>             elif c == "(":
>                 m = self._KEYCRE.match(rest)
>                 if m is None:
>                     raise InterpolationSyntaxError(option, section,
>                         "bad interpolation variable reference %r" % rest)
>                 var = parser.optionxform(m.group(1))
>                 rest = rest[m.end():]
>                 try:
>                     v = map[var]
>                 except KeyError:
>                     raise from_none(InterpolationMissingOptionError(
>                         option, section, rawval, var))
>                 if "%" in v:
>                     self._interpolate_some(parser, option, accum, v,
>                                            section, map, depth + 1)
>                 else:
>                     accum.append(v)
>             else:
>                 raise InterpolationSyntaxError(
>                     option, section,
>                     "'%%' must be followed by '%%' or '(', "
> >                   "found: %r" % (rest,))
> E               InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
> 
> /home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py:434: InterpolationSyntaxError
> _______________________________________________________ test_provenance_exists _______________________________________________________
> 
> tmpdir = local('/tmp/pytest-of-ccury/pytest-6/test_provenance_exists0')
> 
>     def test_provenance_exists(tmpdir):
>         tempdir = str(tmpdir)
>         os.chdir(tempdir)
>         from nipype import config
>         from nipype.interfaces.base import CommandLine
>         provenance_state = config.get('execution', 'write_provenance')
>         hash_state = config.get('execution', 'hash_method')
>         config.enable_provenance()
>         CommandLine('echo hello').run()
>         config.set('execution', 'write_provenance', provenance_state)
>         config.set('execution', 'hash_method', hash_state)
>         provenance_exists = os.path.exists(os.path.join(tempdir, 'provenance.provn'))
> >       assert provenance_exists
> E       assert False
> 
> /home/ccury/Codes/NipypeVisages/nipype/utils/tests/test_provenance.py:35: AssertionError
> -------------------------------------------------------- Captured stdout call --------------------------------------------------------
> 171029-20:09:23,340 utils WARNING:
> 	 Writing provenance failed - Exception details:
> Traceback (most recent call last):
>   File "/home/ccury/Codes/NipypeVisages/nipype/utils/provenance.py", line 291, in write_provenance
>     ps.add_results(results)
>   File "/home/ccury/Codes/NipypeVisages/nipype/utils/provenance.py", line 427, in add_results
>     for key, value in list(get_info().items()):
>   File "/home/ccury/Codes/NipypeVisages/nipype/__init__.py", line 47, in get_info
>     return _get_pkg_info(os.path.dirname(__file__))
>   File "/home/ccury/Codes/NipypeVisages/nipype/pkg_info.py", line 88, in get_pkg_info
>     src, hsh = pkg_commit_hash(pkg_path)
>   File "/home/ccury/Codes/NipypeVisages/nipype/pkg_info.py", line 56, in pkg_commit_hash
>     archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
>   File "/home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py", line 811, in get
>     d)
>   File "/home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py", line 384, in before_get
>     self._interpolate_some(parser, option, L, value, section, defaults, 1)
>   File "/home/ccury/Codes/NipypeVisages/.eggs/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py", line 434, in _interpolate_some
>     "found: %r" % (rest,))
> InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
> 
> 
> Exception arguments:
> "archive_subst_hash", "commit hash", "'%' must be followed by '%' or '(', found: u'%h'"
> 

Any idea why I have those errors? 

Many thanks for your help and time.

**Comment by cclairec** [comment]
Hi again!

I still have the issues above, that I don't know how to deal with. But I also have some strange warnings. For exemple:
```
nipype/workflows/dmri/fsl/tbss.py::nipype.workflows.dmri.fsl.tbss.create_tbss_2_reg
  /home/ccury/Codes/NipypeVisages/nipype/workflows/dmri/fsl/tbss.py:139: UserWarning: NO FSL found
    warn('NO FSL found')
```

When I check in the code, it is when testing `fsl.no_fsl()`, which is determined by `os.environ['FSLDIR']`.
But when I try in python to do:
```
$ python
Python 2.7.13 (default, Sep  5 2017, 08:53:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from nipype.interfaces import fsl as fsl
fatal: No names found, cannot describe anything.
>>> fsl.no_fsl()
False
>>> import os
>>> os.environ['FSLDIR']
'/usr/local/fsl'
>>> 

```
Which means that I shouldn't have the warning mentioned above. What am I missing there? 

Thanks  for your help !
cclairec
