### ISSUE TITLE
where to find the dataset ds000114 required for the docker image tutorial 

### ISSUE THREAD

**Issue by athanell** [nipy/nipype#2259]
### Summary
In the tutorial [ https://miykael.github.io/nipype_tutorial/notebooks/introduction_docker.html](url) the location of a specific data set is required.
Where can someone find the dataset ds000114 that is required by the tutorial?
It might be an idea to include the link for this dataset in the tutorial

Thank you

**Comment by djarecka** [comment]
@athanell thank you for your suggestions. This information is now in the [BIDS & Tutorial Dataset](https://miykael.github.io/nipype_tutorial/notebooks/introduction_dataset.html)

**Comment by djarecka** [comment]
You might also report the tutorial related issue in the [Michael repository](https://github.com/miykael/nipype_tutorial/issues)

**Comment by athanell** [comment]
Thank you @djarecka
