### ISSUE TITLE
FSL FAST interface does not accept absolute paths with nipype in python3

### ISSUE THREAD

**Issue by dpisner453** [nipy/nipype#2262]
### Summary
FSL FAST interface does not accept absolute paths with nipype in python3

### Actual behavior
Need to os.chdir into the base directory to run, and cannot provide the full path to the T1 image explicitly, otherwise I get this mess:

```
Segmenting anatomical image using FAST...
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1130                 try:
-> 1131                     setattr(outputs, key, val)
   1132                     _ = getattr(outputs, key)

~/.local/lib/python3.6/site-packages/nipype/interfaces/traits_extension.py in validate(self, object, name, value)
     79 
---> 80         self.error(object, name, value)
     81 

~/.local/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    171         raise TraitError( object, name, self.full_info( object, name, value ),
--> 172                           value )
    173 

TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be an existing file name, but a value of '/scratch/04171/dpisner/HNU1/sub-0025428_ses-1_T1w_seg.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-e7001853410f> in <module>()
     76     return out_file
     77 
---> 78 [csf_loc, wm_mask_loc] = gen_anat_segs(anat_loc, FSLDIR)
     79 vent_CSF_diff_mask_path = coreg_vent_CSF_to_diff(nodif_brain_mask_path, bedpostx_dir, csf_loc, mni_csf_loc)
     80 WM_diff_mask_path = coreg_WM_mask_to_diff(nodif_brain_mask_path, bedpostx_dir, wm_mask_loc)

<ipython-input-13-e7001853410f> in gen_anat_segs(anat_loc, FSLDIR)
     20     fastr.inputs.in_files = anat_loc
     21     fastr.inputs.img_type = 1
---> 22     out = fastr.run()
     23     old_file_csf = anat_loc.split('.nii.gz')[0] + '_pve_0.nii.gz'
     24     new_file_csf = anat_dir + '/CSF.nii.gz'

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in run(self, **inputs)
   1042         try:
   1043             runtime = self._run_wrapper(runtime)
-> 1044             outputs = self.aggregate_outputs(runtime)
   1045             runtime.endTime = dt.isoformat(dt.utcnow())
   1046             timediff = parseutc(runtime.endTime) - parseutc(runtime.startTime)

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1136                         msg = ("File/Directory '%s' not found for %s output "
   1137                                "'%s'." % (val, self.__class__.__name__, key))
-> 1138                         raise FileNotFoundError(msg)
   1139                     else:
   1140                         raise error

FileNotFoundError: File/Directory '/scratch/04171/dpisner/HNU1/sub-0025428_ses-1_T1w_seg.nii.gz' not found for FAST output 'tissue_class_map'.
Interface FAST failed to run. 
```
### Expected behavior
Flexibility to include input file as absolute path or the basename of the file, when in the working directory.

### How to replicate the behavior
Try this yourself using different path specifications (absolute and relative) to any T1 image

### Platform/Exec env. details:
Note: I am getting this issue using python3, but have not tried it in python2.7

**Comment by mgxd** [comment]
@dpisner453 can you provide the code you used that generated that traceback?

I just tried
```python
from nipype.interfaces import fsl
import os
fl = '/full/path/to/file'
fast = fsl.FAST()
fast.inputs.in_files = fl
eg = fast.run()
assert os.path.dirname(eg.outputs.tissue_class_map) == os.path.dirname(fl)
```
on python 3.6.2 and things seem fine

**Comment by dpisner453** [comment]
Interesting, here's a minimal example:

```
from nipype.interfaces import fsl
import os

fastr = fsl.FAST()
fastr.inputs.in_files = '/scratch/04171/dpisner/HNU1/data/sub-0025428/ses-1/anat/sub-0025428_ses-1_T1w.nii.gz'
fastr.inputs.img_type = 1
fastr.run()
```
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1130                 try:
-> 1131                     setattr(outputs, key, val)
   1132                     _ = getattr(outputs, key)

~/.local/lib/python3.6/site-packages/nipype/interfaces/traits_extension.py in validate(self, object, name, value)
     79 
---> 80         self.error(object, name, value)
     81 

~/.local/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    171         raise TraitError( object, name, self.full_info( object, name, value ),
--> 172                           value )
    173 

TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be an existing file name, but a value of '/home1/04171/dpisner/sub-0025428_ses-1_T1w_seg.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-6adeb432aa99> in <module>()
      1 fastr.inputs.img_type = 1
----> 2 out = fastr.run()

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in run(self, **inputs)
   1042         try:
   1043             runtime = self._run_wrapper(runtime)
-> 1044             outputs = self.aggregate_outputs(runtime)
   1045             runtime.endTime = dt.isoformat(dt.utcnow())
   1046             timediff = parseutc(runtime.endTime) - parseutc(runtime.startTime)

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1136                         msg = ("File/Directory '%s' not found for %s output "
   1137                                "'%s'." % (val, self.__class__.__name__, key))
-> 1138                         raise FileNotFoundError(msg)
   1139                     else:
   1140                         raise error

FileNotFoundError: File/Directory '/home1/04171/dpisner/sub-0025428_ses-1_T1w_seg.nii.gz' not found for FAST output 'tissue_class_map'.
Interface FAST failed to run.

**Comment by mgxd** [comment]
can you verify this works with your image using the command line?

**Comment by dpisner453** [comment]
Yes, it does. And in fact, if I run the nipype wrapper from within the working directory of the T1 image, I get no error. Again, only an issue when I specify an absolute path...

**Comment by mgxd** [comment]
Is this being run locally or inside a VM/container? Have you tried moving the data to a different partition (`/home`, etc) and replicating? Are you using current master version of `nipype`? Have you tried providing an option for `out_basename`?

i'm unsure why your file's prefix 
```
/scratch/04171/dpisner/HNU1/data/sub-0025428/ses-1/anat/
```
is being replace with
```
/home1/04171/dpisner/
```

**Comment by oesteban** [comment]
@mgxd I guess he is running on `/home1/04171/dpisner/`, as `base_dir` for the interface.

**Comment by dpisner453** [comment]
Thanks guys for being so responsive. This looks like a version-specific bug that only occurs with nipype 0.12.1, but not with 0.13.1!

Oscar-- in case you were still curious what happens if I change dirs and run fast with nipype 0.12.1 (e.g.  using `/scratch/04171/dpisner/HNU1`) as my base_dir, I get a similar error:

```
In [7]: pwd
Out[7]: '/scratch/04171/dpisner/HNU1'

In [8]: anat_loc
Out[8]: '/scratch/04171/dpisner/HNU1/data/sub-0025428/ses-1/anat/sub-0025428_ses-1_T1w.nii.gz'

In [9]: fastr.inputs.in_files = anat_loc

In [10]: fastr.inputs.img_type = 1

In [11]: fastr.cmdline
Out[11]: 'fast -t 1 -S 1 /scratch/04171/dpisner/HNU1/data/sub-0025428/ses-1/anat/sub-0025428_ses-1_T1w.nii.gz'

In [12]: fastr.inputs
Out[12]: 

args = <undefined>
bias_iters = <undefined>
bias_lowpass = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
hyper = <undefined>
ignore_exception = False
img_type = 1
in_files = ['/scratch/04171/dpisner/HNU1/data/sub-0025428/ses-1/anat/sub-0025428_ses-1_T1w.nii.gz']
init_seg_smooth = <undefined>
init_transform = <undefined>
iters_afterbias = <undefined>
manual_seg = <undefined>
mixel_smooth = <undefined>
no_bias = <undefined>
no_pve = <undefined>
number_classes = <undefined>
other_priors = <undefined>
out_basename = <undefined>
output_biascorrected = <undefined>
output_biasfield = <undefined>
output_type = NIFTI_GZ
probability_maps = <undefined>
segment_iters = <undefined>
segments = <undefined>
terminal_output = stream
use_priors = <undefined>
verbose = <undefined>

In [13]: out = fastr.run()
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1130                 try:
-> 1131                     setattr(outputs, key, val)
   1132                     _ = getattr(outputs, key)

~/.local/lib/python3.6/site-packages/nipype/interfaces/traits_extension.py in validate(self, object, name, value)
     79 
---> 80         self.error(object, name, value)
     81 

~/.local/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    171         raise TraitError( object, name, self.full_info( object, name, value ),
--> 172                           value )
    173 

TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be an existing file name, but a value of '/scratch/04171/dpisner/HNU1/sub-0025428_ses-1_T1w_seg.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-8e4572785486> in <module>()
----> 1 out = fastr.run()

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in run(self, **inputs)
   1042         try:
   1043             runtime = self._run_wrapper(runtime)
-> 1044             outputs = self.aggregate_outputs(runtime)
   1045             runtime.endTime = dt.isoformat(dt.utcnow())
   1046             timediff = parseutc(runtime.endTime) - parseutc(runtime.startTime)

~/.local/lib/python3.6/site-packages/nipype/interfaces/base.py in aggregate_outputs(self, runtime, needed_outputs)
   1136                         msg = ("File/Directory '%s' not found for %s output "
   1137                                "'%s'." % (val, self.__class__.__name__, key))
-> 1138                         raise FileNotFoundError(msg)
   1139                     else:
   1140                         raise error

FileNotFoundError: File/Directory '/scratch/04171/dpisner/HNU1/sub-0025428_ses-1_T1w_seg.nii.gz' not found for FAST output 'tissue_class_map'.
Interface FAST failed to run. 

In [5]: ls
```

Unless you guys care about debugging older nipype versions, this issue can now be closed :-)

**Comment by mgxd** [comment]
@dpisner453 no problem! for the future, it does help to fill out the issue template as fully as possible, since platform details would have helped out here

**Comment by andys0975** [comment]
got the same issue in version 1.1.2
pass without error only when executing in the nii.gz's folder

**Comment by effigies** [comment]
Hi @andys0975, could you open a new issue (linking back to this one) with the full error, your runtime environment, and code to reproduce the issue?
