### ISSUE TITLE
Getting Interface BET failed to run Error

### ISSUE THREAD

**Issue by AnjaliPullabhotla** [nipy/nipype#2266]
Mac OS

import os
from nipype.interfaces import fsl
btr = fsl.BET()
btr.inputs.in_file = 'trainer/input.nii'
btr.inputs.frac = 0.7
btr.inputs.out_file = 'trainer/output.nii'
res = btr.run()

Fails with the below error:
IOError: command 'bet' could not be found on host MacBook-Pro.local
Interface BET failed to run

Any help appreciated

**Comment by oesteban** [comment]
Can you run `bet` in your shell prompt without nipype at all?

**Comment by AnjaliPullabhotla** [comment]
No.  bet is not working on shell prompt either.  It returns command not found.

**Comment by AnjaliPullabhotla** [comment]
Also I'm using virtualenv.  Not sure if that is causing issues

**Comment by oesteban** [comment]
Please reopen if it did not work :+1:

**Comment by AnjaliPullabhotla** [comment]
It worked after installing FSL. Thank you so much!

**Comment by Cynthia0629** [comment]
I also faced the same problem. And I've installed FSL successfully. It works well. But when I try these codes the error comes like this:
_______________________________________
Traceback (most recent call last):
  File "/home/sunny/PycharmProjects/nipype/test_build_pipeline.py", line 19, in <module>
    myb.run()
  File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/preprocess.py", line 144, in _run_interface
    runtime = super(BET, self)._run_interface(runtime)
  File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1750, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
OSError: command 'bet' could not be found on host cynthia-PC
Interface BET failed to run.
________________________________________________
Any help will be appreciated.
By the way. I've sourced .bashrc and set the path like this:
___________________________________________________________
#FSL
FSLDIR=/usr/share/fsl
. ${FSLDIR}/5.0/etc/fslconf/fsl.sh
PATH=${FSLDIR}/5.0/bin:${PATH}
export FSLDIR PATH

#FreeSurfer
export FREESURFER_HOME=/usr/local/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

#AFNI
export PATH=/usr/lib/afni/bin:$PATH
_____________________________________

**Comment by junhaols** [comment]
> I also faced the same problem. And I've installed FSL successfully. It works well. But when I try these codes the error comes like this:
> 
> Traceback (most recent call last): File "/home/sunny/PycharmProjects/nipype/test_build_pipeline.py", line 19, in myb.run() File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1081, in run runtime = self._run_wrapper(runtime) File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper runtime = self._run_interface(runtime) File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/preprocess.py", line 144, in _run_interface runtime = super(BET, self)._run_interface(runtime) File "/home/sunny/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1750, in _run_interface (self.cmd.split()[0], runtime.hostname)) OSError: command 'bet' could not be found on host cynthia-PC Interface BET failed to run.
> 
> Any help will be appreciated. By the way. I've sourced .bashrc and set the path like this:
> 
> #FSL FSLDIR=/usr/share/fsl . ${FSLDIR}/5.0/etc/fslconf/fsl.sh PATH=${FSLDIR}/5.0/bin:${PATH} export FSLDIR PATH
> 
> #FreeSurfer export FREESURFER_HOME=/usr/local/freesurfer source $FREESURFER_HOME/SetUpFreeSurfer.sh
> 
> #AFNI export PATH=/usr/lib/afni/bin:$PATH

Oh,I also faced the same problem,have you soved it?

**Comment by junhaols** [comment]
> Please reopen if it did not work 👍

In terminal the command bet can work but it can not work when called in nipype,the error is "command 'bet' could not be found ".
