### ISSUE TITLE
SPMCommand & python 3 issue ?

### ISSUE THREAD

**Issue by alaurent4** [nipy/nipype#2286]
Hello,

I am trying to launch SPM with MCR via nipype and python 3.6.
Using the usual lines for testing the integration, spm.SPMCommand().version seems blocked in an infinite loop or something. When I kill the command, I get the following: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/spm/base.py", line 293, in version
    use_mcr=self.inputs.use_mcr)
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/spm/base.py", line 181, in version
    out = mlab.run()
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/matlab.py", line 145, in _run_interface
    runtime = super(MatlabCommand, self)._run_interface(runtime)
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1668, in _run_interface
    runtime = run_command(runtime, output=self.terminal_output)
  File "/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1431, in run_command
    stdout, stderr = proc.communicate()
  File "/srv/shares/softs/anaconda3/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/srv/shares/softs/anaconda3/lib/python3.6/subprocess.py", line 1514, in _communicate
    ready = selector.select(timeout)
  File "/srv/shares/softs/anaconda3/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
```

It seems related to the subprocess within python3.6, I tried to dig a little without any success.
It used to work with my Python 2.7 and Nipype0.12.0.

### Platform details:

{'pkg_path': '/srv/shares/softs/anaconda3/lib/python3.6/site-packages/nipype', 'commit_source': 'installation', 'commit_hash': '68e8ef0', 'nipype_version': '1.0.0-dev', 'sys_version': '3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) \n[GCC 7.2.0]', 'sys_executable': '/srv/shares/softs/anaconda3/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.13.3', 'scipy_version': '0.19.1', 'networkx_version': '2.0', 'nibabel_version': '2.2.0', 'traits_version': '4.6.0'}
1.0.0-dev

If someone can take a look at these commands 👍 

Thank you !

Best,
A.Laurent

**Comment by mgxd** [comment]
@alaurent4 I had to wait a few minutes, but was able to output the version:

```
In [7]: spm.SPMCommand().version
Out[7]: '12.6225'
```
with current master in Python 3.6.3.

How did you wait for the command to output?

**Comment by alaurent4** [comment]
I killed the command after about 5mins thinking It was not working. 
With my old version it was pretty instant so it misled me. 

I will try again but if I may, is it normal that it takes so long ?

Thank you for your reply !

**Comment by mgxd** [comment]
@alaurent4 are you also having problems running spm interfaces?

**Comment by alaurent4** [comment]
@mgxd No, I am able to launch the SPM interfaces via matlab

**Comment by mgxd** [comment]
sorry if I wasn't clear - are you able to run any spm interfaces through nipype?

**Comment by alaurent4** [comment]
Sorry my mistake. Yes, when I am just using the complete version of matlab (not mcr) the routines seem to work

**Comment by alexsavio** [comment]
Are you still having issues? When I had this kind of issues, it was usually an error in the environment variables to enable SPM with MCR:
```
if [ -d ${SOFT_PATH}/spm_mcr ];
then
    export MCR_DIR=${SOFT_PATH}/spm_mcr/mcr/v91
    export SPM_DIR=${SOFT_PATH}/spm_mcr/spm12
    export SPMMCRCMD="$SPM_DIR/run_spm12.sh $MCR_DIR script"
    export FORCE_SPMMCR=1
fi
```

Check which version folder you have in MCR_DIR.

**Comment by oesteban** [comment]
The changes in #2325 (https://github.com/nipy/nipype/pull/2325/files#diff-9208df2bc74d92af5581c683cc78f91fR129) may affect this issue.

**Comment by alaurent4** [comment]
Sorry for the delay and thanks for the replies.
Sadly, I still have the same problem even with newer version..

**Comment by satra** [comment]
@alaurent4 - could you please do the following from your python terminal:

```
import os
print(os.environ)
```

and separately in the shell, making appropriate changes to the two paths and your mcr version:
```
echo "[name, version] = spm('ver')" > spmver.m
/path/to/run_spm8.sh /path/to/Compiler_Runtime/v???/ script spmver.m
```

**Comment by alaurent4** [comment]
Here are the outputs : 

**FOR SPM** 
name =

SPM12

version =

6685

**FOR PYTHON**
environ({'LMOD_FAMILY_COMPILER_VERSION': '5.4.0', 'MANPATH': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/share/man:/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/man:/opt/ohpc/pub/compiler/gcc/5.4.0/share/man:/opt/ohpc/pub/utils/autotools/share/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man', 'VNCDESKTOP': 'pipeau.dgin.bor:14 (alaurent)', 'SSH_AGENT_PID': '30843', 'XDG_SESSION_ID': 'c38', 'HOSTNAME': 'pipeau.dgin.bor', '_ModuleTable003_': 'bE5hbWUiXT0iYWZuaS8xNiIsWyJsb2FkT3JkZXIiXT0xMyxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJhZm5pLzE2Iix9LGFuYWNvbmRhPXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvYW5hY29uZGEvMy5sdWEiLFsiZnVsbE5hbWUiXT0iYW5hY29uZGEvMyIsWyJsb2FkT3JkZXIiXT0yMCxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJhbmFjb25kYS8zIix9LGFudHM9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9hbnRzLzIuMS5sdWEiLFsiZnVsbE5hbWUiXT0iYW50cy8yLjEiLFsibG9hZE9yZGVyIl09OSxwcm9wVD17', 'GPG_AGENT_INFO': '/homes_unix/alaurent/.gnupg/S.gpg-agent:30854:1', '_ModuleTable009_': 'cGk9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVkZXBzL2dudS9vcGVubXBpLzEuMTAuNiIsWyJmdWxsTmFtZSJdPSJvcGVubXBpLzEuMTAuNiIsWyJsb2FkT3JkZXIiXT00LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTEsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09Im9wZW5tcGkiLH0scHJ1bj17WyJmbiJdPSIvb3B0L29ocGMvcHViL21vZHVsZWZpbGVzL3BydW4vMS4yIixbImZ1bGxOYW1lIl09InBydW4vMS4yIixbImxvYWRPcmRlciJdPTIscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MSxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0icHJ1biIsfSxzY2lscHk9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9zY2lscHkvYmV0', 'MATLABPATH': ':/srv/shares/softs/spm12:/srv/shares/softs/spm12', 'R_BASE_LIB': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/lib64', 'SHELL': '/bin/bash', 'TERM': 'xterm', 'HISTSIZE': '1000', 'ANTSPATH': '/srv/shares/softs/ants', 'FSLMULTIFILEQUIT': 'TRUE', 'PERL5LIB': '/srv/shares/softs//freesurfer-6.0/mni/lib/perl5/5.8.5', 'LMOD_PKG': '/opt/ohpc/admin/lmod/lmod', 'WINDOWID': '44044347', 'QTDIR': '/usr/lib64/qt-3.3', 'LMOD_VERSION': '7.7.1', 'QTINC': '/usr/lib64/qt-3.3/include', 'R_BASE_DIR': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2', '__LMOD_REF_COUNT_LOADEDMODULES': 'autotools:1;prun/1.2:1;gnu/5.4.0:1;openmpi/1.10.6:1;ohpc:1;openblas/0.2.19:1;Freesurfer/6.0:1;fsl/5:1;ants/2.1:1;Matlab/R2015b:1;mricron/2013:1;gdcm/2.6:1;afni/16:1;c3d/1:1;itksnap/3.4:1;dcm4che/3.3:1;mrtrix/2:1;scilpy/beta:1;R_base/3.3.2:1;anaconda/3:1', '_ModuleTable007_': 'PTE1LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09Iml0a3NuYXAvMy40Iix9LG1yaWNyb249e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9tcmljcm9uLzIwMTMubHVhIixbImZ1bGxOYW1lIl09Im1yaWNyb24vMjAxMyIsWyJsb2FkT3JkZXIiXT0xMSxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJtcmljcm9uLzIwMTMiLH0sbXJ0cml4PXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvbXJ0cml4LzIubHVhIixbImZ1bGxOYW1lIl09Im1ydHJpeC8yIixbImxvYWRPcmRlciJdPTE3LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAs', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'USER': 'alaurent', 'OPENBLAS_DIR': '/opt/ohpc/pub/libs/gnu/openblas/0.2.19', 'LD_LIBRARY_PATH': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/lib64:/opt/ohpc/pub/libs/gnu/openblas/0.2.19/lib:/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib:/opt/ohpc/pub/compiler/gcc/5.4.0/lib64:/srv/shares/softs/jdk1.8.0_72/jre/lib/amd64/server', '_ModuleTable010_': 'YS5sdWEiLFsiZnVsbE5hbWUiXT0ic2NpbHB5L2JldGEiLFsibG9hZE9yZGVyIl09MTgscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MCxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0ic2NpbHB5Iix9LH0sbXBhdGhBPXsiL29wdC9vaHBjL3B1Yi9tb2R1bGVkZXBzL2dudS1vcGVubXBpIiwiL29wdC9vaHBjL3B1Yi9tb2R1bGVkZXBzL2dudSIsIi9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcyIsfQ==', 'FSLGECUDAQ': 'cuda.q', 'FSFAST_HOME': '/srv/shares/softs/freesurfer-6.0/fsfast', 'SSH_AUTH_SOCK': '/tmp/ssh-bmnKkgEOgXgJ/agent.30840', '_ModuleTable004_': 'fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJhbnRzLzIuMSIsfSxhdXRvdG9vbHM9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9hdXRvdG9vbHMiLFsiZnVsbE5hbWUiXT0iYXV0b3Rvb2xzIixbImxvYWRPcmRlciJdPTEscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MSxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0iYXV0b3Rvb2xzIix9LGMzZD17WyJmbiJdPSIvb3B0L29ocGMvcHViL21vZHVsZWZpbGVzL2MzZC8xLmx1YSIsWyJmdWxsTmFtZSJdPSJjM2QvMSIsWyJsb2FkT3JkZXIiXT0xNCxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJj', '__LMOD_REF_COUNT__LMFILES_': '/opt/ohpc/pub/modulefiles/autotools:1;/opt/ohpc/pub/modulefiles/prun/1.2:1;/opt/ohpc/pub/modulefiles/gnu/5.4.0:1;/opt/ohpc/pub/moduledeps/gnu/openmpi/1.10.6:1;/opt/ohpc/pub/modulefiles/ohpc:1;/opt/ohpc/pub/moduledeps/gnu/openblas/0.2.19:1;/opt/ohpc/pub/modulefiles/Freesurfer/6.0.lua:1;/opt/ohpc/pub/modulefiles/fsl/5.lua:1;/opt/ohpc/pub/modulefiles/ants/2.1.lua:1;/opt/ohpc/pub/modulefiles/Matlab/R2015b.lua:1;/opt/ohpc/pub/modulefiles/mricron/2013.lua:1;/opt/ohpc/pub/modulefiles/gdcm/2.6.lua:1;/opt/ohpc/pub/modulefiles/afni/16.lua:1;/opt/ohpc/pub/modulefiles/c3d/1.lua:1;/opt/ohpc/pub/modulefiles/itksnap/3.4.lua:1;/opt/ohpc/pub/modulefiles/dcm4che/3.3.lua:1;/opt/ohpc/pub/modulefiles/mrtrix/2.lua:1;/opt/ohpc/pub/modulefiles/scilpy/beta.lua:1;/opt/ohpc/pub/moduledeps/gnu/R_base/3.3.2:1;/opt/ohpc/pub/modulefiles/anaconda/3.lua:1', 'FSF_OUTPUT_FORMAT': 'nii.gz', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/30795,unix/unix:/tmp/.ICE-unix/30795', 'LMOD_PREPEND_BLOCK': 'normal', 'SUBJECTS_DIR': '/data/analyses/work_in_progress/freesurfer/recon3Tcor', 'LMOD_FAMILY_MPI_VERSION': '1.10.6', 'MAIL': '/var/spool/mail/alaurent', '_ModuleTable001_': 'X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXtbIk1QSSJdPSJvcGVubXBpIixbImNvbXBpbGVyIl09ImdudSIsWyJvcGVuYmxhcyJdPSJvcGVuYmxhcyIsfSxtVD17RnJlZXN1cmZlcj17WyJmbiJdPSIvb3B0L29ocGMvcHViL21vZHVsZWZpbGVzL0ZyZWVzdXJmZXIvNi4wLmx1YSIsWyJmdWxsTmFtZSJdPSJGcmVlc3VyZmVyLzYuMCIsWyJsb2FkT3JkZXIiXT03LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09IkZyZWVzdXJmZXIvNi4wIix9LE1hdGxhYj17WyJmbiJdPSIvb3B0L29ocGMvcHViL21v', 'PATH': '/srv/shares/softs/anaconda3/bin:/opt/ohpc/pub/libs/gnu/R_base/3.3.2/bin:/homes_unix/alaurent/workspace/nighres/lesion_tool:/srv/shares/softs/scilpy/scripts:/srv/shares/softs/mrtrix2/bin:/srv/shares/softs/dcm4che-3.3.7/bin:/srv/shares/softs/itksnap-3.4.0-20151130-Linux-x86_64/bin:/srv/shares/softs/c3d-1.0.0-Linux-x86_64/bin:/srv/shares/softs/afni:/srv/shares/softs/gdcm/bin:/srv/shares/softs/mricron-2013:/srv/shares/softs/MATLAB/R2015b/bin:/srv/shares/softs/ants:/srv/shares/softs/fsl/bin:/srv/shares/softs/freesurfer-6.0/bin:/srv/shares/softs/freesurfer-6.0/tktools:/srv/shares/softs/freesurfer-6.0/mni/bin:/opt/ohpc/pub/libs/gnu/openblas/0.2.19/bin:/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/bin:/opt/ohpc/pub/compiler/gcc/5.4.0/bin:/opt/ohpc/pub/utils/prun/1.2:/opt/ohpc/pub/utils/autotools/bin:/opt/ohpc/pub/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/homes_unix/alaurent/bin/eclipse:/srv/shares/softs/jdk1.8.0_72/bin:/homes_unix/alaurent/R/x86_64-pc-linux-gnu-library/3.2/snow:/homes_unix/alaurent/workspace/ginnipi/bin:/homes_unix/alaurent/mipav:/homes_unix/alaurent/bin:/homes_unix/alaurent/R_packages/snow', 'LMOD_SETTARG_CMD': ':', 'PWD': '/homes_unix/alaurent', 'R_LIBS': '~/R/x86_64-pc-linux-gnu-library/3.2', '_LMFILES_': '/opt/ohpc/pub/modulefiles/autotools:/opt/ohpc/pub/modulefiles/prun/1.2:/opt/ohpc/pub/modulefiles/gnu/5.4.0:/opt/ohpc/pub/moduledeps/gnu/openmpi/1.10.6:/opt/ohpc/pub/modulefiles/ohpc:/opt/ohpc/pub/moduledeps/gnu/openblas/0.2.19:/opt/ohpc/pub/modulefiles/Freesurfer/6.0.lua:/opt/ohpc/pub/modulefiles/fsl/5.lua:/opt/ohpc/pub/modulefiles/ants/2.1.lua:/opt/ohpc/pub/modulefiles/Matlab/R2015b.lua:/opt/ohpc/pub/modulefiles/mricron/2013.lua:/opt/ohpc/pub/modulefiles/gdcm/2.6.lua:/opt/ohpc/pub/modulefiles/afni/16.lua:/opt/ohpc/pub/modulefiles/c3d/1.lua:/opt/ohpc/pub/modulefiles/itksnap/3.4.lua:/opt/ohpc/pub/modulefiles/dcm4che/3.3.lua:/opt/ohpc/pub/modulefiles/mrtrix/2.lua:/opt/ohpc/pub/modulefiles/scilpy/beta.lua:/opt/ohpc/pub/moduledeps/gnu/R_base/3.3.2:/opt/ohpc/pub/modulefiles/anaconda/3.lua', 'JAVA_HOME': '/srv/shares/softs/jdk1.8.0_72', 'LANG': 'fr_FR.UTF-8', 'MODULEPATH': '/opt/ohpc/pub/moduledeps/gnu-openmpi:/opt/ohpc/pub/moduledeps/gnu:/opt/ohpc/pub/modulefiles', 'FSLTCLSH': '$FSLDIR/bin/fsltclsh', 'LOADEDMODULES': 'autotools:prun/1.2:gnu/5.4.0:openmpi/1.10.6:ohpc:openblas/0.2.19:Freesurfer/6.0:fsl/5:ants/2.1:Matlab/R2015b:mricron/2013:gdcm/2.6:afni/16:c3d/1:itksnap/3.4:dcm4che/3.3:mrtrix/2:scilpy/beta:R_base/3.3.2:anaconda/3', 'KDEDIRS': '/usr', '_ModuleTable_Sz_': '10', 'FSLMACHINELIST': '', 'R_BASE_BIN': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/bin', 'LMOD_CMD': '/opt/ohpc/admin/lmod/lmod/libexec/lmod', '_ModuleTable005_': 'M2QvMSIsfSxkY200Y2hlPXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvZGNtNGNoZS8zLjMubHVhIixbImZ1bGxOYW1lIl09ImRjbTRjaGUvMy4zIixbImxvYWRPcmRlciJdPTE2LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09ImRjbTRjaGUvMy4zIix9LGZzbD17WyJmbiJdPSIvb3B0L29ocGMvcHViL21vZHVsZWZpbGVzL2ZzbC81Lmx1YSIsWyJmdWxsTmFtZSJdPSJmc2wvNSIsWyJsb2FkT3JkZXIiXT04LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09ImZzbC81Iix9LGdkY209e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9n', 'FSLREMOTECALL': '', 'FSLWISH': '$FSLDIR/bin/fslwish', 'SSH_ASKPASS': '/usr/libexec/openssh/gnome-ssh-askpass', 'HISTCONTROL': 'ignoredups', 'SHLVL': '3', 'HOME': '/homes_unix/alaurent', 'MNI_DIR': '/srv/shares/softs/freesurfer-6.0/mni', '__LMOD_REF_COUNT_PATH': '/srv/shares/softs/anaconda3/bin:1;/opt/ohpc/pub/libs/gnu/R_base/3.3.2/bin:1;/homes_unix/alaurent/workspace/nighres/lesion_tool:2;/srv/shares/softs/scilpy/scripts:1;/srv/shares/softs/mrtrix2/bin:1;/srv/shares/softs/dcm4che-3.3.7/bin:1;/srv/shares/softs/itksnap-3.4.0-20151130-Linux-x86_64/bin:1;/srv/shares/softs/c3d-1.0.0-Linux-x86_64/bin:1;/srv/shares/softs/afni:1;/srv/shares/softs/gdcm/bin:1;/srv/shares/softs/mricron-2013:1;/srv/shares/softs/MATLAB/R2015b/bin:1;/srv/shares/softs/ants:1;/srv/shares/softs/fsl/bin:1;/srv/shares/softs/freesurfer-6.0/bin:1;/srv/shares/softs/freesurfer-6.0/tktools:1;/srv/shares/softs/freesurfer-6.0/mni/bin:1;/opt/ohpc/pub/libs/gnu/openblas/0.2.19/bin:1;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/bin:1;/opt/ohpc/pub/compiler/gcc/5.4.0/bin:1;/opt/ohpc/pub/utils/prun/1.2:1;/opt/ohpc/pub/utils/autotools/bin:1;/opt/ohpc/pub/bin:1;/usr/lib64/qt-3.3/bin:1;/usr/local/bin:1;/bin:1;/usr/bin:1;/usr/local/sbin:1;/usr/sbin:1;/homes_unix/alaurent/bin/eclipse:2;/srv/shares/softs/jdk1.8.0_72/bin:2;/homes_unix/alaurent/R/x86_64-pc-linux-gnu-library/3.2/snow:2;/homes_unix/alaurent/workspace/ginnipi/bin:2;/homes_unix/alaurent/mipav:2;/homes_unix/alaurent/bin:2;/homes_unix/alaurent/R_packages/snow:2', 'FREESURFER_HOME': '/srv/shares/softs/freesurfer-6.0', 'FSLDISPLAY': '/usr/bin/display', '_ModuleTable002_': 'ZHVsZWZpbGVzL01hdGxhYi9SMjAxNWIubHVhIixbImZ1bGxOYW1lIl09Ik1hdGxhYi9SMjAxNWIiLFsibG9hZE9yZGVyIl09MTAscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MCxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0iTWF0bGFiL1IyMDE1YiIsfSxSX2Jhc2U9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVkZXBzL2dudS9SX2Jhc2UvMy4zLjIiLFsiZnVsbE5hbWUiXT0iUl9iYXNlLzMuMy4yIixbImxvYWRPcmRlciJdPTE5LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTAsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09IlJfYmFzZSIsfSxhZm5pPXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvYWZuaS8xNi5sdWEiLFsiZnVs', 'FSLCONVERT': '/usr/bin/convert', 'MPI_DIR': '/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6', '__LMOD_REF_COUNT_INCLUDE': '/opt/ohpc/pub/libs/gnu/openblas/0.2.19/include:1;/opt/ohpc/pub/compiler/gcc/5.4.0/include:1', 'SHOST': 'pipeau', 'LMOD_FAMILY_OPENBLAS_VERSION': '0.2.19', '_ModuleTable008_': 'WyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09Im1ydHJpeC8yIix9LG9ocGM9e1siZm4iXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcy9vaHBjIixbImZ1bGxOYW1lIl09Im9ocGMiLFsibG9hZE9yZGVyIl09NSxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJvaHBjIix9LG9wZW5ibGFzPXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZGVwcy9nbnUvb3BlbmJsYXMvMC4yLjE5IixbImZ1bGxOYW1lIl09Im9wZW5ibGFzLzAuMi4xOSIsWyJsb2FkT3JkZXIiXT02LHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTEsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09Im9wZW5ibGFzIix9LG9wZW5t', 'BASH_ENV': '/opt/ohpc/admin/lmod/lmod/init/bash', 'PYTHONPATH': '/homes_unix/alaurent/workspace:/srv/shares/softs/scilpy:/homes_unix/alaurent/.local/lib/python2.7/site-packages', 'LOGNAME': 'alaurent', 'CVS_RSH': 'ssh', 'LMOD_FAMILY_OPENBLAS': 'openblas', 'FSLDIR': '/srv/shares/softs/fsl', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-H5RqHafWCN,guid=091ae008c633e272faaa82865a5367b4', 'MODULESHOME': '/opt/ohpc/admin/lmod/lmod', 'R_BASE_SHARE': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/share', 'PKG_CONFIG_PATH': '/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/pkgconfig', '__LMOD_REF_COUNT_LD_LIBRARY_PATH': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/lib64:1;/opt/ohpc/pub/libs/gnu/openblas/0.2.19/lib:1;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib:1;/opt/ohpc/pub/compiler/gcc/5.4.0/lib64:1;/srv/shares/softs/jdk1.8.0_72/jre/lib/amd64/server:2', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'LMOD_FAMILY_COMPILER': 'gnu', 'LMOD_FULL_SETTARG_SUPPORT': 'no', 'XDG_RUNTIME_DIR': '/run/user/30082', '__LMOD_REF_COUNT_PKG_CONFIG_PATH': '/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/pkgconfig:1', 'DISPLAY': ':14.0', 'OPENBLAS_LIB': '/opt/ohpc/pub/libs/gnu/openblas/0.2.19/lib', 'QT_PLUGIN_PATH': '/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins', 'FSLLOCKDIR': '', '__LMOD_REF_COUNT_MANPATH': '/opt/ohpc/pub/libs/gnu/R_base/3.3.2/share/man:1;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/man:1;/opt/ohpc/pub/compiler/gcc/5.4.0/share/man:1;/opt/ohpc/pub/utils/autotools/share/man:1;/usr/local/share/man:2;/usr/share/man/overrides:2;/usr/share/man/en:2;/usr/share/man:2', '_ModuleTable006_': 'ZGNtLzIuNi5sdWEiLFsiZnVsbE5hbWUiXT0iZ2RjbS8yLjYiLFsibG9hZE9yZGVyIl09MTIscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MCxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0iZ2RjbS8yLjYiLH0sZ251PXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvZ251LzUuNC4wIixbImZ1bGxOYW1lIl09ImdudS81LjQuMCIsWyJsb2FkT3JkZXIiXT0zLHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTEsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09ImdudSIsfSxpdGtzbmFwPXtbImZuIl09Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMvaXRrc25hcC8zLjQubHVhIixbImZ1bGxOYW1lIl09Iml0a3NuYXAvMy40IixbImxvYWRPcmRlciJd', 'LMOD_DIR': '/opt/ohpc/admin/lmod/lmod/libexec', 'INCLUDE': '/opt/ohpc/pub/libs/gnu/openblas/0.2.19/include:/opt/ohpc/pub/compiler/gcc/5.4.0/include', 'FSLOUTPUTTYPE': 'NIFTI_GZ', 'LMOD_FAMILY_MPI': 'openmpi', 'LMOD_COLORIZE': 'no', 'OPENBLAS_INC': '/opt/ohpc/pub/libs/gnu/openblas/0.2.19/include', 'COLORTERM': 'xfce4-terminal', 'BASH_FUNC_module()': '() {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\n}', 'BASH_FUNC_ml()': '() {  eval $($LMOD_DIR/ml_cmd "$@")\n}', '_': '/srv/shares/softs/anaconda3/bin/python'})

Thanks for taking the time to help

**Comment by alaurent4** [comment]
Hello,

just some news about the issue I experienced.
I am still with the same environment and with the version 1.0.2 of nipype, now it seems to work!

Thanks for your replies
