### ISSUE TITLE
iterable with Node

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2311]
### Summary

I was just reviewing some of the examples in Nipype Tutorial and was stuck with `iterables` used together with a `Node` (or interface).

This is a simple example that gives me an error (`IdentityInterface requires a value for input 'b' because it was listed in 'fields'.`)

```
from nipype import Function, Node, Workflow
from nipype.interfaces.utility import IdentityInterface

ii = Node(IdentityInterface(fields=['a', 'b']), name="test")                                                                                                                                 
ii.inputs.a = 4
ii.iterables = [("b", [1,4])]
ii.run()
```

if I create a `Workflow` and connect with other node it works fine, e.g.:

```
def add_numbers(x, y):
    return x + y

adding = Node(Function(input_names=["x", "y"],
                           output_names=["sum"],
                       function=add_numbers),
              name='add_numbers')

wf = Workflow(name="test_iterable")
wf.connect([(ii, adding, [("a", "x"), ("b", "y")])])
res = wf.run()

print(list(res.nodes())[0].result.outputs)
print(list(res.nodes())[1].result.outputs)
```

So my question is, if this is the expected results? In most examples I saw, `iterable` is used in workflows but it wasn't clear to me if this is the only way.

**Comment by satra** [comment]
@djarecka - the output is expected. `iterables` are set on `(Map)Node` but are expanded in a `Workflow`. the `Node` function `run` does not know what an `iterable` is.

**Comment by djarecka** [comment]
@satra thanks for explanation. I'm thinking about removing [this part from Nipype Tutorial](https://miykael.github.io/nipype_tutorial/notebooks/basic_iteration.html#IdentityInterface-(special-use-case-of-iterabels) 
It's slightly misleading IMO. I can only point to the example from preprocessing workflow

**Comment by satra** [comment]
i think that tutorial should clarify how iterables work and the identitynode interface usage description can also be improved.

**Comment by JohannesWiesner** [comment]
I also got stuck in this situation and I agree, it's confusing that the Node cannot run on its own but only when you connect it to another Node within a workflow (also makes developing harder, because one would probably like to test out if the node on its own delivers the right output and only then connect it to another node)
