### ISSUE TITLE
Environment canonicalization bugs

### ISSUE THREAD

**Issue by JeremieMelo** [nipy/nipype#2326]
line 1346
for key, val in env:
I don't think this works, because you cannot iterate dict like this, you have to write like this ：
for key, val in env.items()     rights?

(Edit by @effigies):
From #2327:

> line 1350:
> val = key.encode('utf-8')
> ????  I think it should be:
> val = val.encode('utf-8')

**Comment by effigies** [comment]
Thanks for the reports. Collapsing into a single report with a descriptive title.
