### ISSUE TITLE
Hi, I was running the CPAC pipeline and was having trouble actually getting nipype workflows to run. 

### ISSUE THREAD

**Issue by mk2299** [nipy/nipype#2329]
<img width="538" alt="screen shot 2017-11-30 at 1 57 44 pm" src="https://user-images.githubusercontent.com/33186673/33518323-fcca6926-d760-11e7-983b-831945ac641e.png">
HI, I couldn't get the workflow to run and keep getting this error message. The workflow graph was created just fine but I believe it is having some problem with the iterables. Any suggestions?
Thank you!

**Comment by effigies** [comment]
Hi, I don't see an error reported. There's a warning that does not appear to be fatal. The traceback is cut off, but it may be that you hit Ctrl-C, thinking that it wasn't working? The part of the traceback that's visible shows that the full workflow graph was being computed in preparation to run.

If you ran `top` or `htop`, was CPAC using any cores?

**Comment by mk2299** [comment]
Hi, here is the screen shot of the error message I am getting. 
![screen shot 2017-12-02 at 1 19 51 pm](https://user-images.githubusercontent.com/33186673/33518485-a6c92230-d763-11e7-98a1-261d05da7d96.png)
It gives a TypeError. Thanks! Would really appreciate any feedback. 

P.S. CPAC wasn't using any cores. I was just trying it out on a single subject.

**Comment by effigies** [comment]
It looks like you have a modified version of nipype installed? That line in nipype is `for child in func():`:

https://github.com/nipy/nipype/blob/b401014954aabc92e4084faf0caeb6d7ff3c7fff/nipype/pipeline/engine/utils.py#L384

**Comment by satra** [comment]
@sgiavasis - can you please take a look at this issue?

**Comment by anibalsolon** [comment]
Duplicated of https://github.com/FCP-INDI/C-PAC/issues/706
Should be closed for now, since it looks like a C-PAC/pipeline setup problem.

**Comment by effigies** [comment]
Sounds good. @mk2299 please reopen if this is not resolved or you believe there's something to be done on our end.
