### ISSUE TITLE
spm.EstimateModel & spm.EstimateContrast give error although completing

### ISSUE THREAD

**Issue by SebastianSpeer** [nipy/nipype#2340]
### Summary
When running spm.EstimateModel & spm.EstimateContrast:
```
print "- Estimate",
level1estimate = spm.EstimateModel()
level1estimate.inputs.estimation_method = {'Classical': 1}
level1estimate.inputs.spm_mat_file = '/data/sebastian/SPD/Firstlevel/unvariate/SPM.mat'
level1estimate.inputs.use_mcr=True
level1estimate.inputs.mfile=False
out = level1estimate.run()
```
```
print "- Contrast",
level1contrast = spm.EstimateContrast()
level1contrast.inputs.spm_mat_file = '/data/sebastian/SPD/Firstlevel/unvariate/SPM.mat'
level1contrast.inputs.beta_images = glob('/data/sebastian/SPD/Firstlevel/unvariate/beta*')
level1contrast.inputs.residual_image =glob('/data/sebastian/SPD/Firstlevel/unvariate/Res*')[0]
# Condition names DID
condition_names = ['Disg', 'Neutral']

cont01=['Disgusting>Baseline','T', condition_names,[1,0]]
cont02=['Neutral>Baseline','T', condition_names,[0,1]]
cont03=['Disgusting>Neutral','T',condition_names,[1,-1]]
cont04=['Neutral>Disgusting','T', condition_names,[-1,1]]
#cont05=['fd>Baseline','T',['FD'],[1]]
contrast_list = [cont01, cont02, cont03, cont04]
level1contrast.inputs.contrasts = contrast_list
out=level1contrast.run()
```

 I get the following error:

`AttributeError: 'NoneType' object has no attribute 'split'`

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`
```
import nipype
nipype.get_info()
print(nipype.get_info(),nipype.__version__)
```
`({'nibabel_version': '2.2.1', 'sys_executable': '/home/sebastian/anaconda2/bin/python', 'networkx_version': '2.0', 'numpy_version': '1.13.3', 'sys_platform': 'linux2', 'sys_version': '2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'commit_hash': 'ac1412ff', 'pkg_path': '/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype', 'nipype_version': '0.14.0-rc1', 'traits_version': '4.6.0', 'scipy_version': '1.0.0'}, u'0.14.0-rc1')
`

### Execution environment

I'm running in a Jupyter notebook on a VM running on  ubuntu 14.04

**Comment by djarecka** [comment]
Do you have the same error with both interfaces or one of them? Can you please specify and try to create a minimal example.

Please, paste entire error message.

**Comment by SebastianSpeer** [comment]
I get the same error with both interfaces.

```

print "- Estimate",
level1estimate = spm.EstimateModel()
level1estimate.inputs.estimation_method = {'Classical': 1}
level1estimate.inputs.spm_mat_file = '/data/sebastian/SPD/Firstlevel/unvariate/model/SPM.mat'
level1estimate.inputs.use_mcr=True
level1estimate.inputs.mfile=False
out = level1estimate.run()
```

```
- Estimate

AttributeErrorTraceback (most recent call last)
<ipython-input-30-af2a668588f9> in <module>()
      5 level1estimate.inputs.use_mcr=True
      6 level1estimate.inputs.mfile=False
----> 7 out = level1estimate.run()

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in run(self, **inputs)
   1087         try:
   1088             runtime = self._run_interface(runtime)
-> 1089             outputs = self.aggregate_outputs(runtime)
   1090         except Exception as e:
   1091             import traceback

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in aggregate_outputs(self, runtime, needed_outputs)
   1152         """
   1153 
-> 1154         predicted_outputs = self._list_outputs()
   1155         outputs = self._outputs()
   1156         if predicted_outputs:

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/model.pyc in _list_outputs(self)
    255         outputs = self._outputs().get()
    256         pth = os.path.dirname(self.inputs.spm_mat_file)
--> 257         outtype = 'nii' if '12' in self.version.split('.')[0] else 'img'
    258         spm = sio.loadmat(self.inputs.spm_mat_file, struct_as_record=False)
    259 

AttributeError: 'NoneType' object has no attribute 'split'

```


```
print "- Contrast",
level1contrast = spm.EstimateContrast()
level1contrast.inputs.spm_mat_file = '/data/sebastian/SPD/Firstlevel/unvariate/SPM.mat'
level1contrast.inputs.beta_images = glob('/data/sebastian/SPD/Firstlevel/unvariate/beta*')
level1contrast.inputs.residual_image =glob('/data/sebastian/SPD/Firstlevel/unvariate/Res*')[0]
# Condition names DID
condition_names = ['Disg', 'Neutral']

cont01=['Disgusting>Baseline','T', condition_names,[1,0]]
cont02=['Neutral>Baseline','T', condition_names,[0,1]]
cont03=['Disgusting>Neutral','T',condition_names,[1,-1]]
cont04=['Neutral>Disgusting','T', condition_names,[-1,1]]
#cont05=['fd>Baseline','T',['FD'],[1]]
contrast_list = [cont01, cont02, cont03, cont04]
level1contrast.inputs.contrasts = contrast_list
out=level1contrast.run()
```

```
 - Contrast

AttributeErrorTraceback (most recent call last)
<ipython-input-38-acdc3873f045> in <module>()
     14 contrast_list = [cont01, cont02, cont03, cont04]
     15 level1contrast.inputs.contrasts = contrast_list
---> 16 out=level1contrast.run()

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in run(self, **inputs)
   1087         try:
   1088             runtime = self._run_interface(runtime)
-> 1089             outputs = self.aggregate_outputs(runtime)
   1090         except Exception as e:
   1091             import traceback

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in aggregate_outputs(self, runtime, needed_outputs)
   1152         """
   1153 
-> 1154         predicted_outputs = self._list_outputs()
   1155         outputs = self._outputs()
   1156         if predicted_outputs:

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/model.pyc in _list_outputs(self)
    466             outputs['con_images'] = con_images
    467             outputs['spmT_images'] = spmT_images
--> 468         spm12 = '12' in self.version.split('.')[0]
    469         if spm12:
    470             ess = glob(os.path.join(pth, 'ess*.nii'))

AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by satra** [comment]
@SebastianSpeer - it can't find spm. you can test this by doing:

```python
from nipype.interfaces import spm
spm.SPMCommand().version
```

either spm has to be in your matlab path or you need to explicitly set the paths in your python script using SPMCommand.

**Comment by SebastianSpeer** [comment]
@satra  

I'm using a standalone SPM and I'm starting SPM with:
```
matlab_cmd = '/home/ubuntu/spm12/run_spm12.sh /home/ubuntu/MCR/v713/ script'
spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)
```
spm.SPMCommand().version gives:

`None`

**Comment by SebastianSpeer** [comment]
@satra 

So if I use a standalone SPM and add this to line to the beginning of my code and spm.SPMCommand().version still gives "None". What else can I try?

**Comment by satra** [comment]
@SebastianSpeer  - i am a bit at a loss  as to what's causing your problem. i have tried several computers and all of them give me the version.

for example you can try this: 

https://mybinder.org/v2/gh/miykael/nipype_tutorial/master

and open a new notebook, type the commands i listed earlier, and then execute the cell. that service uses SPM via MCR.

that version check code requires two things: an MCR or MATLAB in your path and a valid spm directory

you could turn on nipype debugging.

```
from nipype import config, logging
config.enable_debug_mode()
logging.update_logging(config)
```
that should print an error message when version is returning None.

**Comment by SebastianSpeer** [comment]
@satra 

When I run it in your notebook it works indeed.
also when I execute :
'/home/ubuntu/spm12/run_spm12.sh /home/ubuntu/MCR/v713/ script'
It runs fine.

However, when I run it in the notebook the `spm.SPMCommand().version` still gives me` None`.

**Comment by satra** [comment]
@SebastianSpeer - did you turn on debugging mode for your local test?

**Comment by SebastianSpeer** [comment]
`from nipype import config, logging
config.enable_debug_mode()
logging.update_logging(config)
import nipype.interfaces.spm as spm 
matlab_cmd = '/home/ubuntu/spm12/run_spm12.sh /home/ubuntu/MCR/v713/ script'
spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)
spm.SPMCommand().version`

```
171214-15:46:23,564 interface DEBUG:
	 command 'matlab' could not be found on host 145
```

**Comment by djarecka** [comment]
@SebastianSpeer - do you still have this problem?

**Comment by SebastianSpeer** [comment]
@djarecka - Yes, the problem still persists. Oddly, when running a first level analysis spm.Level1Design() works without throwing an error, but spm.EstimateModel() and spm.EstimateContrasts both result in the error:


```
AttributeErrorTraceback (most recent call last)
<ipython-input-97-373dabe533e8> in <module>()
      5 level1estimate.inputs.use_mcr=True
      6 level1estimate.inputs.mfile=False
----> 7 out = level1estimate.run()

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in run(self, **inputs)
   1087         try:
   1088             runtime = self._run_interface(runtime)
-> 1089             outputs = self.aggregate_outputs(runtime)
   1090         except Exception as e:
   1091             import traceback

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in aggregate_outputs(self, runtime, needed_outputs)
   1152         """
   1153 
-> 1154         predicted_outputs = self._list_outputs()
   1155         outputs = self._outputs()
   1156         if predicted_outputs:

/home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/model.pyc in _list_outputs(self)
    255         outputs = self._outputs().get()
    256         pth = os.path.dirname(self.inputs.spm_mat_file)
--> 257         outtype = 'nii' if '12' in self.version.split('.')[0] else 'img'
    258         spm = sio.loadmat(self.inputs.spm_mat_file, struct_as_record=False)
    259 

AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by djarecka** [comment]
Ok, I'll find some time soon to take a look. However, I'd like to know if this errors are from pure Python or you have them only in the Notebook?
Do you run any script before this workflows?

**Comment by SebastianSpeer** [comment]
I am running this script first to initialize SPM and FSL. If I run the scripts from the terminal it works fine without the error. So the error only occurs in the notebook.

```
import os, subprocess
import nipype
import nipype.interfaces.spm as spm
import nipype.interfaces.fsl as fsl

def init():
    matlab_cmd = '/home/ubuntu/spm12/run_spm12.sh /home/ubuntu/MCR/v713/ script'
    spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)

    FSLDIR = '/usr/share/fsl/5.0'

    if os.getenv("FSLDIR") == None:
        os.environ['FSLDIR'] = FSLDIR

    if os.getenv("FSLOUTPUTTYPE") == None:
        os.environ['FSLOUTPUTTYPE'] = 'NIFTI_GZ'
 
    if 'fsl' not in os.environ["PATH"]:
        pathvar = os.environ["PATH"]
        os.environ["PATH"] = FSLDIR+'/bin' + os.pathsep + pathvar

    if os.getenv("LD_LIBRARY_PATH") == None:
        os.environ["LD_LIBRARY_PATH"] = '/usr/lib/fsl/5.0'
    elif 'fsl' not in os.environ["LD_LIBRARY_PATH"]:
        os.environ["LD_LIBRARY_PATH"] += os.pathsep + '/usr/lib/fsl/5.0'  

    #res = subprocess.call('/etc/fsl/5.0/fsl.sh',shell=True)

    fsl.FSLCommand.set_default_output_type('NIFTI')

    if 'afni/bin' not in os.environ["PATH"]:
        os.environ["PATH"] += os.pathsep + '/usr/lib/afni/bin'

    FREESURFER_HOME='/data/freesurfer'
    if os.getenv("FREESURFER_HOME") == None:
        os.environ['FREESURFER_HOME'] = FREESURFER_HOME
```

**Comment by djarecka** [comment]
I've noticed that you don't provide `paths` argument when you call `spm.SPMCommand.set_mlab_paths`. Can you try to provide a proper `paths` and see if this helps?

**Comment by djarecka** [comment]
if it doesn't help, we can compare your environmental variables from jupyter and from python interpreter, running`os.environ`.

**Comment by djarecka** [comment]
@SebastianSpeer are you still working on it or this issue can be closed?

**Comment by djarecka** [comment]
@SebastianSpeer - closing the issue for now, please feel free to reopen.

**Comment by SebastianSpeer** [comment]
Hi, I am sorry for the delayed response I have been on holidays for some time.
The issue still has not been resolved.

The suggestion regarding the paths did not help.

for the `os.environ` in the Jupyter notebook I get the following output:
`{'FSLDIR': '/usr/share/fsl/5.0', 'POSSUMDIR': '/usr/share/fsl/5.0', 'UPSTART_EVENTS': 'runlevel', 'FSLREMOTECALL': '', 'USER': 'sebastian', 'HOME': '/home/sebastian', 'PATH': '/home/sebastian/anaconda2/bin:/usr/lib/fsl/5.0:/data/sebastian/ICA-AROMA:/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib/afni/bin', 'LD_LIBRARY_PATH': '/usr/lib/fsl/5.0', 'previous': 'N', 'LANG': 'en_US.UTF-8', 'FSLLOCKDIR': '', 'TERM': 'xterm-color', 'SHELL': '/bin/bash', 'FSLBROWSER': '/etc/alternatives/x-www-browser', 'SHLVL': '1', 'PREVLEVEL': 'N', 'FREESURFER_HOME': '/data/freesurfer', 'UPSTART_INSTANCE': '', 'runlevel': '2', 'LOGNAME': 'sebastian', 'FSLWISH': '/usr/bin/wish', 'XDG_RUNTIME_DIR': '/run/user/1002', 'JPY_PARENT_PID': '1459', 'UPSTART_JOB': 'rc', 'GIT_PAGER': 'cat', 'XDG_SESSION_ID': 'c2', '_': '/home/sebastian/anaconda2/bin/jupyter', 'FSLOUTPUTTYPE': 'NIFTI_GZ', 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline', 'FSLMACHINELIST': '', 'FSLMULTIFILEQUIT': 'TRUE', 'OLDPWD': '/', 'FSLTCLSH': '/usr/bin/tclsh', 'CLICOLOR': '1', 'PWD': '/data', 'RUNLEVEL': '2', 'MAIL': '/var/mail/sebastian', 'PAGER': 'cat', 'XDG_SEAT': 'seat0'}`

from the python interpreter I get:
`{'FSLDIR': '/usr/local/fsl', 'GLADE_PIXMAP_PATH': ':', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/sebastian', 'UPSTART_EVENTS': 'started xsession', 'XDG_RUNTIME_DIR': '/run/user/1002', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LOGNAME': 'sebastian', 'USER': 'sebastian', 'HOME': '/home/sebastian', 'XDG_VTNR': '7', 'PATH': '/home/sebastian/anaconda2/bin:/usr/local/fsl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'DISPLAY': ':0.0', 'SSH_AGENT_PID': '1685', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/sebastian/.Xauthority', 'LANGUAGE': 'en_US', 'SESSION_MANAGER': 'local/145:@/tmp/.ICE-unix/1792,unix/145:/tmp/.ICE-unix/1792', 'SHLVL': '1', 'MANDATORY_PATH': '/usr/share/gconf/xubuntu.mandatory.path', 'TEXTDOMAIN': 'im-config', 'UPSTART_INSTANCE': '', 'JOB': 'dbus', 'WINDOWID': '38249172', 'SESSIONTYPE': '', 'IM_CONFIG_PHASE': '1', 'GLADE_CATALOG_PATH': ':', 'SELINUX_INIT': 'YES', 'GLADE_MODULE_PATH': ':', 'INSTANCE': '', 'SSH_AUTH_SOCK': '/tmp/ssh-hOXYcGBUNdR8/agent.1683', 'GDMSESSION': 'xubuntu', 'UPSTART_JOB': 'startxfce4', 'TEXTDOMAINDIR': '/usr/share/locale/', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_CURRENT_DESKTOP': 'XFCE', 'XDG_SESSION_ID': 'c5', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-eI5ho5lDdm', '_': '/home/sebastian/anaconda2/bin/python', 'SESSION': 'xubuntu', 'DESKTOP_SESSION': 'xubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1002/1518', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-xubuntu:/usr/share/upstart/xdg:/etc/xdg:/etc/xdg', 'DEFAULTS_PATH': '/usr/share/gconf/xubuntu.default.path', 'GDM_LANG': 'en_US', 'XDG_DATA_DIRS': '/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share', 'PWD': '/home/sebastian/Desktop', 'SSH_AGENT_LAUNCHER': 'upstart', 'COLORTERM': 'xfce4-terminal', 'XDG_MENU_PREFIX': 'xfce-', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_SEAT': 'seat0'}`
