### ISSUE TITLE
Strip Base Directory From DataGrabber

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/nipype#2341]
### Summary
I would like to strip the base_directory from my variables when I connect them to different nodes. I enjoy the functionality that verifies whether particular subject ids and filenames exist, however when moving on to subsequent processes steps I would prefer to strip out the base directory and be able to just enter subject id or filename. 

Please help!

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by mgxd** [comment]
@tjhendrickson by removing the full path, the interfaces that follow the datagrabber node will not be able to find the file - did you run into a problem by including full paths?

**Comment by effigies** [comment]
You could use a function interface to parse components of the filename however you like, and wrap in a MapNode to apply to the full list of fetched files.

**Comment by tjhendrickson** [comment]
Good idea @effigies, thank you!
