### ISSUE TITLE
SPM Segment clarifications

### ISSUE THREAD

**Issue by mick-d** [nipy/nipype#2342]
Hi,

SPM 12 default segmentation corresponds to SPM 8 "New Segment". In NiPype I am not sure how to use the latest SPM 12 Segmentation (probably updated since the old SPM 8 "New Segment"), as:
- NiPype SPM Segment seems to correspond to SPM 8 "Old Segment"
- NiPype SPM New Segment seems to correspond to SPM 8 "New Segment", with the documentation indicating that it accepts multi-channels but with a note indicated multi-channel is not implemented

Then what should one choose to use the latest SPM 12 Segment (which is likely an updated version of the old SPM 8 "New Segment")? Shouldn't the default Segment correspond to that latest version?

Best,

Michael

**Comment by satra** [comment]
@mick-d - in spm there is a difference between the UI, and the underlying functions. in 12, they switched the ui pointers to their new routines. nipype interfaces at the level of the routines. so if you use new segment with spm12, you get the new segment routine. normalize12 specifically refers to spm12.

http://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.spm/preprocess.html

**Comment by mick-d** [comment]
Thanks @satra! The way to go is simply to use the NewSegment interface then, great.

I had a look into the source code and it was not clear to me if the NiPype interface supports multi-channel inputs. The NiPype documentation says `Supports multiple modalities. NOTE: This interface currently supports single channel input only.`

**Comment by jhuguetn** [comment]
Hi there,

It's been a while since this issue went live but, and recovering the initial thread idea, SPM's `NewSegment` interface still does not support the multi-channel segmentation feature which I think could be a good addition to nipype. Are there any _cons_ to that addition?

Segmentation using multiple scan types (e.g. T1w+T2w) may, in some scenarios, improve results over conventional single scan-only method.

**Comment by effigies** [comment]
Closed in #3162, I believe. Please reopen if something remains unresolved.
