### ISSUE TITLE
0.14.0 debian oldstable (9.0 stretch) traits 4.4.0 TraitError: Each key of the 'environ' trait of a MRIConvertInputSpec

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#2346]
### Summary

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/build/nipype-0.14.0/nipype/interfaces/freesurfer/base.py", line 134, in _subjects_dir_update
    self.inputs.subjects_dir})
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 3206, in update
    new_dic = self._validate_dic( dic )
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 3304, in _validate_dic
    raise excp
TraitError: Each key of the 'environ' trait of a MRIConvertInputSpec instance must be an implementor of, or can be adapted to implement, newbytes or None or an implementor of, or can be adapted to implement, newstr or None, but a value of u'SUBJECTS_DIR' <type 'unicode'> was specified.
== 277 failed, 2326 passed, 230 skipped, 7 xfailed, 7 error in 60.47 seconds ===
```

### Actual behavior
TraitError
### Expected behavior
no Error, tests pass
### How to replicate the behavior
try to test on Debian stretch (e.g. `docker pull neurodebian:nd90`)
### Platform details:
debian oldstable (9.0 stretch) traits 4.4.0

full log at http://neuro.debian.net/_files/_buildlogs/nipype/0.14.0/nipype_0.14.0-1~nd80+1_amd64.build

**Comment by mgxd** [comment]
@yarikoptic we've moved to support `traits >= 4.6.0`, does incrementing the version fix this?

**Comment by djarecka** [comment]
@yarikoptic please let us know if this is an issue with newer version of traits

**Comment by yarikoptic** [comment]
just limit version to be `>= 4.5` - builds/tests fine on Debian/Ubuntu systems with that version

**Comment by djarecka** [comment]
@satra @oesteban - any opinion? Moving from 4.5 didn't solve all of problems, but as far as I remember 4.6 did work better (especially on OSX)

**Comment by mgxd** [comment]
closing for now - reopen if needed
