### ISSUE TITLE
Node nii_wrangler.a0 failed to run on host

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/nipype#2370]
### Summary

I am attempting to run the nii_wrangler interface on my local machine, however I receive the following error message: **Node nii_wrangler.a0 failed to run on host**. I tried looking for dependencies for this interface, but couldn't track that down. What dependencies do I need and what other pieces might I need in order for this to run properly?

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by djarecka** [comment]
@tjhendrickson - could you please provide an example (preferable a short one) that leads to the issue together with the full error message?

Please, provide also the platform details.

**Comment by mgxd** [comment]
@tjhendrickson please reopen and provide the code you're using if this is still an issue
