### ISSUE TITLE
TestSignalExtraction.test_signal_extr_traits_valid failing

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2380]
### Summary

I just noticed that TestSignalExtraction.test_signal_extr_traits_valid is failing on my OSX with the message:
```
E           traits.trait_errors.TraitError: The trait 'out_file' of a SignalExtractionOutputSpec instance is an existing file name, but the path  '/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp_2bektow/SignalExtraction/signals.tsv' does not exist.
```
I can see that the file `signals.tsv` is being created but is being deleted [here](https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/nodes.py#L630). 

@oesteban I'll try to figure out why this happens on my OSX and not on CircleCI (or other Linux we tried today), but if you have any suggestions, please let me know.

**Comment by oesteban** [comment]
Looks a lot like poldracklab/fmriprep#936

**Comment by oesteban** [comment]
@djarecka  could you try on you OSX the PR referenced above? Thanks!

**Comment by djarecka** [comment]
it could be related to the temporary directory paths IMO.

i'm debugging it right now, and I can see that `needed file` [here](https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/utils.py#L1416) contains `signals.tsv` as `/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmpuuucmm6n/SignalExtraction/signals.tsv`
but file from `walks_files(cwd)` has `/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmpuuucmm6n/SignalExtraction/signals.tsv`.

**Comment by djarecka** [comment]
just run with your `oesteban-maint/node-hash` and the test is still failing

**Comment by djarecka** [comment]
@oesteban not sure if this helps, but only `signals.tsv` in `needed_files` has `/private` at the beginning, i.e.:
```
(Pdb) needed_files
['/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp1fmidn70/SignalExtraction/signals.tsv', '/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp1fmidn70/SignalExtraction/_0x074086d35e0945269f2581ef95cdb8c1_unfinished.json', '/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp1fmidn70/SignalExtraction/_inputs.pklz', '/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp1fmidn70/SignalExtraction/_node.pklz']
```

**Comment by oesteban** [comment]
Ok, this is the problem 
https://github.com/nipy/nipype/blob/045b28ef9056fac1107bc4f0707859d043f3bfd1/nipype/interfaces/nilearn.py#L109

which aligns well with [this discussion](https://github.com/nipy/nipype/pull/2368#discussion_r160794434) and the issue in fmriprep.

The problem, basically, is that interfaces shouldn't use `os.getcwd()` and stick with `runtime.cwd`. In general this shouldn't be a problem, but apparently `SimpleInterface` circumvents the change of directory in `Node`.

Since you are running step-by-step, would you mind checking why this line:

https://github.com/nipy/nipype/blob/f3b09125eceec7b90ad801176892aab06e012f8c/nipype/pipeline/engine/nodes.py#L462

seems not to be run with SimpleInterfaces (like SignalExtraction)?

**Comment by oesteban** [comment]
Got it. Working on a fix. Sorry for the issue.

**Comment by djarecka** [comment]
@oesteban sorry for late reply, had a lunch break. Let me know if there is something I can test for you

**Comment by djarecka** [comment]
#2384 solves the problem on my OSX!

**Comment by oesteban** [comment]
Oh, you are fast!

**Comment by djarecka** [comment]
@oesteban I just update my master and I have the issue again..:(

When I checked your branch oesteban-fix/2380 yesterday with the commit 653f690 it works, since you deleted this branch I'm not sure how to check the final changes introduced by your PR (master had a few more merges since yesterday)

**Comment by oesteban** [comment]
Okay, now the corresponding report.rst should have more info. What is the content of cwd and prevcwd when it breaks?

**Comment by djarecka** [comment]
in my `_reprt/report.rst` I can only find info about `Node` and `Original Input`:

Node: nilearn
=============


 Hierarchy : SignalExtraction
 Exec ID : SignalExtraction


Original Inputs
---------------


* class_labels : ['CSF', 'GrayMatter', 'WhiteMatter']
* detrend : False
* ignore_exception : False
* in_file : /private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/pytest-of-dorota/pytest-83/test0/fmri.nii
* incl_shared_variance : False
* include_global : False
* label_files : ['/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/pytest-of-dorota/pytest-83/test0/labels.nii']
* out_file : signals.tsv

**Comment by djarecka** [comment]
@oesteban
If runtime parameters were written in  the `report.rst` that would be:
`cwd: '/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmpjjlptgmu/SignalExtraction'`
`prevcwd: '/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/pytest-of-dorota/pytest-88/test0'`

But I found which changes cause the test failing on my OSX(I tested your branch before this commit):
https://github.com/nipy/nipype/pull/2384/commits/f4c3db723b405193b1406a7c512780a8615ab32e

**Comment by effigies** [comment]
That suggests that the interface isn't being run in the `runtime.cwd`, which seems to be a bigger problem. I'll have a look at this first thing in the morning. Oscar, ignore this thread.

**Comment by effigies** [comment]
Set this to 1.0 since. @satra @djarecka @mgxd if you think it's okay to release without resolving whether interfaces are running in their working directories, untag.

**Comment by djarecka** [comment]
@effigies just so you know why the f4c3db7 commit makes difference, when I check `os.path.abspath(self.inputs.out_file)` [here](https://github.com/nipy/nipype/blob/master/nipype/interfaces/nilearn.py#L109) I have:
`'/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmp5uxkdu21/SignalExtraction/signals.tsv'`

`runtime.cwd` doesn't have `/private/` at the beginning, i.e.: '/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmptnlizxv7/SignalExtraction'

so that's why the test ended up in the same place as on Thursday, i.e. [needed files](https://github.com/nipy/nipype/blob/master/nipype/pipeline/engine/utils.py#L1418) contains:
`'/private/var/folders/5s/hk2j7ylx54b2clm9bx1mpvj00000gq/T/tmptnlizxv7/SignalExtraction/signals.tsv'` (with this extra `private`)

fyi: on my OSX I can search either `private/var/folders/...` or `/var/folders/..`, they are the same. Not sure why OSX has this kind of structure...

**Comment by effigies** [comment]
@djarecka Can you run the following in a terminal?

```Shell
ls -ld / /private /var /private/var /var/folders /private/var/folders
```

It would be good to know what the symlink situation is.

**Comment by djarecka** [comment]
Witalis:~ dorota$ ls -ld / /private /var /private/var /var/folders /private/var/folders
drwxr-xr-x  36 root  wheel  1292 Jan 15 23:16 /
drwxr-xr-x@  6 root  wheel   204 Nov 10  2016 /private
drwxr-xr-x  28 root  wheel   952 Feb 27  2017 /private/var
drwxr-xr-x   9 root  wheel   306 Feb 27  2017 /private/var/folders
lrwxr-xr-x@  1 root  wheel    11 Nov 10  2016 /var -> private/var
drwxr-xr-x   9 root  wheel   306 Feb 27  2017 /var/folders

**Comment by effigies** [comment]
Okay. As I think about this I'm a little inclined just to revert f4c3db7. `os.path.join(runtime.cwd, ...)` is going to be robust to invalid `chdir`s and also doesn't have to use an unnecessary system call. And I'm having trouble seeing a case where this would go wrong that `os.path.abspath` wouldn't.

**Comment by djarecka** [comment]
It would solve problem for this test on OSX (at least my OSX, we might want to check with some other, more reliable OSX...)

But I still don't understand why for `test_signal_extr_traits_valid` my `runtime.cwd` is `/var/folders/` and for other `test_nilearn` `runtime.cwd` is `/private/var/folders`.

**Comment by satra** [comment]
on osx these two things differ, so it's possible that tmpdir is returning one of these in pytests:

```python
In [65]: os.path.abspath('/var/folders/ff/ttgp9pp94_7gfs7_5xn9f90c0000gl/0/com.apple.LaunchSer
    ...: vices')
Out[65]: '/var/folders/ff/ttgp9pp94_7gfs7_5xn9f90c0000gl/0/com.apple.LaunchServices'

In [66]: os.path.realpath('/var/folders/ff/ttgp9pp94_7gfs7_5xn9f90c0000gl/0/com.apple.LaunchSe
    ...: rvices')
Out[66]: '/private/var/folders/ff/ttgp9pp94_7gfs7_5xn9f90c0000gl/0/com.apple.LaunchServices'
```

**Comment by effigies** [comment]
It's almost certainly going to boil down to a `os.path.realpath` call, or possibly a quirk where `os.getcwd()` can result in expanding symlinks. But as long as we use `runtime.cwd` when it's available, then a rogue `chdir` or `realpath` won't affect the outputs.

Assuming that we aren't shooting for a deeper fix than this one line change (and I think we shouldn't), any objections to pushing a revert directly to master? Runs through tests once instead of twice.

**Comment by djarecka** [comment]
@satra I did check that changing to `realpath` [here](https://github.com/nipy/nipype/blob/master/nipype/interfaces/nilearn.py#L109) doesn solve the problem

**Comment by satra** [comment]
@djarecka - i don't think realpath generally helps with a solution :)

@effigies - fine with me.

**Comment by djarecka** [comment]
@effigies can you also comment on the sub-issue that I couldn't get any runtime info from `report.rst` file when the test was failing.

**Comment by effigies** [comment]
My guess would be that this is another function of a path mismatch, where the call to update the `report.rst` is also using a path that was canonicalized to include `/private`. (It's unclear to me why OSX would *care* whether the path had `/private` in it, as it's the exact same thing.)

**Comment by effigies** [comment]
But perhaps we should open a new issue to correctly handle temporary directories in OS X. I wouldn't target 1.0, though. My feeling is that it's enough of an edge case that we can resolve by telling people to set a `base_dir`.

**Comment by oesteban** [comment]
I'll keep track of https://github.com/poldracklab/fmriprep/issues/936 where something very similar is happening without pytest, on a linux setup.

**Comment by achetverikov** [comment]
I had a lot of weird issues after updating to 1.01 before I realized that the nodes run from the main script directory instead of their own folders for some reason. Changing the base_dir to the absolute path without symlinks helped.

**Comment by oesteban** [comment]
I think what @achetverikov said is still necessary.

> I had a lot of weird issues after updating to 1.01 before I realized that the nodes run from the main script directory instead of their own folders for some reason. Changing the base_dir to the absolute path without symlinks helped.

**Comment by djarecka** [comment]
@oesteban I recently wrote #2639 , can you please see if this doesn't solve the problem

**Comment by oesteban** [comment]
Cool, I'll reopen if that did not work.

**Comment by djarecka** [comment]
@oesteban - sure, we also have #2395 on our watchlist.
