### ISSUE TITLE
How to specify an exact filename for DataSink output?

### ISSUE THREAD

**Issue by achetverikov** [nipy/nipype#2388]
Is it possible to set an exact filename for DataSink output? E.g., I have three nodes that output registration headers and I want to save them in the same folder but with different names:
```
combine_masks.connect(func_to_t1main_bb, 'out_reg_file', main_out, 'MRI.PREPROC.REG.A.dat')
combine_masks.connect(func_to_t1main_tk, 'out_reg_file', main_out, 'MRI.PREPROC.REG.B.dat')
combine_masks.connect(func_to_t1main_fl, 'out_reg_file', main_out, 'MRI.PREPROC.REG.C.dat')
```
where A.dat, B.dat, and C.dat should be the desired names. I know that DataSink has regex substitution, but it's not convenient when the inputs have the same filenames. I can use a workaround (see below) by setting a fake directory in DataSink outputs and then replacing it with a substitution, but it looks like a very ugly solution, so I was hoping for something better.
Current workaround:
```
combine_masks.connect(func_to_t1main_bb, 'out_reg_file', main_out, 'MRI.PREPROC.REG_A')
main_out.inputs.regexp_substitutions = [('/REG_A/','/REG/funct_to_t1main_bb.dat')]
```

**Comment by effigies** [comment]
Have you looked at the Rename interface? This is very flexible and can probably do what you want.

**Comment by achetverikov** [comment]
Thanks for the replies! 

@effigies I was hoping to avoid adding more nodes. 
@mgxd "@" notation does not rename the outputs, as far as I understand, it's simply a stub to put different files in the same folder. Or am I missing something?

**Comment by satra** [comment]
@achetverikov - you can use regexes or simple substitutions to rename the output.

simple substitution example:
https://miykael.github.io/nipype_tutorial/notebooks/basic_data_output.html#DataSink

regexp substitution example:
https://github.com/nipy/nipype/blob/b3dacd070f0e768b434b512d468496fc75c61c9a/examples/rsfmri_vol_surface_preprocessing_nipy.py#L853

generally the way we determine this is to run a workflow normally and then figure out what the substitutions will be (since order of substitution matters - all substitutions are applied in order).

**Comment by satra** [comment]
@achetverikov - sorry didn't see that you are already using regexp. i think with a regexp you can group the working directory name of the input. i.e. match a previous section of the path and use that as a variable in your output.

**Comment by achetverikov** [comment]
@satra OK, thanks! regexp is the answer then.

**Comment by satra** [comment]
something like this:

```python
In [79]: p1
Out[79]: '/folder1/file.txt'

In [80]: p2
Out[80]: '/folder2/file.txt'

In [81]: re.subn(r'/(folder\d+)/file.txt', r'file_\1.txt', p1) 
Out[81]: ('file_folder1.txt', 1)

In [82]: re.subn(r'/(folder\d+)/file.txt', r'file_\1.txt', p2) 
Out[82]: ('file_folder2.txt', 1)
```
