### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by emdupre** [nipy/nipype#2390]
I'd like to update the contributing guidelines to explicitly link to the [documentation on how to specify new interfaces](http://nipype.readthedocs.io/en/latest/devel/interface_specs.html).

Since I'd be updating the file, is there any preference on whether I update its general format to be more beginner friendly? Something like the current [FMRIPREP contributing guidelines](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md).

**Comment by effigies** [comment]
👍 to beginner friendliness. Due to relatively high activity at the moment, for simple doc updates, please use `[skip ci]` somewhere in your commit messages.

**Comment by mgxd** [comment]
@emdupre thanks, that would be appreciated! We could probably also drop the `contributing issues` section since we now have an issue template for the project

**Comment by satra** [comment]
@emdupre - i guess i can't call nipype a "young project" anymore :) perhaps any updates to the documentation would also be much appreciated.

**Comment by djarecka** [comment]
I guess not as young anymore :) the documentation suggests using traits 3.x ;-)

**Comment by mwaskom** [comment]
> i guess i can't call nipype a "young project" anymore :) perhaps any updates to the documentation would also be much appreciated.

Nipype could have a phd now! Also, the mailing list address on that page needs to be updated.

**Comment by emdupre** [comment]
I went ahead and opened #2393 to starting addressing this !

@effigies, I included `[skip ci]` in the commit and PR but it still seems to have triggered circle. Any pointers for how to avoid that in submitting future commits ?

**Comment by effigies** [comment]
It may have been triggered by opening the PR, and Circle didn't check the commit message. I'm not sure whether that's a bug or a feature... I went ahead and canceled the build.

**Comment by djarecka** [comment]
actually only one CircleCi was triggered, the one that check images, am I right? or you canceled before I checked it?

**Comment by effigies** [comment]
I canceled it before it started running, so the other jobs wouldn't have been queued.
