### ISSUE TITLE
update tutorial for interface creation

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2391]
### Summary
the current tutorial lacks a section for creating interfaces.

we should add a create your own interface section (for python, matlab, command line interfaces) to the tutorial (https://miykael.github.io/nipype_tutorial/) that replaces the documentation in the longer run. cc: @djarecka  @miykael

**Comment by emdupre** [comment]
This would be great! The 2017 OHBM "AFNI Love" team might also be able to help, since we spent most of the hack learning how to add interfaces (we didn't know there were developer docs ! 😅). cc: @tsalo @Shotgunosine @62442katieb

**Comment by djarecka** [comment]
@emdupre that would be great if you can help with creating this section of the tutorial!

**Comment by oesteban** [comment]
This resource could also serve for brain storming: https://github.com/nipy/workshops/blob/master/170327-nipype/notebooks/new-workflows-and-interfaces/advanced_interfaces.ipynb

**Comment by 62442katieb** [comment]
I'd be happy to help @emdupre

**Comment by miykael** [comment]
@oesteban's `advanced_interfaces` notebook was added to the nipype tutorial with https://github.com/miykael/nipype_tutorial/pull/72.

This issue could therefore be closed. Except if more content should be added to the notebook? For the moment it covers `CommandLine`, `Python` and `MATLAB`/`Octave` interfaces.

**Comment by satra** [comment]
closed via https://github.com/miykael/nipype_tutorial/pull/72
