### ISSUE TITLE
Inconsistent hashes for the same output

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2404]
I'm seeing that `nipype.interfaces.freesurfer.utils.LTAConvert` is producing different hashes for the same file (same contents). We use it in [FMRIPREP here](https://github.com/poldracklab/fmriprep/blob/a5d4b3689974b24c297cb3a0a7f434892aef6710/fmriprep/workflows/anatomical.py#L1168).

On a first run I got:

```
	 [Node] Outdated cache found for "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_derivatives_wf.lta_2_itk".
180126-02:17:28,662 workflow VERBOSE:
	 [Node] Old/new hashes = d7de0665bb20748f2eec238105b02dd8/6c90808591574e80c738cb685bef419e
180126-02:17:28,664 workflow VERBOSE:
	           Some dictionary entries had differing values:
            * in_lta: ('/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/t1_2_fsnative_xfm/out.lta', 'cd799f450e6abf6b125433049fba64e4') != ['/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/t1_2_fsnative_xfm/out.lta', '8f01b86f62ded5a17bfc9ccb165d1351']
```
A second run gave:
```
	 [Node] Outdated cache found for "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_derivatives_wf.lta_2_itk".
180126-02:55:13,221 workflow VERBOSE:
	 [Node] Old/new hashes = d7de0665bb20748f2eec238105b02dd8/6c90808591574e80c738cb685bef419e
180126-02:55:13,222 workflow VERBOSE:
	           Some dictionary entries had differing values:
            * in_lta: ('/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/t1_2_fsnative_xfm/out.lta', 'cd799f450e6abf6b125433049fba64e4') != ['/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/t1_2_fsnative_xfm/out.lta', '8f01b86f62ded5a17bfc9ccb165d1351']
```

I've manually checked the md5sum (using the linux tool instead of nipype) of `/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/t1_2_fsnative_xfm/out.lta` in both runs, and both gave the same value `c4fafdaf1fa60a83965095fb6a233f09`.

Seems like the hash stored by the interface (`8f01b86f62ded5a17bfc9ccb165d1351`) is different from the hash it calculates to check if the inputs changed (`cd799f450e6abf6b125433049fba64e4`). To add on the problem, the md5sum calculated with other tools does not match the hash calculated by nipype.

@satra, can you think of a lead to debug this issue?

**Comment by oesteban** [comment]
Running this in a different system, with the same file:

```Python
>>> from nipype.interfaces.freesurfer.utils import LTAConvert
>>> from nipype.pipeline import engine as pe
>>> lta_2_itk = pe.Node(LTAConvert(out_itk=True), name='lta_2_itk')
>>> lta_2_itk.inputs.in_lta = 'out.lta'
>>> lta_2_itk.is_cached()
>>> lta_2_itk._hashed_inputs
[('in_lta', ('out.lta', '452351a5e6e9014b5fb5b0762928f68a')),
 ('out_itk', True)]
```
while the md5 sum of out.lta is `c4fafdaf1fa60a83965095fb6a233f09`.

**Comment by oesteban** [comment]
okay, the default hash method is timestamp ... sorry for the noise

**Comment by satra** [comment]
@oesteban - for 2.0 i think i would change the default to content, especially as we will also target a distributed cache. and my thought is that the hash computation will be a little more complex instead of just bitwise. each interface can implement it's own hashing. the default will still be bitwise.

**Comment by tashrifbillah** [comment]
@oesteban , how do I manually calculate the hash that is stored in `.json` file?

Should I do `ls -la myFile.txt` ,

`-rw-r--r--. 1 tb571 PosixUsers 508 Nov  6 14:24`

And then `hashlib.md5('Nov  6 14:24'.encode('utf-8')).hexdigest()` ? I did this but the obtained hash doesn't match with the stored hash pertinent to one of my input files to the pipeline.

**Comment by tashrifbillah** [comment]
I found it. Here is the function:
https://github.com/nipy/nipype/blob/865adc91535e9fc7aeccfd5d9f6527af756b3b70/nipype/utils/filemanip.py#L302

Thanks.
