### ISSUE TITLE
Nipype warning: could not get linked libraries

### ISSUE THREAD

**Issue by meenakshik1993** [nipy/nipype#2419]
Hi, 

I am running a pipeline using nipype. I get the following warning almost for every node but still the pipeline runs without any error. 

WARNING: Could not get linked libraries for "%s"

Is this a cause for concern that something did not execute as it should have?

Thanks!

Best,
Meenakshi

**Comment by mgxd** [comment]
@meenakshik1993 this was just a visual bug that should have been fixed in #2322 - could you update to the latest nipype (1.0.0) and retry?
