### ISSUE TITLE
ICC: Cannot set the undefined 'sessions_F_map' attribute of a 'ICCOutputSpec' object

### ISSUE THREAD

**Issue by dangom** [nipy/nipype#2421]
### Summary

Trying to run ICC raises a `TraitError` with the following description: "TraitError: Cannot set the undefined 'sessions_F_map' attribute of a 'ICCOutputSpec' object."
I may be doing things wrong, in which case a more informative error message would be welcome. Please look at the code snippet under _Script/Workflow Details_.

_Note:_ I do get maps (icc_map.nii, session_var_map.nii, subject_var_map.nii) as an output in my `os.getcwd()`.

### Actual behavior
ICC triggers an exception.

### Expected behavior
ICC runs smoothly.

### How to replicate the behavior
```bash
mkdir /Users/user/test
mv mask.nii.gz sub-{01,02}_ses-{01,02}.nii.gz /Users/user/test
# Where these niftis are sensible "ICC compatible" files
# And now run code pasted below
```
### Script/Workflow details

Please put URL to code or code here (if not too long).
```python
import os.path
from nipype.algorithms import icc

project_dir = '/Users/user/test/'

def fname(sub, ses):
    return os.path.join(project_dir, f'sub-{sub}_ses-{ses}.nii.gz')

lst = [[fname(1, 1), fname(1, 2)], 
       [fname(2, 1), fname(2, 2)]]
mask = os.path.join(project_dir, 'mask.nii.gz')

x = icc.ICC(subjects_sessions=lst, mask=mask)
x.run()
```

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

```python
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.0',
 'nibabel_version': '2.2.1',
 'nipype_version': '1.0.0',
 'numpy_version': '1.13.3',
 'pkg_path': '/Users/user/anaconda3/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.0.0',
 'sys_executable': '/Users/user/anaconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]',
 'traits_version': '4.6.0'}

```

### Execution environment

Choose one
- My python environment outside container

**Comment by djarecka** [comment]
@dangom - thank you for reporting, it looks like these are some remains after old version
