### ISSUE TITLE
Nipype installation failure

### ISSUE THREAD

**Issue by BaharJa** [nipy/nipype#2434]
### Summary
I am having problem with nipy installation. I read similar issue but none of them solved the problem like upgrading the setup tools  .  
### Actual behavior
The problem is when I enter python -m pip install nipy the error shows up that saying the system cannot find the file specified, and complied failed with the error code pip-build-k2650 and addressing Appdate/Local/Temp/pip-build.., while the python installed on drive C:\Python.
### Script/Workflow details
C:\Users\Bahar>python -m pip install nipy
Collecting nipy
  Using cached nipy-0.4.1.zip
Collecting nibabel>=1.2 (from nipy)
  Using cached nibabel-2.2.1.zip
Collecting sympy>=0.7.0 (from nipy)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))': /simple/sympy/
  Using cached sympy-1.1.1.tar.gz
Collecting mpmath>=0.19 (from sympy>=0.7.0->nipy)
  Using cached mpmath-1.0.0.tar.gz
Installing collected packages: nibabel, mpmath, sympy, nipy
  Running setup.py install for nibabel ... error
    Complete output from command C:\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Bahar\\AppData\\Local\\Temp\\pip-build-k2650exj\\nibabel\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Bahar\AppData\Local\Temp\pip-tsa3_m1w-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\nibabel
    copying nibabel\affines.py -> build\lib\nibabel
    copying nibabel\analyze.py -> build\lib\nibabel
    copying nibabel\arrayproxy.py -> build\lib\nibabel
    copying nibabel\arraywriters.py -> build\lib\nibabel
    copying nibabel\batteryrunners.py -> build\lib\nibabel
    copying nibabel\casting.py -> build\lib\nibabel
    copying nibabel\checkwarns.py -> build\lib\nibabel
    copying nibabel\data.py -> build\lib\nibabel
    copying nibabel\dataobj_images.py -> build\lib\nibabel
    copying nibabel\deprecated.py -> build\lib\nibabel
    copying nibabel\deprecator.py -> build\lib\nibabel
    copying nibabel\dft.py -> build\lib\nibabel
    copying nibabel\ecat.py -> build\lib\nibabel
    copying nibabel\environment.py -> build\lib\nibabel
    copying nibabel\eulerangles.py -> build\lib\nibabel
    copying nibabel\filebasedimages.py -> build\lib\nibabel
    copying nibabel\fileholders.py -> build\lib\nibabel
    copying nibabel\filename_parser.py -> build\lib\nibabel
    copying nibabel\fileslice.py -> build\lib\nibabel
    copying nibabel\fileutils.py -> build\lib\nibabel
    copying nibabel\funcs.py -> build\lib\nibabel
    copying nibabel\imageclasses.py -> build\lib\nibabel
    copying nibabel\imageglobals.py -> build\lib\nibabel
    copying nibabel\info.py -> build\lib\nibabel
    copying nibabel\keywordonly.py -> build\lib\nibabel
    copying nibabel\loadsave.py -> build\lib\nibabel
    copying nibabel\minc.py -> build\lib\nibabel
    copying nibabel\minc1.py -> build\lib\nibabel
    copying nibabel\minc2.py -> build\lib\nibabel
    copying nibabel\mriutils.py -> build\lib\nibabel
    copying nibabel\nifti1.py -> build\lib\nibabel
    copying nibabel\nifti2.py -> build\lib\nibabel
    copying nibabel\onetime.py -> build\lib\nibabel
    copying nibabel\openers.py -> build\lib\nibabel
    copying nibabel\optpkg.py -> build\lib\nibabel
    copying nibabel\orientations.py -> build\lib\nibabel
    copying nibabel\parrec.py -> build\lib\nibabel
    copying nibabel\parrec2nii_cmd.py -> build\lib\nibabel
    copying nibabel\pkg_info.py -> build\lib\nibabel
    copying nibabel\processing.py -> build\lib\nibabel
    copying nibabel\py3k.py -> build\lib\nibabel
    copying nibabel\pydicom_compat.py -> build\lib\nibabel
    copying nibabel\quaternions.py -> build\lib\nibabel
    copying nibabel\rstutils.py -> build\lib\nibabel
    copying nibabel\spaces.py -> build\lib\nibabel
    copying nibabel\spatialimages.py -> build\lib\nibabel
    copying nibabel\spm2analyze.py -> build\lib\nibabel
    copying nibabel\spm99analyze.py -> build\lib\nibabel
    copying nibabel\tmpdirs.py -> build\lib\nibabel
    copying nibabel\trackvis.py -> build\lib\nibabel
    copying nibabel\tripwire.py -> build\lib\nibabel
    copying nibabel\viewers.py -> build\lib\nibabel
    copying nibabel\volumeutils.py -> build\lib\nibabel
    copying nibabel\wrapstruct.py -> build\lib\nibabel
    copying nibabel\xmlutils.py -> build\lib\nibabel
    copying nibabel\__init__.py -> build\lib\nibabel
    creating build\lib\nibabel\externals
    copying nibabel\externals\netcdf.py -> build\lib\nibabel\externals
    copying nibabel\externals\six.py -> build\lib\nibabel\externals
    copying nibabel\externals\__init__.py -> build\lib\nibabel\externals
    creating build\lib\nibabel\externals\tests
    copying nibabel\externals\tests\test_netcdf.py -> build\lib\nibabel\externals\tests
    copying nibabel\externals\tests\test_six.py -> build\lib\nibabel\externals\tests
    copying nibabel\externals\tests\__init__.py -> build\lib\nibabel\externals\tests
    creating build\lib\nibabel\gifti
    copying nibabel\gifti\gifti.py -> build\lib\nibabel\gifti
    copying nibabel\gifti\giftiio.py -> build\lib\nibabel\gifti
    copying nibabel\gifti\parse_gifti_fast.py -> build\lib\nibabel\gifti
    copying nibabel\gifti\util.py -> build\lib\nibabel\gifti
    copying nibabel\gifti\__init__.py -> build\lib\nibabel\gifti
    creating build\lib\nibabel\gifti\tests
    copying nibabel\gifti\tests\test_1.py -> build\lib\nibabel\gifti\tests
    copying nibabel\gifti\tests\test_gifti.py -> build\lib\nibabel\gifti\tests
    copying nibabel\gifti\tests\test_giftiio.py -> build\lib\nibabel\gifti\tests
    copying nibabel\gifti\tests\test_parse_gifti_fast.py -> build\lib\nibabel\gifti\tests
    copying nibabel\gifti\tests\__init__.py -> build\lib\nibabel\gifti\tests
    creating build\lib\nibabel\cifti2
    copying nibabel\cifti2\cifti2.py -> build\lib\nibabel\cifti2
    copying nibabel\cifti2\parse_cifti2.py -> build\lib\nibabel\cifti2
    copying nibabel\cifti2\__init__.py -> build\lib\nibabel\cifti2
    creating build\lib\nibabel\cifti2\tests
    copying nibabel\cifti2\tests\test_cifti2.py -> build\lib\nibabel\cifti2\tests
    copying nibabel\cifti2\tests\test_cifti2io.py -> build\lib\nibabel\cifti2\tests
    copying nibabel\cifti2\tests\test_new_cifti2.py -> build\lib\nibabel\cifti2\tests
    copying nibabel\cifti2\tests\__init__.py -> build\lib\nibabel\cifti2\tests
    creating build\lib\nibabel\nicom
    copying nibabel\nicom\csareader.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\dicomreaders.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\dicomwrappers.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\dwiparams.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\structreader.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\utils.py -> build\lib\nibabel\nicom
    copying nibabel\nicom\__init__.py -> build\lib\nibabel\nicom
    creating build\lib\nibabel\freesurfer
    copying nibabel\freesurfer\io.py -> build\lib\nibabel\freesurfer
    copying nibabel\freesurfer\mghformat.py -> build\lib\nibabel\freesurfer
    copying nibabel\freesurfer\__init__.py -> build\lib\nibabel\freesurfer
    creating build\lib\nibabel\freesurfer\tests
    copying nibabel\freesurfer\tests\test_io.py -> build\lib\nibabel\freesurfer\tests
    copying nibabel\freesurfer\tests\test_mghformat.py -> build\lib\nibabel\freesurfer\tests
    copying nibabel\freesurfer\tests\__init__.py -> build\lib\nibabel\freesurfer\tests
    creating build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\data_pkgs.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_csareader.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_dicomreaders.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_dicomwrappers.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_dwiparams.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_structreader.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\test_utils.py -> build\lib\nibabel\nicom\tests
    copying nibabel\nicom\tests\__init__.py -> build\lib\nibabel\nicom\tests
    creating build\lib\nibabel\testing
    copying nibabel\testing\np_features.py -> build\lib\nibabel\testing
    copying nibabel\testing\__init__.py -> build\lib\nibabel\testing
    creating build\lib\nibabel\tests
    copying nibabel\tests\nibabel_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\scriptrunner.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_affines.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_analyze.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_api_validators.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_arrayproxy.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_arraywriters.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_batteryrunners.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_casting.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_checkwarns.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_dataobj_images.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_deprecated.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_deprecator.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_dft.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_ecat.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_ecat_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_endiancodes.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_environment.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_euler.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_filebasedimages.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_filehandles.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_fileholders.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_filename_parser.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_fileslice.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_files_interface.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_fileutils.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_floating.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_funcs.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_helpers.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_imageclasses.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_imageglobals.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_image_api.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_image_load_save.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_image_types.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_info.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_keywordonly.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_loadsave.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_minc1.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_minc2.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_minc2_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_mriutils.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_nibabel_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_nifti1.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_nifti2.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_openers.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_optpkg.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_orientations.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_parrec.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_parrec2nii.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_parrec_data.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_processing.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_proxy_api.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_quaternions.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_recoder.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_round_trip.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_rstutils.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_scaling.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_scripts.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_spaces.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_spatialimages.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_spm2analyze.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_spm99analyze.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_testing.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_tmpdirs.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_trackvis.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_tripwire.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_viewers.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_volumeutils.py -> build\lib\nibabel\tests
    copying nibabel\tests\test_wrapstruct.py -> build\lib\nibabel\tests
    copying nibabel\tests\__init__.py -> build\lib\nibabel\tests
    creating build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_arrayproxy_slicing.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_array_to_file.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_fileslice.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_finite_range.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_load_save.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\bench_streamlines.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\butils.py -> build\lib\nibabel\benchmarks
    copying nibabel\benchmarks\__init__.py -> build\lib\nibabel\benchmarks
    creating build\lib\nibabel\streamlines
    copying nibabel\streamlines\array_sequence.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\header.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\tck.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\tractogram.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\tractogram_file.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\trk.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\utils.py -> build\lib\nibabel\streamlines
    copying nibabel\streamlines\__init__.py -> build\lib\nibabel\streamlines
    creating build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_array_sequence.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_streamlines.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_tck.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_tractogram.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_tractogram_file.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_trk.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\test_utils.py -> build\lib\nibabel\streamlines\tests
    copying nibabel\streamlines\tests\__init__.py -> build\lib\nibabel\streamlines\tests
    creating build\lib\nisext
    copying nisext\py3builder.py -> build\lib\nisext
    copying nisext\sexts.py -> build\lib\nisext
    copying nisext\testers.py -> build\lib\nisext
    copying nisext\__init__.py -> build\lib\nisext
    creating build\lib\nisext\tests
    copying nisext\tests\test_sexts.py -> build\lib\nisext\tests
    copying nisext\tests\test_testers.py -> build\lib\nisext\tests
    copying nisext\tests\__init__.py -> build\lib\nisext\tests
    creating build\lib\nibabel\tests\data
    copying nibabel\tests\data\0.dcm -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\1.dcm -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\analyze.hdr -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\anatomical.nii -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\ASL_3D_Multiecho.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\check_parrec_reslice.py -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\complex.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\complex_big_endian.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\DTI.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\DTIv40.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\empty.tck -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\empty.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\example4d.nii.gz -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\example_nifti2.nii.gz -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\fieldmap.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\functional.nii -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\gen_standard.py -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\make_moved_anat.py -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc1-no-att.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc1_1_scale.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc1_4d.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc2-4d-d.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc2-no-att.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc2_1_scale.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\minc2_4d.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\NA.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\nifti1.hdr -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\nifti2.hdr -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_cor_20APtrans_15RLrot_SENSE_15_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_cor_SENSE_8_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_sag_15AP_SENSE_13_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_sag_15FH_SENSE_12_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_sag_15RL_SENSE_11_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_sag_SENSE_7_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_tra_-30AP_10RL_20FH_SENSE_14_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_tra_15FH_SENSE_9_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_tra_15RL_SENSE_10_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\Phantom_EPI_3mm_tra_SENSE_6_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_EPI_asc_CLEAR_2_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_EPI_asc_CLEAR_2_1.REC -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_fake_dualTR.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_fake_v4.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_fake_v4_1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_truncated.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_truncated.REC -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_varscale.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\phantom_varscale.REC -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\README.rst -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\reoriented_anat_moved.nii -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\resampled_anat_moved.nii -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\resample_using_spm.m -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\simple.tck -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\simple.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\simple_big_endian.tck -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\small.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\standard.LPS.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\standard.nii.gz -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\standard.tck -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\standard.trk -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T1.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T1_3echo_mag_real_imag_phase.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T1_dual_echo.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T2-interleaved.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T2.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T2_-interleaved.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\T2_.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\test.mgz -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\tiny.mnc -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\tinypet.v -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\to_canonical.m -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\umass_anonymized.PAR -> build\lib\nibabel\tests\data
    copying nibabel\tests\data\variant_v4_2_header.PAR -> build\lib\nibabel\tests\data
    creating build\lib\nibabel\externals\tests\data
    copying nibabel\externals\tests\data\example_1.nc -> build\lib\nibabel\externals\tests\data
    creating build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\4d_multiframe_test.dcm -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa2_b0.bin -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa2_b1000.bin -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa2_zero_len.bin.gz -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa_slice_norm.dcm -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa_str_200n_items.bin -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\csa_str_valid.bin -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\decimal_rescale.dcm -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\philips_mprage.dcm.gz -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\siemens_dwi_0.dcm.gz -> build\lib\nibabel\nicom\tests\data
    copying nibabel\nicom\tests\data\siemens_dwi_1000.dcm.gz -> build\lib\nibabel\nicom\tests\data
    creating build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\ascii.gii -> build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\base64bin.gii -> build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\gzipbase64.gii -> build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\label.gii -> build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\rh.aparc.annot.gii -> build\lib\nibabel\gifti\tests\data
    copying nibabel\gifti\tests\data\rh.shape.curv.gii -> build\lib\nibabel\gifti\tests\data
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Bahar\\AppData\\Local\\Temp\\pip-build-k2650exj\\nibabel\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Bahar\AppData\Local\Temp\pip-tsa3_m1w-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Bahar\AppData\Local\Temp\pip-build-k2650exj\nibabel\

C:\Users\Bahar>
Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by djarecka** [comment]
@BaharJa, have you tried to follow [nipype installation suggestions](http://nipype.readthedocs.io/en/latest/users/install.html)

**Comment by BaharJa** [comment]
I used pip to install nipy, as one of the instruction says..but it cannot be installed

**Comment by djarecka** [comment]
@BaharJa I'm not sure why installing `nipy` doesn't work for you, but try to install `nipype`. See the instruction for exact command (name of the package)

**Comment by djarecka** [comment]
@BaharJa, please let us know if you're still having problem when installing `nipype`

**Comment by BaharJa** [comment]
Thank you so much you are too kind to me. I really appreciate your great
consideration.

I wanted to preprocess fMRI data by using python, and its necessary
component is nipype and I used to work on it for a week almost whole days
to find up what the problem is, unfortunately it cannot be solved, maybe
the issue comes from visual studio, because the error has changed to cl.exe
does not exist. I have tried to reinstalled the visual c++ and its
component but still there is still error. Or maybe numpy, because the error
line comes from the compaq.py([winerror]the file does not
find)(unfortunately reinstalling numy did not solve the problem as well).
However, I have used matlab to preprocess fMRI data . I think I have to use
Linux instead, I will install and let you know soon.

Your great kindness and help are greatly appreciated. Thank you so much

Best Regards,
Bahar

**Comment by djarecka** [comment]
@BaharJa , did you have the same error when you changed from `nipy` to `nipype` in your pip install command? I'm assuming that you want to install `nipype` (and not `nipy` - i don't know too much about this).
You can also try installing `conda` and use this to install the package.

**Comment by djarecka** [comment]
I just noticed that your paths suggest that you're using Windows... Don't have too much experience, Linux might be indeed a better option. You can also try to use Docker on your Windows machine

**Comment by BaharJa** [comment]
Thank you so much for your great help and assistance.

Yes, I tried to install nipy as well but encountered the same error. I read
comments who experienced the same issue and applied all the methods to
solve the problem but I have no idea what is the problem. Okay, I try
conda. Yes, Linux is totally friendly with python. Now, I have my project
done by MATLAB, but come back to check conda soon. I really appreciate your
great kindness.

Best Regards,
Bahar

**Comment by djarecka** [comment]
@BaharJa - ok, so I'm closing this issue for now. Feel free to reopen or open a new one if you have problems with nipype

**Comment by BaharJa** [comment]
Thank you so much. Your great help and thoughtfulness mean so much to me.
Best,

**Comment by oesteban** [comment]
Maybe [fMRIPrep](http://fmriprep.org) would meet your needs for this preprocessing.

**Comment by BaharJa** [comment]
Dear Doctor Oscar,

Thank you so much. I test fMRIPrep to see how it works. My supervisor has
sent preprocessed data to me.  I also like to see how it works that's why I
put so much time on it. I did preprocess with Matlab but I wish I could use
Python, I have decided to install Linux.  Thank you so much for your help
and kindness.

Best Regards,
bahar

**Comment by RuizhiH** [comment]
problem is same as yours ,but i use this line of code and  it solved
conda install --channel conda-forge nipype

**Comment by NOSHEENSANAY** [comment]
Thanx  Dear RuizhiH, it now solved my issue..
