### ISSUE TITLE
HistogramMatchingFilter could not be found on host

### ISSUE THREAD

**Issue by shpavisaslan** [nipy/nipype#2438]
Hiii,

I am almost new in nipype and python. I am trying to apply histogram matching on my images, however when I try to use HistogramMatchingFilter function I face an error like "IOError: command 'HistogramMatchingFilter' could not be found on hosti "
Actually, I had the same problem with nipype_spm, but I gave the path to the source spm.
Here I have no idea how I can specify a path for this functions. Do have any idea?!
Thanks.

Code:
hist = se.HistogramMatchingFilter()
hist.inputs.inputVolume = 'brain1.nii.gz'
hist.inputs.referenceVolume = 'brain2.nii.gz'
hist.inputs.numberOfHistogramBins = 10
hist.inputs.outputVolume = 'brain3.nii.gz'
Hist = hist.run()

Error:
IOError: command 'HistogramMatchingFilter' could not be found on host

**Comment by djarecka** [comment]
Hi @shpavisaslan, have you checked if you have `HistogramMatchingFilter` on your machine? Can you type in a terminal `HistogramMatchingFilter`?

If you have it, you would have to extend your `PATH` and add the path where `HistogramMatchingFilter` is installed (you can check `which  HistogramMatchingFilter`). We don't provide any method within `nipype` to set this path.

**Comment by mgxd** [comment]
@shpavisaslan if you are still having issues, please reopen this issue
