### ISSUE TITLE
Add a neurodocker section to the docs

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2439]
it would be good to show people how to use neurodocker to create their own environment for running nipype with various tools. it would be nice if the page made it in before the 1.0.1 release

**Comment by mgxd** [comment]
cc-ing @kaczmarj

**Comment by kaczmarj** [comment]
I can definitely help put together a neurodocker section for the docs.

**Comment by effigies** [comment]
@kaczmarj It would be good to try to get as much as possible in over the weekend so we can queue up final test builds. Do you have time to add these docs tomorrow?

**Comment by kaczmarj** [comment]
@effigies - I will do my best to do this tomorrow.
