### ISSUE TITLE
spm.SPMCommand.set_mlab_paths doesn't change spm version

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2442]
### Summary
It looks like changing paths using `spm.SPMCommand.set_mlab_paths` doesn't affect some of the checks: e.g. `spm.Info.name()`, `spm.SPMCommand().version` or `spm.base.no_spm()`.

Some checks (e.g. `spm.SPMCommand().version` ) stopped working properly between 0.13.1 and 0.14

This problem is related to #2436

**Comment by satra** [comment]
@djarecka - if `SPMCommand` paths are set, they should influence `Info` as well. i think that is all that is broken. once `Info` is updated, the others should work automatically.

**Comment by satra** [comment]
@djarecka - i just ran this in the nipype test container (`nipype/nipype:py36`) without invoking the entrypoint, and with some debug prints.

```python
>>> import nipype.interfaces.spm as spm
>>> spm.Info.version()
/opt/mcr/v92/toolbox/matlab
>>> spm.Info.version(matlab_cmd='/opt/spm12/run_spm12.sh /opt/mcr/v92/ script')
/opt/spm12/run_spm12.sh /opt/mcr/v92/ script
stty: 'standard input': Inappropriate ioctl for device
path:/opt/spm12/spm12_mcr/spm/spm12|name:SPM12|release:7169
'7169'
spm.SPMCommand().version
'12.7169'
```

**Comment by satra** [comment]
also on os x:

```python
In [1]: import nipype.interfaces.spm as spm
180219-15:35:18,460 duecredit ERROR:
	 Failed to import duecredit due to No module named 'duecredit'

In [2]: spm.SPMCommand().version
matlab -nodesktop -nosplash

In [3]: spm.Info.version
Out[3]: <bound method Info.version of <class 'nipype.interfaces.spm.base.Info'>>

In [4]: spm.Info.version()
matlab -nodesktop -nosplash

In [5]: spm.SPMCommand.set_mlab_paths(paths='/software/matlab/spm12')

In [6]: spm.SPMCommand().version
matlab -nodesktop -nosplash
path:/software/matlab/spm12|name:SPM12|release:6225
Out[6]: '12.6225'

In [7]: spm.Info.version()
Out[7]: '6225'
```

**Comment by satra** [comment]
so everything seems like it's working the way it is supposed to.

**Comment by satra** [comment]
let me take that back - i did make one fix :)

will push in a second.

**Comment by djarecka** [comment]
@satra I was checking last week what happens when I change `matlab_cmd` with `spm.SPMCommand.set_mlab_paths`. And I noticed that `spm.SPMCommand().version` returns the same even if I provide a non-existing path/command.
I've just checked your PR, and I still have the same problem.

**Comment by satra** [comment]
@djarecka - ok  just pushed a fix. can you try it now?

**Comment by djarecka** [comment]
@satra 
ok, when I provide `matlab_cmd` that doesn't make sense, I get `spm.SPMCommand().version = None`, but:
- `spm.Info.name()` still gives me `SPM12`
- if I only change `paths` with  `spm.SPMCommand.set_mlab_paths`, I don't see any difference in `spm.SPMCommand().version` or `spm.Info.name()`.

can copy the output to show you what I mean

**Comment by satra** [comment]
can you please paste the code?

**Comment by djarecka** [comment]
sorry, Chris has just come and started talking to him...

```
>>> from nipype.interfaces import spm
>>> print(spm.Info.name())
SPM12
>>> print(spm.SPMCommand().version)
12.7169
>>> spm.SPMCommand.set_mlab_paths(paths='/Applications/MATLAB_R2016b.app/toolbox/spm12/')
>>> print(spm.Info.name())
SPM12
>>> print(spm.SPMCommand().version)
12.7169
>>> spm.SPMCommand.set_mlab_paths(matlab_cmd='/Applications/MATLAB_R2016b.app/bin/matlab -nodesktop -nosplash')
>>> print(spm.Info.name())
SPM12
>>> print(spm.SPMCommand().version)
None
```
this is Linux and the paths don't amke sense

**Comment by satra** [comment]
so there are two types of matlab installs:

in the container, we use MCR, which always has the specific command line for spm12:

`/opt/spm12/run_spm12.sh /opt/mcr/v92/ script` this will always find spm since that's the only thing it runs.

the other type is a normal matlab install without mcr - i will push another change to retrieve version when SPMCommand is set.

```python
In [1]: from nipype.interfaces import spm
180220-12:59:07,562 duecredit ERROR:
	 Failed to import duecredit due to No module named 'duecredit'

In [2]: print(spm.Info.name())
None

In [3]: print(spm.Info.name(paths='/software/matlab/spm12/'))
SPM12

In [4]: print(spm.Info.name())
SPM12

In [5]: spm.SPMCommand.set_mlab_paths(paths='/Applications/MATLAB_R2016b.app/toolbox/spm12/')
   ...: 

In [6]: print(spm.Info.name())
SPM12

In [7]: print(spm.SPMCommand().version)
None
```

**Comment by djarecka** [comment]
@satra do you want me also to test this on OSX? I simply don't have SPM on my laptop, so I was testing basic things in a container. Can always install...

**Comment by satra** [comment]
i think we need a better version of memoize over here. i will push some changes after lunch.

**Comment by djarecka** [comment]
@satra so you're saying that the version with MCR doesn't anticipate any changes in paths/versions for `spm`, is that right?

**Comment by satra** [comment]
> so you're saying that the version with MCR doesn't anticipate any changes in paths/versions for spm, is that right?

correct, as long as the appropriate environment variables are set.

**Comment by djarecka** [comment]
ok. I wonder if a warning might be useful, but probably no one tries to set a weird path if everything is working (as I was trying to set).
