### ISSUE TITLE
update testing docs

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2445]
as noted in #1905 CONTRIBUTING.md does not directly provide users with how to test nipype easily on their system. it perhaps should point to this link `http://nipype.readthedocs.io/en/latest/devel/testing_nipype.html`, which should be updated. especially this section:
`http://nipype.readthedocs.io/en/latest/devel/testing_nipype.html#testing-nipype-using-docker`

**Comment by effigies** [comment]
As I don't test using Docker, am not familiar with the intended usage of the Docker hub images, and would need to become familiar with both, I wouldn't be able to write this quickly. Is this something someone can put together quickly?

Also, should we go ahead, start a release branch and test on conda-forge? If the only thing changing is docs, there's little chance of test-breaking changes.

**Comment by oesteban** [comment]
I can have a look on this next week. But impossible for me right now

**Comment by djarecka** [comment]
@oesteban  - I can start updating and ask you for  review once you have time.

**Comment by effigies** [comment]
Related to https://github.com/nipy/nipype/issues/2313#issuecomment-365330143 Q1, what is the intended usage of the docker hub images? Are these intended for testing? Or are users expected to build the main Dockerfile on top of `nipype/nipype:base`?

**Comment by satra** [comment]
@effigies - i use nipype/nipype:py36 for my local development/testing. so for those using docker, those docker hub images give people the exact environment that's needed for nipype testing.

**Comment by oesteban** [comment]
Same here. Would be great to take the specific command lines from the CircleCI scripts into this piece of docs.

**Comment by effigies** [comment]
We should update `CONTRIBUTING.md` to recommend `pip install` rather than `python setup.py`.

From https://github.com/nipy/nipype/pull/2471#issuecomment-369610815.

**Comment by djarecka** [comment]
@effigies so you want to have just `pip install -e .` instead of `python setup.py`? or should we have `pip install -e .[all]` or `pip install -e .[specs]`?

**Comment by effigies** [comment]
I actually updated this in the MAINT PR.

**Comment by djarecka** [comment]
can someone tell me if we care about `make` testing commands? I would just remove them completely from `testing_nipype.rst` (and possibly from `Makefile`)
