### ISSUE TITLE
 Dcm2niix in nypipe not working and no error message nipype 

### ISSUE THREAD

**Issue by bgagl** [nipy/nipype#2447]
### Summary
Hello,
I am trying to convert my dicoms with the dcm2niix function in python.
Also tried for a list of dicoms and selecting a whole folder by using ``` soucre_dir```

Any suggestions?
Thanks in advance

### Actual behavior
output:
```python
‘dcm2niix -b y -z i -x n -t n -m n -f func_bl_1.nii.gz -o /data/…some long path…/0003_MR000014.dcm’
```
Problem is now that no nii is written in the output folder and no error is given …

### Expected behavior
nii written to the output directory
### Script/Workflow details
```python
func_out_dir = output_dir+vp_name+"/func"

converter = Dcm2niix()
converter.inputs.compress = 'i’
converter.inputs.source_names = func_b1_dcm[1] #string for dicom file with full path … see output
converter.inputs.single_file = True
converter.inputs.out_filename = "func_bl_1.nii.gz"
converter.inputs.output_dir = func_out_dir
converter.cmdline
```
Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

{'pkg_path': '/data/.../anaconda3/lib/python3.6/site-packages/nipype', 'commit_source': 'archive substitution', 'commit_hash': '%h', 'nipype_version': '0.14.0', 'sys_version': '3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]', 'sys_executable': '/data/.../anaconda3/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.13.1', 'scipy_version': '0.19.1', 'networkx_version': '1.11', 'nibabel_version': '2.2.1', 'traits_version': '4.6.0'}
0.14.0

### Execution environment

- My python environment outside container

**Comment by satra** [comment]
you have to call the run function to execute: `converter.run()`

**Comment by bgagl** [comment]
thanks, sorry for that stupit one ... now everything is working

**Comment by djarecka** [comment]
we're glad that it works! closing the issue.
