### ISSUE TITLE
Cannot import TProject from afni interface

### ISSUE THREAD

**Issue by sjburwell** [nipy/nipype#2468]
### Summary
I cannot import the TProject function from the afni interface within nipype. I have updated the version of nipype being used -- but this doesn't change behavior. Please advise. 

The latter of the two commands below fails:
from nipype.interfaces.afni.preprocess import TCorr1D
from nipype.interfaces.afni.preprocess import TProject
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-f87de3ad0f67> in <module>()
----> 1 from nipype.interfaces.afni.preprocess import TProject

ImportError: cannot import name TProject

### Platform details:
{'nibabel_version': '2.2.1', 'sys_executable': '/labs/burwellstudy/projects/nipype2/bin/python2', 'networkx_version': '2.1', 'numpy_version': '1.14.1', 'sys_platform': 'linux2', 'sys_version': '2.7.6 (default, Nov 23 2017, 15:53:45) \n[GCC 4.8.4]', 'commit_source': 'installation', 'commit_hash': '0a5948a0', 'pkg_path': '/labs/burwellstudy/projects/nipype2/lib/python2.7/site-packages/nipype', 'nipype_version': '1.0.0', 'traits_version': '4.6.0', 'scipy_version': '1.0.0'}
1.0.0

### Execution environment
- My python environment outside container

**Comment by mgxd** [comment]
@sjburwell `afni.TProject` was added after version `1.0.0`, which is why your installation cannot find it.

we just released version `1.0.1` which should include that interface, it should be pip/conda installable shortly.

**Comment by mgxd** [comment]
`nipype 1.0.1` is now available through pip/conda - within that version you should be able to use `afni.TProject`. If you are still having problems, feel free to reopen this issue
