### ISSUE TITLE
Problem building pipeline nipype

### ISSUE THREAD

**Issue by tragus1** [nipy/nipype#2483]
### I get the following error when running my code:
    (dwibet, bedp, [('mask_file', 'mask')]),  
  File "/home/demenzbild/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 151, in connect
    for srcnode, destnode, _ in connection_list:
ValueError: too many values to unpack

I'm new to nipype and Iḿ not sure how to solve this problem.

Thank you for your help!

### Script/Workflow details
from os.path import join as opj
from nipype.interfaces import fsl 
from nipype.interfaces.utility import IdentityInterface
from nipype.interfaces.io import SelectFiles, DataSink
from nipype.pipeline.engine import Workflow, Node
import nipype.interfaces.io as nio

# ---specify variables 

# What is the location of your experiment folder
experiment_dir = '/home/demenzbild/Schreibtisch/DTI_testdata_pipeline' 

# What are the names of your subjects
subject_list = ['sub-HCP002S6009', 'sub-HCP002S6053', 'sub-MCI041S4974', 'sub-SMC041S5253' ]  

# What is the name of your working directory and output folder
output_dir = 'output_firstSteps'  
working_dir = 'workingdir_firstSteps'

# What are experiment specific parameters
deltaTE = 2.46
echtime1 = 0.00492
echotime2 = 0.00738
dwelltime = 0.290

# ---- nodes

eddyc = Node(fsl.EddyCorrect(), name="eddyc")

fugue = Node(fsl.FUGUE(dwell_to_asym_ratio=0.00029), name="fugue")

betfmapmag = Node(fsl.BET(mask=True), name="betfmapmag")

prepare = Node(fsl.PrepareFieldmap(delta_TE=2.46), name="prepare")

dwibet = Node(fsl.BET(mask=True), name="dwibet")

bedp = Node(fsl.BEDPOSTX5(n_fibres=1), name="bedp")

# ---- specify workflows and connect nodes

preproc = Workflow(name='preproc')
preproc.base_dir = opj(experiment_dir, working_dir)

preproc.connect([(eddyc, fugue, [('out_file', 'in_file')],
			     (betfmapmag, prepare, [('out_file', 'in_magnitude')]),
			     (prepare, fugue, [('out_fieldmap', 'phasemap_in_file')]),
			     (fugue, bedp, [('unwarped_file', 'dwi')]),
			     (dwibet, bedp, [('mask_file', 'mask')]),  
			      )])

# ---- imput and output stream

#Infosource - a function free node to iterate over the list of subject names

infosource = Node(IdentityInterface(fields=['subject_id']),
                  name="infosource")
                  
infosource.iterables = [('subject_id', subject_list)]

#SelectFiles
templates = {'anat': '{subject_id}/anat/{subject_id}_T1w.nii.gz',
             'dwi': '{subject_id}/dwi/{subject_id}_dwi.nii.gz',
             'bval': '{subject_id}/dwi/{subject_id}_dwi.bval',
             'bvec': '{subject_id}/dwi/{subject_id}_dwi.bvec',
             'fmap_mag': '{subject_id}/fmaps/{subject_id}_magnitude1.nii.gz',
             'fmap_pha': '{subject_id}/fmaps/{subject_id}_phasediff.nii.gz',
				  }
				    

selectfiles = Node(SelectFiles(templates,
                               base_directory=experiment_dir),
                   name="selectfiles")

#Datasink
datasink = Node(DataSink(base_directory=experiment_dir,
                         container=output_dir),
                name="datasink")

#Use the following DataSink output substitutions
substitutions = [('subject_id', '')]
datasink.inputs.substitutions = substitutions

#Connect SelectFiles and DataSink to the workflow
preproc.connect([(infosource, selectfiles, [('subject_id', 'subject_id')]),
                 (selectfiles, dwibet, [('dwi', 'in_file')]),
                 (selectfiles, betfmapmag, [('fmap_mag', 'in_file')]),
                 (selectfiles, prepare, [('fmap_pha', "in_phase")]),
                 (selectfiles, bedp, [('bval', 'bvals')]),
                 (selectfiles, bedp, [('bvec', 'bvecs')]),
                 (dwibet, datasink, [('out_file', 'dwibet')])  ])
                
# --- run workflow
preproc.write_graph(graph2use='flat')
preproc.run('MultiProc', plugin_args={'n_procs': 8})

**Comment by djarecka** [comment]
Can you please paste entire error message?

Can you  also please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`.

**Comment by mgxd** [comment]
This looks like a problem within the connections - could you share the connection lines before/after 
`(dwibet, bedp, [('mask_file', 'mask')]),  `?

**Comment by oesteban** [comment]
check for a missing trailing comma in the previous line 👍

**Comment by oesteban** [comment]
Actually:

```Python
preproc.connect([
    (eddyc, fugue, [('out_file', 'in_file')],
    (betfmapmag, prepare, [('out_file', 'in_magnitude')]),
    (prepare, fugue, [('out_fieldmap', 'phasemap_in_file')]),
    (fugue, bedp, [('unwarped_file', 'dwi')]),
    (dwibet, bedp, [('mask_file', 'mask')]),
)])
```
there is a misplaced parenthesis.

```Python
preproc.connect([
    (eddyc, fugue, [('out_file', 'in_file')]),
    (betfmapmag, prepare, [('out_file', 'in_magnitude')]),
    (prepare, fugue, [('out_fieldmap', 'phasemap_in_file')]),
    (fugue, bedp, [('unwarped_file', 'dwi')]),
    (dwibet, bedp, [('mask_file', 'mask')]),
])
```

**Comment by tragus1** [comment]
Thanks, sorry the misplaced parenthesis caused the problem.
