### ISSUE TITLE
loops in CircleCI

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2489]
### Summary
I'm not sure if [for loops in config.yml](https://github.com/nipy/nipype/blob/master/.circleci/config.yml#L51) change anything, I think it does not retry if the command fails. I mostly noticed this when I tried to use the same logic in the Nipype Tutorial repo, where `datalad` command fails quite often. 

A simple example showing that CircleCI tries only once is [here](https://circleci.com/gh/djarecka/nipype_tutorial/64?utm_campaign=build-failed&utm_medium=email&utm_source=notification)

**Comment by effigies** [comment]
We could write a script to do something similar to [`travis_retry`](https://github.com/nipy/nipype/blob/88dbce1ce5439440bcc14c9aa46666c40f642152/.travis.yml#L31).
