### ISSUE TITLE
may be pydotplus would be sufficient?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#2494]
### Summary

nipype depends on both pydot and pydotplus packages, with pydot versioned so not available e.g. on debian stable.   but internally it seems to use neither of them directly:

```shell
$> git grep pydot
doc/users/install.rst:    'doc': ['Sphinx>=1.4', 'matplotlib', 'pydotplus', 'pydot>=1.2.3'],
nipype/info.py:    'pydotplus',
nipype/info.py:    'pydot>=%s' % PYDOT_MIN_VERSION,
nipype/info.py:    'doc': ['Sphinx>=1.4', 'numpydoc', 'matplotlib', 'pydotplus', 'pydot>=1.2.3'],
nipype/pipeline/engine/utils.py:    nx.drawing.nx_pydot.write_dot(pklgraph, simple_dot)
requirements.txt:pydotplus
requirements.txt:pydot>=1.2.3
rtd_requirements.txt:pydotplus
rtd_requirements.txt:pydot>=1.2.3
```
so is it just for networkx? shouldn't networkx then depend appropriately and nipype not declare any special relationship with pydot?

Thanks in advance for clarification
### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by effigies** [comment]
Networkx previously depended on pydotplus (1.11), and now depends on pydot (2.0). The main problem is we need to support pre- and post-2.0. They did not previously include `pydotplus` in their explicit dependencies, although they now include `pydot` in their extras (albeit with no minimum version).

I'm not sure what the best way to accommodate this situation is. We do limit our dependency to "doc" extras. Possibly we could depend on `pydotplus` and use `networkx[all]` to pull in `pydot` if necessary, although the lack of a minimum version for `pydot` makes that difficult. Perhaps we should open an issue upstream, but that's not going to help with the networkx releases in the wild.

See #2159, #2196, networkx/networkx#1924, networkx/networkx#2272.
