### ISSUE TITLE
Error in nipype interfaces core.py

### ISSUE THREAD

**Issue by piyusharma95** [nipy/nipype#2510]
Already installed Xquartz as mentioned in [https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/MacOsX](FSL installation MacOSX)
Downloaded _fslinstaller.py_ from [https://fsl.fmrib.ox.ac.uk/fsldownloads_registration/download/fsl=4,o_s=9,d_type=release/](FSLinstaller.py) 
Ran the commands:
> sudo python fslinstaller.py
`--- FSL Installer - Version 3.0.11 ---`
`The requested version matches the installed version - do you wish to re-install FSL? [no]: no`
> ipython
In [1]: from nipype.interfaces import fsl

In [2]: skullstrip = fsl.BET(in_file="/Users/doxbin/Downloads/NIfTI/BRAINIX_NIFT
   ...: I_T1.nii.gz",out_file="~/Downloads/sub-02_T1w_brain.nii.gz",mask=True)

In [3]: skullstrip.run()

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-3-73bf8e648af8> in <module>()
> ----> 1 skullstrip.run()
> 
> /Users/doxbin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/core.pyc in run(self, cwd, **inputs)
>     514 
>     515         try:
> --> 516             runtime = self._run_interface(runtime)
>     517             outputs = self.aggregate_outputs(runtime)
>     518         except Exception as e:
> 
> /Users/doxbin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/fsl/preprocess.pyc in _run_interface(self, runtime)
>     146         # in stderr and if it's set, then update the returncode
>     147         # accordingly.
> --> 148         runtime = super(BET, self)._run_interface(runtime)
>     149         if runtime.stderr:
>     150             self.raise_exception(runtime)
> 
> /Users/doxbin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/core.pyc in _run_interface(self, runtime, correct_return_codes)
>    1018                                                  runtime.environ)
>    1019                                 if self._ldd else '<skipped>')
> -> 1020         runtime = run_command(runtime, output=self.terminal_output)
>    1021         if runtime.returncode is None or \
>    1022                 runtime.returncode not in correct_return_codes:
> 
> /Users/doxbin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/core.pyc in run_command(runtime, output, timeout)
>     759     if output == 'stream':
>     760         streams = [
> --> 761             Stream('stdout', proc.stdout),
>     762             Stream('stderr', proc.stderr)
>     763         ]
> 
> /Users/doxbin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/support.pyc in __init__(self, name, impl)
>     251         self._rows = []
>     252         self._lastidx = 0
> --> 253         self.default_encoding = locale.getdefaultlocale()[1] or 'UTF-8'
>     254 
>     255     def fileno(self):
> 
> /Users/doxbin/anaconda2/lib/python2.7/locale.pyc in getdefaultlocale(envvars)
>     543     else:
>     544         localename = 'C'
> --> 545     return _parse_localename(localename)
>     546 
>     547 
> 
> /Users/doxbin/anaconda2/lib/python2.7/locale.pyc in _parse_localename(localename)
>     475     elif code == 'C':
>     476         return None, None
> --> 477     raise ValueError, 'unknown locale: %s' % localename
>     478 
>     479 def _build_localename(localetuple):
> 
> ValueError: unknown locale: UTF-8

**Comment by effigies** [comment]
I found this on a quick search. Could you try this?

https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python
