### ISSUE TITLE
expert.opts are being written to the root directory

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#2518]
### Summary
`expert.opts` file is being written to the root directory which is not writable under singularity. 
See https://neurostars.org/t/singularity-fmriprep-export-opts-error/1491 for more details.

**Comment by effigies** [comment]
At a first glance, this is probably related to previous attempts to properly set the working directory for `Node`s.

**Comment by oesteban** [comment]
https://github.com/nipy/nipype/blob/6ca791d9c5ec0efb9f56cc9e44758d6e53ffb800/nipype/interfaces/freesurfer/preprocess.py#L1317

**Comment by effigies** [comment]
Related: #2368.

**Comment by effigies** [comment]
Okay, it looks like `interface.cmdline` is called before the working directory is entered.

Also afterwards, but for some reason the running command is the one generated outside.

Probably the big problem is that it's all a massive hack to turn what should be runtime flags into a file. Maybe we should have gone with the "ExpertOptions" interface (260a27577dea454640bfc5117e0ad8e53ece02dd). Anyway, I'll see if there's any plausible way to have `cmdline` not drop a file in the CWD, whatever that happens to be.

**Comment by effigies** [comment]
Actually, my mistake. The correct command is being run, the problem is just that `cmdline` dumps a file wherever it happens to be, and we call `node.interface.cmdline` before running the node for logging purposes.

**Comment by oesteban** [comment]
Good catch
