### ISSUE TITLE
add oscar's advanced tutorials to nipype_tutorial

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2528]
@oesteban created a few notebooks for creating interfaces for the nipype workshop last year.

@djarecka and @miykael : could we add them to  nipype_tutorial?

**Comment by djarecka** [comment]
You mean the two notebooks from [here](https://github.com/nipy/workshops/tree/master/170327-nipype/notebooks/new-workflows-and-interfaces)?
I can test and add it.

**Comment by satra** [comment]
indeed - but adapted to the dataset being used in the tutorial. 

also perhaps creating an advanced section.

**Comment by djarecka** [comment]
yes, that was on our TODO list anyway. I've created a issue in the tutorial repo

**Comment by miykael** [comment]
@oesteban's notebook about "how to create interfaces" will be added with https://github.com/miykael/nipype_tutorial/pull/72. This PR will also initiate the "advanced concepts" section of the nipype_tutorial.
