### ISSUE TITLE
multiple outputs with function node

### ISSUE THREAD

**Issue by jjuwono** [nipy/nipype#2535]
### Summary
Hi All on the Nipype team, I was wondering if there was a way to define multiple outputs using the function node. For example something like (modified from the documentation)
def add_two(val):
    return val + 2, val+3 
from nipype.interfaces.utility import Function
add_two_interface = Function(input_names=["val"],
                             output_names=["out_val","out_val_1"],
                             function=add_two)

**Comment by oesteban** [comment]
You can just try that:

```Python
from nipype.interfaces.utility import Function

def add_two(val):
    return val + 2, val+3

add_two_interface = Function(
    input_names=["val"],
    output_names=["out_val","out_val_1"],
    function=add_two)

add_two_interface.inputs.val = 10

print(add_two_interface.run().outputs)
```

**Comment by jjuwono** [comment]
hahhahah thank you!
