### ISSUE TITLE
antsRegistrationSyNQuick- spelling error?

### ISSUE THREAD

**Issue by atsuch** [nipy/nipype#2543]
### Summary
I'm not sure why others wouldn't have caught this one, but I think there is a spelling mistake in the command for antsRegistrationSyNQuick.sh... 

I think it has to be the capital N for SyN, but in nipype/interfaces/ants/registration.py the _cmd is antsRegistrationSynQuick.sh

### Actual behavior
Causes a crash when using a node with antsRegistrationSyNQuick with the following message

IOError: No command "antsRegistrationSynQuick.sh" found on host c2. Please check that the corresponding package is installed.

### Platform details:
I am using nipype 1.0.2, ants version 2.1.

**Comment by effigies** [comment]
Yup, you're right. Any interest in submitting a fix? The `_cmd` attribute and test commands in the doc string will need updating.

**Comment by effigies** [comment]
@atsuch This will be fixed in 1.0.3.

**Comment by atsuch** [comment]
@effigies, Thank you! 

I will try contributing next time...!
