### ISSUE TITLE
deprecated traits in BaseInterfaceInputSpec and CommandLineInputSpec

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2551]
### Summary

we have two traits that are marked ad `deprecated='1.0.0'` in `interfaces/base/specs.py`:
- [ignore_exception in BaseInterface](https://github.com/nipy/nipype/blob/master/nipype/interfaces/base/specs.py#L322)
- [terminal_output in CommandLine](https://github.com/nipy/nipype/blob/master/nipype/interfaces/base/specs.py#L374)

At the same time we're using these traits in some plugins, e.g. [here](https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/condor.py#L57) and it leads to [errors](https://neurostars.org/t/traiterror-for-condor-plugin/1567/5)

I'm not sure why we wanted to deprecate these traits, and if we still want to do it now, or we want to set a different nipype version.

Related to #2508

**Comment by effigies** [comment]
Yeah, I think we should remove those. I believe the justification for deprecation was that they were more properly attributes of an interface or node, rather than inputs.

**Comment by effigies** [comment]
I'm actually a little surprised that these aren't throwing errors in our tests as of 1.0. And to be clear, I think we should remove them ASAP. Setting 1.0.3 milestone.

**Comment by djarecka** [comment]
I didn't check everything carefully, but there are not in all plugins, and I don't think we test e.g. `condor ` plugin

**Comment by djarecka** [comment]
I can remove `ignore_exception=True` from `condor`, `lsf` and `pbs`; `terminal_output` is set in couple more places.
