### ISSUE TITLE
Crashdump directory is not properly set in workflow config file

### ISSUE THREAD

**Issue by eort** [nipy/nipype#2557]
Crash files are written to the current directory despite setting the crashdump directory of a workflow with `workflow.config = {"execution": {"crashdump_dir": 'crashdump'}}`.

I suspect the problem is line 594 in [pipeline/engine/workflows.py](https://github.com/nipy/nipype/blob/3c43f0c5041eaa127cbfb2e6a5ee765357aa262e/nipype/pipeline/engine/workflows.py/) when the workflow config file is being merged with the node config file. The default behaviour of `merge_dict` is that in case of a key conflict the second dictionary has precedence, so that the user-defined setting from the workflow level is being overwritten with the default settings from the node level. 

As far as I can see the ideal behaviour would be that node settings override workflow settings, but additionally, explicitly defined settings override default-settings.

**Comment by satra** [comment]
thanks @eort - indeed this is happening because nodes are initialized with default settings. this should be a very simple fix. nodes already import default settings when config is empty. as such they should be initialized with an empty config.

**Comment by eort** [comment]
Something like this?
