### ISSUE TITLE
Unable to pickle local function

### ISSUE THREAD

**Issue by jjuwono** [nipy/nipype#2565]
Hi all at Nipype I am trying to wrap a function I wrote in a function Node 

HERE IS MY CODE (abbreviated for clarity):

    def hsm(files,wmpath,workingdir):
        import Pool
        import nipype 
        import numpy
        #calls transform function and other functions
        def transform(imagep,wm_image,pc1,pc2,s1,s2,mu_s,workingdir):
            #preprocessing 
            def f(hist_normed,hist,x):
                            try:
                                a=hist_normed[x]/hist[1][x]
                            except:
                                a=hist_normed[x-1]/hist[1][x-1]
                            return a
        
           binn=np.digitize(image,hist[1])
           m_test=np.amax(binn)
            

          #parrallel
           xp,yp,zp=binn.shape
           p=Pool(4)
           fi=partial(f,hist_normed,hist)
           factor1=np.reshape(p.map(fi,np.reshape(binn,[xp*yp*zp])),[xp,yp,zp])

    hsm = Node(Function(input_names=["files",'wmpath','workingdir'],
                   output_names=["normalized_ims"], function=hsm),
                   name = "hsm")
    hsm.inputs.workingdir=base
    les_grow.connect(getwhite, 'white_mask', hsm, 'wmpath')
    les_grow.connect(inputnode, 'warped_brains', hsm, 'files')### Platform details:

THIS IS THE ERROR MESSAGE:
  File "<string>", line 217, in hsm
  File "<string>", line 188, in transform
  File "/data/henry10/jjuwono/anaconda3/envs/pbr_dev_jj/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/henry10/jjuwono/anaconda3/envs/pbr_dev_jj/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/data/henry10/jjuwono/anaconda3/envs/pbr_dev_jj/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/data/henry10/jjuwono/anaconda3/envs/pbr_dev_jj/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/data/henry10/jjuwono/anaconda3/envs/pbr_dev_jj/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'hsm.  < locals > .transform. < locals > .f'

#######
everything works up to the map function where I aim to use multiprocessing.Pool to process data on multiple processors . I also checked all the inputs and connections and I'm getting all the right results up to the map function. I don't really understand pickling and all that. Thank you for any help you can give.
written in python 3.6

#######

**Comment by effigies** [comment]
I would try defining `f()` at the file level, not dynamically within the other function. It doesn't seem to depend on the local environment of that function, so it shouldn't cause problems.

**Comment by jjuwono** [comment]
Hi effigies thanks for the suggestion! actually that was what I had originally. I just tried it again and this is the error I got : 
  File "< string >", line 205, in hsm
  File "< string >", line 175, in transform
NameError: name 'f' is not defined
Originally I assumed this was because of this : 
<img width="1039" alt="screen shot 2018-05-03 at 11 36 24 am" src="https://user-images.githubusercontent.com/35709557/39596171-6d40d1d6-4ec6-11e8-9430-2d626d246cc5.png">

from the docs, but I could definitly be mistaken. Let me know if you have any other suggestions!

**Comment by effigies** [comment]
Ah, right. Yes, that won't be in scope for the function node, but if you build it in the function node, it can't be sent to `Pool().map`. I think you're running up against the bounds of what it's reasonable to ask of a `Function` interface, and it's time to upgrade to a full-fledged interface. Here's a quick template:

```Python
class HSMInputSpec(BaseInterfaceInputSpec):
    in_files = InputMultiPath(File(exists=True))
    white_matter = File(exists=True)

class HSMOutputSpec(TraitedSpec):
    normalized = OutputMultiPath(File)

class HSM(SimpleInterface):
    input_spec = HSMInputSpec
    output_spec = HSMOutputSpec

    def _run_interface(self, runtime):
        ...
        self._results['normalized'] = ...
        return runtime

def f():
    ...
```

**Comment by jjuwono** [comment]
Hi effigies, thank you for the advice! I just changed my code to a interface. Now I was wondering, how do I connect this interface in my workflow? Thank you for all your help

**Comment by effigies** [comment]
To get going on workflows, I would recommend the [Nipype tutorials](https://miykael.github.io/nipype_tutorial/).

If you meant more specifically how to adapt what you had before:

```Python
hsm = Node(Function(input_names=["files",'wmpath','workingdir'],
               output_names=["normalized_ims"], function=hsm),
               name = "hsm")
hsm.inputs.workingdir=base
les_grow.connect(getwhite, 'white_mask', hsm, 'wmpath')
les_grow.connect(inputnode, 'warped_brains', hsm, 'files')
```

This would become:

```Python
hsm = Node(HSM(), name='hsm')
les_grow.connect(inputnode, 'warped_brains', hsm, 'in_files')
les_grow.connect(getwhite, 'white_mask', hsm, 'white_matter')
```
