### ISSUE TITLE
conda-forge shows two labels, one broken

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2575]
https://anaconda.org/conda-forge/nipype/labels

info about labels:
https://docs.anaconda.com/anaconda-cloud/user-guide/tutorials#using-labels-in-the-development-cycle

**Comment by mgxd** [comment]
@satra 

it looks to me like the first release on conda (0.12) was premature (conda-forge/nipype-feedstock#1), and needed to be fixed. Conda-forge [outlines why they don't like removing packages](https://github.com/ericdill/conda-forge.github.io/blob/0e530b6c614d03ce7dd16379ad57c6bcad8b7c1b/src/guidelines.rst#fixing-broken-packages), so we can just leave the broken label for that failed release - however, I submitted a request to remove the main tag from the broken files to avoid any confusion.
