### ISSUE TITLE
SLURMGraphPlugin attribute error

### ISSUE THREAD

**Issue by GReguig** [nipy/nipype#2584]
Hello everyone,

### Summary

I am currently trying to execute a workflow on a cluster using  SLURM and therefor I am trying to use the SLURMGraph plugin, but I get an attribute error.

### Actual Behavior 

```
Traceback (most recent call last):
  File "/export/dataCENIR/users/ghiles.reguig/connectivityworkflow/connectivityworkflow/connectivity_workflow.py", line 80, in <module>
    RunConnectivityWorkflow(path, outDir, workdir, conf)
  File "/export/dataCENIR/users/ghiles.reguig/connectivityworkflow/connectivityworkflow/connectivity_workflow.py", line 58, in RunConnectivityWorkflow
    wf.run()
  File "/network/lustre/iss01/apps/lang/anaconda/fmriprep/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/network/lustre/iss01/apps/lang/anaconda/fmriprep/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 556, in run
    self._submit_graph(pyfiles, dependencies, nodes)
  File "/network/lustre/iss01/apps/lang/anaconda/fmriprep/lib/python3.6/site-packages/nipype/pipeline/plugins/slurmgraph.py", line 83, in _submit_graph
    if self._dont_resubmit_completed_jobs:  # A future parameter for controlling this behavior could be added here
AttributeError: 'SLURMGraphPlugin' object has no attribute '_dont_resubmit_completed_jobs'
```
I don't know if this contributes but the configurations are modified using a json file which is used  like this 

```
from nipype import config

res=open(conf_file,'r').read()
conf=json.loads(res)
config.update_config(conf)
```

The json file which contains the configuration

```
{"execution":
    {"plugin":"SLURMGraph", 
    "plugin_args":
        {
            "dont_resubmit_completed_jobs":"False",
            "sbatch_args":" --mem 12G"
        }
    }
}
```

### Platform details:
Nipype is in 1.0.3

Would you have any idea about how to fix this ? 

Thank you

**Comment by GReguig** [comment]
Hello again,

I managed to fix the issue by explicitly specifying the plugin and the plugin_args to the run function of the workflow using the config.get function.

It appears that the issue happens when the default config plugin is set to SLURMGraph before running the workflow and the run plugin arguments are not specified.

**Comment by mgxd** [comment]
Thanks for posting your fix!

**Comment by ellisdg** [comment]
This error still occurs when running a workflow without setting the "plugin_args" . 
During the submission of the graph, the value of the '_dont_resubmit_completed_jobs' attribute is checked:
https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/pipeline/plugins/slurmgraph.py#L80-L82
But in the __init__ method '_dont_resubmit_completed_jobs' is never actually defined if plugin_args is either not specified or is empty/False:
https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/pipeline/plugins/slurmgraph.py#L44-L61
