### ISSUE TITLE
Restart job on error

### ISSUE THREAD

**Issue by achetverikov** [nipy/nipype#2602]
It would be great if nipype could try to run the job on particular node more than one time. I work on a cluster and sometimes things fail for no apparent reason and run OK on a second try. I know that it is possible to set max_tries for PBS plugin but it only tells to resubmit the job when _submitting_ failed. I want to do the same but in a more broad way, like whatever the reason for failing, try again N times.

I can try looking into that for PBS plugin if this is something potentially worth doing.

**Comment by oesteban** [comment]
Have you experienced these errors with sequential executors?

**Comment by achetverikov** [comment]
Well, there could be errors with sequential executions but that's usually when I'm doing something wrong. I'm talking more about errors that are outside of my direct control. Usually, it's some kind of OS error: job finished but the results do not appear (even though I set the waiting time for 60 seconds) or some stale file handle, the decoder stuck and did not complete in allotted time or something else seemingly random.

**Comment by oesteban** [comment]
Sure, I think this is a great idea. But for nipype to implement it we would need to identify clearly what we are targeting.

Some examples:

  - With sequential execution, a node failing for memory allocation will always fail unless a) the system + your process are right there at the limit and repetition might hold a chance to run; or b) repetition changes settings to consume less memory (e.g. reduce internal parallelization of the node).
  - With parallel execution, reducing internal settings of the node may not work either.

If the node being repeated is fast, or some file synchronization happened (and cache would kick in), then plain repetition would be just fine.

Makes sense?

**Comment by satra** [comment]
@oesteban - for current version of nipype i think this would be the equivalent of `travis_retry` for a given job. given things like memory limits, time limits, and os discrepancies on clusters, i thought we can handle this in distributed plugin base.

in the next engine, we will likely enable redundant computing (allow the same job to be executed N times in parallel) in addition to retry settings.

**Comment by achetverikov** [comment]
@oesteban yeah, makes sense. In theory, it would be very nice to distinguish error types and either throw an error (e.g., if memory/time limit breached) or restart the job (if it's some random (?) error). That would require parsing job logs if they are available and implementing error types. The former could be done but it might be cluster-specific. I'm not sure if nipype currently has mechanisms for the latter.
