### ISSUE TITLE
Try to run example  fmri_nipy_glm.py.  get error: glm = GLM.GeneralLinearModel();  TypeError: __init__() missing 1 required positional argument: 'X'

### ISSUE THREAD

**Issue by gody7334** [nipy/nipype#2624]
### Summary
glm = GLM.GeneralLinearModel()                                                                                                                           
TypeError: __init__() missing 1 required positional argument: 'X'

### Actual behavior
180627-13:22:25,768 workflow ERROR:                                                                                                                          
         Node model_estimate.a0 failed to run on host af6c3de2e4a0.                                                                                          
180627-13:22:25,770 workflow ERROR:                                                                                                                          
         Saving crash info to /home/gody7334/Project/nipype/nipype_examples/crash-20180627-132225-gody7334-model_estimate.a0-9800893f-3500-4ebf-8598-1d2f95d8
aed9.pklz                                                                                                                                                    
Traceback (most recent call last):                                                                                                                           
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node                             
    result['result'] = node.run(updatehash=updatehash)                                                                                                       
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run                                      
    result = self._run_interface(execute=True)                                                                                                               
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface                           
    return self._run_command(execute)                                                                                                                        
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command                             
    result = self._interface.run(cwd=outdir)                                                                                                                 
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run                                       
    runtime = self._run_interface(runtime)                                                                                                                   
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/nipy/model.py", line 180, in _run_interface                           
    glm = GLM.GeneralLinearModel()                                                                                                                           
TypeError: __init__() missing 1 required positional argument: 'X'

### Script/Workflow details

Please put URL to code or code here (if not too long).
https://github.com/nipy/nipype/blob/a7a9c85c79cb1412ba03406074f83200447ef50b/examples/fmri_nipy_glm.py

### Platform details:
{'pkg_path': '/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype', 'commit_source': 'archive substitution', 'commit_hash': '%h', 'nipype_ver
sion': '1.1.0-dev', 'sys_version': '3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]', 'sys_execu
table': '/opt/miniconda-latest/envs/neuro/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.14.5', 'scipy_version': '1.1.0', 'networkx_version': '2.1
', 'nibabel_version': '2.3.0', 'traits_version': '4.6.0'}                                                                                                    
1.1.0-dev 

### Execution environment

Choose one
- Container 
nipype_tutorial:latest docker

**Comment by djarecka** [comment]
can you please tell me which dataset you're using to run this example?

**Comment by mgxd** [comment]
closing this in favor of #2627
