### ISSUE TITLE
AROMA: TraitError: The trait 'nonaggr_denoised_file' of an ICA_AROMAOutputSpecRPT instance is an existing file name

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2631]
### Summary
https://github.com/poldracklab/fmriprep/issues/1090#issuecomment-401900380

### Actual behavior
The trait `nonaggr_denoised_file` defines `exists=True`

### Expected behavior
The resulting file may not exist. Maybe check the existence of the file only iff detected components > 0?

### How to replicate the behavior
Run AROMA on a datasets where no components are found.

### Script/Workflow details
FMRIPREP

### Platform details:
Any

### Execution environment
Any

**Comment by mgxd** [comment]
Even if there are no detected components, [those files should exist](https://github.com/maartenmennes/ICA-AROMA/blob/a629eb70e7fe6669d65761bd543b8186af6c21a9/ICA_AROMA_functions.py#L583-L587)

**Comment by oesteban** [comment]
Thanks for the finding. @effigies' theory getting more and more support https://github.com/poldracklab/fmriprep/issues/1090#issuecomment-402216416

Responsibility would remain here if that is confirmed. Otherwise, it could be a problem with the container and FMRIPREP. In the latter case this issue could be closed.

**Comment by mgxd** [comment]
closing this for now, but let's keep an eye on it
