### ISSUE TITLE
Adding Segmentation Output to FSL:Epi_Reg

### ISSUE THREAD

**Issue by weningerleon** [nipy/nipype#2657]
The command epi_reg (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT/UserGuide#epi_reg) produces a segmentation map. In the current version of nipype, only the white-matter segmentation can be accessed, the white-matter, gray-matter, csf segmentation map is included in the output specs.

I would suggest adding this segmentation map to the output specs. May I open a pull request for this?

**Comment by effigies** [comment]
A pull request would be very welcome!
