### ISSUE TITLE
Testing with nosetests

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#2660]
Hi, is any testing still done via nosetests? I see the `Makefile` contains

```
NOSETESTS=`which nosetests`
```

But that variable is never called again, and I don't see nose listed under the dependencies. Running nosetests in the package root starts executing a lot of stuff, however, but I'm not sure whether this is the proper way to test recent nipype versions (working with `1.1.0`).

**Comment by effigies** [comment]
No. Nipype switched to pytest. Do you want to open a PR to remove any `nose`-related cruft?

**Comment by TheChymera** [comment]
Ah, turns out most of the nose stuff has already been cleaned. two comment mentions were left: https://github.com/nipy/nipype/pull/2662/files
