### ISSUE TITLE
BUG: CircleCI (over)usage

### ISSUE THREAD

**Issue by larsoner** [nipy/nipype#2667]
I opened a CircleCI page for a `nipy/PySurfer` PR and was alerted that:
```
Your current usage represents 467% of your nipy Linux plan's limit.
Please upgrade in order to ensure no disruption in building.
```
Looking at the list of recent runs, it looks like there are tens of ~30 minute runs on some days for nipype, so I assume that's the culprit (?):

https://circleci.com/gh/nipy

The free plan is 1500 minutes/month. In the [settings page](https://circleci.com/gh/organizations/nipy/settings) it looks like in the last 10 days we've burned through about as much as last month, which was already 7308 minutes itself (and the month before was 13244 min):
```
Jul 21 - Aug 21 | 116h 47m 11s
Jun 21 - Jul 21 | 121h 48m 24s
May 20 - Jun 20 | 220h 44m 31s
```
I'm not sure if there is anything you can do to reduce the CircleCI build requirements, but it might be worth looking into lest we get busted by the CircleCI folks. I'm not sure what action they might take, if any, but I assume at some point they will cancel our builds or suspend them to the next build cycle. (In the past I've also had to wait to have PySurfer CircleCI builds start in the, too, so even if we don't get busted for overuse, any optimization/streamlining that can be done would be appreciated by other `nipy` projects!)

**Comment by oesteban** [comment]
An effective solution would be moving nipype to its own organization.

**Comment by larsoner** [comment]
That would fix the problem/risk for other `nipy` projects, but the problem of nipype using too many CI minutes would probably remain. It looked like the other repos were using a small fraction of the total org minutes, but I didn't look too closely.

**Comment by effigies** [comment]
I'd suggest that we reduce the number of cases where the example workflows
are run.

This should be resolved as niflows comes online, but in the meantime we can
only run them on some branches.

**Comment by satra** [comment]
@larsoner - while we have been told by circle that we were one of the top users we have never had any disruption to service. we have consistently used over 500% of the limit over many months. my preference for the moment will be to not disrupt things unless we actually run into issues. 

please let us know if you run into any practical issues. as far as i know some of the other nipy projects have had no trouble with circle thus far.

in terms of our roadmap, a lot of the time consuming bits (workflows/examples) will get moved to a different organization over the next six months, with travis/circle focused on core nipype elements, which should reduce time significantly.

**Comment by larsoner** [comment]
> please let us know if you run into any practical issues.

Sometimes I've had to wait a few hours for a CircleCI (or Travis) build to start for PySurfer, but it's manageable, especially with a low PR load for PySurfer.

Sounds like you're aware of the issue, so I'll close -- thanks for the discussion.
