### ISSUE TITLE
incorrect detailed graphs being generated

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2668]
### Summary

the detailed graph is not listing names of nodes appropriately resulting in incorrect graphs.

scroll down to see the multiple arrows containing nodes in the figures of the following notebook.
https://miykael.github.io/nipype_tutorial/notebooks/introduction_quickstart.html

an example here:

![image](https://user-images.githubusercontent.com/184063/43534422-50e73862-9585-11e8-83d9-697675db63e8.png)

i suspect this has something to do with how `__repr__` and `__str__` are being used. 

@oesteban, @effigies  - any quick ideas before i look into the code?

### Expected behavior

should have printed the old style with multiple nodes. 

see cell 14 in this notebook:
https://github.com/ReproNim/reproducible-imaging/blob/master/notebooks/introductory_dataflows.ipynb

### How to replicate the behavior

run the current quickstart notebook in @miykael binder repo.

**Comment by djarecka** [comment]
I've just done some renaming, so it's now called `introduction_quickstart_non-neuroimaging`. I also built the new container for binder, can go [here](https://mybinder.org/v2/gh/miykael/nipype_tutorial/master)

**Comment by djarecka** [comment]
@oesteban - in tis [PR](https://github.com/djarecka/nipype/compare/before2381...djarecka:aster2381) you removed `__repr__` and created `__str__` in `engine.base.py`, but `self.fullname` doesn't have information about the iterables, so the difference between  `self.fullname` and `'.'.join((self._hierarchy, self._id))` can be:
'hello_mapnode.add_1' vs 'hello_mapnode.add_1.a1'

was this on purpose?

**Comment by oesteban** [comment]
I can remember having issues with those three properties. If I recall correctly, iterable nodes were not returning the hierarchy with the `fullname` property. I tried to sort that out (with little success, seemingly).

**Comment by oesteban** [comment]
And also, `Workflows` should not have `itername`, is that correct?

**Comment by djarecka** [comment]
@oesteban - I  wasn't completely sure whether `Workflow` should have `itername`, it looks like it used to have. I moved back `itername` to `EngineBase` in #2669, but I can revert my changes if you believe that it's better to keep it in `Node`. Do you have a better solution to [test_deep_nested_write_graph_runs fail](https://travis-ci.org/nipy/nipype/jobs/411118845)?
We decided to use `n.itername` [here](https://github.com/nipy/nipype/pull/2669/files#diff-9ba5414cd648e8822760bda3f509fe1dR510), and that was working fine for Satra's tutorial and simpler examples, but not for nested workflows.

**Comment by oesteban** [comment]
With 2.0 on the horizon I don't think it is worth your time finding out how to make this the most rigorous way. If it works, I'm fine with it.

**Comment by djarecka** [comment]
@oesteban - ok, if anyone has any problems with naming, printing etc., we will review it

**Comment by satra** [comment]
seems like this is still the case:

scroll down a few cells from here: https://miykael.github.io/nipype_tutorial/notebooks/basic_joinnodes.html#Exercise-1

@miykael @djarecka - any thoughts.

**Comment by miykael** [comment]
@satra, this is corrected in the docker image, but not in the figure on the webpage. The current setup doesn't create the webpage dynamically, i.e. with every new PR. It's me manually updating the page and especially the figures from time to time.

I chose this option because I didn't know better and because I also didn't want to have multiple image-diffs in the git log and make it explode with this. Do you think this is a reasonable concern or is there an alternative? I thought about generating the page via circleci and directly pushing it to a particular branch?

**Comment by satra** [comment]
@miykael - i think doing something with circle would be good. just like dorota runs the tests on the repo everytime we release, we should update everything on the page, when we release. i think it would not explode with every release. and in some sense no worse off than the main notebook repo itself.

**Comment by effigies** [comment]
You can have a look at the nipybot stuff ([tools/update_feedstock.sh](https://github.com/nipy/nipype/blob/master/tools/feedstock.sh) + [.circleci/config.yml](https://github.com/nipy/nipype/blob/master/.circleci/config.yml#L376-L406)) for submitting/updating PRs on release branches.
