### ISSUE TITLE
Different Coregistration results using spm GUI in matlab and nipype SPM interfaces!

### ISSUE THREAD

**Issue by mrahimpour** [nipy/nipype#2697]
### Summary
Hi, 

I was trying to coregister PET and MR images using nipype spm interfaces, CalcCoregAffine to get the coregistration affine matrix and ApplyTransform to apply the transform (affine matrix) to the PET images. The coregisterd result was so distorted and also not right in orientation. So I tried coregistration using spm GUI in matlab  (Estimate & reslice) and got totally different result. I am expecting same affine matrix for PET/MR coregistration using nipype and smp GUI. should I set something else?

### Script/Workflow details
import nipype.interfaces.spm as spm
import nipype.interfaces.spm.utils as spmu

import pdb
"""
Mtalab-SPM path
"""
import nipype.interfaces.matlab as mlab

mlab.MatlabCommand.set_default_paths('/usr/local/MATLAB/R2018a/toolbox/spm12')

"""
coreg = spmu.CalcCoregAffine(matlab_cmd='matlab spm')
coreg.inputs.target = '/home/PET_COREG_WF/Data/600136/anat_1/n600136_MPRAGE.nii'
coreg.inputs.moving = '/home/PET_COREG_WF/Data/600136/pet_1/n600136_KENNIS_FET_DYN.nii'
coreg.inputs.mat = '/home/PET_COREG_WF/func_to_struct.mat'
coreg.run() 

#pdb.set_trace()
"""
applymat = spmu.ApplyTransform()
applymat.inputs.in_file = '/home/masoomeh/PET_COREG_WF/Data//600136/pet_1/n600136_KENNIS_FET_DYN.nii"
applymat.inputs.mat = '/home/PET_COREG_WF/func_to_struct.mat'
applymat.run()

Please put URL to code or code here (if not too long).

### Platform details:

```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.1',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.2',
 'numpy_version': '1.15.0',
 'pkg_path': '/home/masoomeh/opt/anaconda3/lib/python3.5/site-packages/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/home/masoomeh/opt/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) \n'
                '[GCC 7.2.0]',
 'traits_version': '4.6.0'}

```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by satra** [comment]
@mrahimpour - can you try the `Coregister` interface in Nipype - to make things equivalent?

https://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.spm/preprocess.html#coregister

**Comment by mrahimpour** [comment]
I have already tried this one, but I am working with dynamic PET; so I need to have affine transformation matrix to apply to different time frames. Uisng Coregister, I did not know how to save this matrix !!!

**Comment by satra** [comment]
the spm gui uses the Coregister function (with estwrite), hence you were comparing two different tools. could you describe the problem you are trying to address? it's possible that coregister is sufficient to address your use case. the estimate part of Coregister does save an affine matrix that can be applied using just coregister write.

**Comment by mrahimpour** [comment]
Thanks for your quick reply. 

I am trying to write a pipeline using nipype to coregister the dynamic PET to structral MR image. I want to do one coregistration between mean PET and MR, save the affine transformation matrix and then apply this matrix to all time frames in dynamic PET. Checking spm.Coregister() function, I could not understand how  to save the matrix and also how to apply it to the other time frames. Is there anyway to fix it by using spm.Coregister().

**Comment by mrahimpour** [comment]
Many thanks for your help! It is working quite well for me.
