### ISSUE TITLE
nipype.interfaces.elastix - Library not loaded: libANNlib.dylib

### ISSUE THREAD

**Issue by ad12** [nipy/nipype#2709]
### Summary
Using nipype library to interface with elastix, but getting error ```Library not loaded: libANNlib.dylib```.

### Actual behavior
Error - Library not loaded: libANNlib.dylib

```
180921-15:18:30,846 nipype.interface INFO:
	 stderr 2018-09-21T15:18:30.846329:dyld: Library not loaded: libANNlib.dylib
180921-15:18:30,846 nipype.interface INFO:
	 stderr 2018-09-21T15:18:30.846329:  Referenced from: ~/elastix_macosx64_v4.8/bin/elastix
180921-15:18:30,846 nipype.interface INFO:
	 stderr 2018-09-21T15:18:30.846329:  Reason: image not found
RuntimeError: Command:
elastix -f ./temp/2018-09-21-22-18-30/001.nii -m ./temp/2018-09-21-22-18-30/002.nii -threads 1 -out ./ -p ~/elastix_params/parameters-affine.txt
Standard output:

Standard error:
dyld: Library not loaded: libANNlib.dylib
  Referenced from: /Users/ad/elastix_macosx64_v4.8/bin/elastix
  Reason: image not found
Return code: -6
```

### Expected behavior
No error. `libANNlib.dylib` is added to path in `.bash_profile`. nipype should know that it has been added.

### Script/Workflow details
I have added `export DYLD_LIBRARY_PATH=path_to_elastix/lib:$DYLD_LIBRARY_PATH` to my `~/.bash_profile`.

I am running the python code in a conda virtual environment. After activating the virtual env, I run a python script that uses nipype. These details are provided in the **Standard output** section

When I run elastix directly from the command line, using the command below, there are no errors
```
elastix -f ~/2018-09-21-22-13-46/001.nii -m ~/002.nii -threads 1 -out ./ -p ~/parameters-affine.txt
```

Standard output:
Please put URL to code or code here (if not too long).

Code:
```
            from nipype.interfaces.elastix import Registration
            reg = Registration()
            reg.inputs.fixed_image = target_filepath
            reg.inputs.moving_image = spin_file
            reg.inputs.parameters = ['~/parameters-affine.txt']
            reg.run()
```

### Platform details:

```
{'commit_hash': '8690d55d9',
 'commit_source': 'installation',
 'networkx_version': '2.1',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.2',
 'numpy_version': '1.14.3',
 'pkg_path': '/Users/ad/anaconda3/envs/tf/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/Users/ad/anaconda3/envs/tf/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) \n'
                '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]',
 'traits_version': '4.6.0'}
```

### Execution environment
conda 4.5.11 virtual environment
Mac OS 10.13.6

**Comment by satra** [comment]
are you by any chance executing this via an IDE like pycharm? or running nipype from the same terminal where you ran the elastix code. many IDE's do not invoke the bashrc when they launch a shell.

**Comment by ad12** [comment]
@satra I'm running the nipype script from the terminal as well. I am using a conda virtual env, but the bashrc should be invoked when the terminal window is launched.

**Comment by ad12** [comment]
@satra Running the code in the section below. Not sure if `result = reg.run()` would work though because the line `reg.run()` throws the error of not loading the `libANNlib.dylib` library.

Error:
```
Standard error:
dyld: Library not loaded: libANNlib.dylib
  Referenced from: /Users/arjundesai/elastix_macosx64_v4.8/bin/elastix
  Reason: image not found
Return code: -6
```

Code:
```            
from nipype.interfaces.elastix import Registration
reg = Registration()
reg.inputs.fixed_image = target_filepath
reg.inputs.moving_image = spin_file
reg.inputs.parameters = ['~/parameters-affine.txt']
result = reg.run()
```

**Comment by satra** [comment]
ah, yes you are right. could you simply run this:

```
from nipype.interfaces.elastix import Registration
reg = Registration()
import os
os.environ['DYLD_LIBRARY_PATH']
```

and make sure the output from the last line includes the elastix library path and that the path contains the missing library from the error message: `libANNlib.dylib`

**Comment by ad12** [comment]
The output is detailed below. My understanding was that the output should be the path to the directory where the library lives, which is what is outputted. Should the path be the full path to the library itself (i.e. `/Users/ad/elastix_macosx64_v4.8/lib/libANNlib.dylib`)

Output:
```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nipype.interfaces.elastix import Registration
>>> reg = Registration()
>>> import os
>>> os.environ['DYLD_LIBRARY_PATH']
'/Users/ad/elastix_macosx64_v4.8/lib'
```

**Comment by ad12** [comment]
@satra is there a specfic version of elastix that nipype 1.1.2 is compatible with?

**Comment by ad12** [comment]
@satra I think I found the issue - see details below

I inspected the `runtime.dependencies` variable on line 1030 in `core.py` as see below.

```
b'/Users/ad/elastix/bin/elastix:\n\t/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)\n\tlibANNlib.dylib (compatibility version 0.0.0, current version 0.0.0)\n\t/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)\n\t/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)\n\t/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)'
```

It seems as though when loading the `libANNlib.dylib`, the path to the dependency `libANNlib.dylib` is not loaded. For example, the full path should be something like `/Users/ad/elastix/lib/libANNlib.dylib`. 

When I copy the `libANNlib.dylib` file to my project folder where I am executing the python script from,  the interface runs as expected.

I think there is an issue with how the dependency paths are loaded. Maybe an easy fix could be to replace the `libANNlib.dylib` in the `runtime.dependencies` variable with the full path to the `libANNlib.dylib` file?

**Comment by satra** [comment]
@ad12 - this has to do with OS X restrictions. as an example see this thread:

https://github.com/rbenv/rbenv/issues/962#issuecomment-275858404

so ideally this would be fixed in elastix. 

the other possible thing you can try, but i'm not sure it will help is to try:

```python
reg._cmd = 'DYLD_LIBRARY_PATH=/Users/ad/elastix/lib/ elastix'
...
reg.run()
```

this would be a workaround, but could work.

**Comment by ad12** [comment]
@satra Ah got it thanks for the help! 

Also, is there a way to suppress the output of the interfaces from printing to the console?

I followed the instructions [here](https://thesmithfam.org/blog/2012/10/25/temporarily-suppress-console-output-in-python/), but it did not seem to work.

Thanks again!

**Comment by satra** [comment]
depending on what you want to achieve, you will need to either:

1. set the appropriate logging level 

https://miykael.github.io/nipype_tutorial/notebooks/basic_execution_configuration.html#Global,-workflow-&-node-level

2. or use the `terminal_output` options for command line interfaces :

https://nipype.readthedocs.io/en/latest/devel/interface_specs.html#controlling-outputs-to-terminal
