### ISSUE TITLE
Couldn't use functions within fsl 

### ISSUE THREAD

**Issue by Irisfee** [nipy/nipype#2710]
### Summary
Hi,

I have installed nipype successfully, and also I have fsl on my computer. I have set the PATH and the FSLDIR to the correct location, but when I run nipype with jupyter lab, I still got an error that:

OSError: No command "fslstats" found on host dyn-184-171-77-168.uoregon.edu. Please check that the corresponding package is installed.

I have tried : from nipype.interfaces.fsl import Info; print(Info.version())
and it returned "None"

### Script/Workflow details

https://uoregon-my.sharepoint.com/:u:/g/personal/yzhao17_uoregon_edu/EcJYePVPt85ChHXEldsL8jkBg_E4ZvWTLY_mZ9Rh3TuBEQ?e=D2NaSa

### Platform details:

None
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.1',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.2',
 'numpy_version': '1.14.3',
 'pkg_path': '/Users/yufei/anaconda3/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/Users/yufei/anaconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) \n'
                '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]',
 'traits_version': '4.6.0'}

### Execution environment

- My python environment outside container (locally on the Mac OS)

thanks a lot!

**Comment by djarecka** [comment]
And what happen if you run `from nipype.interfaces.fsl import Info; print(Info.version())` in normal python interpreter (not jupyter-lab)?

could you run  `fslstats` in  your terminal?

**Comment by Irisfee** [comment]
I typed:

python -c "import nipype; from pprint import pprint; pprint(nipype.get_info())"

and I got:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named nipype

I can run fslstats in the terminal

**Comment by Irisfee** [comment]
I have figured out the problem - I opened my jupyterlab from anaconda launch pad, not the terminal, so the env there were totally messed up. I could use the script successfully by opening jupyterlab through terminal.
