### ISSUE TITLE
ensure docs build properly on readthedocs

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2713]
nipype on readthedocs has not been building properly, since release 1.1.1:

https://readthedocs.org/projects/nipype/builds/7835987/

we should try to ensure that our own doc build returns appropriate errors on circle if they fail, which i thought it did. we should resolve what it is between our tests and readthedocs is altering the failure mode.

according to the error above it seems something about matplotlib sphinx extension

**Comment by satra** [comment]
this extension exists at least in `matplotlib` release `2.2.2`, which is available inside the `nipype/nipype:py36` docker container.

so this is likely some setting in/for readthedocs that's causing issues.

**Comment by miykael** [comment]
I tried to build the docs locally and got an error concerning `matplotlib.sphinxext.only_directives`. The easy solution was to just remove/comment this dependency in the `conf.py` file ([here](https://github.com/nipy/nipype/blob/master/doc/conf.py#L53)). But I'm not sure if it will lead to other errors down the line (or for what this extension is actually needed).
