### ISSUE TITLE
pytest never exits due to "config.enable_resource_monitor()" in test_resource_monitor.py

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#2719]
while building 1.1.3 (doesn't happen with 1.1.2) debian package, and showed to @effigies and @mgxd , pytest process never exits with some processes started within test_CommandLine_prefix still running in the background, not killed.
With some manual bisection it seems boiled down to `config.enable_resource_monitor()` call within `test_resource_monitor.py`.  Even if all tests are skipped in that file, that call is ran while pytest is just collecting the tests, so it is "in effect".

I wonder if that relates to 87ef62f1cd4d1de2cd554a6fae51de6de12c64ec (and may be some related changes)?

**Comment by effigies** [comment]
cc @oesteban

**Comment by yarikoptic** [comment]
probably there should be `disable_resource_monitor` as well, and enable/disable should happen in tests fixture, not at the test module import level

**Comment by effigies** [comment]
:+1:

**Comment by yarikoptic** [comment]
I will submit a PR shortly.... seems to "work" (those tests are sskipped atm anyways)

**Comment by effigies** [comment]
Closed by #2725.
