### ISSUE TITLE
Additional parameters for FSL Eddy

### ISSUE THREAD

**Issue by divetea** [nipy/nipype#2744]
### Summary
nipype's interface for FSL eddy currently does not support the  parameters "--cnr_maps" and "--residuals".

### Actual behavior
You can use the parameters through the args string, but then you can not connect the resulting output to other nodes!

### Expected behavior
Make them proper optional parameters that produce proper output specified in the OutputSpec 

### Platform details:
{'commit_hash': '3ec8065',
 'commit_source': 'repository',
 'networkx_version': '2.1',
 'nibabel_version': '2.1.0',
 'nipype_version': '1.1.4-dev+g3ec8065',
 'numpy_version': '1.15.0',
 'pkg_path': 'private/nipype/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.9 (default, Jun 29 2016, 13:08:31) \n[GCC 4.9.2]',
 'traits_version': '4.6.0'}

FSL version: 5.0.10

These eddy parameters are kind of hidden since they do not appear in the usage page, they do however appear in the eddy user guide: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide

    my_eddy_output.eddy_cnr_maps
        Written iff --cnr_maps is set
    my_eddy_output.eddy_residuals
         Written iff --residuals is set.

I have already written the code because someone at our chair needed it, so if you want i can make a pull request.
Kind regards,
Niklas Förster

**Comment by mgxd** [comment]
Hi Niklas - that would be great!
