### ISSUE TITLE
 adding SliceEncodingDirection to afni.TShift

### ISSUE THREAD

**Issue by fliem** [nipy/nipype#2752]
### Summary
BIDS allows to specify `SliceEncodingDirection`. How about adding a  parameter to `afni.TShift` to use this information and `SliceTiming` from BIDS sidecar files directly.

This comes via [fmriprep](https://github.com/poldracklab/fmriprep/issues/1345). @effigies suggested to add this here.

BIDS allows to declare `SliceEncodingDirection` to specify the direction of `SliceTiming`. What do you think about adding a `SliceEncodingDirection` input (`{k, k-}`) to `afni.TShift`. If this is `k-`, reverse the slice timing list before running the correction.

Does it make sense to also add `i, j, i-, j-`? Or does it make sense to always assume that slices have been acquired along the third axis?

What do you think?

**Comment by effigies** [comment]
I'll review, so I'd say full speed ahead. :-)

`SliceTiming` is passed to the `slice_timing` input, defined here:

https://github.com/nipy/nipype/blob/39675df33fadf4459e46b0dcdb78425b853dd22d/nipype/interfaces/afni/preprocess.py#L2615-L2620

I would start with `{k, k-}` as you suggest, as that will cover the majority of the cases, and we can think about `i` and `j` in a separate PR.
