### ISSUE TITLE
Incompatibility with networkx>=2 and version conflict with prov dependency

### ISSUE THREAD

**Issue by tclose** [nipy/nipype#2820]
### Summary

As far as I can tell nipype isn't compatible with networkx>=2, as running with networkx>=2 raises a "graph change during iteration" error. So perhaps this should be reflected in the install requires of the setup.py (i.e. frozen at networkx==1.9).

However, it is complicated by the fact that another dependency, prov>=1.5.2 requires networkx>=2, and attempting to use the nipypecli with prov>=1.5.2 with networkx==1.9 raises a 'pkg_resources.ContextualVersionConflict' error (at least with Python 3.7)

### Actual behavior

An error is raised

```
Traceback (most recent call last):
  File "/usr/local/bin/nipypecli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3123, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.9 (/usr/local/lib/python3.7/site-packages), Requirement.parse('networkx>=2.0'), {'prov'})
```

### How to replicate the behavior

Install networkx==1.9 and prov==1.5.2 and use nipypcli crash to open a crash file

### Script/Workflow details

N/A

### Platform details:

```
{'commit_hash': 'b448b6061',
 'commit_source': 'installation',
 'networkx_version': '1.9',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.6',
 'numpy_version': '1.15.4',
 'pkg_path': '/usr/local/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/usr/local/opt/python/bin/python3.7',
 'sys_platform': 'darwin',
 'sys_version': '3.7.1 (default, Nov  6 2018, 18:45:35) \n'
                '[Clang 10.0.0 (clang-1000.11.45.5)]',
 'traits_version': '4.6.0'}
```

### Execution environment

My python environment outside container

**Comment by satra** [comment]
@tclose - there is obviously some weird thing happening here, but we have been running with `networkx > 2` for a while. would it be possible to test your workflow in a fresh environment? if you are using conda you can create one with `conda create -n testweirderror python=3.7.1 nipype`

**Comment by effigies** [comment]
This might be pip's problem, which doesn't do full-bore dependency resolution. I would just try `pip install --upgrade networkx>=2.0`.

**Comment by tclose** [comment]
Actually, I just realised it doesn't happen for every workflow that I run, so it looks as though it might be another case of my funky auto-generated workflows exploring an obscure corner of the code.

You should hopefully be able to reproduce the error by checking out the master branch from http://github.com/MonashBI/arcana and running the <repo-root>/test/unittests/study/test_study.py unittests (Arcana's dependencies can be installed using the setup.py, however it will force the installation of networkx==1.9, which you will need to manually upgrade after). Only the 'test_run_pipeline_with_prereqs' test errors so you should be able to compare the workflow generated by it with the others in the module. I have had a quick look but can't see anything obvious.

**Comment by effigies** [comment]
That's a fairly distinctive sort of error. It looks like we didn't wrap enough calls to `nx.topological_sort` in `list()`. Can you try the branch in #2828 and see if that fixes your error?

If `prov` requires `networkx>=2.0`, that may present the opportunity to get rid of networkx 1.x compatibility measures.

**Comment by tclose** [comment]
Yep #2828 fixes the problem, thanks
