### ISSUE TITLE
BIDS support for modelgen removed?

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#2863]
Hi @effigies it seems this PR e88a825858090883856a91cb1e71655c04a8c2a5 ended up being undone somewhere along the way. Can you please reinstate it?

**Comment by effigies** [comment]
I still see it in [`master`](https://github.com/nipy/nipype/blob/master/nipype/algorithms/modelgen.py). What are you looking at where you don't see it?

**Comment by TheChymera** [comment]
ah, yes,  was pulling master from my fork rather than the official repo. Sorry for that.
