### ISSUE TITLE
Sticky Draft on Release Page

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#2897]
If I navigate to the release page I am met by this:

![screenshot from 2019-03-07 21-08-49](https://user-images.githubusercontent.com/950524/53987413-375bcc80-4121-11e9-8bba-d94f5509f298.png)

Did I do this? If so, sorry. How should I best get rid of it?

**Comment by effigies** [comment]
No, I think that was @oesteban. We don't really use it, but it does give users a running changelog for the upcoming release. It resets after each release.
