### ISSUE TITLE
pip install nipype completely destroys conda

### ISSUE THREAD

**Issue by lillepeder** [nipy/nipype#2898]
I ran `pip install nipype` from my Windows 10 conda environment, as `conda install nipype` and conda-forge had failed.

Now, conda is completely useless. For instance 
`conda list`

outputs

`RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Can't open list: [Errno 2] No such file or directory: 'list'
RefactoringTool: No files need to be modified.
RefactoringTool: There was 1 error:
RefactoringTool: Can't open list: [Errno 2] No such file or directory: 'list'`

Is there any way to undo the changes (preferably without reinstalling all of Anaconda)?

**Comment by mgxd** [comment]
hi @lillepeder - unfortunately, i'm not sure how this interaction would work (especially on windows). However, if you do a fresh install of conda and retry install nipype, I'd like to take a look at why your `conda install nipype` is failing.

**Comment by lillepeder** [comment]
> 
> 
> hi @lillepeder - unfortunately, i'm not sure how this interaction would work (especially on windows). However, if you do a fresh install of conda and retry install nipype, I'd like to take a look at why your `conda install nipype` is failing.

After losing my patience I did just that, but this time the conda install functioned properly! Thanks for the reply.
