### ISSUE TITLE
nipype 1.1.9 -  is it possible to import freesurfer utils module ImageInfo?

### ISSUE THREAD

**Issue by switt4** [nipy/nipype#2902]
### Summary
I am in the process of converting some matlab code that resamples image files in fsaverage space into the new fs_lr space.  The matlab code calls freesurfer's mri_info to get the voxel to RAS transform matrix.  I noticed in the freesurfer utils.py code that there is a module called 'ImageInfo' which calls mri_info.  This module is not described in the nipype documentation, though.  

When I try to import the module into python, I get an error saying that the module cannot be imported.  Is ImageInfo an accessible module, or is it some private module that is called by other freesurfer modules?  If the latter, is there another freesurfer module I could replace to get the same transform matrix?  Or barring that, any other way I can get the vox to RAS transform matrix in python?

Thanks,
suzanne

### Actual behavior

from nipype.interfaces.freesurfer import ImageInfo
File "<ipython-input-23-226fabf62ac0>", line 1, in <module>
    from nipype.interfaces.freesurfer import ImageInfo

ImportError: cannot import name 'ImageInfo'

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

```
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.1',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.9',
 'numpy_version': '1.14.3',
 'pkg_path': '/anaconda3/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.1.0',
 'sys_executable': '/anaconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) \n'
                '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]',
 'traits_version': '4.6.0'}
```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by effigies** [comment]
It looks like `ImageInfo` isn't imported into `nipype.interfaces.freesurfer`, so you'll need to import it from the module it's defined in.

```Python
from nipype.interfaces.freesurfer.utils import ImageInfo
```

**Comment by switt4** [comment]
Thanks for the quick response.
