### ISSUE TITLE
Tiny BET configuration and output specification bugs

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nipype#2916]
Hi all,

Just wanted to point out a couple of tiny bugs:
- [BETInputSpec][1]'s default frac value is 0, whereas [BET][2]'s actual default value is 0.5. That should be easy enough to update.
- BETInputSpec includes a "skull" option which does, in fact, result in another .nii file with a __skull_ suffix, however, it is not included in BETOutputSpec's definition or the __list_output_ method. 
- When setting BET's out_file to some location other than the pwd, everything is created properly, but the interface's BETOutputSpec instance (output_spec) seems to list all of the output files' locations (other than the out_file) as if they were still created in the pwd. It seems to have something to do with [FSLCommand][3]'s _gen_fname method and its call to fname_presuffix with _newpath=cwd_, but I haven't yet really tried to understand what might be the repercussions of changing anything there. 

I hope I fork the repo and propose fixes sometime soon, but it's a pretty busy time right now. Just thought it wouldn't hurt to put it here, for future reference if nothing else. 

Thank you for all your amazing work! 
Zvi

[1]: https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/preprocess.py
[2]: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET/UserGuide
[3]: https://github.com/nipy/nipype/blob/27490e67a48428699466c0a4cfa36ce25cf7222d/nipype/interfaces/fsl/base.py

**Comment by effigies** [comment]
Thanks for these notes. Can you verify these are true for all versions of BET? In particular, if the default frac value varies by version, we should encode that.

**Comment by ZviBaratz** [comment]
I couldn't find any documentation for previous versions of BET, however, I searched for "BET" references in [FSL's release history](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/WhatsNew) and did not find any mention of changing it. [BET's FAQ page](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET/FAQ) does also mention that the default value is 0.5, if that helps.

**Comment by satra** [comment]
@ZviBaratz - just a quick note that BET does not have a default for `frac`. 

https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/preprocess.py#L45

in nipype, for something to have a default and be used two things need to happen.

1. a default value needs to be set
2. the metadata `usedefault=True` has to be added.

the way nipype deals with defaults is therefore not consistent across interfaces. we will likely implement a clear default policy for nipype 2.0, but i'm inclined not to introduce this in nipype 1.x.

**Comment by ZviBaratz** [comment]
@satra - Thank you for the note. 
Also, I'm excited to hear 2.0 is in the works! I am actually trying to create a django application to better support analysis configuration and execution serialization for [our lab](http://neuroimaging.tau.ac.il/) and would be more than happy to also become involved in the future development of nipype if I can. I subscribed to the mailing list and will follow up soon.

**Comment by ZviBaratz** [comment]
Just to follow up on this - BET still seems to return incorrect output paths. If anyone has an idea for a quick fix I will gladly come up a PR. Maybe during next week's Nilearn's event would be a good time to resolve this.
