### ISSUE TITLE
EddyQuad input specification -> should omit "="

### ISSUE THREAD

**Issue by fBeyer89** [nipy/nipype#2935]
Dear community,
eddy_quad from FSL 6.0.1 doesn't seem to accept input defined by the nipype input spec.  It only runs if input is formatted like  -bvals "bvals.scheme" compared to -bvals="bvals.scheme" (input spec from nipype version 0.1.2)

(on my machine with FSL 6.0.1, this command worked:
eddy_quad /data/pt_life_dti_followup/diffusion/LI0026893X/eddy_corrected --eddyIdx /home/raid1/fbeyer/Documents/Scripts/LIFE_followup/preprocessing/nipy1.4/diffusion/index.txt --eddyParams /home/raid1/fbeyer/Documents/Scripts/LIFE_followup/preprocessing/nipy1.4/diffusion/acqparams_dwi.txt --mask /data/pt_life_dti_followup/diffusion/LI0026893X/dwi_appa_corrected_maths_brain_mask.nii.gz --bvals /data/pt_life_dti_followup/diffusion/LI0026893X/cmrrmbep2ddiffs009a001.bval

but this one generated by nipype does not:
eddy_quad /data/pt_life_dti_followup/diffusion/LI0026893X/eddy_corrected --eddyIdx=/home/raid1/fbeyer/Documents/Scripts/LIFE_followup/preprocessing/nipy1.4/diffusion/index.txt --eddyParams=/home/raid1/fbeyer/Documents/Scripts/LIFE_followup/preprocessing/nipy1.4/diffusion/acqparams_dwi.txt --mask=/data/pt_life_dti_followup/diffusion/LI0026893X/dwi_appa_corrected_maths_brain_mask.nii.gz --bvals=/data/pt_life_dti_followup/diffusion/LI0026893X/cmrrmbep2ddiffs009a001.bval

Maybe the input spec should be updated?

### Platform details:
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.2',
 'nibabel_version': '2.2.0',
 'nipype_version': '1.2.0',
 'numpy_version': '1.13.1',
 'pkg_path': '/home/raid1/fbeyer/local_pt_life/miniconda2/envs/agewell_nip1.2/lib/python2.7/site-packages/nipype',
 'scipy_version': '0.19.1',
 'sys_executable': '/home/raid1/fbeyer/local_pt_life/miniconda2/envs/agewell_nip1.2/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.15 | packaged by conda-forge | (default, Oct 12 2018, 14:10:50) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]',
 'traits_version': '4.6.0'}

**Comment by effigies** [comment]
Fixed in #2941.
