### ISSUE TITLE
Transformix (ApplyWarp()) doesn't generate warp file

### ISSUE THREAD

**Issue by SeleneDS** [nipy/nipype#2938]
Hi everyone!

I am using Nipype for a preprocessing pipeline. In my pipeline I use transformix (function ApplyWarp() from the elastix interface).

When I apply the ApplyWarp() function seperately and run it, it works perfectly.
However, when I use the function inside a Node in the pipeline and connect the output warped_file to a following node, the node executes but the warped_file of the output is never generated. I cannot find a ‘result.nii’ file anywhere.

How could I fix this?

This is the code inside the pipeline:

GM_r_reg.inputs.transform_file = abspath('./param_Rig.txt')
GM_a_reg.inputs.transform_file = abspath('./param_Aff.txt')
GM_r_reg.inputs.moving_image = abspath('./output_FAST_seg_1.nii.gz')
GM_r_reg.inputs.output_path = './'

test_wf = Workflow(name="test", base_dir=".")
test_wf.connect([(GM_r_reg, GM_a_reg, [("warped_file","moving_image")])])

test_wf.run()

This is the code when I run it seperately:

test = ApplyWarp()

test.inputs.moving_image = './Outputs/output_FAST_seg_1.nii.gz'
test.inputs.transform_file = './Outputs/param_Rig.txt'
test.inputs.output_path = './Outputs/test/'

test.run()

Thanks!

**Comment by oesteban** [comment]
Replied here: https://neurostars.org/t/transformix-applywarp-doesnt-generate-output/4362/2?u=oesteban

Please follow up there.
