### ISSUE TITLE
Dcm2niix out_filename argument moved from 'inputs' to 'input_spec' in nipype version 1.2.0?

### ISSUE THREAD

**Issue by Matt-A-Bennett** [nipy/nipype#2952]
### Summary
I'm a new nipype user and installed version 1.2.0 on my system (ubuntu 18.04). I'm trying to set the 'out_filename' argument in Dcm2niix. This argument appears in the 'input_spec' drop-down list. I consulted a colleague who is more familiar with nipype and is using version 1.1.9 and on his system the  'out_filename' argument appears in the 'inputs' drop-down list.

I tried setting a filename using  input_spec.out_filename but it had no effect...

I wonder if this move is a bug  in nipype version 1.2.0 or if I am missing something?

Thanks!

### Script/Workflow details
from nipype.interfaces.dcm2nii import Dcm2niix
converter = Dcm2niix()
converter.inputs. ### <- no option for out_filename on version 1.2.0
converter.input_spec.out_filename  ### <- option for out_filename on version 1.2.0

### Platform details:
ubuntu 18.04

```

```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by effigies** [comment]
`out_filename` is still a valid input. I'm not sure what dropdown lists you're referring to, but static analysis can be difficult in Python, and I wouldn't expect every tool to get it right. If it's an attribute of the input spec, then it can be set in `inputs`.

**Comment by Matt-A-Bennett** [comment]
Hi Chris,

Thanks for the fast reply. Sorry i explained my problem badly - maybe this screenshot helps:

[cid:97d7ee66-1400-49a5-bad1-1b8d07eeddcc]

My colleague using versions 1.1.9 would get to 'out_filename' by going converter.inputs.out_filename = 'some_string' and we couldn't understand how to set the filename with version 1.2.0. e.g.
converter.input_spec.out_filename = 'some_string' outputs nifti files with default names.

Does this help clarify?

Thanks,
Matt
________________________________

**Comment by effigies** [comment]
Sure. Even if it doesn't show up in the drop-down of your tool, it's still valid.

**Comment by Matt-A-Bennett** [comment]
Ah perfect thank you! 

I didn't realise I could nonetheless use 
converter = Dcm2niix()
converter.inputs.out_filename  = 'some_string' 
And that it would be happy and not error.
