### ISSUE TITLE
Specify limit for queued jobs on SLURM

### ISSUE THREAD

**Issue by 20zinnm** [nipy/nipype#2957]
### Summary

As far as I can tell, `n_procs` specifies how many of a single node can run in parallel. This should be extended to the workflow-level, so that we can specify a maximum total number of nodes to run at any time.

This would resolve an issue I am having with my university's HPC SLURM setup and nipype. Our cluster has a secondary queue that enforces resource limits by holding jobs over the limit, only releasing them four at a time every two minutes. When I am under my user-limit, the secondary queue immediately dumps my jobs back to SLURM to start running. However, when the SLURM plugin enqueues several hundred jobs at once for a large pipeline run, many jobs get stuck in this secondary queue and are forced to wait in line to be released. The issue is compounded  when many of the jobs need only run for only a few minutes each on the cluster computers. Thus, nodes that take longer to run are stuck waiting for the queue to be exhausted before they can even request a SLURM allocation.

I am working with our HPC team to resolve the issue, but in the meantime a quick solution would be to extend MultiProc's process limits to the workflow-level by allowing `n_procs` to be set on the workflow, which limits the number of nodes sent to the plugin for execution at any given time. If this is not practical, then the SLURM plugin could simply be adapted to not issue more than `n_procs` jobs before waiting for completion.

**Comment by 20zinnm** [comment]
I just noticed this seems to already be possible (https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/base.py#L182). This behaviour should be documented. I will test it out and see if it works.

**Comment by 20zinnm** [comment]
This is documented for 0.11 at https://nipype.readthedocs.io/en/0.11.0/users/plugins.html. Where is this doc page for 1.2?

**Comment by mgxd** [comment]
Hey @20zinnm - much of the documentation has moved over to [the tutorial page](https://miykael.github.io/nipype_tutorial/), including the [execution plugins](https://miykael.github.io/nipype_tutorial/notebooks/basic_plugins.html).

Did `max_jobs` fix your problem?

**Comment by 20zinnm** [comment]
It did. I did not realize the tutorial also serves as formal docs since it links to the homepage for further documentation. I could not find the `max_jobs` parameter for quite a while because of this.

**Comment by lcebaman** [comment]
So, is ```max_jobs``` the number of compute nodes to run on the cluster?

**Comment by satra** [comment]
it is the number of slurm jobs to run.
