### ISSUE TITLE
Run ``make specs`` on Circle/Travis

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2967]
### Summary
The idea is to free devs and contributors from running ``make specs``.

One build (maybe a lighter one with few dependencies) runs make specs and stores the `git diff` as an artifact that should be reviewed before merging in a PR.

Then, merge commits have a special section after `make specs` were the updated specs are committed and pushed back to `master` automatically.

**Comment by effigies** [comment]
A simple Travis job:

```
make specs
git add nipype
[ "$( git diff --cached | wc -l )" -eq 0 ] || ( git diff --cached && false )
```

You could also do `make check-before-commit` in place of calling pytest directly, and that will catch tests that pollute the repository, as well.

**Comment by effigies** [comment]
I'm a little hesitant to give CI the ability to push to the repository.
