### ISSUE TITLE
generate_gantt_chart fails on logfile

### ISSUE THREAD

**Issue by SiegfriedWagner** [nipy/nipype#2982]
### Summary
generate_gantt_chart fails on generating charts based on profiler log file
### Actual behavior

Exception occurs:

 > Traceback (most recent call last):
  File "./profiler_chart.py", line 2, in <module>
    generate_gantt_chart('/mnt/connectomics/profiler.log', cores=4)
  File "/home/siegfriedwagner/.local/lib/python3.6/site-packages/nipype-1.2.0-py3.6.egg/nipype/utils/draw_gantt_chart.py", line 507, in generate_gantt_chart
    duration = (last_node['finish'] - start_node['start']).total_seconds()
TypeError: unsupported operand type(s) for -: 'str' and 'str'

### Expected behavior

Graph generates flawlessly 
### How to replicate the behavior

Run script presented bellow on log from https://gist.github.com/SiegfriedWagner/891bb05bff3cb8224f23915634672a83
### Script/Workflow details

> from nipype.utils.draw_gantt_chart import generate_gantt_chart
> generate_gantt_chart('profiler.log', cores=4)

### Platform details:

```
{'commit_hash': 'a0f756d1c',
 'commit_source': 'installation',
 'networkx_version': '2.3',
 'nibabel_version': '2.4.1',
 'nipype_version': '1.2.0',
 'numpy_version': '1.17.0',
 'pkg_path': '/home/siegfriedwagner/.local/lib/python3.6/site-packages/nipype-1.2.0-py3.6.egg/nipype',
 'scipy_version': '1.3.0',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.8 (default, Jan 14 2019, 11:02:34) \n'
                '[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]',
 'traits_version': '5.1.2'}

```

### Execution environment

Choose one
- My python environment outside container

**Comment by shnizzedy** [comment]
I ran into this issue as well and [fixed it](https://github.com/shnizzedy/nipype/tree/fix/gantt_chart) for [my own purpose](https://github.com/FCP-INDI/C-PAC/issues/1404#issuecomment-756383588). I'll put in a PR with the fix.

**Comment by shnizzedy** [comment]
With the changes in #3290,

```Python
from nipype.utils.draw_gantt_chart import generate_gantt_chart
generate_gantt_chart('profiler.log', cores=4)
```
with [`profiler.log`](https://gist.github.com/SiegfriedWagner/891bb05bff3cb8224f23915634672a83) from [this issue](https://github.com/nipy/nipype/issues/2982#issue-475717026) results in a chart like this:
[![profiler.log.html](https://user-images.githubusercontent.com/5974438/104063554-59fe1700-51ca-11eb-954f-8818bd226de6.png)](https://github.com/nipy/nipype/files/5789337/profiler.log.html.zip)

In the PR's comments, [the issue of the large values in `runtime_threads` in the logfile](https://github.com/nipy/nipype/pull/3290#issuecomment-756994047) is noted.
