### ISSUE TITLE
Multiple output files at datasink

### ISSUE THREAD

**Issue by pkashya** [nipy/nipype#2986]
Hey,

I'm wrapping the FAST-FSL segmentation using nipype.
Is there a way to siphon multiple outputs to different output folders at the datasink node?
I'm trying to separate the WM, CSF, GM segmentations generated from the 'tissue_class_files' into different folders to reference them later in the pipeline.

Please help.

Thanks,
Pratik

**Comment by satra** [comment]
@pkashya - you can use a split node, a function node, or possibly regex options in datasink

**Comment by pkashya** [comment]
Thanks!
I'm using a function node.
