### ISSUE TITLE
Propose removing "versioning" argument from loadpkl

### ISSUE THREAD

**Issue by stilley2** [nipy/nipype#3018]
The "versioning" argument to loadpkl no longer serves much purpose. I propose it be deleted. Thoughts?

https://github.com/nipy/nipype/blob/508df5e0531fb691b8b052e81a3bc03d1300d594/nipype/utils/filemanip.py#L678

**Comment by effigies** [comment]
cc @anibalsolon, as this was added in #2626.

**Comment by anibalsolon** [comment]
Hi @stilley2 ! I am actually not aware of why it isn't required anymore. But if it is not, I am always happy with cutting off code.

**Comment by stilley2** [comment]
Hi @anibalsolon , if my reading of the code is correct, the only thing it changes now is error reporting. loadpkl tries to read the version information regardless of if this flag is set, and if that fails it assumes it doesn't exist.

**Comment by anibalsolon** [comment]
Yes @stilley2 so it can be removed indeed!
