### ISSUE TITLE
etelemetry not available in conda-forge

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#3039]
@satra @mgxd The etelemetry dependency makes conda packaging difficult, since we can't depend on things that are not in conda-forge. I can wrap `import etelemetry` in a `try`/`except` block, but it means that conda-installed packages will more often than not just skip the version check.

The two easiest approaches I see:

1) Package up etelemetry-client
2) Include etelemetry-client in `nipype.external` for now

Also, @mgxd, you'll probably want to look into conda-forge's build environment variables. It builds and tests packages inside Docker on Azure.

**Comment by effigies** [comment]
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=73471

Related: conda-forge/nipype-feedstock#51

**Comment by satra** [comment]
creating a recipe.

**Comment by satra** [comment]
created: https://github.com/conda-forge/staged-recipes/pull/9599

@mgxd - i need your sign off there as maintainer

**Comment by mgxd** [comment]
this should be all set now that [conda-forge/etelemetry-feedstock](https://github.com/conda-forge/etelemetry-feedstock) is up
