### ISSUE TITLE
How to use RobustFOV function in nipype.interfaces.fsl

### ISSUE THREAD

**Issue by leonardo-oz** [nipy/nipype#3051]
HI, All. I am trying to remove neck from an MRI sample image using nipype.interfaces.fsl. 

The function I used is as following:

````
    neckRM = fsl.RobustFOV()
    print(help(neckRM))
    neckRM.inputs.in_file = inPath
````
I could not find a way to save the neck removed image or make a reference to it. Can someone shed a light on this?

Thanks.

**Comment by effigies** [comment]
Hi @leonardo-oz, could you provide your whole script? There doesn't seem to be anything wrong with what you've shown. If you would like to save the output to a specific location, you can probably add:

```Python
neckRM = fsl.RobustFOV(in_file=inPath, out_roi=outPath)
res = neckRM.run()
print(res.outputs.out_roi)
```

**Comment by leonardo-oz** [comment]
@effigies , Thanks for the reply. I think I did not known to add outPath as value of out_roi.  Does res.outputs.out_roi here is another image object reference and I can do nib.save(res.outputs.out_ro, outPath2) or I have to load the neck removed image from outPath again?

**Comment by effigies** [comment]
Whether you specify `out_roi` or not, `res.outputs.out_roi` will be a filename. If you specify it, it should be the same filename as the input.

I don't think any nipype interfaces return nibabel images as outputs.

**Comment by leonardo-oz** [comment]
@effigies , got it, thanks!
