### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by yaowang1111** [nipy/nipype#3082]
When i set the mean_vol of FSL MCFLIRT to TRUE, the program reports following:
traits.trait_errors.TraitError: The trait 'mean_img' of a MCFLIRTOutputSpec instance is an existing file name, but the path  '/gpfs/share/home/1801110663/project/alexithymia/icaFIX/work_preproc/_subject_id_L100/mcflirt/006_merged_mcf.nii.gz_mean_reg.nii.gz' does not exist.

However there is a file named '/gpfs/share/home/1801110663/project/alexithymia/icaFIX/work_preproc/_subject_id_L100/mcflirt/006_merged_mcf_mean_reg.nii.gz'

I guess there is something wrong with the naming system in this part.

**Comment by effigies** [comment]
Duplicate of #2925. This should be fixed in nipype 1.2.3. However, there are some other issues with that release, so I would recommend upgrading to `>=1.3.0rc1`.

**Comment by yaowang1111** [comment]
Solved my problem,Thanks
