### ISSUE TITLE
poll_sleep_duration for specific nodes?

### ISSUE THREAD

**Issue by dPys** [nipy/nipype#3104]
Is it currently possible to regulate poll_sleep_duration for specific workflow nodes? If so, how? if not, why not?

@dPys

**Comment by effigies** [comment]
`poll_sleep_duration` is for the master loop that looks to see whether any new nodes can be run. It doesn't really make sense from a per-node context.

**Comment by satra** [comment]
however, if you choose to you can always set any config options at the node level. every node has a config object/attribute.

**Comment by effigies** [comment]
... But I don't think that config option gets read on a per-node basis by any execution plugin. I suppose you could write a new plugin that did.

**Comment by satra** [comment]
> But I don't think that config option gets read on a per-node basis by any execution plugin

that is true. and `poll_sleep_duration` is a global thing at present.

**Comment by dPys** [comment]
Bummer, because I think it would be a cool feature.

> `poll_sleep_duration` is for the master loop that looks to see whether any new nodes can be run. It doesn't really make sense from a per-node context.

To clarify-- I'm talking about a mechanism that allows the master loop to dynamically wait to check whether new nodes can be run, depending on what nodes specifically are being checked. 

...for instance, assume I have a workflow consisting of nodes A, B, C, and D. Also assume that C is a MapNode and B is more memory-intensive than the others such that it requires a relatively longer poll_sleep_duration to avoid crashing at very high levels of parallelism (without this, MapNode C can overwhelm the scheduler without sufficient refresh time to avoid submitting more B-jobs). With a a globally higher poll_sleep_duration, the workflow runs without issue, but it will finish more slowly. It is not efficient because the sleeping is only needed to manage B-jobs (i.e. and not A-jobs or C-jobs). 

Interesting that every node has a config attribute, but it sounds like modifying the poll_sleep_duration at that resolution wouldn't impact what happens globally? Has this been tested with MultiProc before?

**Comment by effigies** [comment]
Your use case still isn't very clear to me. If you're using poll sleep to manage resources, I think you've picked a large hammer for your needlework.

**Comment by dPys** [comment]
![graph](https://user-images.githubusercontent.com/16432683/69393865-f94b0c80-0c9f-11ea-8bbf-65977d1fdc81.png)
If there's a better solution, I'm all ears. Basically the goal is to avoid clobbering across nested workflows (the above workflow is a single DAG for processing 7 scan runs for the same subject in parallel). Without a sufficiently long poll_sleep_duration for the scheduler to refresh, MultiProc will begin to do whacky things. If the refresh rate (i.e. poll_sleep_duration) is too low, when the scheduler fills up the queue with many fast, low-memory jobs (e.g. thr_info_node, 1 GB), it fails to register the server's true load and can mistakenly start submitting high-memory jobs (e.g. extract_ts_node, 8 GB) from a different run, despite the server not being ready to do so. In other words, under conditions of very high parallelism where iterables are being coordinated across multiple nested workflows, MultiProc needs much longer refresh rates to avoid clobbering.

Please let me know if what I'm saying still doesn't make sense.

**Comment by effigies** [comment]
So you have N cores, and you start N 1GB jobs. If you don't wait 45 seconds, those jobs, having finished in <2s will still hold onto N GB of memory, and then large jobs will be started.

This sounds like a more fundamental failure than individualized minimum durations, which seems like a difficult hack to manage. You could probably use a modified interface, like:

```Python
class SleepingInterface(BaseInterface):
    def __init__(self, interface, sleep_time=0.):
        self._interface = interface
        self._sleep_time = sleep_time
        # You'll probably need to hack this up a bit more
        self.inputs = self._interface.inputs

    def _run_interface(self, runtime):
        t = time.time()
        runtime = self._interface.run_interface(runtime)
        # Give subprocess a chance to clean up
        sleep(t + self._sleep_time - time.time())
        return runtime

    def _list_outputs(self):
        return self._interface._list_outputs()
```

So you'd call it:

```Python
node = Node(SleepingInterface(RealInterface(), sleep_time=45), name='node')
```

You could also try writing a new execution plugin, but it would be substantially more complicated than one with a master thread that polls at a constant interval.

**Comment by dPys** [comment]
> So you have N cores, and you start N 1GB jobs. If you don't wait 45 seconds, those jobs, having finished in <2s will still hold onto N GB of memory, and then large jobs will be started.
> 
> This sounds like a more fundamental failure than individualized minimum durations, which seems like a difficult hack to manage. You could probably use a modified interface, like:
> 
> ```python
> class SleepingInterface(BaseInterface):
>     def __init__(self, interface, sleep_time=0.):
>         self._interface = interface
>         self._sleep_time = sleep_time
>         # You'll probably need to hack this up a bit more
>         self.inputs = self._interface.inputs
> 
>     def _run_interface(self, runtime):
>         t = time.time()
>         runtime = self._interface.run_interface(runtime)
>         # Give subprocess a chance to clean up
>         sleep(t + self._sleep_time - time.time())
>         return runtime
> 
>     def _list_outputs(self):
>         return self._interface._list_outputs()
> ```
> 
> So you'd call it:
> 
> ```python
> node = Node(SleepingInterface(RealInterface(), sleep_time=45), name='node')
> ```
> 
> You could also try writing a new execution plugin, but it would be substantially more complicated than one with a master thread that polls at a constant interval.

I ❤️the SleepingInterface and will give this approach a try to see if I can avoid a new execution plugin. Thanks @effigies !

**Comment by dPys** [comment]
So after further testing, the sleeping interface will suffice as a band-aid fix. In the long-term, however, a new execution plugin will be needed. The minimal node-level poll sleep_time needed varies depending on the degree of parallelism, the topology of the DAG, and the available resources on the server. As soon as I finish my dissertation and/or find a source of funding, I'll try my best to build it. Flow network optimization will solve this.

**Comment by dPys** [comment]
@effigies -- You were right from the get-go on this. I was trying to use a large hammer for my needlework. This issue was better addressed through more fine-grained I/O handling at the interface-level. AsyncIO would probably be a further improvement, but for now I think this issue can be closed.

Cheers,
@dPys
