### ISSUE TITLE
DataSink S3 support does not work

### ISSUE THREAD

**Issue by AKSoo** [nipy/nipype#3105]
### Summary
The DataSink interface does not work.

### Actual behavior
Only the local copy works. Oddly, when used in a workflow, DataSink creates a local directory named `s3:/` instead.

### Expected behavior
DataSink creates objects in S3 buckets when base_directory starts with `s3://`.

### How to replicate the behavior
```
ds = DataSink()

ds.inputs.base_directory = 's3://kimsin-test'
ds.inputs.creds_path = os.path.abspath('aws.csv')
ds.inputs.encrypt_bucket_keys = True
ds.inputs.local_copy = os.path.abspath('log')
setattr(ds.inputs, 'out_s3', 'DELETE.me')

ds.run()
```
This basic S3 test code does not create the desired output in the S3 bucket.

### Platform details:
```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.4',
 'nibabel_version': '2.5.1',
 'nipype_version': '1.3.0-rc1',
 'numpy_version': '1.17.3',
 'pkg_path': '/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.3.1',
 'sys_executable': '/opt/miniconda-latest/envs/neuro/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.7 | packaged by conda-forge | (default, Jul  2 2019, '
                '02:18:42) \n'
                '[GCC 7.3.0]',
 'traits_version': '5.1.2'}
```

### Execution environment
- My python environment inside container

**Comment by effigies** [comment]
For things like this, I'll often debug as follows:

```Python
>>> from nipype.interfaces.io import *
>>> ds = DataSink()
>>> ds.inputs.base_directory = 's3://kimsin-test'
>>> ds.inputs.creds_path = os.path.abspath('aws.csv')
>>> ds.inputs.encrypt_bucket_keys = True
>>> ds.inputs.local_copy = os.path.abspath('log')
>>> ds.inputs.out_s3 = 'DELETE.me'
>>> self = ds
```

Then just manually walk through the `_list_outputs` method to see where things break down.

https://github.com/nipy/nipype/blob/1a869991adc024577536689d557fc748c764f15d/nipype/interfaces/io.py#L944-L1067

I'm sure there's a way to do this in pdb that will save you typing/pasting, if you prefer...

**Comment by wtriplett** [comment]
Hi,

this may be related to the use of `traits.Directory` in the input spec, as opposed to `Str`. Maybe `traits.Directory` is stripping out the double `/` in the S3 url.

**Comment by AKSoo** [comment]
Good find!

I suppose the simplest fix would be changing `DataSink._check_s3_base_dir` to accommodate this quirk. The other option of editing `traits.Directory` has too much potential to affect other interfaces.

I will submit a quick PR after testing.

**Comment by oesteban** [comment]
I think `base_directory` should not be a `traits.Directory`. Why not just changing it to `traits.Str`?

**Comment by AKSoo** [comment]
@oesteban I am not quite sure about all the implications, but doing so would skip whatever cleanup `pathlib.Path` does on DataSink base_directory. This notably includes various backslash shenanigans.

For now, I will leave the discussion on what format DataSink expects as inputs up to others.
