### ISSUE TITLE
Stop using NUMPY_MMAP constant

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#3112]
### Summary

This is now always `True`:

https://github.com/nipy/nipype/blob/388f140fceaf55438a987e9cdfa2a8e995428afd/nipype/utils/config.py#L31

https://github.com/nipy/nipype/blob/388f140fceaf55438a987e9cdfa2a8e995428afd/nipype/info.py#L104

All of its uses can now be removed.

**Comment by steve19922** [comment]
Hi, I would like to contribute on this one.

**Comment by effigies** [comment]
Great! Please let us know if you need any help getting started.

**Comment by effigies** [comment]
Closed in #3121.
