### ISSUE TITLE
Keyword argument to .splitlines() not supported in py 2.7

### ISSUE THREAD

**Issue by wtriplett** [nipy/nipype#3113]
https://github.com/nipy/nipype/blob/388f140fceaf55438a987e9cdfa2a8e995428afd/nipype/pipeline/plugins/tools.py#L32-L45

Removing the explicit keyword reference should produce the expected behavior on both py2 and 3.

**Comment by satra** [comment]
@wtriplett - if you are looking at current master, all development in master is continuing only using python 3 as of the last release. any changes in relation to support python 2 should be made to the 1.3.x release branch (the last release that is py2 compatible).

@effigies - we should update the README to reflect this clearly, and may be even our "latest" docs.

**Comment by wtriplett** [comment]
@satra: Got it, sorry about that. I will rework the PR.
