### ISSUE TITLE
fsl CopyGeom does not change the destination file when caching

### ISSUE THREAD

**Issue by salma1601** [nipy/nipype#3136]
### Summary
The geometry is not copied into the given destination file
### Actual behavior
The geometry is not copied into the given destination file but into a file with the same basename located inside the cached folder in `nipype_mem/nipype-interfaces-fsl-utils-CopyGeom/` when caching
### Expected behavior
Geometry of `"/tmp/reference.nii.gz"` should be copied into `"/tmp/anat.nii.gz"` 

### How to replicate the behavior
```Python
from nipype.caching import Memory
from nipype.interfaces import afni, ants, fsl

memory = Memory('/tmp')
copy_geom = memory.cache(fsl.CopyGeom)
out_copy_geom = copy_geom(dest_file="/tmp/anat.nii.gz", in_file="/tmp/reference.nii.gz")
```
does not change the file `"/tmp/anat.nii.gz"`

### Platform details:

```Shell
200103-23:58:17,498 nipype.utils INFO:
	 Running nipype version 1.5.0-dev+g71ab10b80 (latest: 1.4.0)
{'commit_hash': '71ab10b80',
 'commit_source': 'repository',
 'networkx_version': '2.4',
 'nibabel_version': '3.0.0',
 'nipype_version': '1.5.0-dev+g71ab10b80',
 'numpy_version': '1.17.4',
 'pkg_path': '/home/salma/CODE/nipype/nipype',
 'scipy_version': '1.3.2',
 'sys_executable': '/home/salma/miniconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]',
 'traits_version': '5.2.0'}

```

### Execution environment
- My python environment outside container

**Comment by satra** [comment]
this "bug" is consistent with nipype dataflow behavior. when used in a Node/caching mode, the destination file is copied over and changed. see discussion in #3137
