### ISSUE TITLE
dcmstack interface; problem with file suffixes 

### ISSUE THREAD

**Issue by ch-n** [nipy/nipype#3151]
### Summary
I try to use the dcmstack interface to work with Siemens raw DICOM files. These files are in the *.IMA format. I used dcmstack as standalone and it worked fine on these files. The nipype dcmstack interface in contrast does not recognize these files.

### Cause of Issue
The file suffix is hard coded as .dcm despite dcmstack is capable of reading other DICOM suffixes.

### Question
Why is the file suffix hard coded to .dcm? Is there a specific reason why other suffixes are not valid?

### Solution?
Quick and dirty: I simply changed the hard coding in the script.
Is there an other better solution for my problem?

Greetings
Chris

**Comment by satra** [comment]
the input `dicom_files` accepts several options: https://github.com/nipy/nipype/blob/master/nipype/interfaces/dcmstack.py#L96

you can also do: `stacker.inputs.dicom_files = 'path/to/series/*'` it accepts any `glob`  string.  or you can get the list of files yourself and provide that to the input.

**Comment by ch-n** [comment]
Thanks for the quick reply. I already use the second of your suggestions as of now. By providing a glob generated list everything works fine for me. The other solution still does not work.
