### ISSUE TITLE
No module named 'nipype.sphinxext.apidoc'

### ISSUE THREAD

**Issue by liamtimms** [nipy/nipype#3161]
### Summary
I've been keeping up with the last few nipype releases without issue and appreciate the revamping of the docs that seems to have happened on the website. However, I am running into an issue building nipype since this update to the docs.

### Actual behavior
Attempting to build nipype **1.4.1** results in the error:

```
Could not import extension nipype.sphinxext.apidoc (exception: No module named 'nipype.sphinxext.apidoc')
```

I installed sphinxcontrib-apidoc as I saw it was added as a new dependency under /doc/requirements.txt but this doesn't seem to resolve the error. I can call `sphinx-apidoc` as a function directly from the shell so it seems that it is installed correctly. 

### Expected behavior

To be able to build nipype in the same way I did for 1.4.0

### Platform details:

```
200202-18:54:53,386 nipype.utils INFO:
	 Running nipype version 1.4.0 (latest: 1.4.1)
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.4',
 'nibabel_version': '3.0.1',
 'nipype_version': '1.4.0',
 'numpy_version': '1.18.0',
 'pkg_path': '/usr/lib/python3.8/site-packages/nipype',
 'scipy_version': '1.4.1',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.8.1 (default, Jan 22 2020, 06:38:00) \n[GCC 9.2.0]',
 'traits_version': '5.2.0'}
```

**Comment by oesteban** [comment]
Can you elaborate more on the steps you are taking to build nipype?

**Comment by liamtimms** [comment]
Hi @oesteban thanks, sorry I didn't elaborate initially: I have been packaging nipype for Arch Linux. 

For context: I find this useful as it allows me to install nipype with many of the neuroimaging suites and nipy projects as dependencies. I can then have the latest versions of the relevant software with the whole installation managed by the system package manager and share the work with the (small) neuroimaging community on that distro. I have found this to be simpler to use and update than installing packages with a mix of `pip`, `conda install`, neurodebian `apt`, `make install`, etc. though those may be used under the hood. 

I was not the initial contributor of this package but took over maintenance a little while ago. The build process which I inherited used the following functions:

```
_setpaths(){

    # Try to auto-detect the matlab install directory
    if [ -z "${_MATLAB_DIR}" ]; then
      if [ -d "/opt/matlab" ]; then
        MATLABCMD=$(find /opt/matlab/R*/bin -mindepth 2 -maxdepth 2 -name MATLAB | sort | tail -n 1 )
      fi
    else
      MATLABCMD=$(find "${_MATLAB_DIR}"/bin -mindepth 2 -maxdepth 2 -name MATLAB | sort | tail -n 1 )
    fi
    if [ -z "${_SPM_DIR}" ]; then
      if [ -e "/opt/spm12" ]; then
        _SPM_DIR="/opt/spm12"
      fi
    fi
    if [ ! -z "${_SPM_DIR}" ]; then
      export MATLABCMD="${MATLABCMD} -sd ${_SPM_DIR}"
    else
      export MATLABCMD
    fi

}

build() {

    cd ${srcdir}/${_name}-${pkgver}

    _setpaths
    echo "MATLABCMD: ${MATLABCMD}"
    make

}


package() {

    cd $srcdir/${_name}-${pkgver}
    python setup.py install --root="${pkgdir}/" --optimize=1

}
```
It is on the `make` step that this failure in building the docs seems to occur. 

I just tested an alternate approach replacing `make` with `python setup.py build` and in this case it seems to build correctly but I'm assuming this is skipping the creation of the docs? 

Any suggestion or feedback is appreciated but this is a low priority issue as 1.4.0 is working fine for me and I recognize that this is not an officially supported installation method.

**Comment by oesteban** [comment]
> it seems to build correctly but I'm assuming this is skipping the creation of the docs?

Yes - would it make any sense to separate the docs out of the package? (and maybe have a nipype-doc, for those who want to also install the documentation).

**Comment by liamtimms** [comment]
Yes, if that's the only real effect of this change I think it's fine. Thanks!
