### ISSUE TITLE
interfaces.ants.segmentation does not have options for PriorLabelImage arguments

### ISSUE THREAD

**Issue by eilidhmacnicol** [nipy/nipype#3178]
Summary: PriorLabelImage argument for Atroposis accepted as an initialization, but there is no option for PriorLabelImage declaration and prior weighting isn't included in the command. So:
command-line argument currently reads `--initialization PriorLabelImage[k]`
instead of: `--initialization PriorLabelImage[k, priorlabelimage.nii, weighting]`

**Comment by effigies** [comment]
What are the types of the inputs? Looks like the second is a file, and I assume weighting is a float (does it have a limited range?). Is `k` an integer?

**Comment by eilidhmacnicol** [comment]
That's it exactly: k is the number of segments to be produced, so an integer, then a discrete segmentation image to use as a prior, and a weighting score for the prior (relative to the input image) between 0 and 1.
