### ISSUE TITLE
AttributeError: module 'nipype.pipeline.plugins' has no attribute 'MultiprocPlugin'

### ISSUE THREAD

**Issue by JamesSexton11** [nipy/nipype#3183]
### Summary
Currently working in PyCharm to run a preprocessing pipeline on resting state data. Running nipype workflows with plugins such as 'Linear' (or no specified plugins at all) works, however I am scaling up my preproc workflow to take advantage of the multi-core computer. I was previously seeing the multiproc workflow haulting in the middle of processing and in attempt to fix it I removed nipype from my virtual environment and reinstalled it. However now I recieve the following error when I run the following.

### Actual behavior

fproc.run('Multiproc')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/James/nipype/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 616, in run
    plugin_mod = getattr(sys.modules[name], "%sPlugin" % plugin)
AttributeError: module 'nipype.pipeline.plugins' has no attribute 'MultiprocPlugin'

### Expected behavior

I expect this to run normally and give me the output of a basic ExtractRoi workflow that iterates over 10 files.

### How to replicate the behavior

import nipype 
from nipype import Workflow

a = Workflow(name = 'a')

a.run('Multiproc')

### Script/Workflow details

from os.path import join as opj
from nipype.interfaces.fsl import ExtractROI
experiment_dir = '/Users/James/Desktop/exp'
output_dir = 'datasink'
working_dir = 'workingdir'

#####list of subject identifiers
subject_list = ['01', '02', '03', '04', '05']

###### list of session identifiers
ses_list = ['1', '2']

############### Functional_Procedure ##################################

fproc = Workflow(name='fproc')
fproc.base_dir = '/Users/James/Desktop/fproc'

#########ExtractROI - skip dummy scans
trim = Node(ExtractROI(t_min=3,
                       t_size=476,
                       output_type='NIFTI_GZ'),
               name="trim")
infosource = Node(IdentityInterface(fields=['subject_id', 'ses']),
                  name="infosource")
infosource.iterables = [('subject_id', subject_list),
                        ('ses', ses_list)]

######### SelectFiles - to grab the data (alternative to DataGrabber)
func_file = opj('sub-ID{subject_id}', 'ses-{ses}', 'func', 'sub-ID{subject_id}_ses-{ses}*.nii.gz')

templates = {'func': func_file}
selectfiles = Node(SelectFiles(templates,
                               base_directory='/Users/James/BIDS/'),
                   name="selectfiles")

######### Datasink - creates output folder for important outputs
datasink = Node(DataSink(base_directory=experiment_dir,
                         container=output_dir),
                name="datasink")

fproc.connect([(infosource, selectfiles, [('subject_id', 'subject_id'),
                                            ('ses', 'ses')])])

fproc.connect([(selectfiles, trim, [('func', 'in_file')])])

fproc.run('Multiproc')

### Platform details:

```
200306-12:46:55,663 nipype.utils INFO:
         No new version available.
{'commit_hash': 'c5ce0e2c9',
 'commit_source': 'installation',
 'networkx_version': '2.4',
 'nibabel_version': '3.0.1',
 'nipype_version': '1.4.2',
 'numpy_version': '1.18.1',
 'pkg_path': '/Users/James/nipype/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.4.1',
 'sys_executable': '/usr/local/opt/python/bin/python3.7',
 'sys_platform': 'darwin',
 'sys_version': '3.7.6 (default, Dec 30 2019, 19:38:26) \n'
                '[Clang 11.0.0 (clang-1100.0.33.16)]',
 'traits_version': '6.0.0'}

```

**Comment by effigies** [comment]
The P is capitalized.

**Comment by JamesSexton11** [comment]
> The P is capitalized.

I am both embarassed and grateful.
