### ISSUE TITLE
Installation failure python 3.7 

### ISSUE THREAD

**Issue by garciadias** [nipy/nipype#3187]
### Summary

Installation error

### Actual behavior

...
  ERROR: Failed building wheel for traits
  Running setup.py clean for traits
Failed to build traits
Installing collected packages: pyparsing, pydot, traits, numpy, nibabel, decorator, networkx, six, isodate, rdflib, lxml, python-dateutil, prov, neurdflib, idna, certifi, chardet, urllib3, requests, etelemetry, packaging, click, scipy, simplejson, pydotplus, filelock, nipype
    Running setup.py install for traits ... error
    ERROR: Command errored out with exit status 1:
     command: /home/kcl_2/test/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ulb4vuax/traits/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ulb4vuax/traits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s158xwz1/install-record.txt --single-version-externally-managed --compile --install-headers /home/kcl_2/test/include/site/python3.7/traits
         cwd: /tmp/pip-install-ulb4vuax/traits/
    Complete output (193 lines):
    Reading version file /tmp/pip-install-ulb4vuax/traits/traits/version.py
    Package version from version file: ('6.0.0', '9349ab9c55f7831b7c8e636d66d8a145b64f6070')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/traits
    copying traits/trait_dict_object.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/base_trait_handler.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_handlers.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_handler.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/constants.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/editor_factories.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/interface_checker.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_types.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/api.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/ctrait.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_numeric.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/traits.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_set_object.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/version.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_converters.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/__init__.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/has_traits.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_base.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_errors.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/traits_listener.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_factory.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_type.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_list_object.py -> build/lib.linux-x86_64-3.7/traits
    copying traits/trait_notifiers.py -> build/lib.linux-x86_64-3.7/traits
    creating build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/api.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/adapter.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/adaptation_error.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/__init__.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/adaptation_offer.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    copying traits/adaptation/adaptation_manager.py -> build/lib.linux-x86_64-3.7/traits/adaptation
    creating build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_has_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_event_order.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_dynamic_trait_definition.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_ctraits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_new_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_automatic_adaptation.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_callable.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_copyable_trait_names.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_get_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/check_timing.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_sync_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_clone.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_interfaces.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_anytrait_static_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_version.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_directory.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_integer.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_weak_ref.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_historical_unpickling.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_ui_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_target.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_configure_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_constants.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_view_elements.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_uuid.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_types.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_pickle_validated_dict.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_regression.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/tuple_test_mixin.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_dict.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_long_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_prefix_list.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_static_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_dynamic_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_base.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_deprecated_handlers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_class_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_container_events.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_rich_compare.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_array_or_none.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_str_handler.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_converters.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_undefined.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_type.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_list_events.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_exceptions.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_cythonized_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_list_dict.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_enum.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_change_event_tracer.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_validated_tuple.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_keyword_args.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_bool.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_tuple.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_copy_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/__init__.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_abc.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_default_initializer.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_float_range.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_list.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_string.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_unicode_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_special_event_handlers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_range.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_delegate.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_float.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_property_notifications.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_listeners.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_editor_factories.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_property_delete.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_extended_trait_change.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_integer_range.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_file.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_extended_notifiers.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_has_required_traits.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_array.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_cycle.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_trait_get_set.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_interface_checker.py -> build/lib.linux-x86_64-3.7/traits/tests
    copying traits/tests/test_int_range_long.py -> build/lib.linux-x86_64-3.7/traits/tests
    creating build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/api.py -> build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/optional_dependencies.py -> build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/nose_tools.py -> build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/__init__.py -> build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/doctest_tools.py -> build/lib.linux-x86_64-3.7/traits/testing
    copying traits/testing/unittest_tools.py -> build/lib.linux-x86_64-3.7/traits/testing
    creating build/lib.linux-x86_64-3.7/traits/etsconfig
    copying traits/etsconfig/etsconfig.py -> build/lib.linux-x86_64-3.7/traits/etsconfig
    copying traits/etsconfig/api.py -> build/lib.linux-x86_64-3.7/traits/etsconfig
    copying traits/etsconfig/__init__.py -> build/lib.linux-x86_64-3.7/traits/etsconfig
    creating build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/trait_documenter.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/import_symbol.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/home_directory.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/async_trait_wait.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/camel_case.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/event_tracer.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/api.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/clean_strings.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/deprecated.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/__init__.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/toposort.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/resource.py -> build/lib.linux-x86_64-3.7/traits/util
    copying traits/util/weakiddict.py -> build/lib.linux-x86_64-3.7/traits/util
    creating build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/test_adaptation_manager.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/test_global_adaptation_manager.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/abc_examples.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/benchmark.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/test_adaptation_offer.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/__init__.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/lazy_examples.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/test_adapter.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    copying traits/adaptation/tests/interface_examples.py -> build/lib.linux-x86_64-3.7/traits/adaptation/tests
    creating build/lib.linux-x86_64-3.7/traits/testing/tests
    copying traits/testing/tests/test_optional_dependencies.py -> build/lib.linux-x86_64-3.7/traits/testing/tests
    copying traits/testing/tests/test_unittest_tools.py -> build/lib.linux-x86_64-3.7/traits/testing/tests
    copying traits/testing/tests/__init__.py -> build/lib.linux-x86_64-3.7/traits/testing/tests
    creating build/lib.linux-x86_64-3.7/traits/etsconfig/tests
    copying traits/etsconfig/tests/test_etsconfig.py -> build/lib.linux-x86_64-3.7/traits/etsconfig/tests
    copying traits/etsconfig/tests/__init__.py -> build/lib.linux-x86_64-3.7/traits/etsconfig/tests
    creating build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_deprecated.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_import_symbol.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_clean_strings.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_trait_documenter.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_record_containers.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/__init__.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_async_trait_wait.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_camel_case.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_record_events.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_message_records.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    copying traits/util/tests/test_weakidddict.py -> build/lib.linux-x86_64-3.7/traits/util/tests
    creating build/lib.linux-x86_64-3.7/traits/tests/test-data
    creating build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/README -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p0-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p4-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p5-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p3-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p2-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/hipt-t5.2.0-p1-float-ctrait.pkl -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    copying traits/tests/test-data/historical-pickles/generate_pickles.py -> build/lib.linux-x86_64-3.7/traits/tests/test-data/historical-pickles
    running build_ext
    building 'traits.ctraits' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/traits
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/kcl_2/test/include/python3.7m -c traits/ctraits.c -o build/temp.linux-x86_64-3.7/traits/ctraits.o
    traits/ctraits.c:15:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/kcl_2/test/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ulb4vuax/traits/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ulb4vuax/traits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s158xwz1/install-record.txt --single-version-externally-managed --compile --install-headers /home/kcl_2/test/include/site/python3.7/traits Check the logs for full command output.
### Expected behavior
Installation completed sucessfuly
### How to replicate the behavior
pip install nipype
### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:
Ubuntu 16.04, clean virtual environment.
Tried multiple versions, none of them work.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nipype'
```

### Execution environment
Clean enviroment.

### Solution
The problem is that the trails package will not be installed unless you install python3.7-dev.
apt-get install python3.7-dev

**Comment by effigies** [comment]
`traits` installation issues aren't within Nipype's purview. I'm glad you found a solution. You can also try using `pip install --prefer-binary` to find the newest binary distributions that meet your constraints.
