### ISSUE TITLE
nipype.test() throws AssertionError when testing FSL

### ISSUE THREAD

**Issue by fazilii** [nipy/nipype#3189]
### Summary
I've installed nipype, and when i run the test  to verify the installation, it shows an error when testing FSL. I ran FSL independently, and it runs fine. 
I'm new to nipype. any assistance will be appreciated.  
### Actual behavior
_______________________________ test_fslversion ________________________________

    @pytest.mark.skipif(no_fsl(), reason="fsl is not installed")
    def test_fslversion():
        ver = fsl.Info.version()
        ver = ver.split('.')
>       assert ver[0] in ['4', '5']
E       AssertionError: assert '6' in ['4', '5']

/home/fazili/.local/lib/python2.7/site-packages/nipype/interfaces/fsl/tests/test_base.py:17: AssertionError

**Comment by effigies** [comment]
Fixed in #3195.
