### ISSUE TITLE
"Could not check for version updates" Error Message

### ISSUE THREAD

**Issue by pritomrajkhowa** [nipy/nipype#3191]
bmi@bmi-Workstation:~/preprocessing/nipype$ python3 -c "import nipype; print(nipype.__version__)"
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
https://rig.mit.edu/et/projects/nipy/nipype
200319-15:21:19,165 nipype.utils WARNING:
	 Could not check for version updates: 
No response from server in 5 seconds
1.4.2

Not able run code

**Comment by satra** [comment]
the server should be fixed for a bit. however, these are just warnings, not errors.
