### ISSUE TITLE
antslegacy module

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#3197]
I notice that in the newest version the `nipype.interfaces.ants.legacy` module is missing, and I cannot find a class for `antsIntroduction()` anywhere in the package.

I know that using antsIntroduction is probably not the best idea, in fact I need it for an article recommending against it for preclinical imaging, but I need it for the benchmark. Is ti not coming back, and should I thus depend on older nipype for the article source code?

**Comment by oesteban** [comment]
It seems to have been dropped here https://github.com/nipy/nipype/pull/2654/files#diff-a2e391882927e53f0bd8855c06af7009.

What's `antsIntroduction` for and, if its usage is not discouraged, maybe we should bring just that one back?

**Comment by TheChymera** [comment]
@oesteban it's a mini-workflow by the ANTs team which is useful if you don't want to use an external preprocessing pipeline. I actually try to convince people not to use it with preclinical data, but with human data it can be quite useful given the numerous good heuristic presets they figured out: https://github.com/ANTsX/ANTs/blob/master/Scripts/antsIntroduction.sh

**Comment by TheChymera** [comment]
@oesteban seeing as there's no action on this, can I just go ahead and bring it back? Will you pull?

**Comment by satra** [comment]
@TheChymera - i can't remember why it was in the legacy module in the first place. perhaps @hjmjohnson does.

if there is no good reason for it to have been discarded, we should bring it back in some standard location, not legacy.

**Comment by oesteban** [comment]
@TheChymera sure, I have no bandwidth to do it but I'd be happy to accept the PR. As Satra mentions, please do not restore the whole antslegacy module, just the interface you need somewhere more appropriate.
