### ISSUE TITLE
New Sphinx-3.0 breaks nipype-workflow's sphinx extension

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#3201]
I guess pinning sphinx<3.0 would be enough for now.

**Comment by mgxd** [comment]
We'd probably want to refactor
https://github.com/nipy/nipype/blob/47de76e6f66ce68940758b96eebc3a3b8af9bcb1/nipype/sphinxext/plot_workflow.py#L149
into a class.

https://het.as.utexas.edu/HET/Software/Sphinx/extdev/appapi.html#sphinx.application.Sphinx.add_directive

https://docutils.sourceforge.io/docs/howto/rst-directives.html#the-directive-class
