### ISSUE TITLE
FSL (+6.0) BET chokes with long filenames

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#3211]
Would adding the copyfile metadata just fix this, @satra?

I think I've seen this issue reported before, but I can't seem to find it. Feel free to link and close this if it is a duplicate

**Comment by satra** [comment]
is it a path length issue or a filename issue or a command path length issue? 

we could use `copyfile=False` and change the command to use a relative path. but that interface (one of our oldest), also returns absolute path for the output file name, which bet needs to run.

**Comment by oesteban** [comment]
> is it a path length issue or a filename issue or a command path length issue?

Not sure, it could definitely be that it doesn't like nipype's parameterized folders.

> we could use `copyfile=False` and change the command to use a relative path. but that interface (one of our oldest), also returns absolute path for the output file name, which bet needs to run.

The output file is the first thing I tried shortening, so you're probably right on this one too. Which means there's not an immediate fix for this, right?

**Comment by oesteban** [comment]
Okay, this also happens with the output:

```
terminate called after throwing an instance of 'NiftiIO::NiftiException'
  what():  Error: cant open file /home/oesteban/tmp/fmriprep-ds210/work/fmriprep_wf/single_subject_02_wf/func_preproc_task_cuedSGT_run_03_echo_1_wf/skullstrip_bold_wf/_bold_file_..oak..stanford..groups..russpold..data..openfmri..ds000210..sub-02..func..sub-02_task-cuedSGT_run-03_echo-3_bold/skullstrip_first_pass/vol0000_xform-00000_merged_brain.nii.gz
```

**Comment by satra** [comment]
is it possible that just this part `..oak..stanford..groups..russpold..data..openfmri..ds000210..sub-02..func..sub-02_task` is throwing things off?

**Comment by oesteban** [comment]
Doesn't seem so:

```
bet derivatives/smriprep-0.6/sub-02/anat/sub-02_desc-preproc_T1w.nii.gz _bold_file_..oak..stanford..groups..russpold..data..openfmri..ds000210..sub-02..func..sub-02_task-cuedSGT_run-03_echo-3_bold/skullstrip_first_pass//some.file.nii.gz
```

**Comment by satra** [comment]
so the easiest fix would be:
1. use `copyfile=False` to link locally
2. make the output filename be local (no absolute path) for generation, but not for list_outputs.

bet allows the user to send an output location, so that would have to remain as is.

**Comment by oesteban** [comment]
Yup, I imagined this was the solution.
