### ISSUE TITLE
Unable to find Camino commands

### ISSUE THREAD

**Issue by sergior2** [nipy/nipype#3227]
### Summary
Hello, I'm new to the nipype environment so apologies if this isn't the correct place to mention the error I've been receiving or if I'm not following proper procedure. However, I've been recently attempting to run a workflow on Linux utilizing camino functions Track() as well as Conmat(), but from what appears to be the case it can't find where the functions are located. I've tried appending to the $PATH environment variables where they can be located but to no success. I would appreciate any help or guidance as to what may be the cause of this. Thank you very much.
### Actual behavior
runfile('/home/usr/Documents/ConnectomicsPipelines/tractography_camino.py', wdir='/home/usr/Documents/ConnectomicsPipelines')
Reloaded modules: __mp_main__
200629-12:40:26,479 nipype.workflow INFO:
         Workflow Tractography settings: ['check', 'execution', 'logging', 'monitoring']
200629-12:40:26,486 nipype.workflow INFO:
         Running in parallel.
200629-12:40:26,490 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 113.01/113.01, Free processors: 56/56.
200629-12:40:27,14 nipype.workflow INFO:
         [Node] Setting-up "Tractography.selectfiles" in "/tmp/tmpbsfg1l5y/Tractography/selectfiles".
200629-12:40:27,26 nipype.workflow INFO:
         [Node] Running "selectfiles" ("nipype.interfaces.io.SelectFiles")
200629-12:40:27,34 nipype.workflow INFO:
         [Node] Finished "Tractography.selectfiles".
200629-12:40:28,494 nipype.workflow INFO:
         [Job 0] Completed (Tractography.selectfiles).
200629-12:40:28,501 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 113.01/113.01, Free processors: 56/56.
200629-12:40:28,594 nipype.workflow INFO:
         [Node] Setting-up "Tractography.trackNode" in "/tmp/tmpz9yb_by9/Tractography/trackNode".
200629-12:40:28,626 nipype.workflow INFO:
         [Node] Running "trackNode" ("nipype.interfaces.camino.dti.Track"), a CommandLine Interface with command:
track -inputfile /opt/test/output/dwi_analysis/preproc/sub_234/data.nii.gz -seedfile data_brain_mask.nii.gz -curvethresh 75.000000 -inputmodel bedpostx_dyad -stepsize 0.500000 -tracker euler -outputfile data_tracked
200629-12:40:28,632 nipype.workflow WARNING:
         Storing result file without outputs
200629-12:40:28,634 nipype.workflow WARNING:
         [Node] Error on "Tractography.trackNode" (/tmp/tmpz9yb_by9/Tractography/trackNode)
200629-12:40:30,496 nipype.workflow ERROR:
         Node trackNode failed to run on host Grievous.
200629-12:40:30,497 nipype.workflow ERROR:
         Saving crash info to /home/usr/Documents/ConnectomicsPipelines/crash-20200629-124030-usr-trackNode-75c33ae1-f62f-4243-813b-04d70e5fcdbb.pklz
Traceback (most recent call last):
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 569, in _run_interface
    return self._run_command(execute)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    runtime.hostname))
OSError: No command "track" found on host Grievous. Please check that the corresponding package is installed.

200629-12:40:30,503 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 113.01/113.01, Free processors: 56/56.
200629-12:40:32,494 nipype.workflow INFO:
         ***********************************
200629-12:40:32,496 nipype.workflow ERROR:
         could not run node: Tractography.trackNode
200629-12:40:32,497 nipype.workflow INFO:
         crashfile: /home/usr/Documents/ConnectomicsPipelines/crash-20200629-124030-usr-trackNode-75c33ae1-f62f-4243-813b-04d70e5fcdbb.pklz
200629-12:40:32,498 nipype.workflow INFO:
         ***********************************
Traceback (most recent call last):

  File "<ipython-input-2-68c0edf3b8b3>", line 1, in <module>
    runfile('/home/usr/Documents/ConnectomicsPipelines/tractography_camino.py', wdir='/home/usr/Documents/ConnectomicsPipelines')

  File "/home/usr/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/usr/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/usr/Documents/ConnectomicsPipelines/tractography_camino.py", line 73, in <module>
    tracto.run('MultiProc', plugin_args = {'num_procs': 10})

  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 599, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)

  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 190, in run
    report_nodes_not_run(notrun)

  File "/home/usr/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '

RuntimeError: Workflow did not execute cleanly. Check log for details
### Expected behavior
Unsure, as this is my first experience with nipype.
### How to replicate the behavior
Please see code below
### Script/Workflow details

import os
from nipype import Node, Workflow
from nipype.interfaces.io import SelectFiles, DataSink
import nipype.interfaces.camino as camino

experiment_dir = '/opt/test/output/dwi_analysis/preproc/sub_234/'
output_dir = 'tractography'
os.chdir("/opt/test/output/dwi_analysis/preproc/sub_234/")

templates = {'dwi': 'data.nii.gz'}

selectfiles = Node(SelectFiles(templates, base_directory = experiment_dir),
                   name = 'selectfiles')

datasink = Node(DataSink(base_directory = experiment_dir,
                         container = output_dir), 
                name = 'datasink')

trackNode = Node(camino.Track(inputmodel = 'bedpostx_dyad',
                              seed_file = 'data_brain_mask.nii.gz', 
                              curvethresh = 75, 
                              tracker = 'euler', 
                              stepsize = 0.5),
                 name = 'trackNode')

conmatNode = Node(camino.Conmat(target_file = '/home/michael/Connectomics/test1.nii.gz'), 
                  name = 'conmatNode')

tracto = Workflow('Tractography')

tracto.connect([(selectfiles, trackNode, [('dwi', 'in_file')]), 
                (trackNode, conmatNode, [('tracked', 'in_file')]),
                (conmatNode, datasink, [('conmat_ts', 'results')]),
                ])

tracto.run('MultiProc', plugin_args = {'num_procs': 10})

### Platform details:

```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.3',
 'nibabel_version': '2.5.1',
 'nipype_version': '1.3.0-rc1',
 'numpy_version': '1.17.2',
 'pkg_path': '/home/usr/anaconda3/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.3.1',
 'sys_executable': '/home/usr/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]',
 'traits_version': '5.1.2'}
```

### Execution environment

Choose one
- My python environment outside container: Python 3.7

**Comment by effigies** [comment]
Can you run `track` from your shell?

**Comment by sergior2** [comment]
Hello, sorry for the very late reply. I wasn't expecting a response so soon.
Yes I'm still able to run `track` from my shell as it still outputs a track object

E.g:
In[12]: camino.Track(in_file = 'data.nii.gz', inputmodel = 'bedpostx_dyad', seed_file = 'data_brain_mask.nii.gz')
Out[12]: <nipype.interfaces.camino.dti.Track at 0x7f822fc59250>

**Comment by effigies** [comment]
I mean in bash:

```
track --help
```

**Comment by sergior2** [comment]
Ahh sorry about that, unfortunately no it's still informing me that the command isn't found. I'm considering a full reinstall would hopefully solve the problem

> Command 'track' not found, did you mean:
> 
>   command 'tracd' from deb trac
>   command 'tack' from deb tack
> 
> Try: apt install <deb name>

**Comment by effigies** [comment]
It looks like you don't have Camino installed. Nipype does not include the tools that it wraps; it provides a common interface to them.

http://camino.cs.ucl.ac.uk/index.php?n=Main.Installation

**Comment by sergior2** [comment]
Thank you very much for the help, I'm using a shared computer and was informed that it had already been installed but it seems that is not the case.
