### ISSUE TITLE
workflow is rerun if whole working directory is moved to a different location

### ISSUE THREAD

**Issue by s2334** [nipy/nipype#3233]
I have finished processing using a custom workflow with nipype and now I'd like to move the entire workflow folder to a different location.

For example:

```
    subjects = ["001"]

    infosource = Node(IdentityInterface(fields=["sub"]), name="infosource")
    infosource.iterables = [("sub", subjects)]

    wf = Workflow(name="wf", base_dir="/data/")
    wf.config(dict(execution={"use_relative_paths": True})

    templates = {"func": "func.nii.gz"}
    select_files = Node(SelectFiles(templates), base_directory="/data/files/", name="select_files")

    gunzip = Node(Gunzip(), name="gunzip")

    wf.connect((infosource, select_files, [("sub", "sub")]),
                     (select_files, gunzip, [("func", "in_file")])])
    wf.run()
```

If I move the workflow from  `/data/wf` to `/newdata/wf` and rerun the code above only changing `wf = Workflow(name="wf", base_dir='/data/')` to `wf = Workflow(name="wf", base_dir='/newdata/')` I get the output `Outdated cache found for "wf.select_files"`.
and the whole workflow is run again.

I thought the point of `execution={"use_relative_paths":True}` was to avoid rerunning workflows when the working directory has been moved around.

Thanks for your help!

**Comment by satra** [comment]
@s2334 - this is only true if the computed hash remains the same. 

the default setting for this is based on timestamps which would require careful copying and dependent on whether the location is on the same or different filesystem

the non-default setting for hashing is content based (can take longer since it has to ready every byte of every input file). if you use this, then together with `use_relative_paths` it will preserve the cache.

**Comment by s2334** [comment]
Thanks @satra. Is there a way to find out what is causing the "Outdated Cache" warning? How can I see what has changed in the computed hash?

**Comment by satra** [comment]
you can use this config option `stop_on_first_rerun` for the execution: https://miykael.github.io/nipype_tutorial/notebooks/basic_execution_configuration.html#Execution

that should stop if something is rerun and show you the differences

**Comment by s2334** [comment]
Thanks @satra, I figured out the reason for the outdated cache.

A very minimal example:

 ```
   subjects = ["001"]
    path = "/data"
    infosource = Node(IdentityInterface(fields=["sub"]), name="infosource")
    infosource.iterables = [("sub", subjects)]

    wf = Workflow(name="wf", base_dir=path)
    wf.config(dict(execution={"use_relative_paths": True, "hash_method":"content"})

    def fun_path(sub, path):
	return path
    
    path_fun= Node(Function(function=fun_path, input_names=["sub","path"], output_names=["path"],  name="path_fun")
    path_fun.inputs.path = path
    wf.connect((infosource, select_files, [("sub", "sub")]))
    wf.run()
```

Let's say I run this code and then move the resulting workflow folder from `/data/wf` to `/newdata/wf`. 
If I change the line `path = "/data"` to `path = "/newdata"`, nipype will rerun the `path_fun` node because the variable `path` has been modified.

But this is not ideal, because none of the results really changed. Only the location of the files changed but none of the contents, but because of the path change my entire pipeline has to be rerun.
Do you have an idea what I can do to prevent this?

**Comment by satra** [comment]
ah, the issue is the use of a function node. these are not very helpful regarding types since nipype doesn't know whether path is a file or a string. thus it hashes it as if it were just another string.

you can use the simpleinterface to turn this into a true interface and there you can ensure that the type of path is properly set.

see: https://nipype.readthedocs.io/en/1.1.7/interfaces/generated/interfaces.base/core.html#simpleinterface

ps. this is improved in pydra, but it will be a while before all interfaces make their way to pydra - if you only have python functions, you can start switching right away though because you can decorate the function to say something is a File.

**Comment by s2334** [comment]
Thank you @satra. I tried using a `SimpleInterface `like you suggested:

```
subjects = ["001"]
path = "/data"
infosource = Node(IdentityInterface(fields=["sub"]), name="infosource")
infosource.iterables = [("sub", subjects)]

wf = Workflow(name="wf", base_dir=path)
wf.config(dict(execution={"use_relative_paths": True, "hash_method":"content"}))

def funpath(sub, path):
    return path

class myclassInputSpec(BaseInterfaceInputSpec):
    path=traits.Directory()
    sub=traits.Str()
class myclassOutputSpec(TraitedSpec):
    out=traits.Directory()
class myclass(SimpleInterface):
    input_spec=myclassInputSpec
    output_spec=myclassOutputSpec
    def _run_interface(self, runtime)
	self._results['out'] = funpath(path=self.inputs.path)
	return runtime

funclass=Node(myclass(),  name="funclass")
funclass.inputs.path = path

wf.connect([(infosource, funclass, [("sub", "sub")])])
wf.run()

```
now I have turned my function into `myclass`. However, I get an error when I run this:

`TypeError: funpath() missing 1 required positional argument 'sub'
`
It seems I need to include `sub` in the function call on line `self._results['out'] = funpath(path=self.inputs.path)`, but `sub` is supposed to be connected via `infosource` node. Is there a way to do that?

Thanks!

**Comment by effigies** [comment]
```Python
elf._results['out'] = funpath(sub=self.inputs.sub, path=self.inputs.path)

**Comment by s2334** [comment]
Thank you @effigies. I managed to get the code above to work, but it's still reporting Outdated Cache...
After moving the wf from the original (`/data`) to a new location (`/newdata`), I get the message (in DEBUG mode):
```
Some dictionary entries had differing values:
	* path: '/data' != '/newdata'
```
If you run the code above twice and change directories between runs, does it preserve the cache?

**Comment by satra** [comment]
@s2334 - directories are not hashed in nipype as it was considered an arbitrarily expensive process.

**Comment by s2334** [comment]
@satra - I see. Going back to my original question then, nipype will always rerun a pipeline like the above if the directory has changed between runs. So there isn't a solution to my problem other than not moving the workflow directory, is that correct?

**Comment by satra** [comment]
@s2334 - i think we are mixing two types of directories:

1. the working directory location or cache. if this is changed it will not rerun as long as content type hashing is used.

2. an input to a node that is a directory. if this directory changes, then any node that takes as input a directory will always rerun. it is simply treated as a string, hence any change in string will rerun the node.

**Comment by s2334** [comment]
Thank you @satra, I understand it now!
