### ISSUE TITLE
use string inside class to inform input

### ISSUE THREAD

**Issue by s2334** [nipy/nipype#3243]
Hello nipype experts!

I'm trying to create a command line class that takes a string which can then be used to inform the contents of an input. For example:
```
hello_str = "hello"
class myclassInputSpec(CommandLineInputSpec):
   hello_str = traits.Str()
   my_string=traits.Str(argstr="%s")
   sub=traits.Str(argstr="%s")
class myclassOutputSpec(TraitedSpec):
   outstr = traits.Str()
class myclass(CommandLine):
   input_spec = myclassInputSpec
   output_spec = myclassOutputSpec
   _cmd = "echo"
   def _run_interface(self, runtime):
       self.inputs.my_string = self.inputs.hello_str
       return runtime

C = myclass(sub="sub01",hello_str=hello_str)
C.run()
```

but this will not print anything... Can I somehow get `hello_str `to influence the input `my_string`? The command should be `echo hello`
I know the example is silly because I could just do `myclass.my_string=hello_str`, but it makes sense in my actual code.

I have played around with the class components but haven't found a solution to this problem yet. Maybe this type of operation isn't supported?

Thank you in advance!

**Comment by s2334** [comment]
Hello experts!
Could someone help me with this issue please? I still haven't managed to come up with a solution...
Thank you!

**Comment by satra** [comment]
you will also want to call the parent run_interface in the commandline class prior to returning runtime
return super()._run_interface(runtime)

but, one should never change inputs when running as this could mess up any hash computation. if you do need to set/process input values, the _format_arg method is what you may want to override.  and more generally, you typically don't want to channel input values between input fields.

**Comment by s2334** [comment]
Thank you very much @satra. I'm trying to use the `_format_arg` as you suggested but I could not find many examples in which it is used so I'm struggling to make it work.
Here is what I tried:

```
hello_str = "hello"
class myclassInputSpec(CommandLineInputSpec):
   hello_str = traits.Str()
   my_string=traits.Str(argstr="%s")
   sub=traits.Str(argstr="%s")

class myclassOutputSpec(TraitedSpec):
   outstr = traits.Str()

class myclass(CommandLine):
   input_spec = myclassInputSpec
   output_spec = myclassOutputSpec
   _cmd = "echo"

   def _format_arg(self, opt, spec, val):
       if opt in ["my_string"]:
          val = self.inputs.hello_str
       return super(myclass,self)._format_arg(opt,spec,val)

   def _run_interface(self, runtime):
       return super()._run_interface(runtime)

C = myclass(sub="sub01",hello_str=hello_str)
C.run()
```
However only `sub01 `is printed. I tried to play around with the code but with no success... Could you please let me know what is missing in my code example above? 
Thanks in advance!

**Comment by effigies** [comment]
@s2334 It could be I'm wrong, but this feels a bit like a toy problem, and I'm having trouble extrapolating it to a real use case that I can think through. I think it would be easier to discuss with your specific use case. What tool are you trying to wrap, and what exact behavior are you trying to model?

**Comment by s2334** [comment]
@effigies, my user case is a bit convoluted and would probably be an overkill to post it here, so I thought a simple reproducible example that clarifies my problem would be better. Basically the idea is that I'm trying to prevent my class instance to recompute every time a certain input changes.

Let's say I have timestamp as one of the inputs in my class "myclass" and I don't want to recompute the whole pipeline just because of the change in timestamp (as it doesn't affect any of the outputs). So I make the timestamp a variable in another class for example and pass this to myclass instance. This way the pipeline is not recomputed every time the timestamp changes.

I agree this might be unusual, but does it mean there is not a way to use _format_arg in my example problem to print "hello sub01"?
