### ISSUE TITLE
Pydotplus dependency

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#3244]
Is there a roadmap to deprecating the pydotplus depencency?

The project ( https://github.com/carlos-jenkins/pydotplus ) seems to have gone stale quite a while ago, and with all the updates to the python interpreter coming out now that 2.7 is out, I think the package is likely to run into issues soon.

**Comment by TheChymera** [comment]
@effigies @satra any thoughts on this? I recently updated the package on gentoo, and I don't think it will hold up for long, also it doesn't seem to be used by any other package.

**Comment by effigies** [comment]
I think we can probably get rid of it at this point. Networkx 2 is a few years old, and support for older networkx was the reason we had it at all. Care to open a PR bumping the minimum networkx to 2 and dropping pydotplus?

**Comment by TheChymera** [comment]
> Care to open a PR bumping the minimum networkx to 2 and dropping pydotplus?

Sure thing. Would this just require changes to the dependencies lists? Will any features be lost?

**Comment by effigies** [comment]
Yes, just the dependencies. Should have no effect on features at all.
