### ISSUE TITLE
beast,minc toolkit, can't read the image

### ISSUE THREAD

**Issue by HaoLi12345** [nipy/nipype#3253]
Hi, 

im running the example of beast, minc toolkit.

code as follow:

file0 = nonempty_minc_data(0)
beast = Beast(input_file=file0, library_dir='/home/minc-toolkit-v2/BEaST_library')
beast.run()

but it returns an error:
ERROR! Image not read: /home/anaconda3/envs/test/lib/python3.7/site-packages/nipype/testing/data/minc_test_2D_00.mnc
Return code: 255

i'm not sure what happened, can someone help me?
Is this because I didn't install minc successfully?

Thanks!

**Comment by effigies** [comment]
That appears to be an empty file. Do you have your own MINC files to work with?

**Comment by HaoLi12345** [comment]
Hi @effigies 
I think you are right, I just made a mnc file by nii2mnc command.
However, it returned the error like:
ERROR! Mask dimension does not match image dimension!

I have no idea with the size of mask.

From author's instruction, mask can be enabled or not by "-mask and -positive and disabled using -no_mask and -no_positive".
But I didn't find it in the nipype.
How can I fix this error?

Thanks for helping!

**Comment by effigies** [comment]
> From author's instruction, mask can be enabled or not by "-mask and -positive and disabled using -no_mask and -no_positive".
> But I didn't find it in the nipype.

Doesn't look like those are encoded in the input spec, so that would need updating. In the meantime, you can add any extra arguments with the `args` input, e.g.,

```Python
beast = Beast(input_file=fname, library_dir='/home/minc-toolkit-v2/BEaST_library', args="-no_mask")
```

For issues with the `beast` app itself, I would see if MINC has any help forum. If they don't have a specific one, [Neurostars](https://neurostars.org/) is a good place to get help.

**Comment by HaoLi12345** [comment]
Hi @effigies 
Thanks for helping me! Your replies are very useful!
