### ISSUE TITLE
Consider alternative to using Exception.message to get message text

### ISSUE THREAD

**Issue by wtriplett** [nipy/nipype#3270]
### Summary
Apparently, some `Exception` classes may not have a `.message` attribute. This can be more problematic when catching base `Exception` and then trying to log/warn using a string incorporating the original Exception's `.message` attribute. Maybe using `str(ex)` is more compatible, or more specific exception classes?

Example (from `master`):
https://github.com/nipy/nipype/blob/b356ad16828afd4c63f862dfc72fa7e841863391/nipype/utils/filemanip.py#L866-L877

will cause a throw exception if an `OSError` is caught, since OSError does not have a `.message` attribute (at least in python 3.8.3)
 
### Actual behavior
```
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = OSError('darn')
>>> a.message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OSError' object has no attribute 'message'
```
### Expected behavior
```
>>> str(a)
'darn'
```

**Comment by effigies** [comment]
I agree, let's move to str.
