### ISSUE TITLE
Travis now limiting OSS builds

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#3274]
Travis won't run until OSS credit builds for the nipy organization are replenished at some unknown time.

We may want to transition to GitHub actions.

**Comment by satra** [comment]
i have requested additional credits. but github actions would be fine as well.

**Comment by effigies** [comment]
I'm going to try to transition nibabel. Azure has been dissatisfying for Windows anyway, so I'm a bit motivated to abstract out the CI into shell scripts that just need to be invoked from whatever the next CI is.

**Comment by effigies** [comment]
FWIW: nipy/nibabel#972

The unification of Linux/OSX/Windows is quite nice. The handling of environment variables less so.

**Comment by effigies** [comment]
Looks like a couple daily cron jobs was enough to exhaust our extended supply. I cut nibabel way back, so either ARM jobs cost a TON or nipype is chewing through credits with the parameterized jobs.

**Comment by satra** [comment]
they extended my credits. are they not being used for this? i'll try to look into it.

**Comment by effigies** [comment]
We did get more. And it seems they're used up.
