### ISSUE TITLE
Cannot make system calls from Python in the nipype/nipype docker in CircleCI

### ISSUE THREAD

**Issue by eurunuela** [nipy/nipype#3281]
### Summary

I'm trying to write some tests for a little Python package I have for simulating fMRI data. In my workflow, I make some `subprocess.run()` and `subprocess.check_output()` calls from Python to run AFNI commands. However, these do not work on CircleCI when I use the nipype/nipype docker image. Basically, the error says the AFNI commands do not exist.

I have tried the commands on the same docker image on my laptop and they do work.

I guess your suggestion would be to use `nipype` to make those calls and avoid `subprocess`. I'd be happy to but I'm totally new to `nipype` and I'd need help.

The AFNI calls I make are these (they were written a couple of years apart, hence the difference in how they're written):

```
"3dDeconvolve -x1D_stop -nodata %d %f -polort -1 -num_stimts 1 -stim_times 1 '1D:0' '%s' -quiet -x1D stdout: | 1deval -a stdin: -expr 'a'" % (dur_hrf, tr, lop_hrf)
```

```
"3dEmpty -nxyz {} {} {} -nt {} -prefix {}/{} -overwrite".format(
            dims[0], dims[1], dims[2], dims[3], path, "empty.nii.gz"
```

```
'3dNotes -h "{}" {}'.format(history, img_filename)
```

### Script/Workflow details

You can see my `.config.yml` file [here](https://github.com/eurunuela/fmrisim/blob/master/.circleci/config.yml) and the error [here](https://app.circleci.com/pipelines/github/eurunuela/fmrisim/27/workflows/f716c3e1-b208-44bf-97e3-0747cea6d3e2/jobs/143).

**Comment by effigies** [comment]
The docker image uses the neurodocker.sh script as an entrypoint, which sets up the environment. My guess is Circle is replacing the entrypoint with bash.

**Comment by eurunuela** [comment]
How can I change the entrypoint to `neurodocker.sh` then?

**Comment by satra** [comment]
you could potentially source the file (source /neurodocker/neurodocker.sh) so that the different environments and paths are set. i haven't tested this, so ymmv. alternatively you could set the PATH variable. you may want to test this locally by setting the entrypoint explicitly.

**Comment by eurunuela** [comment]
Thank you so much @effigies and @satra !

I tried with `source /neurodocker/startup.sh` but it raised the following error:

```
INFO: /home/neuro/matlab/startup.m does not exist ... creating
```

So, given that I only need AFNI, I decided to only source AFNI and that worked. In case someone ends up reading this:

```
source /etc/afni/afni.sh
```

Thank you so much once again!
