### ISSUE TITLE
Error in AFNI deconvolve interface

### ISSUE THREAD

**Issue by danella** [nipy/nipype#3286]
When I run the following command: 

deconvolve = afni.Deconvolve()
deconvolve.inputs.in_files = [scaled_file]
deconvolve.inputs.mask = mask_file
deconvolve.inputs.ortvec = (regressors_file, 'regressors')
deconvolve.inputs.out_file = 'output1.nii.gz'
deconvolve.inputs.reml_script = 'output2.REML_cmd'
deconvolve.inputs.polort=4
deconvolve.inputs.x1D = 'output.1D.xmat.1D'
deconvolve.inputs.stim_times = [(1, 'sub-109_ses-pre_twoback_2.txt', 'BLOCK(30,1)'),
                                (2, 'sub-109_ses-pre_zeroback_2.txt', 'BLOCK(30,1)')]
deconvolve.inputs.stim_label = [(1, 'TwoBack'),(2, 'ZeroBack')]
deconvolve.inputs.gltsym = [('SYM: TwoBack -ZeroBack'),('SYM: ZeroBack -TwoBack')]
deconvolve.inputs.glt_label = [(1, 'TwoBack-ZeroBack'),(2, 'ZeroBack-TwoBack')]
res = deconvolve.run()  

I get the error:
TraitError: Cannot set the undefined 'reml_script' attribute of a 'DeconvolveInputSpec' object.

If I leave this line out, I get the following error:
TraitError: The 'reml_script' trait of a DeconvolveOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/output1.REML_cmd' <class 'str'> was specified.

If I go to this directory and create a file called output1.REML_cmd then this does not create an error.

This is because apparently reml_script must already exist, and I do not have this script in the current directory. I have two questions. First, is it possible that the first error can be fixed? Second, and perhaps more importantly, is it possible that the code can create an output1.REML_cmd file if one does not currently exist (to avoid that error message)?

Thanks!

Python 3.7

**Comment by effigies** [comment]
@rmarkello Looks like you added the interface in #2095. Any insights?

**Comment by effigies** [comment]
@danella For what it's worth, `reml_script` is not an input, but appears to be an output that is expected to be generated. For some reason it's not being generated, which might be a permissions issue, or a change in the behavior of 3dDeconvolve.

**Comment by danella** [comment]
I see. I thought the reml_script command allowed for flexibility in terms of where this script would be generated, but I guess not. Well, it does generate the output fine if the file already exists. But if it does not exist yet, I think it is producing an error (will double check that though).

**Comment by danella** [comment]
Never mind, I figured it out. I actually was not running Deconvolve from the directory with the data. So more accurately, the code was:

deconvolve = afni.Deconvolve()
deconvolve.inputs.in_files = [scaled_file]
deconvolve.inputs.mask = mask_file
deconvolve.inputs.ortvec = (regressors_file, 'regressors')
deconvolve.inputs.out_file = '{path}/output1.nii.gz'
deconvolve.inputs.polort=4
deconvolve.inputs.x1D = '{path}/output.1D.xmat.1D'
deconvolve.inputs.stim_times = [(1,{path}/ 'sub-109_ses-pre_twoback_2.txt', 'BLOCK(30,1)'),
(2, {path}/'sub-109_ses-pre_zeroback_2.txt', 'BLOCK(30,1)')]
deconvolve.inputs.stim_label = [(1, 'TwoBack'),(2, 'ZeroBack')]
deconvolve.inputs.gltsym = [('SYM: TwoBack -ZeroBack'),('SYM: ZeroBack -TwoBack')]
deconvolve.inputs.glt_label = [(1, 'TwoBack-ZeroBack'),(2, 'ZeroBack-TwoBack')]
res = deconvolve.run()

I think the problem was that the REML_cmd file was being created in a separate (working) directory. If I change directory to where the data and outputs are, it runs fine. Thank you!

**Comment by effigies** [comment]
If you run in a `Node`, then this may be resolved, since that's designed to handle directory isolation and will copy inputs in as needed.
