### ISSUE TITLE
nipype module take a while for import

### ISSUE THREAD

**Issue by servoz** [nipy/nipype#3293]
I had already observed that the import time can be long or short sometimes.

This morning it seems like an eternity ... Do you have an explanation for this slowness? 

```
$ python3
Python 3.8.6 (default, Sep 25 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> t0 = time.time(); from nipype.interfaces.spm import Smooth; print('import time:', time.time() - t0)
import time: 10.510946035385132
>>> import nipype
>>> nipype.__version__
'1.6.0'
>>> import sys
>>> sys.platform
'linux'

```
EDIT:
We are developing a project that proposes, among other things, nipype by default.
The current problem makes it impossible to use our project because of the current slowness of nipype.
The quick tests I have done indicate that the current slowness is having a dramatic impact on our project with nipype >1.4.2.
The problem would come from check_latest_version which is done automatically and which is currently working badly.

**Comment by satra** [comment]
@servoz - this is likely because of the check that nipype does to see if there is an updated version available, and whether the current version has some incurable bug! the server went down yesterday night due to a power outage. you can set an environment variable `NO_ET` to disable the check.

**Comment by servoz** [comment]
I think you suggest NIPYPE_NO_ET!
Thank you for your answer which offers a nice workaround option!

**Comment by satra** [comment]
actually both variables exist. `NIPYPE_NO_ET` prevents nipype's ET check but not if an underlying library uses ET. `NO_ET` disables any ET check.

**Comment by servoz** [comment]
Ah ok thank you!

**Comment by servoz** [comment]
oh I see! NYPIPE_NO_ET is used in nipype and NO_ET is used directly in etelemetry !!!!!
Thanks, I didn't know!
