### ISSUE TITLE
BaseInterfaceInputSpec pass list of input files

### ISSUE THREAD

**Issue by Chercas** [nipy/nipype#3299]
Hello,

can you please suggest a method to pass a list of '*.nii' files to a custom made averaging interface of functional images. I want to make an analogue of 3dMean AFNI to average more than 2 images.

Thanks in advance!
best regards,
Kostya

**Comment by effigies** [comment]
You probably want a list of files, e.g.:

https://github.com/nipy/nipype/blob/e9217c299149be829a985d8f822c3a91e29b2f4b/nipype/interfaces/fsl/utils.py#L337

**Comment by Chercas** [comment]
> You probably want a list of files, e.g.:
> 
> https://github.com/nipy/nipype/blob/e9217c299149be829a985d8f822c3a91e29b2f4b/nipype/interfaces/fsl/utils.py#L337

Thanks, that worked!
