### ISSUE TITLE
fsl randomise f_only flag contains typo, can't work

### ISSUE THREAD

**Issue by henrymj** [nipy/nipype#3322]
### Summary
when calling randomise with f_only=True, nipypes interfaces appends --f_only instead of --fonly. This is incorrect and prevents the call from working.

The offending line is [here](https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/model.py#L2250), where the last bit should be `argstr="--fonly"`
### Actual behavior
appending --fonly to the randomise call.

### Expected behavior

--f_only is appended, breaking the call.

### Script/Workflow details

```
    fsl_randomise = mem.cache(fsl.Randomise)
    randomise_results = fsl_randomise(
        in_file=`fourdimage.nii`,
        mask=`mask.nii`,
        num_perm=10000,
        f_only=True,
        **kwargs
        )
```

### Platform details:

```
{'commit_hash': 'c5ce0e2c9',
 'commit_source': 'installation',
 'networkx_version': '2.5',
 'nibabel_version': '3.2.1',
 'nipype_version': '1.4.2',
 'numpy_version': '1.20.1',
 'pkg_path': '/usr/local/miniconda/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.6.1',
 'sys_executable': '/usr/local/miniconda/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]',
 'traits_version': '6.2.0'}
```

**Comment by effigies** [comment]
What version of FSL? Are we sure that or didn't change from one to the other?

Would you be up for submitting a PR?

**Comment by henrymj** [comment]
FSL Version 6.0. I just scrolled through the FSL history [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/WhatsNew#anchor1) and didn't see any references to changing the command-line interface, but I may not be digging deep enough. 

I can submit a PR later in the week if no objections arise in the meantime!
