### ISSUE TITLE
Developer install guide link not working.

### ISSUE THREAD

**Issue by RaunakJalan** [nipy/nipype#3329]
### Summary
In [install.rst](https://github.com/nipy/nipype/blob/master/doc/users/install.rst) at the end we have link for developers to install nipype. But that link is not working and goes to Error 404.

![Link Location](https://user-images.githubusercontent.com/41023976/115599499-5285f800-a2f9-11eb-853c-b2bde4088227.png)

![Error image](https://user-images.githubusercontent.com/41023976/115599557-6598c800-a2f9-11eb-9181-62bbf8fb3369.png)

[Link generating 404](https://github.com/nipy/nipype/blob/master/doc/devel/testing_nipype.html)

**Comment by effigies** [comment]
Yes, it should point to an [RST file](https://github.com/nipy/nipype/blob/master/doc/devel/testing_nipype.rst). Would you care to submit a fix?

**Comment by RaunakJalan** [comment]
Yeah sure @effigies . I will submit the fix.

**Comment by RaunakJalan** [comment]
Closing this issue. Fixed the link.
