### ISSUE TITLE
ANTS antsMotionCorr implementation

### ISSUE THREAD

**Issue by JoeZiminski** [nipy/nipype#3352]
### Summary
Are there plans to implement antsMotionCorr [1] in niypyes ants package? [2]. I would be happy to help with this using one of the other ants commands as a guide if it would be useful.

Best,
Joe

[1] http://manpages.ubuntu.com/manpages/bionic/man1/antsMotionCorr.1.html
[2] https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.ants.html?

**Comment by effigies** [comment]
There are no active plans to add more interfaces, but we are always willing to review pull requests with new interfaces.

**Comment by oesteban** [comment]
Unce upon a time there was #1812.

**Comment by JoeZiminski** [comment]
Thanks, I would be happy to adpot this pull request. I can take a look at existing ANTS function interfaces and the pull request, and submit a plan for others to review before starting, if that would be useful.

**Comment by effigies** [comment]
For myself, I would be fine with you opening a pull request whenever you're ready, but please feel free to run things by us first if that would be helpful to you.

**Comment by JoeZiminski** [comment]
Thanks @effigies I think in the end I did not make any meaningful progress and have since moved on from my previous position. Thanks for your help with this issue, I will close it now.
