### ISSUE TITLE
voliso error Illegal division by zero NumericUtilities.pm

### ISSUE THREAD

**Issue by SaibotMagd** [nipy/nipype#3356]
### Summary
I don't understand the error message:
I'm neither a programmer nor linux expert so I can't even say if the problem comes from nipype, minc-toolkit or volgenmodel itself. Sorry if I guessed wrong.

```
{'node': _preprocess_voliso3,
 'traceback': ['Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__\n    mp_context=mp_context,\n',
  "TypeError: __init__() got an unexpected keyword argument 'initializer'\n",
  '\nDuring handling of the above exception, another exception occurred:\n\n',
  'Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node\n    result["result"] = node.run(updatehash=updatehash)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run\n    result = self._run_interface(execute=True)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface\n    return self._run_command(execute)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command\n    result = self._interface.run(cwd=outdir)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run\n    runtime = self._run_interface(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface\n    self.raise_exception(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception\n    ).format(**runtime.dictcopy())\n',
  'RuntimeError: Command:\nvoliso --avgstep --clobber /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_mouse_6_volcentre_norm_volpad.mnc gerbil_mouse_6_volcentre_norm_volpad_voliso.mnc\nStandard output:\n\nStandard error:\n
Illegal division by zero at /home/nistmni/src/minc-toolkit-v2/mni-perllib/MNI/NumericUtilities.pm (autosplit into /home/nistmni/src/build/minc-toolkit-v2/mni-perllib/perl/auto/MNI/NumericUtilities/round.al) line 198.\n
Died at /home/saibotmagd/toolboxes/minc/1.9.18/bin/voliso line 112.\nReturn code: 255\n']}
```

### Actual behavior
Pipeline (https://github.com/carlohamalainen/volgenmodel-nipype) fails.
### Expected behavior
I don't know what the function 'voliso' does but the volgenmodel pipeline runs successfully with the official sample data.
### How to replicate the behavior
Maybe I have to upload the image files?
### Script/Workflow details
It's probably an error regarding the input file. Here the output from nii2mnc:

```
<nifti_image
  nifti_type = 'NIFTI-1+'
  header_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_offset = '352'
  ndim = '3'
  nx = '678'
  ny = '819'
  nz = '448'
  dx = '1'
  dy = '1'
  dz = '1'
  datatype = '4'
  datatype_name = 'INT16'
  nvox = '248766336'
  nbyper = '2'
  byteorder = 'LSB_FIRST'
  scl_slope = '1'
  scl_inter = '0'
  xyz_units = '2'
  xyz_units_name = 'mm'
  qform_code = '2'
  qform_code_name = 'Aligned Anat'
  qto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  qto_ijk_matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  quatern_b = '0'
  quatern_c = '0'
  quatern_d = '1'
  qoffset_x = '-0'
  qoffset_y = '-0'
  qoffset_z = '0'
  qfac = '1'
  qform_i_orientation = 'Right-to-Left'
  qform_j_orientation = 'Anterior-to-Posterior'
  qform_k_orientation = 'Inferior-to-Superior'
  sform_code = '1'
  sform_code_name = 'Scanner Anat'
  sto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  sto_ijk matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  sform_i_orientation = 'Right-to-Left'
  sform_j_orientation = 'Anterior-to-Posterior'
  sform_k_orientation = 'Inferior-to-Superior'
  num_ext = '0'
/>
Using s-form transform:
 -1.0000,   0.0000,   0.0000,  -0.0000, 
  0.0000,  -1.0000,   0.0000,  -0.0000, 
  0.0000,   0.0000,   1.0000,   0.0000, 
  0.0000,   0.0000,   0.0000,   1.0000, 
xspace start:  -0.0000 step:  -1.0000 cosines:   1.0000  -0.0000  -0.0000 flip: 0
yspace start:  -0.0000 step:  -1.0000 cosines:  -0.0000   1.0000  -0.0000 flip: 0
zspace start:   0.0000 step:   1.0000 cosines:   0.0000   0.0000   1.0000 flip: 0
```

### Platform details:

```
210729-11:48:57,947 nipype.utils INFO:
	 Running nipype version 1.4.2 (latest: 1.5.1)
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.5.1',
 'nibabel_version': '3.2.1',
 'nipype_version': '1.4.2',
 'numpy_version': '1.19.5',
 'pkg_path': '/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.5.3',
 'sys_executable': '/home/saibotmagd/anaconda3/envs/py34/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.13 | packaged by conda-forge | (default, Feb 19 2021, '
                '05:36:01) \n'
                '[GCC 9.3.0]',
 'traits_version': '6.2.0'}

```

### Execution environment

Anaconda 3 env with python 3.5

**Comment by effigies** [comment]
The error is arising in the voliso command `voliso --avgstep --clobber /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_mouse_6_volcentre_norm_volpad.mnc gerbil_mouse_6_volcentre_norm_volpad_voliso.mnc`.

If you look at the input file in your nipype working directory, you may be able to see the issue. If not, I would try the minc mailing list.

If there is a problem with the file, you can work backwards to find out which step generated a bad file.

**Comment by SaibotMagd** [comment]
> The error is arising in the voliso command `voliso --avgstep --clobber /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_mouse_6_volcentre_norm_volpad.mnc gerbil_mouse_6_volcentre_norm_volpad_voliso.mnc`.
> 

This could be helpful. I checked the mnc file and as fair as I can see it looks good.

> If you look at the input file in your nipype working directory, you may be able to see the issue. 
I don't know what the working directory is or the input file, but I checked several pkzl files in the volpad folder. Nothing relevant here.

> If not, I would try the minc mailing list.

Don't know what this is, but I try to find out.
 
> If there is a problem with the file, you can work backwards to find out which step generated a bad file.

What does it mean "work backwards"? The last generated file in the pipeline seems fine. I don't know about the steps the pipeline did before (I just used timecodes to find the last created file).

**Comment by effigies** [comment]
> > If you look at the input file in your nipype working directory, you may be able to see the issue.
> 
> I don't know what the working directory is or the input file, but I checked several pklz files in the volpad folder. Nothing relevant here.

The work directory looks like it's probably `/home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2`.

> > If not, I would try the minc mailing list.
> 
> Don't know what this is, but I try to find out.

Just had a quick search and also couldn't find it. OTOH I did find [this page](https://bic-mni.github.io/) so probably the best bet is https://github.com/BIC-MNI/minc-tools/issues. I also see it recommending to contact @gdevenyi (among others), so I'm pinging him here.

> > If there is a problem with the file, you can work backwards to find out which step generated a bad file.
> 
> What does it mean "work backwards"? The last generated file in the pipeline seems fine. I don't know about the steps the pipeline did before (I just used timecodes to find the last created file).

If your input file is bad, then you look in the workflow for the node that created it, find its directory in the working directory and check its inputs and outputs. You continue following that chain until you find the node that had good inputs and bad outputs. It also makes sense to inspect your original inputs to ensure that they're okay.

The failing line is https://github.com/andrewjanke/mni-perllib/blob/master/MNI/NumericUtilities.pm#L195, which means a the caller passed a factor of 0 to this subroutine, but without a full traceback, it's going to take some effort to track down.

> Currently my guess is that the combination of
> sform_code = '1' and the 0 in the last column of the transform matrix create the illegal division issue. Because this seems like the only difference between my datasets and the example onces.
> 
> `Using s-form transform: -1.0000, 0.0000, 0.0000, -0.0000, 0.0000, -1.0000, 0.0000, -0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, `

This is a reasonable affine matrix. It just means the origin is in the corner of the image, rather than near the center. It's possible that there's a bug resulting from that edge case, I suppose.

**Comment by gdevenyi** [comment]
Tracking here:
https://github.com/BIC-MNI/minc-toolkit-v2/issues/138

In particular, `+++ Resulting steps: [0, 0, -0.33]  (minstep: 0) (maxstep: -0.33) +++` indicates that voliso is passing a step size of 0 to autocrop, need to examine the input mnc files to see why.

A side note, you may be interested in a modern implementation of volgenmodel I wrote using ANTs tools, https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction

**Comment by effigies** [comment]
Ah, thanks, I missed that. Closing here. Please reopen if there's something we need to do on our end.

**Comment by SaibotMagd** [comment]
> Ah, thanks, I missed that. Closing here. Please reopen if there's something we need to do on our end.

Yes sure. Thank you I've got some pretty good answers in the minc-toolkit issue.
