### ISSUE TITLE
Failures in Test suite

### ISSUE THREAD

**Issue by tillea** [nipy/nipype#3382]
### Summary

When trying to build the Debian package for version 1.6.1 there are three test suite errors.

### Script/Workflow details

[Here is a link to the full build log in Debian CI](https://salsa.debian.org/med-team/nipype/-/jobs/2013398#L5725)

It says

    =========================== short test summary info ============================
    FAILED ../nipype/algorithms/tests/test_CompCor.py::TestCompCor::test_compcor
    FAILED ../nipype/algorithms/tests/test_CompCor.py::TestCompCor::test_compcor_variance_threshold_and_metadata
    FAILED ../nipype/algorithms/tests/test_CompCor.py::TestCompCor::test_tcompcor
    = 3 failed, 2674 passed, 239 skipped, 1 deselected, 5 xfailed, 25 warnings in 142.68s (0:02:22) =

### Platform details:

Debian unstable.  The command that is suggested here does not really help since the package was not successfully built so it gives no information about the system.  Please see on top of above build log.

Kind regards, Andreas.

**Comment by effigies** [comment]
Hmm. My guess would be that there's been a change in numpy or scipy's SVD implementation. Or possibly that sign flips can happen on different instruction sets. Will see if I can reproduce locally.

**Comment by effigies** [comment]
Locally not seeing this issue. I also can't see in those logs the installation of numpy and scipy, which seem like the most likely sources of variation. Do you have `numpy` and `scipy` packages that can be installed in a virtual environment? Preferably wheels, but `.deb`s are fine too.

**Comment by tillea** [comment]
I'll add these as Build-Depends and will try again.

**Comment by effigies** [comment]
Yes, I can reproduce in Docker. If I install `python3-numpy` and `python3-scipy` Debian packages, then the tests fail. If I `pip install --force numpy=1.19.5` to get the numpy-distributed wheel, this fixes the tests.

Would it be possible to try rebuilding the numpy package to see if there's a stochastic bug here?

**Comment by tillea** [comment]
I tried rebuilding the numpy source package on my side but went into a build error (no idea why).  So I need to admit that this is harder than expected (at least with the current state of the Debian archive).

**Comment by effigies** [comment]
Thanks for checking back in. My feeling is that I would rather not make our tests accept sign flips out of SVD, as reproducibility of results is highly desirable.

If we can reliably produce a numpy build that induces these sign flips, it would be a good issue to open with numpy.

Does this seem reasonable? Let me know if there's anything I can do to help.

**Comment by emollier** [comment]
Hello,

The test failure in _nipype_ eventually lead to [Debian Bug #997126](https://bugs.debian.org/997126), in which Graham Inggs noticed that the failure is similar to the [Debian Bug #994457](https://bugs.debian.org/994457) affecting _r-cran-gnm_.  This could eventually be related to a change of SVD implementation in _lapack_ 3.10, and indeed _numpy_ depends on _lapack_, among other things.

In hope this helps...

**Comment by effigies** [comment]
Thanks for the references. It seems that we should be tolerant to sign flips of entire columns. Opened #3405. Feel free to use the patch in Debian for existing releases of nipype.

**Comment by emollier** [comment]
Thanks very much!  :)
