### ISSUE TITLE
MathsCommand().inputs.out_file has to exist

### ISSUE THREAD

**Issue by 0nu** [nipy/nipype#3384]
When setting `MathsCommand().inputs.out_file` argument, a Trait error is thrown because of the `exists=True`:

https://github.com/nipy/nipype/blob/6a7837c0994367a5f34bb576bb0a97ec70669b8f/nipype/interfaces/fsl/maths.py#L44

I think this doesn't make any sense, because `out_file` is to be created by `MathsCommand()`.
In my case, I just want to get rid of SPM nan's in an .nii file, but I also don't want fsl_maths to append a suffix to the filename - this is why I also provide `out_file` to `MathsCommand().inputs`.
A short example:
```
nan2zero = pe.MapNode(interface=MathsCommand(), name='nan2zero', iterfield=['in_file', 'out_file'])
nan2zero.inputs.nan2zeros = True

```

**Comment by effigies** [comment]
I agree. Would you like to make a PR to remove that?
