### ISSUE TITLE
Nipype FSL renderhighness

### ISSUE THREAD

**Issue by marcostroppi** [nipy/nipype#3431]
It is possibile to use FSL's command "renderhighness" with Nipype?

**Comment by pcamach2** [comment]
Hi @marcostroppi,

This is not currently a module of the fsl interface of nipype, but if you have FSL installed in the environment you use for Nipype, I think you might be able to run renderhighres via a subprocess Popen call:

```
import os
import os.path as op
from subprocess import Popen

#usage: renderhighres <feat_directory> <space> <background> <autothresh> [minZ maxZ]
feat_dir = "/path/to/FEAT_directory"
#<space>: either highres or standard
space = "highres"
#<background>: either highres or standard
background = "highres"
#<autothresh>: either 0 or 1 (colour-code using existing post-threshold range? If 0 then minZ and maxZ are used)
autothresh = "0"

#run the command via subprocess
proc = Popen(["renderhighres", feat_dir, space, background, autothresh], stdout=open(os.devnull, "wb"))

```

This would need to be modified to fit your desired argument values for renderhighres and added to a nipype script you are writing or you could request an official nipype fsl interface for the renderhighres function.

**Comment by marcostroppi** [comment]
Thank you so much for the help :)
