### ISSUE TITLE
Prevent excessive etelemetry pings

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#3483]
When etelemetry is down, nipype can spend excessive time re-trying instead of recording a failure mode.

On the one hand, this is a problem with the client. On the other, we should probably code defensively against bugs in the etelemetry client.

**Comment by mgxd** [comment]
https://github.com/nipy/nipype/blob/71c7a7d5315714bad8c423a587ba15760dc00b77/nipype/interfaces/base/core.py#L188-L189

I think the easiest thing to do would be to add a check if `None` is returned, and if so set `BaseInterface._etelemetry_version_data` to `n/a` or something equivalent
