### ISSUE TITLE
Error when running nipype-tutorial container in VScode

### ISSUE THREAD

**Issue by yufang1039** [nipy/nipype#3491]
### Summary
Thanks for developing this amazing tool. I'm new to nipype and docker and trying to set the tutorial container up in Vscode, however, when I run the following code block, it gives me an error.

```
bet = BET()
bet.inputs.in_file = input_file
bet.inputs.out_file = "/output/T1w_nipype_bet.nii.gz"
res = bet.run
```
![image](https://user-images.githubusercontent.com/23185546/179066011-0648c306-a812-438c-a0fb-177b8558a376.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/23185546/179066018-141f4139-acb9-46e7-812f-a8e133874eb6.png)

### Expected behavior
I'm expecting to get the code block to run suceessfully

### How to replicate the behavior
1. run the docker image in vscode

<img width="278" alt="Screen Shot 2022-07-14 at 12 10 48 PM" src="https://user-images.githubusercontent.com/23185546/179064230-46b45369-6eb1-4434-aa2a-ef450356bd5b.png">

2. Attach to the docker container
<img width="807" alt="Screen Shot 2022-07-14 at 12 13 21 PM" src="https://user-images.githubusercontent.com/23185546/179064773-b5730d0d-de35-4173-91a4-d02318c6030a.png">

3. select interpreter (I selected neuro)
<img width="701" alt="Screen Shot 2022-07-14 at 12 14 35 PM" src="https://user-images.githubusercontent.com/23185546/179064966-b4d9a272-1a27-4c99-842d-f83019d3dff5.png">

4. Run
<img width="1459" alt="Screen Shot 2022-07-14 at 12 15 24 PM" src="https://user-images.githubusercontent.com/23185546/179065064-93be8cfd-06ed-4a4b-b28f-ffee3cdab880.png">

<img width="1265" alt="Screen Shot 2022-07-14 at 12 15 37 PM" src="https://user-images.githubusercontent.com/23185546/179065106-778412ee-af0e-4f56-9a25-821766cf980a.png">

### Script/Workflow details

```
import os
from os.path import abspath

from nipype import Workflow, Node, MapNode, Function
from nipype.interfaces.fsl import BET, IsotropicSmooth, ApplyMask

from nilearn.plotting import plot_anat
%matplotlib inline
import matplotlib.pyplot as plt

input_file =  abspath("/data/ds000114/sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz")

bet = BET()
bet.inputs.in_file = input_file
bet.inputs.out_file = "/output/T1w_nipype_bet.nii.gz"
res = bet.run()
```

### Execution environment
- Container

**Comment by yufang1039** [comment]
Hi @effigies 

I used ```docker pull miykael/nipype_tutorial:latest``` to get the docker image. So I suppose FSL should be already existed in the image?

Because when I run ```docker run -it --rm -p 8888:8888 miykael/nipype_tutorial jupyter notebook``` and open notebooks in my browser, it works fine. But if I do it in the vscode, there's an error.

Thanks in advance for the help!

**Comment by effigies** [comment]
It seems that there might be environment variables that aren't getting loaded, such as the `PATH`? FSL should be available in the container.

Unfortunately, I don't have any experience with using vscode inside a container. (And little enough outside.) But the problem does seem to be that the command can't be found.

**Comment by yufang1039** [comment]
Hi @effigies Thanks for the help! I decided to work in the original jupyter notebook. However, when I try to nount my local file by running this code in the tutorial
```
docker run -p 8888:8888 -it --rm -v /Users/yufang/Leelab/Fmri/Notebooks -v /Users/yufang/Leelab/Fmri/data -v /Users/yufang/Leelab/Fmri/output -v /Users/yufang/Leelab/Fmri/20220618_122133_1_anaesth_auditory_response_1_1  miykael/nipype_tutorial
```
My local files doesn't show up, the directory is still the same to the tutorial's directory and I have no idea how should I fix it

<img width="1204" alt="Screen Shot 2022-07-15 at 11 00 28 AM" src="https://user-images.githubusercontent.com/23185546/179283876-882bf880-45bf-4d49-8474-465ca5c46575.png">

Thanks!

**Comment by effigies** [comment]
Sorry, I'm not really sure what the setup of the tutorial environment is. I would suggest Neurostars for more general questions, as this repository gets very limited views.
