### ISSUE TITLE
dcm2niix update

### ISSUE THREAD

**Issue by TamerGezici** [nipy/nipype#3494]
Dear all,

Is it possible to update the dcm2niix version that comes with dcm2niix? I am having trouble with the issue here: https://github.com/rordenlab/dcm2niix/issues/271

I think the current version uses v1.0.20181125 and what I need is v1.0.20211006

**Comment by effigies** [comment]
You should be able to update dcm2niix in your environment. Nipype will use whatever version it finds.

**Comment by TamerGezici** [comment]
> You should be able to update dcm2niix in your environment. Nipype will use whatever version it finds.

I see. Thanks. Will do.
