### ISSUE TITLE
MATLAB:mpath:PathAlterationNotSupported / Modifying the search path is not supported by MATLAB Compiler using MAtlab 2019b

### ISSUE THREAD

**Issue by servoz** [nipy/nipype#3507]
[It seems modifying the matlab path using addpath() is not likely to be supported at any point after MATLAB MCR_R2018b](https://github.com/populse/populse_mia/issues/238).
However, [nipype use addpath()](https://github.com/nipy/nipype/blob/master/nipype/interfaces/matlab.py#L194) command in the matlab script generated .
So [the easy fix is to stick with R2018b.](https://fr.mathworks.com/matlabcentral/answers/554821-compiling-failing-using-matlab-2019b)
But it's a real problem not to be able to use newer MCRs in the future.
Can you remove the addpath() command when generating the script ? Or is there another way to use MCR after R2018b?

**Comment by DimitriPapadopoulos** [comment]
I'd like to add that upcoming versions of SPM12 will likely be built with R2021b (MCR v911). If so, downgrading to a previous versions of the MCR might not be possible. The only log term fix is ti get rid of `addpath()`.

**Comment by effigies** [comment]
Do y'all know what a fix would be? We can obviously remove the line, but we'd need to confirm that it doesn't break workflows.

**Comment by effigies** [comment]
I understand that it is causing forward compatibility problems. Before removing it, we need to understand what problem it was solving and make sure the problem remains solved with the final change.

At worst, we should be able to detect the Matlab version and drop it for more recent versions.

**Comment by DimitriPapadopoulos** [comment]
We haven't found any problem it could solve. It looks like `addpath()` had been introduced  by https://github.com/nipy/nipype/commit/078619cab5c4de39ac256f9af462289b50504a09 without any explanation.

**Comment by effigies** [comment]
Sounds great to me. Would you like to open a PR?

**Comment by servoz** [comment]
As you like! I do it quickly.

**Comment by DimitriPapadopoulos** [comment]
@servoz I have suggested merge request #3509.

**Comment by DimitriPapadopoulos** [comment]
But I can put you as author of the code if you want to.

Note the `if ~(ismcc || isdeployed)` from https://mathworks.com/help/compiler/isdeployed.html.

**Comment by servoz** [comment]
Oh great ! Thanks @DimitriPapadopoulos !

**Comment by servoz** [comment]
no no it's fine like this, I don't want to be an author!
