### ISSUE TITLE
Unnecessary print used in the FEAT class 

### ISSUE THREAD

**Issue by somso2e** [nipy/nipype#3520]
There is an unnecessary print statement used in the ```_list_outputs``` method in the ```FEAT``` class.
This is especially annoying when running a lot of FEAT analysises since it litters the terminal and messes with other user-defined prints and or with progress bars such as ```tqdm```.

https://github.com/nipy/nipype/blob/72aac961cc53eeaa134d50811ff9ae59c8ea9acb/nipype/interfaces/fsl/model.py#L487

As a temporary workaround, you can suppress the print statement like below. 

```python
import contextlib
with contextlib.redirect_stdout(None):
        feat = fsl.FEAT()
        feat.inputs.fsf_file = fsf_file
        feat.terminal_output = "none"
        feat_output = feat.run()
```

**Comment by effigies** [comment]
Looks like a debug statement added in https://github.com/nipy/nipype/pull/635. Please feel free to open a PR to remove it.
