### ISSUE TITLE
networkx >= 3.0 unsupported

### ISSUE THREAD

**Issue by thomas-vincent** [nipy/nipype#3530]
to_scipy_sparse_matrix will be deprecated, use to_scipy_sparse_array instead

As stated in networkx:
```
warnings.warn(
        (
            "\n\nThe scipy.sparse array containers will be used instead of matrices\n"
            "in Networkx 3.0. Use `to_scipy_sparse_array` instead."
        ),
        DeprecationWarning,
        stacklevel=2,
    )
```

Either nipype code is adapted to handle network 2 and 3 or setup.py should specify that networkx must be < 3 in the dependencies.

**Comment by effigies** [comment]
Good catch. Would you mind submitting a PR?

**Comment by lamaresh** [comment]
this may be userful for you https://github.com/scikit-image/scikit-image/pull/6564

**Comment by TheChymera** [comment]
I am getting the same issue, among others, over [here](https://ppb.chymera.eu/b4e05b.log). Tired to ~fix : https://github.com/nipy/nipype/pull/3535
