### ISSUE TITLE
One test fails in network sandbox on patched `=nipype-1.8.4`

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#3540]
One more issue left after the excellent collection of fixes in https://github.com/nipy/nipype/pull/3538
Build and test log is [here](https://ppb.chymera.eu/476abd.log).

I'm wondering whether nipype has semi-automatic (i.e. via some environment variable) network test deselection which I just haven't figured out how to use yet.

### Platform details:

```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '3.0',
 'nibabel_version': '3.2.1',
 'nipype_version': '1.8.4',
 'numpy_version': '1.24.0',
 'pkg_path': '/usr/lib/python3.10/site-packages/nipype',
 'scipy_version': '1.10.0',
 'sys_executable': '/usr/lib/python-exec/python3.10/python',
 'sys_platform': 'linux',
 'sys_version': '3.10.9 (main, Dec 18 2022, 05:30:37) [GCC 12.2.1 20221210]',
 'traits_version': '6.3.2'}
```

### Execution environment

- My python environment outside container

**Comment by effigies** [comment]
> I'm wondering whether nipype has semi-automatic (i.e. via some environment variable) network test deselection which I just haven't figured out how to use yet.

No, I don't think we do.

**Comment by TheChymera** [comment]
well, ok, explicitly disabled it for now. As long as it's just the one, an envvanr for it might be more work than it's worth.
