### ISSUE TITLE
repeated output_spec in `fsl.epi.eddy`

### ISSUE THREAD

**Issue by yibeichan** [nipy/nipype#3567]
### Summary

`out_shell_pe_translation_parameters` appears twice in a row, see [here](https://github.com/nipy/nipype/blob/450be34b4540a0c3c6761cc04cc9132fdac5f5c8/nipype/interfaces/fsl/epi.py#L848) line 848 & line 854. 

Seems it hasn't caused any errors, but maybe we want to remove the redundant one? @djarecka

**Comment by djarecka** [comment]
indeed it looks the field is repeated. Do you want to open a pr to fix it?

**Comment by yibeichan** [comment]
done, opened PR here #3568
