### ISSUE TITLE
Can't use in Jypeter notebook

### ISSUE THREAD

**Issue by Planetdtudy** [nipy/nipype#3574]
### Script/Workflow details

from nipype.interfaces.spm import Smooth
smooth = Smooth()
smooth.inputs.in_files = 'functional.nii'
smooth.inputs.fwhm = 6
smooth.run()

### Platform details:

ModuleNotFoundError: No module named 'nipype'

```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by effigies** [comment]
I think jupyter forums will have better support for helping get packages installed into the same environment as the Jupyter kernel. I believe that `!pip install nipype` will work.

**Comment by Planetdtudy** [comment]
Thank you. I will try on Jupiter forums. I have tried pip install. I did it
first if all.

Best Regards,
