### ISSUE TITLE
Missing contrast outputs for SPM EstimateModel

### ISSUE THREAD

**Issue by manuegrx** [nipy/nipype#3576]
Hi, 
It seems that if factorial design is used for fMRI model specification (parameter "factor_info" in Level1design), spm automatically creates contrasts (con*, ess*, spmF* and spmT* images) during model estimation (EstimateModel). 

Those outputs are not yet in EstimateModel in Nipype, it could be useful to have them. 
I will create a PR in order to add them if it is okay 

Best,

**Comment by effigies** [comment]
Closed by #3577.
