### ISSUE TITLE
dcm2niix converted_files duplicate entry

### ISSUE THREAD

**Issue by mauriliogenovese** [nipy/nipype#3579]
### Summary
Converting mosaic dti series with dmc2niix results in a duplicated output

### Actual behavior
converted_files output contains twice the generated nifti file

### Expected behavior
converted_files should contain a single entry

###Possible solution
 _parse_files in Dcm2niix should check if the file is already in lists before appending

**Comment by effigies** [comment]
Patches are welcome.
