### ISSUE TITLE
Workflow run return status

### ISSUE THREAD

**Issue by sulantha2006** [nipy/nipype#3614]
### Summary
When a workflow is completed, it would be helpful to have the workflow save its status (success, failed, success with errors etc...)
### Actual behavior
Workflow run doesnt keep its status
### Expected behavior
a return value or a status field that can accessed

**Comment by effigies** [comment]
The return value is the execution graph that allows you to access the result of any node (except `IdentityInterface`s which are removed prior to run). If there's a failure, an exception will be raised.

Nipype is not likely to see any major changes in the future. [Pydra](https://github.com/nipype/pydra) is under active development, and design proposals can be made there.
