### ISSUE TITLE
tkagg display error

### ISSUE THREAD

**Issue by satra** [nipy/nipype#366]
@mwaskom:  shouldn't this not happen with tkagg?

```
  File "/srv/software/python/EPD/virtualenvs/7.2/nipype0.5/lib/python2.7/site-packages/nipype/algorithms/rapidart.py", line 357, in _detect_outliers_core
    fig = plt.figure()
  File "/software/python/EPD/7.2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 343, in figure
    **kwargs)
  File "/software/python/EPD/7.2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 80, in new_figure_manager
    window = Tk.Tk()
  File "/software/python/EPD/7.2/lib/python2.7/lib-tk/Tkinter.py", line 1685, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: couldn't connect to display "computor:1.0"
```

**Comment by djarecka** [comment]
@satra : i don't know how to reproduce the issue and it's pretty old, but i'm guessing that `matplotlib.use('Agg')` or `matplotlib.use(config.get('execution', 'matplotlib_backend'))` solved problems in most of the cases. 
I can see a few places that import `matplotlib` and don't set backend (e.g. https://github.com/nipy/nipype/blob/master/nipype/algorithms/metrics.py#L141). i can search the code and `matplotlib.use(config.get('execution', 'matplotlib_backend'))`

**Comment by oesteban** [comment]
@satra @djarecka What if we clear up all the matplotlib backend options and recommend users to change the matplotlib default? - https://github.com/nipy/nipype/blob/master/Dockerfile#L71

**Comment by djarecka** [comment]
Not sure what is easier to "maintain". There are only a few files where you import `matplotlib`, so can review if you decide to keep the `matplotlib` backend options in the code.

The only thing I'm not completely sure is `matplotlib.is_interactive()`, should we ensure to be `False` regardless of backend? The default is `False`, so it's usually `False` anyway, but I'm not sure if this can also cause a problem.

**Comment by djarecka** [comment]
@satra , @oesteban do we still want to do anything about it?
