### ISSUE TITLE
`ts_Z_corr` not defined

### ISSUE THREAD

**Issue by shnizzedy** [nipy/nipype#3696]
### Summary

In `NetCorr`, there's a check https://github.com/nipy/nipype/blob/237a9a7ca244ca87916e1f9c5bd73c3f08c00c5d/nipype/interfaces/afni/preprocess.py#L2744 which causes

```Python
AttributeError: 'NetCorrInputSpec' object has no attribute 'ts_Z_corr'
```

if `ts_wb_corr` is not specified.

* I'm not 100% sure, but I think `ts_Z_corr` is meant to be `ts_wb_Z` based on the structure of the check and [the definitions of the arguments for 3dNetCorr](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dNetCorr.html).
* I'm also not sure, but I think the check should check if those values are `True` rather than just if they are defined?

### Actual behavior

```Python
AttributeError: 'NetCorrInputSpec' object has no attribute 'ts_Z_corr'
```

### Expected behavior

- [ ] `ts_wb_corr` can be unspecified and interface will be useable.

### How to replicate the behavior

1. Try to use `nipype.interfaces.afni.preprocess.NetCorr` without `ts_wb_corr`

### Script/Workflow details

```Python
    timeseries_correlation = pe.Node(NetCorr(), name=name)
    if method:
        timeseries_correlation.inputs.part_corr = method == "Partial"


    strip_header_node = pe.Node(
        Function(
            input_names=["in_file", "out_file"],
            output_names=["out_file"],
            imports=["import subprocess"],
            function=strip_afni_output_header,
        ),
        name=f"netcorrStripHeader{method}_{pipe_num}",
    )


    name_output_node = pe.Node(
        Function(
            input_names=["atlas_name", "tool", "method"],
            output_names=["filename"],
            imports=["import os"],
            function=connectome_name,
        ),
        name=f"connectomeName{method}_{pipe_num}",
        as_module=True,
    )
    name_output_node.inputs.tool = "Afni"


    wf.connect(
        [
            (
                inputspec,
                timeseries_correlation,
                [("in_rois", "in_rois"), ("in_file", "in_file"), ("mask", "mask")],
            ),
            (
                inputspec,
                name_output_node,
                [("atlas_name", "atlas_name"), ("method", "method")],
            ),
            (
                timeseries_correlation,
                strip_header_node,
                [("out_corr_matrix", "in_file")],
            ),
            (name_output_node, strip_header_node, [("filename", "out_file")]),
            (strip_header_node, outputspec, [("out_file", "out_file")]),
        ]
    )
```
([FCP-INDI/C-PAC/CPAC/connectome/connectivity_matrix.py#L163-L209@`043a004`](https://github.com/FCP-INDI/C-PAC/blob/043a004380075203971ad6c205200a1555389ded/CPAC/connectome/connectivity_matrix.py#L163-L209))

### Platform details:

```Python
{'commit_hash': '<not found>',
 'commit_source': '(none found)',
 'networkx_version': '3.1',
 'nibabel_version': '5.1.0',
 'nipype_version': '1.8.6',
 'numpy_version': '1.25.1',
 'pkg_path': '/usr/share/fsl/6.0/lib/python3.10/site-packages/nipype',
 'scipy_version': '1.11.1',
 'sys_executable': '/usr/share/fsl/6.0/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.10.6 | packaged by conda-forge | (main, Aug 22 2022, '
                '20:36:39) [GCC 10.4.0]',
 'traits_version': '6.3.2'}
```

### Execution environment

Choose one
- My python environment inside container [Base Tag: [:bookmark: `1.8.6`](https://github.com/nipy/nipype/releases/tag/1.8.6)]

**Comment by effigies** [comment]
@aghayoor Could I trouble you to have a look at this? It looks like you added the interface in #3263.

**Comment by effigies** [comment]
@shnizzedy If we don't hear back, I think you can go ahead with the most obvious fixes to you.

> * I'm not 100% sure, but I think `ts_Z_corr` is meant to be `ts_wb_Z` based on the structure of the check and [the definitions of the arguments for 3dNetCorr](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dNetCorr.html).

That seems plausible.

> * I'm also not sure, but I think the check should check if those values are `True` rather than just if they are defined?

Yes, just remove the `isdefined()`. Undefined evaluates to `False`, so it's almost always safe to use `if self.inputs.X`.

**Comment by aghayoor** [comment]
Hi @effigies , It’s been a while since I added this, so I don’t fully remember the details, but your suggested fix makes sense to me. Thanks!
