### ISSUE TITLE
Add tests to cover all AFNI classes

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#4]
The following afni classes have no tests:
- ThreedZcutup
- ThreedSkullStrip
- ThreedBrickStat
- Threedcalc
- ThreedAllineate

http://sourceforge.net/apps/trac/nipy/ticket/30

**Comment by tsalo** [comment]
@chrisfilo It looks like all of these have tests now. Can this be closed?

**Comment by chrisfilo** [comment]
Sure!
