### ISSUE TITLE
portalocker not working well on network file systems

### ISSUE THREAD

**Issue by satra** [nipy/nipype#408]
portalocker is not working well on network file systems. could be an issue with the `with` statement. check disabled for now.

**Comment by effigies** [comment]
Related #2278, I think.

**Comment by effigies** [comment]
@satra Is this something we can fix with [filelock](https://github.com/benediktschmitt/py-filelock)?

**Comment by satra** [comment]
@effigies - we can try. this particular issue was from a while back.

@mgxd - did you do any explicit tests for this on our slurm system? (not the docker environment. although we should add a couple of tests for filelocking on the travis test as well.

**Comment by mgxd** [comment]
No, but l can run some tests today with `SoftFileLock`

**Comment by effigies** [comment]
Okay. Was just skimming through old issues to see if there's anything we might throw on the 1.2.2 or 1.3.0 milestones. We've built quite a backlog again...

**Comment by effigies** [comment]
Closed in #3025.
