### ISSUE TITLE
Default values for outputs make MapNode crash

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#413]
I meant  something like:

```
class TestInputSpec(BaseInterfaceInputSpec):
   in_nbr = traits.Float(0)

class TestOutputSpec(TraitedSpec):
    out_nbr = traits.Int(1,usedefault=True)

class Test(BaseInterface):
    input_spec = TestInputSpec
    output_spec = TestOutputSpec

    def _run_interface(self,runtime):
    print 'hey'
        return runtime

    def _list_outputs(self):
        outputs = self._outputs().get()
    outputs['out_nbr'] = 10
    return outputs
```

the fact of having predefined value used as defaults make the MapNode._collate_results crash: 

---

AttributeError                            Traceback (most recent call last)
/data/tests/t/<ipython-input-10-a8668710ce82> in <module>()
----> 1 r=n.run()

/data/code/nipype/nipype/pipeline/engine.pyc in run(self, updatehash)
   1126                     self.inputs.get_traitsfree())
   1127             try:
-> 1128                 self._run_interface()
   1129             except:
   1130                 os.remove(hashfile_unfinished)

/data/code/nipype/nipype/pipeline/engine.pyc in _run_interface(self, execute, updatehash)
   1736             # map-reduce formulation

   1737             self._collate_results(self._node_runner(self._make_nodes(cwd),
-> 1738                                                     updatehash=updatehash))
   1739             self._save_results(self._result, cwd)
   1740             # remove any node directories no longer required

/data/code/nipype/nipype/pipeline/engine.pyc in _collate_results(self, nodes)
   1639                         values = []
   1640                     if node.result.outputs:
-> 1641                         values.insert(i, node.result.outputs.get()[key])
   1642                     else:
   1643                         values.insert(i, None)

AttributeError: 'int' object has no attribute 'insert

**Comment by effigies** [comment]
This hasn't been a practical problem. Closing. Please reopen if still interested.
