### ISSUE TITLE
Need set working directory to file directory to successfully run fsl.FIRST

### ISSUE THREAD

**Issue by bldrvnlw** [nipy/nipype#434]
Version: master: 0.7.0  dev

You need to chdir (set the working directory) to the directory containing the input file before first.run(). This despite the fact that you need a full path for the in_file. (I saw this with fsl.FAST as well) - 

first = fsl.FIRST()
first.inputs.in_file = "full_path_input_file"
first.inputs.out_file = "path _output"
os.chdir("directory_containing_input_file")
first.run()

If you don't it fails with the following error : 

 in run results = first.run()
 File "/usr/local/lib/python2.6/dist-packages/nipype/interfaces/base.py", line 824, in run
 results.outputs = self.aggregate_outputs(results.runtime)
 File "/usr/local/lib/python2.6/dist-packages/nipype/interfaces/base.py", line 879, in aggregate_ou tputs
 raise FileNotFoundError(msg)
File/Directory '[' <working-directory>/segmented-BrStem_first.vtk']' not found for FIRST ou tput 'vtk_surfaces'.
Interface FIRST failed to run. : File/Directory '['<working-directory>/segmented-BrStem_fi rst.vtk']' not found for FIRST output 'vtk_surfaces'.
Interface FIRST failed to run.

**Comment by satra** [comment]
@bldrvnlw - i'm getting the same issue but only on ubuntu with fsl installed using neurodebian, the files are produced fine on CentOS fsl install. @yarikoptic or @hanke - have you by any chance seen this?

see output here for details:

https://circleci.com/gh/satra/simple_workflow/15

**Comment by satra** [comment]
the files are also generated on OS X.

**Comment by satra** [comment]
figured out the issue - needed to install `fsl-first-data`
