### ISSUE TITLE
CommandLine._gen_filename and filename with points

### ISSUE THREAD

**Issue by bpinsard** [nipy/nipype#510]
I ran into a problem with files having a point in the middle of their name.
`_gen_filename` does not add extension due to `split_filename` returning a extension being the last part of name.
it then crashes with afni interfaces because without ext it add BRIK/HEAD.
I thought maybe adding a line to check if the extension exists in the module's Info.ftypes, but then other outputs like matrices, textfiles cannot be generated properly. 
Does points in filenames have to be banned? Some dicoms/converters and preprocessing adds a point in their output, does files have to be renamed? Use a limit of extension length or a dictionary of plausible extension? Or maybe have output_spec traits to specify the file extension? 
Thanks for your input.

**Comment by djarecka** [comment]
@bpinsard closing this for now. please reopen if this is still relevant
