### ISSUE TITLE
Workflow saving features and tests

### ISSUE THREAD

**Issue by satra** [nipy/nipype#553]
- [ ] test against as many workflows (possibly using testkraut) essentially the workflow and it's saved version should produce the same result on the same machine (subject to random number generators)
- [ ] interfaces that have positional arguments in `__init__` need to be cleaned up - in such interfaces an internal variable `_arg1` for positional argument `arg1` should hold the value of `arg1`.
- [ ] other file formats? (json, yaml?)

**Comment by djarecka** [comment]
@satra please open a new issue with some details if you think that points 2 and 3 are still relevant
