### ISSUE TITLE
profiling nipype structured provenance

### ISSUE THREAD

**Issue by satra** [nipy/nipype#590]
@inati  starting a separate thread here to keep the other one focused on connections/improving nipype pipeline construction

each node when it runs leaves a report.rst file in node_working_dir/_report/report.rst

you can use the duration variable there to profile a node.

alternatively if you have a cluster you can get more info back in terms of memory, disk io and duration, simply by instrumenting the scheduler args.

**Comment by djarecka** [comment]
@satra - I believe you made the changes to `provenance` in 2013. If you  want to keep the issue open and implement additional options please reopen and add some commends.
