### ISSUE TITLE
DataFinder cannot match files in symlinked directories

### ISSUE THREAD

**Issue by mih** [nipy/nipype#656]
Whenever my regex should match a file where any part of the path is a symlink to a directory -- it does not work. An equivalent expression for the DataGrabber works as expected. When the symlink is "physically" replaced by the link target in the file system, also DataFinder can match the file in question.

It would be nice if DataFinder would be symlink-safe.

Thanks

**Comment by effigies** [comment]
Closing as stale. Assume that at least one of the existing data grabbers can handle symlinks.
