### ISSUE TITLE
interfaces.afni classes demand existing input files rather than valid AFNI datasets

### ISSUE THREAD

**Issue by ischwabacher** [nipy/nipype#660]
I propose to replace the `File` trait for input datasets to the interfaces.afni classes with an `AfniDataset` trait that accepts valid afni dataset names that are not names of files on disk.  The restriction to existing file names in nipype is primarily a problem because currently there is no way in nipype to select a subset of the frames of an AFNI dataset, for instance to trim pre-steady-state frames from the beginning of a time series; the way to do this in AFNI is to use sub-brick selection:

```
3dTcat -prefix fred_trimmed "fred+orig[3..$]"
```

where 3dTcat is used as a no-op.  It is unlikely that this string is the name of a file on disk, but there is the further issue that if it is, or if the user creates the file in order to circumvent this check, nipype and AFNI will agree on the name of the dataset but disagree on which file(s) represent it.  This seems like a nightmare for any attempt to document the provenance of the resulting output.

The canonical way to test whether an AFNI dataset exists is with `3dinfo -exists`, which writes "1\n" or "0\n" to stdout depending on whether the input dataset exists (and exits successfully regardless).  Unfortunately, this has some drawbacks; for instance, the following are all valid dataset names, assuming their parts exist:
- `fred+orig elvis+orig` (concatenation in time)
- `3dcalc( -a MNI_avg152T1+tlrc -b 1D:stdin -expr a*b )`
- `http://afni.nimh.nih.gov/pub/dist/data/TTatlas.nii.gz`

These might constitute more rope than you want to give the user.  Furthermore, because of the AFNI interactive viewer's warp-on-demand feature, a dataset is considered to exist if its `.HEAD` file exists, even if it has no accompanying `.BRIK` (or `.BRIK.gz`, `.BRIK.bz2`, etc.) file, though any attempt to read such a dataset in any context other than the interactive viewer will fail.  This also avoids having to search for the appropriate extension for the potentially compressed `.BRIK` file.

In writing this post I've become convinced that ultimately, the correct way to handle all of these issues is with an update to `3dinfo` that adds the option to test for the existence of a dataset on disk and output the names of the files that need to be read in order to load that dataset without reading from any outside source or running an outside program.  In the meantime, however, I do think that adding the capacity to handle sub-brick selection is worth temporarily opening up ways for creative users to screw things up.

This issue doesn't have a patch attached because I am just encountering traits for the first time and I don't understand them well enough yet to create a patch.  I can also imagine that you've thought about this already and rejected this idea, and if so I'd rather find that out before writing the patch.

**Comment by djarecka** [comment]
@ischwabacher I'm closing the issue for now, please open a new one if you still consider it as an issue
