### ISSUE TITLE
Move/rename working directory without rerunning everything

### ISSUE THREAD

**Issue by binarybottle** [nipy/nipype#734]
I would like to rerun my nipype pipeline after moving/renaming the working directory, and have tried setting:
mbFlow.run(updatehash=True), as well as:
mbFlow.config['execution']['use_relative_paths'] = True
(see https://github.com/binarybottle/mindboggle/blob/master/mindboggle/mindboggle#L2164)
but get an error that indicates that the workflow is searching for files in the old directory.

**Comment by djarecka** [comment]
@binarybottle - you closed your PR in 2014, does it mean you don't consider this as an issue anymore? Can we close it?

**Comment by binarybottle** [comment]
It's been so long that I can't remember whether I was ever able to rerun the pipeline after moving the working directory without recreating the working directory.  Please feel free to close, as it clearly isn't an issue for me anymore! :)
