### ISSUE TITLE
3dTshift Parameters

### ISSUE THREAD

**Issue by DaveOC90** [nipy/nipype#815]
Hi,

I have tried using NIPYPE for slice timing correction with the acquisition sequence set to 'altplus', but this does not work, I had to use 'alt+z', which does work. Is the altplus/alt+z duality set up? It says in the user documentation that it is.

doc

**Comment by tsalo** [comment]
It looks like @dclark87 addressed this in #868 by changing `tpattern` from an `Enum` (which was missing some options) to a `Str`. Can this issue be closed?
