### ISSUE TITLE
Dynamic iterables

### ISSUE THREAD

**Issue by dmwelch** [nipy/nipype#819]
@satra @chrisfilo Having runtime defined iterable attributes would be awesome, especially for big data sets.  Issue has been raised on the mailing list before: https://groups.google.com/forum/#!msg/nipy-user/pYW70-xAeu4/4MNbiDVQvAMJ 

The current option is a MapNode of a Function that contains the workflow to iterate...

Cheers,
Dave

**Comment by AlanKuurstra** [comment]
+1, This feature would be useful in combination with the experimental `remove_node_directories` for large datasets whose processing eats up disk space. 

I have an fmri dataset that must be registered to a high resolution atlas.  A number of preprocessing steps are done before the fmri file is split into separate time volumes. It wold be nice to send the split volumes into the next node's iterables list.  After the split, each volume would be processed by a chain of subsequent nodes separately.  The subsequent chain of node directories would be removed (freeing up space) before moving on to the next time volume.

**Comment by effigies** [comment]
This will not be implemented in Nipype 1, but is being implemented in [Pydra](https://github.com/nipype/pydra/), which will be the engine for Nipype 2.
