### ISSUE TITLE
nipype importerror: no module named utils

### ISSUE THREAD

**Issue by zhangyu2ustc** [nipy/nipype#842]
I am just a beginner of nipype. After installation, I tried the common python -c "import nipype;", but always got the error information "ImportError: No module named utils"
  I have checked the version of python and nose: python 2.7, nose 1.3.3. 
  My nipype was downloaded from the website with the latest version: v0.9.2.

Could you tell me what is wrong with it ?
Thanks very much.
Yu

**Comment by barbrakr** [comment]
Dear experts, am having the same issue I think. 
I did these steps but got the error below. Please help.

pip install https://github.com/nipy/nipype/archive/master.zip

python -c "import nipype; nipype.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named nipype

**Comment by effigies** [comment]
Likely you have two Python installations, and your pip doesn't match your Python.

Try:

```
python -m pip install --upgrade pip
python -m pip install --upgrade nipype
```

**Comment by barbrakr** [comment]
Thank you very much, I was able to run the command as only:
`pip install --upgrade pip`
`pip install --upgrade nipype`

Yes, I've got a couple of pythons installed on my MacBook pro running Mojave 10.14.3

`python`
"python             python2.7          python3            python3.7          python3.7m         pythonw            
python-config      python2.7-config   python3-config     python3.7-config   python3.7m-config  pythonw2.7"


However, after running with your suggestion, I still see this output from 
`python -c "import nipype; print(nipype.__version__)"`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nipype/__init__.py", line 12, in <module>
    from .utils.config import NipypeConfig
  File "nipype/utils/__init__.py", line 4, in <module>
    from .config import NUMPY_MMAP
  File "nipype/utils/config.py", line 20, in <module>
    import configparser
ImportError: No module named configparser


Any help is greatly appreciated! Thanks!

**Comment by barbrakr** [comment]
Changing it to python3 seemed to help for my first command
`python3 -c "import nipype; print(nipype.__version__)"`
1.2.0

but still fails here:
` python3 -c "import nipype; nipype.test(doctests=False)"`
-c: error: unrecognized arguments: --doctest-modules

**Comment by effigies** [comment]
For that, you probably need to use `pip install --upgrade "nipype[tests]"`.

If you're having further problems, please open a new issue. Notifications on closed issues are easy to pass over.

**Comment by barbrakr** [comment]
Thank you very much, I managed to run it with your suggestion above and `python3 -c "import nipype; nipype.test(doctests=True)"` Cheers!
