### ISSUE TITLE
local variable 'task' referenced before assignment - IPython 2.1.0 bug - remote ipengines

### ISSUE THREAD

**Issue by armaneshaghi** [nipy/nipype#853]
On anaconda (conda 2.4.1) Ubuntu 14.04 I receive the following error only when I want to use IPython parallel to run a workflow which runs on the same multiprocessors machine when not including remote nodes, sounds like a bug to me: 

```
  File "/opt/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 242, in run 
    self._clear_task(taskid)
  File "/opt/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/ipython.py", line 106, in _clear_task
    self.taskclient.purge_results(self.taskmap[taskid])
  File "/opt/anaconda/lib/python2.7/site-packages/IPython/parallel/client/client.py", line 1767, in purge_results
    self.purge_local_results(jobs=jobs, targets=targets)
  File "/opt/anaconda/lib/python2.7/site-packages/IPython/parallel/client/client.py", line 1689, in purge_local_results
    assert not self.outstanding, "Can't purge a client with outstanding tasks!"
AssertionError: Can't purge a client with outstanding tasks!

```

The problem reproduces on several different servers, does not happen when I use for example Numpy with the same parallel architecture, does not happen when I use only one machine for parallelization. However, as soon as I add a remote host using `ipengine` the problem appears.

**Comment by blakedewey** [comment]
I see this is closed, but I am still having issues. Is this a confirmed IPython bug? If so, is there any idea when it will be fixed? I can't seem to run any workflows using the IPython plugin, even after updating IPython to 3.0. Is there a good workaround if there is no solution?

**Comment by chrisfilo** [comment]
@armaneshaghi was this fixed in master?

**Comment by armaneshaghi** [comment]
There was a bug with IPython (unrelated to nipype) that @satra reported in their forum and was fixed, but I think the issue has re-appeared, and it seems that it persists in IPython 3.0. I'll look into this if I find the time, for now SGE plugin is the most stable one.

**Comment by chrisfilo** [comment]
We should link to that issue here - I cannot find it though: https://github.com/ipython/ipython/issues?q=is%3Aissue+satra

**Comment by armaneshaghi** [comment]
Nor can I, but I guess this is not IPython related now. @satra have we done some new pickle hacking recently? haven't tested it, but it seems that the issue was related to multiple machines, now @blakedewey reported it even with `ipcluster`.

**Comment by satra** [comment]
@blakedewey - would it be possible to replicate this on the vagrant vm with a toy example. it's still a little clunky but it would be great for us to move to an approach where people can easily replicate their issue on a standard setup.

**Comment by blakedewey** [comment]
@satra - I could definitely try. What do I need to do? I have never worked on a vagrant vm before. I could probably put together something that would fail for ipython.

**Comment by satra** [comment]
actually before we debug the nipype side, can you confirm that you can run an ipython parallel command that executes where you want it to?

in nipype we simply create a task client and map to ipython engines using load_balanced_view.

https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/ipython.py#L65
https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/ipython.py#L91

it's possible that something has changed with the version you have, but it would be good to know that the basic ipython mechanism operates, before debugging on the nipype side.

**Comment by blakedewey** [comment]
Python works as expected using `load_balanced_view` and a basic sleep/return inputs function:
```
def sleep_test(a):
    import time
    time.sleep(10)
    return a
from IPython import parallel
clients = parallel.Client()
view = clients.load_balanced_view()
aresult = view.map(sleep_test,range(40))
aresult.get()
```
This works in synchronous and asynchronous runs with 40 engines spawned using ipcluster.

**Comment by satra** [comment]
let me know if the following works:

```
import os

from nipype import Function, Workflow, Node

def test_func(in1):
    import numpy as np
    return in1 + np.random.randint(10)

wf = Workflow('testipy')
node = Node(Function(input_names=['in1'], output_names=['out'], function=test_func),
            name='dummy')
node.iterables = ('in1', [1, 2, 3, 4])

wf.add_nodes([node])
wf.config['execution']['job_finished_timeout'] = 2
wf.base_dir = os.getcwd()
wf.run('IPython')
```

**Comment by satra** [comment]
updated the config option above.

**Comment by blakedewey** [comment]
Yes, this works!

**Comment by satra** [comment]
@blakedewey - great - in this case might things not working be related to your other question, on custom modules/packages? to test, try it with the `PYTHONPATH` option.

**Comment by blakedewey** [comment]
It actually works fine with the `PYTHONPATH` change. I don't know what is different now. The funny thing is that it delays a long time before returning the error. Reducing the `poll_sleep_duration` reduced this waiting time. I will do further testing and report back.

**Comment by blakedewey** [comment]
This only worked once. Then after that it returned to the previous error with the `RemoteError`. Adding to `PYTHONPATH` had no effect.

**Comment by satra** [comment]
@blakedewey - does the above workflow still work? so to be clear - it's your workflow with your routines that breaks? 

did you have PYTHONPATH set in the terminal where you start the kernels? if you are running over ssh, you may want to include it in your bashrc or some such.

**Comment by blakedewey** [comment]
The above script still works. My workflow does not. I set the PYTHONPATH in bashrc.

**Comment by satra** [comment]
and i assume that you did restart `ipcluster`

how about run your other code to check:

```
def check_pythonpath(a):
    import os
    import socket
    return a, socket.gethostname(), os.env['PYTHONPATH']
from IPython import parallel
clients = parallel.Client()
view = clients.load_balanced_view()
aresult = view.map(check_pythonpath, range(40))
aresult.get()
```

**Comment by blakedewey** [comment]
Very strange. It seems to work. I had to redefine the PYTHONPATH in both terminals, the ipcluster and the workflow. I still don't understand why the PYTHONPATH needs to be defined this way.

**Comment by satra** [comment]
in many unix stations changes to bashrc don't have an effect unless you log out and log back in. perhaps that's what's going on.

regarding PYTHONPATH, just putting something in site-packages doesn't always result in being picked up. i don't know the issues well enough. you'll have to do some reading on python and packing and finding things.
