### ISSUE TITLE
AFNI 3dTShift interface, tpattern argument not robust

### ISSUE THREAD

**Issue by dclark87** [nipy/nipype#867]
The tpattern argument for 3dTshift interface in nipype/interfaces/afni/preprocess.py doesn't allow for filepaths (strings) so that users can specify custom temporal offsets from a text file they have on disk. It only allows for standard alternating patterns (e.g. alt+z, alt+z2) arguments. This is in contrary to what the actual function itself allows one to specify.

I have fixed this in my 0.9.2_cpac-tested branch so that it just takes in a string argument and it seems to work. Could this change be incorporated?

**Comment by alexsavio** [comment]
Was this done?

**Comment by dclark87** [comment]
Yep: https://github.com/nipy/nipype/pull/868
