### ISSUE TITLE
create_fixed_effects_workflow needs additional inputs

### ISSUE THREAD

**Issue by Gilles86** [nipy/nipype#871]
Hey there,

I often use the create_modelfit_workflow()- in combination with create_fixed_effects_flow() from the nipype.workflows.fmri.fsl-module to quickly fit a glm to neuroimaging data. However, there is something weird about the fixed effects-workflow. The inputspec-node of the the fixedfx workflow has the following inputs:

inputspec = 
copes = <undefined>
dof_files = <undefined>
varcopes = <undefined>

If you set all these fields and run the workflow, it complains that the 'num_copes' property of the l2model-node and the 'mask'-property of the flameo-node also need to be set. Of course this can be done separately, but maybe it's nice to also incorporate these in the inputspec-inputs? 

Or am I missing something?

**Comment by djarecka** [comment]
I'm not sure if I understand the issue (can see that `num_copes` was written years ago), please reopen and suggest changes if you consider this as an issue.
