### ISSUE TITLE
Issues while running dicom2nifti.py

### ISSUE THREAD

**Issue by mdk142** [nipy/nipype#885]
Hi,

I am trying to run dicom2nifti tool against the dicim data I have. I see that it is expecting some kind of directory structure in the input data. Can you please explain how the directory structure should be for the input directory?

Also does this tool search just the siemens scanners? does it support other scanners as well?

Thanks in advance

**Comment by mgxd** [comment]
@mdk142 dunno if this is still relevant, but I would recommend [heudiconv](https://github.com/nipy/heudiconv), which aims to make this process much easier
