### ISSUE TITLE
fslcomplex lack of output type

### ISSUE THREAD

**Issue by yasinyazici** [nipy/nipype#893]
Hi 
I need to use fslcomplex -realabs option, however Complex function of fsl interface (https://github.com/nipy/nipype/blob/b1b78251dfd6f3b60c6bc63f79f86b356a8fe9cc/nipype/interfaces/fsl/utils.py#L1362) does not support it. It looks like the first three output type (realabs, realphase, realpolar) below are not included to Complex function?

```
   fslcomplex -realabs complexvol absvol [startvol [endvol]]
   fslcomplex -realphase complexvol phasevol [startvol [endvol]]
   fslcomplex -realpolar complexvol absvol phasevol [startvol [endvol]]
   fslcomplex -realcartesian complexvol realvol imagvol [startvol [endvol]]
   fslcomplex -complex realvol imagvol complexvol [startvol [endvol]]
   fslcomplex -complexpolar absvol phasevol complexvol [startvol [endvol]]
   fslcomplex -complexsplit source dest [startvol [endvol]]
   fslcomplex -complexmerge source1 source2 dest
   fslcomplex -copyonly source dest
```

Regards
Yasin

**Comment by djarecka** [comment]
@yasinyazici apologize, that we missed this issue. please reopen if you still consider it as an issue and consider opening a pull request to update the interface.
