### ISSUE TITLE
artifacts.py hmc remove b0 images

### ISSUE THREAD

**Issue by cni-md** [nipy/nipype#941]
I found a bug in the hcm pipeline. The pipeline removes the b0 images.

Fix for only one b0 image at the beginning: https://github.com/cni-md/nipype

(GetMovingDWs extract only images with diff weighting. If we have more than one b0 image or the b=0 is not at the beginning bval/bvec will have wrong values)

I found the procedure from epi.py fieldmap_correction more suitable to coregister the warped fieldmap with the EPIs to get the transformation matrix. Is there a reason to skip this in the BMapMag2B0 part of the fmc pipeline?

No I got stocked at Shiftmap2Warping. vsm2dfm give me a 4D image (one empty volume, one with the shift map?, one empty volume) whereas the ScaleField Node has still a resonable ShiftMap.

How should the result of vsm2dfm look like?

Joerg

**Comment by vinkirk** [comment]
Hi,

I ran the hmc_pipeline on my diffusion imaging dataset and upon inspection of the outputted head motion corrected diffusion-weighted images, I noticed that the b0 volume was missing.  Any help would be greatly appreciated.

Thanks,

Vinny
