### ISSUE TITLE
Enthought Tool Suite configuration

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#972]
ETS should be configured to use the ```null``` toolkit as in https://github.com/nipy/nipype/blob/master/nipype/algorithms/mesh.py#L77. However this results in a ```ValueError``` if it is already set (which is very common with ipython).

I think this setting should be done at the very beginning when importing nipype, isn't it?

**Comment by oesteban** [comment]
@satra, how could I set the environment variable ```ETS_TOOLKIT='null'``` before anything else is executed in nipype?

**Comment by satra** [comment]
@oesteban - you would have to do it in the environment outside. within nipype we try not to touch the environment unless necessary.

**Comment by oesteban** [comment]
@chrisfilo said (https://github.com/nipy/nipype/pull/1219#issuecomment-140938212):

> This might be a better way of doing this: > https://github.com/nipy/nipype/blob/c31a5a819137cbef15f55f7d0a77a65d6a37a88f/nipype/interfaces/ants/base.py#L63

Agreed, but that is a CommandLine interface, so it has it's own environment and we can handle it. In this case, as it is a BaseInterface, the system-wide environment is used.

@satra, what if we save the environment first and then we restore it after loading tvtk?

**Comment by satra** [comment]
that should work. the only thing i don't know is if multiprocessing preserves separate environments (i think it does).
