### ISSUE TITLE
fugue broken by the refactor

### ISSUE THREAD

**Issue by bpinsard** [nipy/nipype#977]
No _list_outputs is implemented in FUGUE interface, so no outputs is set by default.
this seems to be broken by this PR: https://github.com/nipy/nipype/pull/857
it seems that no tests are checking for outputs to be listed if file created.

**Comment by oesteban** [comment]
Maybe @bpinsard or myself have a different nipype version... but in my settings #978 breaks FUGUE interface. Without it, FUGUE works for me (using the ```name_source``` feature).
