### ISSUE TITLE
MapNode hangs when pipeline run with "SGE" plugin under qsub with version 0.10

### ISSUE THREAD

**Issue by moloney** [nipy/nipype#988]
I will often run pipelines with qsub even though the pipeline is running with the "SGE" plugin. This allows me to set `run_without_submitting` on nodes that take very little processing without worrying about using too much resources on the cluster head node.

After upgrading to 0.10 I found that the pipelines will hang after submitting the jobs for the first MapNode in the pipeline, never noticing that the jobs did in fact complete (and thus never kicking off the next set of jobs). The output files for the MapNode jobs are created in the working directory.

**Comment by djarecka** [comment]
Is this problem still present in the current version of nipype? I know this is an old issue, but if you still experience problems, can you please tell me how can I reproduce it?

**Comment by mgxd** [comment]
perhaps fixed in #1002

**Comment by djarecka** [comment]
closing for now, please reopen if needed
